### ISSUE TITLE
redirect caml.org to ocaml.org

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#100]
Ashish has emailed Xavier to request this.

**Comment by Chris00** [comment]
I think another gentle request should be made.

**Comment by Chris00** [comment]
Any news on this?

**Comment by agarwal** [comment]
I sent another email cc'ing several of us.

**Comment by agarwal** [comment]
Update: 11-Feb-2014 - @avsm offered to do the redirect if Xavier and Damien approved. However, we haven't gotten a reply yet.

**Comment by agarwal** [comment]
In an email, Damien has confirmed that Xavier has approved this. @avsm Please go ahead with the redirect when you can. Thanks.

**Comment by Chris00** [comment]
I do not think there is anything left to do here.

**Comment by agarwal** [comment]
Why not? @avsm could still do this.

**Comment by Chris00** [comment]
Right, I was of the wrong impression that this was discussed and settled when the warning was put on http://caml.inria.fr/

**Comment by Chris00** [comment]
Well, 3 years later nothing has changed.  Closing.
