### ISSUE TITLE
Revise homepage discuss.ocaml.org link description?

### ISSUE THREAD

**Issue by mars0i** [ocaml/v2.ocaml.org#1001]
The ocaml.org home page includes "Got a question? Chat live with OCaml experts!" which links to  discuss.ocaml.org.   Including this link on the home age with its implicit suggestion to just ask is great.  

This is a small point, but it's not really a live chat.  It's not what people would expect.  (I thought, "Wow--experienced OCaml users have signed up to have their work interrupted at random times by questions from newbies and the merely curious?!?  Cool.  But surprising!)  

Maybe a different description would be better.  I suggest "Got a question?  Ask OCaml experts!"

(The current description would be more appropriate for IRC or discord, but those require setup by the user.)

**Comment by pmetzger** [comment]
Perhaps you should do a pull request?
