### ISSUE TITLE
Syntax highlight in OCaml manual

### ISSUE THREAD

**Issue by XVilka** [ocaml/v2.ocaml.org#1008]
It will improve readability to a greater level.
Opening issue here because manual located in the main https://github.com/ocaml/ocaml repository and it has issues disabled.

**Comment by pmetzger** [comment]
It isn't useful to open it here. The teams for OCaml itself and the web site are unrelated. There's a Mantis tracker for handling ocaml issues directly at https://caml.inria.fr/mantis/main_page.php , but my suggestion is that you figure out how to do said syntax highlighting and submit a PR.

Before doing much, you will probably want to have a look at the updates that have been made to the manual formatting, which have been significant. Build the manual on the trunk branch of the ocaml repository and see.
