### ISSUE TITLE
website crashes Safari 5.0.5

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#101]
Reported by Mark Shinwell: It seems loading any page, at least the frontpage, causes Safari 5.0.5 to immediately crash (on Mac OS X 10.6.8). This doesn't happen with Safari 6.0.2 on Mac OS X 10.7.5.

**Comment by amirmc** [comment]
Does Mark have any addons in Safari 5? Useful to know.

**Comment by samoht** [comment]
It works fine on Version 5.1.7 (OSX 10.6.8), without any extension

**Comment by Chris00** [comment]
Does it still crash if he comments out some javascript file inclusions?  I do not have a mac, more information is needed.

**Comment by agarwal** [comment]
Cc'ing Mark.

On Tue, Jan 22, 2013 at 12:38 PM, Christophe Troestler <
notifications@github.com> wrote:

> Does it still crash if he comments out some javascript file inclusions? I
> do not have a mac, more information is needed.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ocaml/ocaml.org/issues/101#issuecomment-12556095.

**Comment by Chris00** [comment]
Any news on this?

**Comment by Chris00** [comment]
Given that no information was provided during the last 5 months, I am closing the issue.  Feel free to reopen it if the problem persists.
