### ISSUE TITLE
Mention 4.07 release on web site?

### ISSUE THREAD

**Issue by pmetzger** [ocaml/v2.ocaml.org#1010]
I note that 4.07 isn't in the "News" section etc. Then again, perhaps that is waiting for a more official announcement?

**Comment by agarwal** [comment]
4.07.0 has been officially released. A list item like the current one for the _OCaml Weekly News_ (or the commented out one for the _OCaml Users and Developers Workshop_) could be added and pointed to `/releases/4.07.0.html`.

**Comment by pmetzger** [comment]
@Chris00 Thank you!
