### ISSUE TITLE
Make site tools build using 4.07

### ISSUE THREAD

**Issue by pmetzger** [ocaml/v2.ocaml.org#1012]
I note that whatever builds the site is still using quite an old OCaml, or was when I last checked.

**Comment by Chris00** [comment]
The current build uses 4.06.

**Comment by pmetzger** [comment]
> The current build uses 4.06.

Ah, well that's a significant improvement. Should I close this? (That said, an upgrade to 4.06.1 would probably be in order?)

**Comment by Chris00** [comment]
I just checked on the machine and it is 4.06.1.  Unless there is a feature in the new compiler we want to use — or show, say, in a tutorial — I think there is not rush to upgrade to 4.07.

**Comment by pmetzger** [comment]
There's no rush whatsoever. 4.06.1 is fine. I was really worried it was still 4.02 or 4.03 which was the case the last time I checked.
