### ISSUE TITLE
Set up https: for ocaml.org

### ISSUE THREAD

**Issue by pmetzger** [ocaml/v2.ocaml.org#1021]
Right now, if you look at ocaml.org in Chrome (or a variety of other browsers) it informs you that because it's using http, it isn't secure. Over the next couple of years, the browser vendors are going to be tightening this up more and more.

I'd suggest that a Let's Encrypt certificate (and the script to renew it) be set up, and the site be shifted to https.

**Comment by Chris00** [comment]
The site is available in both HTTP and HTTPS.

**Comment by pmetzger** [comment]
Ah. Perhaps it should be set to redirect people to the https: site?

**Comment by Chris00** [comment]
> Perhaps it should be set to redirect people to the https: site?

Should we?  Anil set up a “Let's encrypt” certificate but why force users?  I made sure to use protocol-relative URLs.  If it is for privacy, we may want to remove the references to third party resources — such as google and cloudfare.

**Comment by pmetzger** [comment]
> why force users

Because at this point, all non-https: URLs in most browsers get a big fat ugly "THIS SITE IS NOT SECURE!!!!" warning. :(

**Comment by Chris00** [comment]
I have added a rule to that effect.  May you please check the site?  There are some problems with “mixed content” to fix — do not hesitate to report (I know for the “planet“ page).

**Comment by pmetzger** [comment]
Sadly, firefox is now complaining about certificate errors:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/1907413/64926797-e0ba0400-d7cf-11e9-9020-7c6aa37940a3.png">

**Comment by redianthus** [comment]
It's only if you visit `www.ocaml.org`, it's working on `ocaml.org`. You should add the `www` domain to the certificate to fix it. Also, redirecting `ocaml.org` to `www.ocaml.org` would be a good thing to do.

**Comment by Chris00** [comment]
@avsm If you have time to do it that would be nice — you were the one setting up Let's Encrypt.  Otherwise I will have a look but it will be slower.

**Comment by Chris00** [comment]
@avsm Since our DNS provider is gandi, we need [a Gandi API token](https://pypi.org/project/certbot-plugin-gandi/) to proceed.  May you send it to me by email?

**Comment by XVilka** [comment]
Were there any updates regarding this one? Recently met this again.

**Comment by Chris00** [comment]
Still waiting for @avsm.

**Comment by pmetzger** [comment]
@avsm ?

**Comment by avsm** [comment]
This is now upgraded and live, to ocaml.org and www.ocaml.org as an alternate name using the new LE validation scheme. Please reopen if you into any issues.

**Comment by redianthus** [comment]
Could someone also set-up a permanent redirect from `ocaml.org` to `www.ocaml.org` please ?

**Comment by pw374** [comment]
reopened because of https://github.com/ocaml/ocaml.org/issues/1127

**Comment by avsm** [comment]
I'm fixing this as part of https://github.com/ocaml/ocaml.org/issues/1178

**Comment by avsm** [comment]
Now done and live.
