### ISSUE TITLE
Index page is empty

### ISSUE THREAD

**Issue by roptat** [ocaml/v2.ocaml.org#1024]
Hi,

the index page is empty:

```
roptat@localhost$ curl http://ocaml.org
<!DOCTYPE HTML>
roptat@localhost$ curl https://ocaml.org
<!DOCTYPE HTML>
roptat@localhost$ 
```

The rest of the website works correctly. For instance, the French index page is OK.

**Comment by Chris00** [comment]
Thanks for reporting.  We know about the problem and will fix it ASAP.

**Comment by Chris00** [comment]
(The problem has been long fixed but I leave this open to remind me that a more robust solution is desirable.)

**Comment by Chris00** [comment]
Added to my TODO list.
