### ISSUE TITLE
Put 4.07.1 announcement on the front page?

### ISSUE THREAD

**Issue by pmetzger** [ocaml/v2.ocaml.org#1027]
Since 4.07.1 is out, perhaps it should be announced on the front page?

**Comment by Chris00** [comment]
Except for the date, it should happen automatically.  I'll check it out — maybe a consequence of the OPAM 2 migration.

**Comment by pw374** [comment]
Something's broken, since it hasn't happened automatically.

That being said, it seems the date of the latest release will still have to be manually edited.

**Comment by Chris00** [comment]
@avsm If there was a convention to determine the release date of OCaml compilers (say to add “Released on ...” to its description), that would be really great.

**Comment by pw374** [comment]
Ummm...  now it shows 4.06.1 ! It’s even worse than yesterday

**Comment by avsm** [comment]
@Chris00 perhaps the best way to do this is to add a `x-released-on` header to the `opam` file for the compilers, and query that from the website build for the descriptive information

**Comment by Chris00** [comment]
@avsm Fine with me!
