### ISSUE TITLE
Wrong Foreach Tutorial (Camlp4 3.10)

### ISSUE THREAD

**Issue by MathieuDutSik** [ocaml/v2.ocaml.org#1038]
The tutorial is hard to read because Python and OCaml are mixed up. I lost a lot of time because both languages are mixed.
It would be easier to just remove Python (which not everyone know) and put directly only the (correct) OCaml code.

**Comment by pw374** [comment]
However it's a tutorial that starts with

> **Deprecation Warning**: this tutorial describes technology that is considered obsolete. It's been replaced by extensions points and ppx rewriters

which raises the following question: who are the people still actually interested by CamlP4? and if there's any, why or what for?

**Comment by MathieuDutSik** [comment]
Which is what came from a google search for "for loops in ocaml".
I solved my problem.

If I have to say something about ocaml it is that better error messages
would be immensely useful.

  Mathieu

**Comment by pw374** [comment]
> Which is what came from a google search for "for loops in ocaml". I solved my problem.

OK, thank you for your feedback. Personally I have mixed feelings towards "fixing" this CamlP4 tutorial. 
Perhaps we should make it clearer that it's deprecated technology. One thing is certain: no OCaml beginner should read that tutorial! @Chris00 @agarwal @amirmc do you have any thoughts regarding that matter? It's probably a bigger issue than we "old OCaml users" wish to acknowledge.

> If I have to say something about ocaml it is that better error messages would be immensely useful. 

Well, yes. I could hardly agree more.
I think there are things going on about that, with the parser being rewritten using Menhir...

**Comment by pmetzger** [comment]
I think discouraging new people from learning camlp4 is reasonable. It's a dead technology.

**Comment by Chris00** [comment]
I would also favor the "deprecated technology" warning.

**Comment by avsm** [comment]
The Camlp4 pieces have been removed in https://github.com/ocaml/ocaml.org/pull/1147
