### ISSUE TITLE
A new school teaches OCaml

### ISSUE THREAD

**Issue by zzdpk2** [ocaml/v2.ocaml.org#1055]
Hi,
University of Minnesota Twin Cities teaches OCaml in CSCi2041(Advanced Programming Principles) and CSci5106(Programming Languages). Please update the Teaching OCaml website.
Thanks for your assistance

**Comment by Chris00** [comment]
May you provide the links to the courses pages?  Thanks.

**Comment by pw374** [comment]
Looks like this one https://www-users.cs.umn.edu/~kauffman/2041/syllabus.html
