### ISSUE TITLE
add CompCert award news item

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#107]
Reported by @smondet.

Unsure where to add this, but it would be good publicity for OCaml.

> Microsoft Research: 2012 Verified Software Milestone Award Winner
> December 19, 2012
> Press Release
> 
> We are delighted to announce that the recipient of the 2012 Microsoft
> Research Verified Software Milestone Award is Xavier Leroy of the
> Paris-Rocquencourt (http://www-rocq.inria.fr) research center of
> INRIA, France, for the CompCert Project
> (http://compcert.inria.fr). Specifically, the award is given in
> recognition for Xavier's role as architect of the CompCert C Verified
> Compiler as well as his leadership of the development team.
> 
> The formal presentation of the Award will be made to Xavier at POPL 2013
> (http://popl.mpi-sws.org/2013/
> ), which takes place in Rome - January 23-25,
> 2013.
> 
> "Microsoft Research is delighted to celebrate the advances made by Dr Leroy
> in
>   the vital field of software verification. Compilers are the basis for all
> the
>   software we generate, and by ruling out compiler-introduced bugs, the
> CompCert
>   project has taken a huge leap in producing strengthening guarantees for
>   reliable critical embedded software across platforms. We congratulate Dr
> Leroy
>   on his significant achievement in winning this Award."
> 
>   Dr. Judith Bishop, Principal Research Director, Computer Science,
>   Microsoft Research, Redmond
> 
> The full award citation is provided along with further details of the award
> process at the VSI website, i.e. http://dream.inf.ed.ac.uk/vsi
> 
> Kind regards,
>        Andrew Ireland & Jim Woodcock (Chairs of the Award Committee)

**Comment by Chris00** [comment]
Maybe we can turn it into a success story?  An announcement on the main page would be nice as well.

**Comment by agarwal** [comment]
I think the best place for it would be on the proposed slower aging blog
feed. That would give it attention on the front page. A success story might
be okay, but not if this is a one-off success. Our current success stories
are ongoing successes (at least I think they should be, but we have some
outdated items there). If CompCert became regularly and widely use then it
would make sense there.

**Comment by Chris00** [comment]
On Tue, 5 Feb 2013 06:13:03 -0800, Ashish Agarwal wrote:

> I think the best place for it would be on the proposed slower aging blog
> feed. [...]

That crossed my mind too but currently what would you put in it?  I
guess announcing new releases would belong to it, what else?

BTW, for the blog feed, one may want to keep the full history
somewhere in searchable form and with permlinks — that will be useful
(recently somebody was wondering were a old post he had seen was),
especially if the original blog post disappear...

**Comment by agarwal** [comment]
On Tue, Feb 5, 2013 at 10:53 AM, Christophe Troestler <
notifications@github.com> wrote:

> That crossed my mind too but currently what would you put in it? I
> guess announcing new releases would belong to it, what else?
- Ocaml Labs announces working groups.
- Next OCaml Users Meeting is in September!
- Help complete 99 Problems.

for the blog feed, one may want to keep the full history


Do you mean the proposed ocaml.org blog? Or all the Planet blogs? The
former should be automatic as we wouldn't delete posts. The latter is a bit
out of scope. We'd be serving as an archive of blogs across the internet.

**Comment by agarwal** [comment]
> On Tue, Feb 5, 2013 at 10:53 AM, Christophe Troestler <
> notifications@github.com> wrote:
> 
> what else?

And in the near future:
- ocaml.org gets a new design
- Real World OCaml now available!
- The OCaml Platform now available!

And we could back date some important items, like:
- Announcing OCaml Labs.
- And previous OCaml meetings.

**Comment by Chris00** [comment]
OK, I am convinced.  I'll see this weekend if I can implement something (no time before).

**Comment by agarwal** [comment]
@Chris00 Did you mean to close this issue? Your mention of it in #233 implies it should stay open.

**Comment by Chris00** [comment]
@agarwal Yes.  I thought that by the time we get the feed, this will be largely out of date.  I understand however that we may wish to keep "old" news in the feed.  The above commit creates a directory from which a script could generate the feed we want.

**Comment by agarwal** [comment]
Thanks. I'm happier with 4a98a82e6b0f53f066b762a614b9dddc5422f390. It keeps the announcement for us to incorporate somewhere.
