### ISSUE TITLE
Add Matrix Lead to companies page

### ISSUE THREAD

**Issue by chengtie** [ocaml/v2.ocaml.org#1077]
Hello,

We, at Matrix Lead (www.matrixlead.com), create tools around spreadsheets, to help people edit, verify and optimise their spreadsheets. Besides the tools listed on the website, there are also [10 Studio](https://appsource.microsoft.com/en-us/product/office/WA200000139) and [Funfun](https://appsource.microsoft.com/en-us/product/office/WA104381207).

The core analyser (by abstract interpretation) was initially developed in Inria, and of cause written in OCaml. Then, we wrap JavaScript or C# around that to make tools.

Additionally, Matrix Lead has a part in China, so that could be the first company followed by China in the companies page?

If you give the green light, I could provide you with a logo & description.

Thank you

Tie Cheng
CEO

**Comment by agarwal** [comment]
Hi Tie. Ideally, we could get a PR. Thank you. If that seems too hard, please provide the logo and description, and I can add it for you.

**Comment by chengtie** [comment]
> Hi Tie. Ideally, we could get a PR. Thank you. If that seems too hard, please provide the logo and description, and I can add it for you.

**Comment by chengtie** [comment]
(I closed the issue by mistake, then I reopened it)

I just created a PR. Could you check if it is OK?

Cheers

Tie

**Comment by Chris00** [comment]
PR merged.  Thanks.
