### ISSUE TITLE
http://ocaml.org/releases/ leads to 404

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#108]
Clicking on the releases item from the drop-down menu takes me to http://ocaml.org/releases/latest.html.  Editing the url to be http://ocaml.org/releases results in a 404 error.

I'd argue that parts of the url should have some page in case someone pokes around the way I did.

**Comment by amirmc** [comment]
> > On Tue, Feb 5, 2013 at 11:50 AM, Amir Chaudhry notifications@github.comwrote:
> > 
> > Clicking on the releases item from the drop-down menu takes me to
> > http://ocaml.org/releases/latest.html.
> 
> Are you sure about this one? It's working for me right now. In our source
> code, latest.html is a symlink, and when we publish it becomes a copy of
> 4.00.1.html?

Sorry, my note might be vague, I was only describing what I did.  More specifically, I clicked on the 'releases' item in the 'Use' menu from the nav bar. No problem here that I could tell :)

> > Editing the url to be http://ocaml.org/releases results in a 404 error.
> 
> Perhaps we should make releases/index.html a symlink to latest.html?

Or perhaps the other way around?  Do we need a 'latest' page?  I'd assume looking at a 'releases' page would show the current one anyway. 

> > I'd argue that parts of the url should have some page in case someone
> >  pokes around the way I did.
> 
> That sounds like a good URL design rule. I just looked, and I think the
> only other one that fails right now is http://ocaml.org/consortium/. This
> should probably redirect to the Consortium section on support.html.

Did google site search and found the licence file (http://ocaml.org/consortium/license.html), so I assume it's this one you meant.  I also noticed the breadcrumb trail has a 'Consortium' link in it which is more important than just my URL poking around.  Yup, pointing that to the support page makes sense as that's where the licence link lives.

Overall, I think it's worth looking at the site as a whole and figuring out the overall architecture/organisation of pages.  This will help with the site design too.  Not sure of the best way to begin this.  Perhaps by looking at an overall sitemap?

**Comment by amirmc** [comment]
> Are you sure about this one? It's working for me right now. In our source
> code, latest.html is a symlink, and when we publish it becomes a copy of
> 4.00.1.html?

I've only just understood what you meant (I think).  In my URL bar I definitely see http://ocaml.org/releases/latest.html and I can manually enter http://ocaml.org/releases/4.00.1.html and see the same page.  I assume this is expected behaviour?

**Comment by agarwal** [comment]
On Tue, Feb 5, 2013 at 12:45 PM, Amir Chaudhry notifications@github.comwrote:

>  Or perhaps the other way around? Do we need a 'latest' page?
> 
> I suppose that makes sense too, and we don't want 3 URLs all pointing to
> the same page. That's adding more confusion. I can change this.

I also noticed the breadcrumb trail has a 'Consortium' link

> Good catch, so we already have a broken link here.

Overall, I think it's worth looking at the site as a whole and figuring out

> the overall architecture/organisation of pages.
> 
> I started this here on the repo's wiki:
> https://github.com/ocaml/ocaml.org/wiki/URL-Scheme
