### ISSUE TITLE
dead link on page /learn/tutorials/file_manipulation.html

### ISSUE THREAD

**Issue by fccm** [ocaml/v2.ocaml.org#1080]
dead link on page /learn/tutorials/file_manipulation.html
"See Std.input_file and Std.output_file."
http://ocaml-extlib.googlecode.com/svn/doc/apiref/Std.html

Maybe we can replace it by:
https://github.com/ygrek/ocaml-extlib/blob/master/src/std.mli

**Comment by Chris00** [comment]
Thanks.
