### ISSUE TITLE
Release page for 4.08.1 is missing

### ISSUE THREAD

**Issue by clarksmr** [ocaml/v2.ocaml.org#1082]
The URL https://ocaml.org/releases/4.08.1.html returns a 404 Not Found.  That URL is linked to by 

- the [front page](https://ocaml.org) news item "Release of OCaml 4.08.1 June 14, 2019".  (N.B. I think June 14, 2019 is the release date for 4.08.0, and August 5, 2019 is the release date for 4.08.1, according to the [changes log](http://caml.inria.fr/pub/distrib/ocaml-4.08/notes/Changes).)
- the [install page](https://ocaml.org/docs/install.html)'s first paragraph, "The latest version of OCaml is 4.08.1. For more information about this release, see the 4.08.1 page."
- the [latest version](https://ocaml.org/releases/latest/) link

and probably others that I'm missing.

**Comment by pmetzger** [comment]
@clarksmr Do you think you could create such a page and submit a pull request? It might speed things up.
