### ISSUE TITLE
remove mantis mention

### ISSUE THREAD

**Issue by redianthus** [ocaml/v2.ocaml.org#1085]
On [this page](https://ocaml.org/community/mailing_lists.html), at the end, there's a section about Mantis, which is not used anymore. I don't know if there's other mentions of Mantis somewhere, but they all should be removed.

**Comment by pmetzger** [comment]
I don't suppose you could clone the repository, grep for mantis, and do a pull request with all such references fixed?

**Comment by pw374** [comment]
Someone could do it without `grep`, GitHub can be enough: https://github.com/ocaml/ocaml.org/search?p=1&q=mantis&unscoped_q=mantis

**Comment by Chris00** [comment]
It is still present on old release pages but I think it is fine as such.

**Comment by Chris00** [comment]
I also removed all mentions of the SVN repository.
