### ISSUE TITLE
Make a 404 page?

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#109]
Would it be worth making a 404 page?

Having it styled similarly to any of the other OCaml.org pages with some basic content that points people to the front page (or site index etc) might be more useful than getting the github 404.

**Comment by agarwal** [comment]
Makes sense to me. If you want to get fancy, it could automatically
generate search results the same way the search box on the top of the site
does.

**Comment by amirmc** [comment]
Relevant to #113

**Comment by gurleennsidhuu** [comment]
Hi. Is this issue still open? If yes, can an Outreachy applicant work on it?

**Comment by patricoferris** [comment]
@gurleennsidhuu sure go ahead, this could be a fix 8 years in the making haha :)) If you need some help with the build process (i.e. the `Makefile`) or anything else let me know.

**Comment by gurleennsidhuu** [comment]
I am not sure if I'm doing it right but this is what I designed.
![404](https://user-images.githubusercontent.com/64313783/113340772-ecd1cc00-9349-11eb-9c04-1857106b355e.png)

**Comment by patricoferris** [comment]
That looks good to me -- we probably don't need the breadcrumbs (`Home > 404page.md`) on this page, but it might be nice to add a link in the 404 message to home. Feel free to open a PR for this :))
