### ISSUE TITLE
ocaml doc: two "iterators" sections for List API

### ISSUE THREAD

**Issue by sanette** [ocaml/v2.ocaml.org#1095]
https://caml.inria.fr/pub/docs/manual-ocaml/libref/List.html

=> there are two sections called "Iterators" (due to the recent addition of Sequences at the end)

**Comment by pmetzger** [comment]
This might need reporting in the ocaml/ocaml repository instead?

**Comment by sanette** [comment]
you're probably right. I wasn't sure where to report this.
