### ISSUE TITLE
Bash on Windows installation tutorial link is broken

### ISSUE THREAD

**Issue by NikolasTzimoulis** [ocaml/v2.ocaml.org#1097]
On the [installation page](https://fdopen.github.io/opam-repository-mingw/installation/) there's a part that says:

> Use « Bash on Windows » and install OCaml as on Ubuntu. Main OCaml versions and OPAM work. The disadvantage of this method is that you don't build native Windows binaries but Linux binaries. See tutorial.

However the "see tutorial" link is broken, leads to some random spam.

**Comment by ahmadrasyidsalim** [comment]
@NikolasTzimoulis Yes the link is broken, but you can follow the step from this link: https://docs.microsoft.com/en-us/windows/wsl/install-win10 then install OCaml as on Ubuntu: https://ocaml.org/docs/install.html#Ubuntu-Ubuntu-19-10
```
sudo apt update
sudo apt install ocaml-nox # If you don't want X11 support.
sudo apt install ocaml
````
