### ISSUE TITLE
Broken link to Ocaml toplevel [install.html]

### ISSUE THREAD

**Issue by markvital** [ocaml/v2.ocaml.org#1099]
There is a broken link to Ocaml toplevel on the following page in "Browser" section:
[https://ocaml.org/docs/install.html#Browser](https://ocaml.org/docs/install.html#Browser)
<img width="593" alt="Screen Shot 2019-12-22 at 10 48 47 PM" src="https://user-images.githubusercontent.com/742796/71327818-a3bb8700-250d-11ea-8b1f-4dd73f30997c.png">
Clicking on the link "OCaml toplevel" gives 404 error

**Comment by citizen428** [comment]
I fixed that in #1098 which was just merged, so I guess this issue can be closed /cc @avsm

**Comment by avsm** [comment]
Thanks @citizen428!
