### ISSUE TITLE
Makefile.common is executed too many times

### ISSUE THREAD

**Issue by sanette** [ocaml/v2.ocaml.org#1105]
Because of the recursive structure of the Makefile (which calls make inside the Makefile),
it turns out that Makefile.common is executed for each processed file.
In this way, if you have 100 files to process, the command

`LATEST_OCAML_VERSION=$(shell opam list -V ocaml-base-compiler --no-switch -s --columns version | tail -n 1)`

is executed 100 times, which slows things down quite a lot.

**Comment by pmetzger** [comment]
Good catch.
