### ISSUE TITLE
404 Not Found for ocaml.org/releases/4.10.0.html

### ISSUE THREAD

**Issue by vp2177** [ocaml/v2.ocaml.org#1109]
[Link](//ocaml.org/releases/4.10.0.html)

Also, the [releases page](//ocaml.org/releases/) doesn't list 4.10.0.

**Comment by XVilka** [comment]
Should be fixed by https://github.com/ocaml/ocaml.org/pull/1106

**Comment by Chris00** [comment]
The PR is merged.
