### ISSUE TITLE
All links on the cheatsheets page are broken!

### ISSUE THREAD

**Issue by danysdragons** [ocaml/v2.ocaml.org#1126]
***All*** the links on the cheatsheet page https://ocaml.org/docs/cheat_sheets.html are currently broken.

**Broken**:

[The OCaml Language](http://www.ocamlpro.com/wp-content/uploads/2019/09/ocaml-lang.pdf)

[OCaml Standard Tools](http://www.ocamlpro.com/files/ocaml-tools.pdf)

[OCaml Standard Library](http://www.ocamlpro.com/wp-content/uploads/2019/09/ocaml-stdlib.pdf)

[OCaml Emacs Mode (Tuareg)](http://www.ocamlpro.com/files/tuareg-mode.pdf)

**Correct Links (2)**:

I was able to track down working links for “Ocaml Language” and “OCaml Standard Library”.

https://www.ocamlpro.com/wp-content/uploads/ocaml-lang.pdf

https://www.ocamlpro.com/wp-content/uploads/ocaml-stdlib.pdf

Unfortunately I didn’t have time to hunt around for working links to the other pages.

---
I did also find a link to a new Opam cheatsheet, which I don't think was ever on the cheatsheets page:

https://www.ocamlpro.com/wp-content/uploads/ocaml-opam-bw.pdf

**Comment by jimt** [comment]
The links to the cheat sheets appear to be fixed. I would suggest this can be closed.

**Comment by pw374** [comment]
Thanks
