### ISSUE TITLE
Certificate for www.ocaml.org is incorrect

### ISSUE THREAD

**Issue by eras** [ocaml/v2.ocaml.org#1127]
It instead provides the certificate of ocaml.org, which does not work for this domain it seems. The fix was apparently done in issue #1021 but perhaps it has broken at some point.

Steps to reproduce:
1) Visit https://www.ocaml.org/
2) Firefox says "SSL_ERROR_BAD_CERT_DOMAIN" that the certificate is only valid for ocaml.org

Expected: no error.

**Comment by avsm** [comment]
I'll fix this as part of https://github.com/ocaml/ocaml.org/issues/1178

**Comment by avsm** [comment]
Fixed.
