### ISSUE TITLE
Proposal: Setting up Your OCaml Environment

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/v2.ocaml.org#1137]
I have been asked by the OCaml Software Foundation https://ocaml-sf.org to have a go at producing a guide for ocaml.org for those new to OCaml, provisionally entitled ``Setting up your OCaml environment''.

Please let me have any feedback in the next couple of weeks, so I can avoid making mistakes which might prevent its merging later.

### Introduction

When beginning a new language, starting by looking at its homepage (for us, [ocaml.org](ocaml.org)), beginners at programming and existing programmers who are beginning with a new language, are very easily put off if they cannot install a compiler and associated tools (build system, package manager, editor support). We know this in the case of OCaml because of how often these pain points come up on OCaml community discussion boards, and bugtrackers, and on places like StackOverflow.

We will propose a structure for a document, to be hosted on [ocaml.org](ocaml.org) which has the right content, the right tone, and which is tested, kept up-to-date, and well-organised.

This is not cut and dried: it is messy. We will have to make some choices on what to recommend and what not to recommend. Testing will be required on many platforms, especially on the perennial troublemaker, Windows.

### What's currently available

- [https://ocaml.org/docs/install.html](https://ocaml.org/docs/install.html) This page describes how to get the OCaml compiler installed, either via OPAM, or via package managers. It describes several Windows possibilities, and links to ways to use OCaml in the browser. 

- [https://opam.ocaml.org/doc/Install.html](https://opam.ocaml.org/doc/Install.html) Installation of OPAM through a convenient binary distribution, or from Linux package managers, or from source. No mention of Windows (we could just add this?)

- [https://ocaml.org/learn/tutorials/get_up_and_running.html](https://ocaml.org/learn/tutorials/get_up_and_running.html) This is, partly, the sort of thing we should like to write. It is, however, judged too opinionated by the \texttt{ocaml.org} developers, and it is out of date (oasis, ocamlbuild etc.).

- [https://ocaml.org/learn/tutorials/setting_up_with_oasis.html](https://ocaml.org/learn/tutorials/setting_up_with_oasis.html) From the tutorial. The community has settled on Dune (for now!) so this should probably be rewritten.

- [https://dev.realworldocaml.org/install.html](https://dev.realworldocaml.org/install.html) From the upcoming new version of ``Real World OCaml''.

- [https://github.com/janestreet/install-ocaml](https://github.com/janestreet/install-ocaml) A recent document from one of OCaml's largest industrial users. Actually mentions Windows!

#### What do other language communities do? -- Haskell

[https://www.haskell.org/downloads/](https://www.haskell.org/downloads/) Good summary page, but links to other resources mostly, rather than taking the user through it. Recommends both Stack and Cabal: [https://www.haskell.org/cabal/](https://www.haskell.org/cabal/) [https://www.haskell.org/cabal/](https://docs.haskellstack.org/en/stable/README/)

#### What do other language communities do? -- Python

[https://www.python.org/about/gettingstarted/](https://www.python.org/about/gettingstarted/) Mostly links to wiki, e.g to page about downloading and installing [https://wiki.python.org/moin/BeginnersGuide/Download](https://wiki.python.org/moin/BeginnersGuide/Download) or editor integration [https://wiki.python.org/moin/PythonEditors](https://wiki.python.org/moin/PythonEditors) or IDEs supporting Python [https://wiki.python.org/moin/IntegratedDevelopmentEnvironments](https://wiki.python.org/moin/IntegratedDevelopmentEnvironments)

#### What do other language communities do? -- Go

Go includes its own package manager and so on, so things are more self-contained: [https://golang.org/doc/install](https://golang.org/doc/install) . Describes uninstallation -- we should too! Shows how to report bugs with `go bug` -- lots of things are subcommands of `go`, which is nice. We don't have that with OCaml though, so we must accept it.

#### What do other language communities do? -- Rust

Instructions extremely simple in the easy case: [https://www.rust-lang.org/tools/install](https://www.rust-lang.org/tools/install) Full instructions: [https://forge.rust-lang.org/infra/other-installation-methods.html](https://forge.rust-lang.org/infra/other-installation-methods.html) Packages: [https://doc.rust-lang.org/cargo/index.html](https://doc.rust-lang.org/cargo/index.html). Very comprehensive, but pretty fragmented.

### Scope and design considerations

- Support all platforms throughout esp. Windows.
- Include screenshots where appropriate - but not too many (they lengthen the page)
- Can we keep it to one easily-navigable page. Multipage instructions can be tedious to follow.
- Verify all information by use of virtual machines to try things out.t
- Give a standard way (e.g dune not OCamlbuild), but link briefly to alternative where there is no community consensus. In other words, be opinionated but not exclusionary.
- Build the structure, in so far as is possible, to be easy to update. It will not always be me doing the updating.
- Two stage process: 1) write the document and get it accepted; and 2) retool the rest of the website around it with any tweaks needed to keep consistency and avoid confusing duplication.
- The scope is setting up an OCaml environment. It does not overlap with the other document we propose, about Learning OCaml. Keep this separation pretty rigid -- one depends on the other, of course. But even so.

### Outline

- Installing OCaml. Point to OPAM page. Mention other mechanisms without OPAM. Point to an up-to-date canonical Windows version to use. List architectures.

- The top level. rlwrap. utop. The .ocamlinit file.

- Using the compilers (without dune). Just a simple example showing a bytecode or native executable being produced. OCamlrun.

- Building with dune! Structuring your project. Adding information for ocamlfind and OPAM. Building documentation.

- Editor support (all platforms, emacs + vim + visual code + whatever else)

- Appropriate .gitignore. - anything else about working with git?

- Installing an example library from OPAM, and using it when building a project with dune and from the top level.

- Standard Library replacements (what fun)

- Where to go for more information

- Uninstallation

**Comment by sanette** [comment]
thanks for the work. Just some remarks from my experience.

* concerning opam and dune
I was really nicely surprised when I finally decided to switch to dune. However it took me some time to realize that, when you have several personal packages that you want to use in a personal project, the simplest, by far, is to install them locally using opam with `opam install .`. Then you may refer to them in your new dune files just like any other "normal" package.

* concerning git
Maybe I did something wrong, but here is a caveat that costed me a couple of hours of puzzlement, and may be worth mentioning. If you develop in a git-handled directory, you may use `dune build`: it will build with whatever files are in the directory. But if you do 'opam install .` it will only complile and install files that are git-committed. In fact it is a nice feature because you are sure that the steps will be reproducible by others when you push to github, but it can be confusing at first.

* installing opam
Since this is the recommended way to install ocaml, I would vote in favor of including "The quickest way to get the latest opam up and working" within `ocaml.org`, instead of immediately force the user to visit another website.

**Comment by gypsydave5** [comment]
Hi - I started learning OCaml 14 days ago. I followed the both the Real World OCaml instructions, installing opam and setting up Emacs on a Mac. I've programmed in a number of languages and have experience of reading lots of 'getting started guides'. Here's a few thoughts.

Setting up OCaml is actually _really easy_ - the community has done a good job here. You should boast about it! Rust is a good example - run this simple shell script and off you go. The experience with opam is similiar but slightly buried in the docs - try and lead with it. It's good and opinionated.

Opinionated is _good_. People who want to set up their editor/environment in their own way will have fun going through the docs to get what they need.

I really admire the way that the `opam install user-setup` script was both opinionated and worked. Having tried to start using Haskell a few times I always feel I'm sucked into the minutiae of editor set up. This way I was up and running in minutes. I cannot comment on the VS Code or Vim set ups, but I think the idea of 'getting it done' and then getting out of the way is the right approach - and again something to be proud of.

**Comment by agarwal** [comment]
Please consider also how [esy](http://esy.sh/) might fit into this page.

**Comment by johnwhitington** [comment]
This work was merged.
