### ISSUE TITLE
Link "Release of OCaml 4.11.0" (News) is broken

### ISSUE THREAD

**Issue by OnkV** [ocaml/v2.ocaml.org#1145]
The link "Release of OCaml 4.11.0" in the news section on the start page is broken:
https://ocaml.org/releases/4.11.0.html

**Comment by pw374** [comment]
Hopefully merging https://github.com/ocaml/ocaml.org/pull/1142 is enough to fix this.

**Comment by pw374** [comment]
It seems it worked. Closing this. Thanks!
