### ISSUE TITLE
deprecate caml.inria.fr

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#115]
All html pages from caml.inria.fr have been ported to ocaml.org. As discussed with Xavier, it will be best to leave caml.inria.fr as-is since many old links still point to it. However, we should mark it deprecated by adding a banner to the top of all caml.inria.fr pages that says something like "This site is deprecated. Please visit the new ocaml.org site." Possibly, we can submit a pull request directly to their svn repo, which can be obtained by doing:

```
svn co http://caml.inria.fr/svn/website/trunk
```

**Comment by arcanis** [comment]
Can't you just send an redirect header toward the right domain ?

**Comment by agarwal** [comment]
That would make the old site disappear, which is not the intention. The old
site has been around for a long time, and numerous links to its pages exist
on the internet. The idea is to leave caml.inria.fr as-is, but point out
visually on its pages that the site is deprecated.

**Comment by Chris00** [comment]
Related to https://github.com/ocaml/ocaml.org/issues/100 (one email for both).

**Comment by agarwal** [comment]
I think this will require us to provide a patch to the Inria site. Just asking them to do it might not be enough.

**Comment by agarwal** [comment]
To clarify this request, all URLs under caml.inria.fr except caml.inria.fr/pub should be deprecated. The `pub/` directory contains static files, which we continue to link to from ocaml.org.

**Comment by agarwal** [comment]
Damien said he could work on this. I've sent him this html snippet to use:

```
<p style="color:red">
This site is deprecated and will no longer be updated. Please visit
the new OCaml website at <a href="http://ocaml.org">ocaml.org</a>.
</p>
```

**Comment by amirmc** [comment]
Dear @planar, I hope you don't mind me tagging you on the GitHub issue this way. It seemed the best way to bring you into the thread.

I was wondering where things stand with the HTML snippet that Ashish mentioned.  As I understand, everything has already been agreed, so it's only a matter of implementation.  I'm not sure of the complexities involved, since I'm unaware of how the original site is put together. 
If there's something we can do to help with this, please do let us know.

Best wishes,
Amir

**Comment by damiendoligez** [comment]
Thanks for reminding me. I've added the snippet to the page header. Please tell me if it's OK like that.

**Comment by agarwal** [comment]
I feel it's not visible enough. I could imagine people not seeing it at all. How about making the style: "color:red; font-size:300%".

**Comment by damiendoligez** [comment]
300% was really too big, so I set it to 200.

**Comment by agarwal** [comment]
Thanks. It is certainly visible now.

**Comment by amirmc** [comment]
Great! Thank you all!

I can update the links on the Wikipedia page now :)

Best wishes,
Amir

## 

sent via mobile

**Comment by damiendoligez** [comment]
Note: I changed the wording on Xavier's suggestion.

**Comment by johnwhitington** [comment]
It is worth noting that there are lots of references to images hosted on caml.inria.fr on, for example, the learn/books.html.

So, if caml.inria.fr ceased to exist, some of our pages would be broken.

**Comment by Chris00** [comment]
We should probably host all images of that page — most of them would not even be downloaded in HTTPS mode.

**Comment by agarwal** [comment]
> if caml.inria.fr ceased to exist

That is unlikely. The Inria team specifically asked us to not take over many of the files hosted there (such as tarballs of the releases) because they want to keep managing them there. We never considered the https issue though, so perhaps now we do need to replicate some of the content.

As a reminder, everything under `caml.inria.fr/pub` is considered valid by ocaml.org, i.e. we do link to it. Links to any other URL under `caml.inria.fr` is considered an error, as ocaml.org has superseded it.

**Comment by avsm** [comment]
How about just providing an rsync mirror of caml.inria.fr into a sub url of ocaml.org? More mirrors of the core distfiles is always useful.

Anil

**Comment by dsheets** [comment]
#515 was tracking the https issue.

**Comment by agarwal** [comment]
> How about just providing an rsync mirror of caml.inria.fr into a sub url of ocaml.org?

That's not a bad idea, but we should only rsync the `pub/` directory. No point in having multiple copies of deprecated stuff. I've opened #664 to track this new request.
