### ISSUE TITLE
Broken external links

### ISSUE THREAD

**Issue by Khady** [ocaml/v2.ocaml.org#1158]
Follow up on https://github.com/ocaml/ocaml.org/pull/1150

|URL                                                         |External outlinks to 4xx                                                                                                                                                                                                 |
|------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|https://ocaml.org/learn/                                    |http://www.codecodex.com/wiki/Category:Objective_Caml                                                                                                                                                                    |
|https://ocaml.org/learn/taste.html                          |http://www.codecodex.com/wiki/Category:Objective_Caml                                                                                                                                                                    |
|https://ocaml.org/learn/index.fr.html                       |http://www.codecodex.com/wiki/Category:Objective_Caml                                                                                                                                                                    |
|https://ocaml.org/learn/tutorials/setting_up_with_oasis.html|https://github.com/mirage/ocaml-cohttp/blob/master/_oasis https://github.com/ocsigen/lwt/blob/master/_oasis https://github.com/ocsigen/lwt/blob/master/dist.sh https://github.com/ocsigen/tyxml/blob/master/Makefile.dist|

**Comment by avsm** [comment]
These are all now fixed. Thanks @Khady and @johnwhitington for the fixes!
