### ISSUE TITLE
what to do about the Hump

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#116]
To be comprehensive in our port of caml.inria.fr, we should consider also the Hump. Is there content in it that would be valuable to port? Or does the publication of ocamlpro/opam-repository information on to the web make it obsolete?

**Comment by avsm** [comment]
I have "look over the hump and import historical packages into OPAM" on my todo list.

But we can certainly generate an excellent trove out of OPAM as soon as the new templates/mockups are ready.
(i.e. merge opam2web with ocaml.org)

-anil

**Comment by samoht** [comment]
Currently the HUMP has a big advantage over OPAM metadata: it has author and homepage information (but it's usually broken). My goal is indeed to transfer these metadata into the package descriptions but that's not something that you can automate easily.

**Comment by avsm** [comment]
I think we'll need a bit of a collaborative beer+hackathon-fest before 1.0 to get this done manually :-)

**Comment by zoggy** [comment]
So I see that you already planned to merge hump info into Opam. One way to semi-automate this would be to export each hump entry X into some tmp-X directory in opam format, then move this directory to the final name.
Regarding information in Opam packages, I understood you already planned to add author, homepage and RSS feed. What about license and "kind" (ocaml library, c-binding, application, ...) ?

**Comment by samoht** [comment]
The license field is already there. For the kind, what not simply use the tags ?

Also, I really like the idea of @avsm to create a separate OPAM repository for packages in the hump but not properly migrated into OPAM yet, and to display the metadata on opam.ocamlpro.com.

**Comment by zoggy** [comment]
Having only tags won't make a trove map, i.e. you can't distinguish tags regarding "kind" from tags regarding "domain". IMHO that is not important since "kind" tags rarely conflict with domain tags. I like @avsm idea too. But will the "new hump" appear on ocaml.org too ?

**Comment by agarwal** [comment]
On Mon, Mar 18, 2013 at 5:25 AM, zoggy notifications@github.com wrote:

> Having only tags won't make a trove map, i.e. you can't distinguish tags
> regarding "kind"
> 
> But can you fully define the terms comprising "kind"? Just using tags
> sounds more straightforward for now.

But will the "new hump" appear on ocaml.org too ?

> Yes. The next phase of ocaml.org includes integration of opam package
> information. I see no reason why two repos couldn't be used. To avoid
> confusion, a distinction should be made as to which ones are "real"
> packages and which ones are just informational.

**Comment by agarwal** [comment]
Is anyone seriously interested in exporting data from the Hump to OPAM still? If so, please say soon. Else, I'd like to close this issue. Note that I've described the Hump as deprecated [here](http://ocaml.org/learn/libraries.html).

**Comment by agarwal** [comment]
I'm reasonably confident there is no interest in doing this, so closing this issue.
