### ISSUE TITLE
Recommended building process for ocaml.org

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/v2.ocaml.org#1162]
I want to see my .md changes reflected in HTML as quickly as possible. Is there a way other than just running `make -j9` each time, which takes more than two minutes on my machine?

What process do `ocaml.org` developers use?

Is there a makefile target I'm missing which generates just the HTML from the .md files, but ignores all the other work (i.e downloads from the internet)? Are any of the other makefile targets useful on their own? If so, can we document them?

**Comment by Chris00** [comment]
The environment variable `SET_STAGING` set by the default make target is supposed to accelerate things.  Given what you say, it may not be optimally taken into account by scripts, which do most of the downloading (the result of which is cached for 1h if my memory serves).  I recompiled the site right now and noticed no downloading but the part that is taking time is the processing of URLs to make them relative (so the site can be navigated locally).  Use `make staging` to avoid that.


P.S. The latest Git commit 8162ce81 does not compile for me, `rss2html.ml` triggers `Error: Unbound module Ssl`.  I have no time to fix it right now unfortunately.

**Comment by johnwhitington** [comment]
Thanks. I will try to produce a patch to allow one to skip the script/relative_urls: frequently I just want to view the page I have edited, not navigate anything.

**Comment by avsm** [comment]
I'm looking at the fix to the website to get it updating again (see https://github.com/ocaml/ocaml.org/issues/1178) -- should have that in a day or two I hope @Chris00!  I've got a broader patch to port the website build to dune, but that will take some time and testing to settle down, so for the moment patching the Makefile should be fine @johnwhitington.  I'll rebase my dune port and open a WIP PR that I can rebase against any such changes in trunk.

**Comment by johnwhitington** [comment]
Unfortunately, if we skip the script, even a single page is not viewable properly, since the CSS can't load. So, I need to look at either (a) speeding up script/relative_urls if it is inefficient, or (b) having it run only on a given file.

(By the way, when I load the site locally, I always get a different body font compared with loading ocaml.org itself. Anyone else?)

**Comment by sanette** [comment]
> (By the way, when I load the site locally, I always get a different body font compared with loading ocaml.org itself. Anyone else?)

I get the correct font. The font is loaded by the CSS, so it's maybe related to your other question
