### ISSUE TITLE
books.html: import pdfs directly to server

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#12]
Write now links to books point to external URLs. It would be better to organize all PDFs into a location on the web server, and provide internal links.

**Comment by Chris00** [comment]
Well, we will not be adding the books to the repository!  So what does this mean as long as we do not have a server...?
Also, one should be careful to ask the authors whether they agree we do that.

**Comment by agarwal** [comment]
Right, this is a reminder to do it when we have a server.

**Comment by agarwal** [comment]
Linking to external content is now widespread throughout ocaml.org. We have videos on youtube, cheat sheets on ocamlpro.com, etc. and so this request now seems outdated. It was motivated by a desire to have everything self contained, which is not feasible (a good sign that the content on the site has grown a lot). Thus, closing this issue as a _will-not-do_.

**Comment by dsheets** [comment]
We might want to implement a broken link checker at some point in the future.

**Comment by avsm** [comment]
We might even want to implement a working link checker at some point too.

_shows himself to the door_
