### ISSUE TITLE
Update index page news feed logic to use discuss + tagged topics

### ISSUE THREAD

**Issue by ghost** [ocaml/v2.ocaml.org#1212]
Change the index.md news feed logic to do the following:
1. Keep the existing ability to hardcode announcements inline
2. Change from automatic fetch of latest planet posts to automatic fetch of all posts tagged with "publish-to-ocaml-org" on discuss.ocaml.org.

The end result behavior will be similar, as most people who post to their blog can simply link to their post in discuss and message admins if they want it highlighted on ocaml.org, but now fresher content from discuss can also be included.

Actions:
- remove use of rss2html to fetch from ocaml planet in index.md
- create new script discourse-tagged-topics which parses discourse json for a list of posts (possibly calling out to curl and jq), and outputs html formatted list of entries, similar to rss2html output
- use new script from index.md

**Comment by ghost** [comment]
There has also been talk of using a separate git repo to house the data, connect to this repo as a submodule. I am not clear on the benefits and the need for any storage to disk/git

**Comment by Chris00** [comment]
What would the planet become in such a scenario?  How does this articulate with https://ocaml.org/community/?

**Comment by ghost** [comment]
Under this scenario, I think planet would stay as is, and still be available through its dedicated page. The "news feed" on the community page can stay dedicated to planet and some announcments. The box on the homepage can be called something else like "announcements and discussion highlights". I'll leave it up to others to decide overall on these points and whether to actually adopt this or just leave it as a prototype for future consideration.

**Comment by ghost** [comment]
Here's some sample code that gets 80% there:

```
$ wget -qO- https://discuss.ocaml.org/tag/batteries.json | jq '.topic_list.topics | .[] | {id: ["https://discuss.ocaml.org/t/", (.id | tostring)], title: .title, created_at: .created_at} | {url: .id | add, title: .title, created_at: .created_at} | ["<a href=" , .url , ">", .title, "</a>", " " , .created_at ] | add'
"<a href=https://discuss.ocaml.org/t/6738>[ANN] latest batteries release: v3.2.0</a> 2020-11-11T01:16:41.017Z"
"<a href=https://discuss.ocaml.org/t/4871>[ANN] batteries batteries.2.11.0</a> 2019-12-17T01:32:53.968Z"
"<a href=https://discuss.ocaml.org/t/4261>[ANN] release of batteries v2.10.0</a> 2019-08-19T08:30:47.879Z"
"<a href=https://discuss.ocaml.org/t/1192>Equality of LazyLists</a> 2017-11-24T18:30:02.782Z"
"<a href=https://discuss.ocaml.org/t/1097>Why is Batteries.LazyList.map2 not lazy?</a> 2017-11-10T20:32:40.782Z"
"<a href=https://discuss.ocaml.org/t/1094>Batteries.LazyList.lazy_fold_right?</a> 2017-11-10T14:53:52.048Z"
"<a href=https://discuss.ocaml.org/t/432>Example or tutorial on Batteries.OptParse</a> 2017-06-17T04:19:38.866Z"
```

**Comment by ghost** [comment]
@avsm does this meet the requirements well enough or is there some subtlety that I missed? If it's accurate, then I will finish it up to be fully functioning

**Comment by ghost** [comment]
Related: https://github.com/ocaml/ocaml.org/issues/393

**Comment by ghost** [comment]
This was to track an interest that Anil mentioned. Can reopen whenever there is time to finalize requirements.
