### ISSUE TITLE
Download link missing (or hard to find)

### ISSUE THREAD

**Issue by suany** [ocaml/v2.ocaml.org#1215]
In https://ocaml.org/docs/install.html, under From Source, it says to "Download an OCaml Release", which links to https://ocaml.org/releases/, but none of the pages under releases has an obvious link to download a distribution. The distrib link is hidden in the "Earlier releases are available here" bullet at the bottom of releases/.

**Comment by ghost** [comment]
So each link in the release notes should have two links?
`
OCaml 4.11.1(release notes link, source tarball link), released Aug 31, 2020.
`

Should the source download link be from inria or github releases?

**Comment by avsm** [comment]
That's right -- two links is fine. The source download link should be from GitHub Releases.

**Comment by rockingrohit9639** [comment]
Hii There, Can you please assign this to me?

**Comment by patricoferris** [comment]
Hi @rockingrohit9639 👋 

Thanks for taking interest in this issue. There's no need for assignment to contribute :)) So if you want to open a PR and reference this issue that would be great! Feel free to ask any question on the PR or this issue if you are having trouble, we appreciate getting started isn't necessarily as straightforward as other sites.

**Comment by victorphoenix3** [comment]
@rockingrohit9639  if you are not working on this issue may I submit a PR?

**Comment by patricoferris** [comment]
Fixed in #1256
