### ISSUE TITLE
Add instructions for inspecting build logs for staging build

### ISSUE THREAD

**Issue by ghost** [ocaml/v2.ocaml.org#1218]
For people submitting PRs, occassionally they may want to read the build log output if there is a failure to deploy to staging.ocaml.org . Under the "maintainers" section, add one sentence explaining how to view the logs for a given deploy to staging. @avsm

**Comment by patricoferris** [comment]
It might also be worthwhile (unless it exists somewhere I can't see) adding a pre-PR checklist. For example it might be useful to add a "test it locally" with something like: 

```
💻  ~ docker build . -t ocamlorg 
💻  ~ docker run -it -p 8080:8080 ocamlorg 
🐳  ~ cd ocaml.org && cohttp-server-lwt -s 0.0.0.0
```

Then go to localhost:8080.

**Comment by ghost** [comment]
If the site ends up using Vercel or Netlify, the instructions can link directly to the Vercel or Netlify documentation page for viewing logs. I'll close this for now and reopen if `ocurrent` is used in the future.
