### ISSUE TITLE
upgrade to support rss 2.1.0

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#122]
The ocamlrss 2.1.0 library introduces [backwards incompatible changes](http://zoggy.github.com/ocamlrss/) that break our code.

**Comment by agarwal** [comment]
For now, constrained rss version to be <= 2.0 in e043d1ff940355beb13c305719f5c80fe5d8f8e2.

**Comment by Chris00** [comment]
Do we expect everybody to upgrade?  If so I'll make the necessary changes in "master".

**Comment by agarwal** [comment]
Not sure how much use rss has in other projects. Version 2.1.0 is the one
in opam, so I'm inclined to say we should transition.

**Comment by amirmc** [comment]
Possibly random question. Anyone ever looked into Atom feeds? 

http://stackoverflow.com/questions/6619717/what-is-the-difference-between-rss-and-atom-feeds

**Comment by avsm** [comment]
Cow has an Atom module we use for the mirage website...

**Comment by Chris00** [comment]
Fixed in commit a46ceb691f06c70f0e756bc51dbba1d03ba27dd8

**Comment by Chris00** [comment]
@amirmc Please re-raise your question about Atom feeds in a new issue — I will close this one.
