### ISSUE TITLE
Use Atom feeds?

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#123]
Opening a thread having mentioned Atom feeds in #122 
Not sure if it's actually relevant as I didn't notice any ocaml.org feeds.

Curious to know what people think.

http://stackoverflow.com/questions/6619717/what-is-the-difference-between-rss-and-atom-feeds

**Comment by dbuenzli** [comment]
The answer on SO pretty much sums it up. The advantage of Atom is that was somehow _designed_ by people that suffered at little bit less brain damage, but only a little. It uses much saner conventions (e.g. RFC 3339 for dates) and is much less ambiguous from a specification point of view which makes it less likely that other consumers missinterpret your content. I don't think there's any point in using RSS if you start from scratch.

**Comment by Chris00** [comment]
WIP in https://github.com/ocaml/ocaml.org/tree/syndic

**Comment by amirmc** [comment]
`syndic` branch has been merged into `master` as part of the reimplementing of OCaml Planet. Closing this issue.
