### ISSUE TITLE
Footer width on mobile

### ISSUE THREAD

**Issue by patricoferris** [ocaml/v2.ocaml.org#1237]
This would be a **good first issue** for anyone looking to get started improving and contributing to OCaml.org.

Currently when viewing the site on a mobile device (or from some quick testing anything less than `768px` in width) the footer no longer stretches completely across the bottom leaving some white margins on either side. I believe it would look better if it (like on larger screen sizes) stretched completely across the bottom. 

### Before 

<img width="329" alt="Screenshot 2021-02-09 at 11 59 30" src="https://user-images.githubusercontent.com/20166594/107360755-45b18080-6ace-11eb-983a-30163cb81ffa.png">

### After 

<img width="318" alt="Screenshot 2021-02-09 at 12 06 50" src="https://user-images.githubusercontent.com/20166594/107361450-4d255980-6acf-11eb-9b73-3fcf745f3167.png">

It may be useful to look into how other full width elements get around this problem such as the navbar at the top.

**Comment by Shubham-Vishwakarma** [comment]
@patricoferris 
I would like to analyse this first, before taking it up
I am very much new to ocaml
But would like to give it try

**Comment by Shubham-Vishwakarma** [comment]
I think I am able to find the issue

In bootstrap.css, there is padding-left and padding-right defined for smaller screen

@media (max-width: 767px) {
  body {
    padding-left: 20px;
    padding-right: 20px;
  }
....... }

If we remove this the footer will be fixed, but other elements will be affected

We could override this in ocamlorg.css where other footer.css are defined
This will fix the issue

@media (max-width: 767px) {
  #footer {
    margin-left: -20px;
    margin-right: -20px;
  }
..........}


Please let me know if this solution will be acceptable, and it's correct way to do it
If everything looks good, please let me know, I will raise a PR

**Comment by patricoferris** [comment]
Hi @Shubham-Vishwakarma thanks for the contribution 🎉 

This is looking good to me, in fact it is how the navbar does it https://github.com/ocaml/ocaml.org/blob/master/site/css/bootstrap.css#L6708-L6713 so I don't think anyone would have anything against this. 

A good next step will be the raise that PR then we can push it to `staging` to double-check everything looks good and then hopefully merge!

Thanks again for doing this.

**Comment by Shubham-Vishwakarma** [comment]
@patricoferris I have created PR to staging branch
Please let me know, if this solves the issues

Thanks for guidance,

**Comment by Shubham-Vishwakarma** [comment]
My PR shows error
Will you please guide me.
How to resolve these things

![image2](https://user-images.githubusercontent.com/25884741/109182217-c6e96280-77b2-11eb-9953-aaef41b772a6.png)

**Comment by patricoferris** [comment]
@Shubham-Vishwakarma thanks for the PR! Looks like it's a problem with our CI infrastructure (in particular the dockerfiles) https://deploy.ocamllabs.io/job/2021-02-25/160625-ocluster-build-8d226d nothing you did 😁  

Looking into it now :))

**Comment by Shubham-Vishwakarma** [comment]
@patricoferris 
https://github.com/ocaml/ocaml.org/pull/1239: You have fixed the issue

Do I need to commit again? or you/someone else will verify the changes and merge it

**Comment by patricoferris** [comment]
No need to commit again, once that fix is in we can double-check this in staging and merge. Thanks again for the contribution.

**Comment by Shubham-Vishwakarma** [comment]
@patricoferris @avsm 
Just wanted to check status on this.

Is this now merged?

**Comment by meenal06** [comment]
Can we close this issue, as the fix is already merged?

**Comment by DivyanshiSingh** [comment]
May I know the status of this issue? Is it open to work @patricoferris

**Comment by patricoferris** [comment]
Sorry, yes this issue was fixed in #1238 thanks @Shubham-Vishwakarma and for the reminded @meenal06. Sorry @DivyanshiSingh we're trying to make more issues.
