### ISSUE TITLE
Keep header when redirecting to opam.ocaml.org

### ISSUE THREAD

**Issue by gs0510** [ocaml/v2.ocaml.org#1246]
When you click on the `packages` tab on `ocaml.org`, it redirects you to `opam.ocaml.org`, it would be nice if there's still the `ocaml.org` header so that the user can go back to the `ocaml.org` website.

**Comment by 0xull** [comment]
The `ocaml.org` header would work perfectly but the idea won't be to "go back to" `ocaml.org` but a link to `ocaml.org` as parent website to the `opam.ocaml.org`. With this, the UX would be well intuitive.

@patricoferris I would love to work on this if you approve on it, then discuss better what the UI would look like.

**Comment by gs0510** [comment]
@Muskan-sam Have you had any progress with the issue? :)

**Comment by dinakajoy** [comment]
I think the best thing to do is open the link on a new tab. Opam website is totally different from ocaml with their individual subsections. Users simply close the tab, return to ocaml and pick up from where they left off when they are done with the content they need on opam.

**Comment by Muskan-sam** [comment]
> @Muskan-sam Have you had any progress with the issue? :)

@gs0510 Instead of keeping the ocaml.org header, I was asked to make the external nature of  `packages`  navigation item of the  navigation bar visible by marking it with an external link icon ( issue : #1308) . I have already submitted a PR for that.

**Comment by patricoferris** [comment]
Changing the header on `opam.ocaml.org` isn't quite in our control because of the different deployment method so I'm going to close this issue for now.
