### ISSUE TITLE
"The Basics" tutorial is using a deprecated function  

### ISSUE THREAD

**Issue by kototama** [ocaml/v2.ocaml.org#1250]
I'm reading https://ocaml.org/learn/tutorials/basics.html. There is an example on how to use `float_of_int`. When trying in utop I get this warning:

```
utop # float_of_int 2;;
Line 1, characters 0-12:
Alert deprecated: Base.float_of_int
[2016-09] this element comes from the stdlib distributed with OCaml.
Use [Float.of_int] instead.
Line 1, characters 0-12:
Alert deprecated: Base.float_of_int
[2016-09] this element comes from the stdlib distributed with OCaml.
Use [Float.of_int] instead.
- : float = 2.
```

**Comment by patricoferris** [comment]
Hi @kototama,

It looks like you are using Jane Street's standard library alternative (probably [Core](https://opensource.janestreet.com/core/) but this is related to [Base](https://opensource.janestreet.com/base/)) -- this is what is used in the popular [Real World OCaml](https://dev.realworldocaml.org/) book. Is this correct? Their `float_of_int` is deprecated in favour of `Float.of_int`. OCaml's standard library `float_of_int` is not deprecated and shouldn't be giving any such warnings.

It sounds like you have maybe opened base or core (`open Base;;`) which would give you those standard library functions. You can choose the default standard library version even if `Base` is open by calling `Stdlib.float_of_int`. Hopefully this clears things up :))?

**Comment by kototama** [comment]
Ah, my mistake. Sorry for that. I had some initial code in `utop` that I forgot! Thank you :-).
