### ISSUE TITLE
All pages in ocaml.org/releases/4.12/api/index.html have a wrong link to ocaml.org/releases/4.12/manual/index.html

### ISSUE THREAD

**Issue by Naereen** [ocaml/v2.ocaml.org#1257]
Hello there,
As noted here https://github.com/ocaml/ocaml/issues/10278#issuecomment-792942227, from the newest 4.12 version of the manual, all pages in <https://ocaml.org/releases/4.12/api/index.html> have a wrong link to <https://ocaml.org/releases/4.12/manual/index.html>, which is not a 404 error but an empty page (as well as <https://ocaml.org/releases/4.12/manual/>, <https://ocaml.org/releases/4.12/>).
See this tiny GIF:
![Peek 08-03-2021 23-10](https://user-images.githubusercontent.com/11994719/110388521-8536a280-8063-11eb-911b-383371294de0.gif)
Apparently, except for the API pages, the link associated to the OCaml logo is directly to <https://ocaml.org>, but on the [OCaml API](https://ocaml.org/releases/4.12/api/index.html) or [OCaml API compiler](https://ocaml.org/releases/4.12/api/compilerlibref/index.html) the link is pointing to <https://ocaml.org/releases/4.12/manual/index.html> which does not exist.

**Comment by Naereen** [comment]
Oups sorry @avsm, I didn't notice that you mentioned the ocaml*.org* repository, and not the ocaml one, sorry!

**Comment by jyotibalodhi** [comment]
Hello @Naereen, I would like to work on this issue. Kindly let me know how should I proceed with this.

**Comment by Naereen** [comment]
Hi @jyotibalodhi,
I have absolutely no idea, I opened this.

**Comment by Octachron** [comment]
It is an issue of backward compatibility between the new postprocessed manual and the previous version. One potential short solution that might be worth some investigation would be to make `releases/4.12/manual` a symlink to `release/4.12/htmlman`.
