### ISSUE TITLE
Improve the Success Stories page

### ISSUE THREAD

**Issue by patricoferris** [ocaml/v2.ocaml.org#1258]
There are probably other success stories we would want to add, but for this issue if we could tidy up the [success stories](ocaml.org/learn/success.html) page that would be great.

There are two main issues I can see (happy to have further improvements too): 

 1. On mobile devices, the logos/images associated with each success story could have a better layout to avoid small bits of text appearing beside them. For example:

<img width="308" alt="Screenshot 2021-03-09 at 09 39 34" src="https://user-images.githubusercontent.com/20166594/110452587-3c133c80-80bd-11eb-84d3-d182d5879350.png">

2. Some of the stories link to images that don't exist (e.g. the coq proof assistant) -- we should probably find and add these images folder.

@yashi-hub would you be interested in taking a look at this in relation to #1245? If yes or no please leave a comment below :))

**Comment by yashi-hub** [comment]
hey @patricoferris. I would love to work on this issue. provided that I am just working on setting up the local project environment right now, so it might take me a day or two before I get started on working on this issue. is that fine?  thank you for assigning it to me. :)

**Comment by patricoferris** [comment]
@yashi-hub take all the time you need, there's no rush :))

**Comment by ghost** [comment]
This page might have the missing images: http://caml.inria.fr/about/successes.en.html

**Comment by yashi-hub** [comment]
hey @patricoferris . as referred to in https://discuss.ocaml.org/t/error-while-setting-up-ocaml-project-using-wsl/7466/2 .
I tried to install everything again according to the guide https://www.cs.umd.edu/class/spring2018/cmsc330/ocamlInstallationGuide.pdf. but now when I run opam install ocamlfind I get the following error- 
![WhatsApp Image 2021-03-15 at 4 15 01 PM](https://user-images.githubusercontent.com/69522036/111142803-18636100-85ab-11eb-951f-06a45e02804e.jpeg)

I installed m4 using the command - sudo apt-get install -y m4.
and now when I run make, I'm getting the same error as in https://discuss.ocaml.org/t/error-while-setting-up-ocaml-project-using-wsl/7466.
continuing the issue here as requested by you to take it to the repo.
I'm unable to understand the steps required to move ahead for setting up the project, things seem to be very new to me.
hoping that I can soon start working on the issues :) :).

**Comment by patricoferris** [comment]
Hi @yashi-hub 👋 

It seems the document I linked is a little out of date, this [guide seems better](https://github.com/janestreet/install-ocaml). 

I think the problem is that newer versions of opam are using `bwrap` for sandboxing, but this isn't supported on WSL. I think the following steps should work: 

 - Remove this installation of opam (i.e. remove `~/.opam`)
 - Run `opam init --disable-sandboxing`
 -  Also install `m4` using `apt`
 
 Then retry the setup for this project. Sorry, I don't have access to a windows machine to help more, but hopefully this will work.

**Comment by yashi-hub** [comment]
hello @patricoferris , i tried the new guide also, and every command runs fine. 
but when I try to run the testing commands the same error prevails. 
![WhatsApp Image 2021-03-19 at 2 49 38 PM](https://user-images.githubusercontent.com/69522036/111758348-65ed1000-88c2-11eb-8e29-bbe432eeb22a.jpeg) 
and if I do not test the system and simply run make I get again the same error that is:
![WhatsApp Image 2021-03-19 at 2 51 20 PM](https://user-images.githubusercontent.com/69522036/111758540-a3519d80-88c2-11eb-8118-24b9b5ac8587.jpeg)
I feel like it is a loop I'm stuck in :/.
it would be a great help if I can get some help with resolving these errors.
PS: I removed the installation of opam and retried setting up the project with the new guide. :)

**Comment by patricoferris** [comment]
Hmm, can you confirm you definitely followed this line: 

> For the Windows Subsystem for Linux, you must also include --disable-sandboxing with opam init

**Comment by yashi-hub** [comment]
> Hmm, can you confirm you definitely followed this line:
> 
> > For the Windows Subsystem for Linux, you must also include --disable-sandboxing with opam init

Yes, i did opam init -y --compiler=4.07.1 --disable-sandboxing and when this didn't work I tried just opam init --disable-sandboxing. 
 I believe that the problem is with the bwrap sandboxing in WSL but the command --disable-sandboxing doesn't seem to work for the same.

**Comment by patricoferris** [comment]
Hm that is strange, could you run `opam init --disable-sandboxing` (having removed the previously initialised `.opam`) and paste the output here or somewhere? Sorry about this -- hopefully we will get to the bottom of it and can add the setup steps to CONTRIBUTING.md :))

**Comment by yashi-hub** [comment]
i removed the previously installed opam using sudo apt-get remove --purge opam and then run opam init --disable-sandboxing. this is the output-
![Screenshot 2021-03-26 114605](https://user-images.githubusercontent.com/69522036/112590507-f24e8400-8e28-11eb-9a76-5b9a93b63684.png)
what can I do next to make things work? :/

**Comment by yashi-hub** [comment]
hey @patricoferris  . i realised that ocamlfind was not installed , so I did it using - `sudo apt install ocaml-findlib` 
this installed ocamlfind i believe and now when I run make I get a different error from the one mentioned earlier in this thread.
![Screenshot make](https://user-images.githubusercontent.com/69522036/112720060-3a050680-8f22-11eb-9077-dbada491c988.png)
what else I can do to resolve this issue?

**Comment by patricoferris** [comment]
See my reply: https://discuss.ocaml.org/t/error-while-setting-up-ocaml-project-using-wsl/7466/6 

Have you run `make deps` now that you have opam installed and working?

**Comment by dinakajoy** [comment]
I am looking for another issue to take up. @yashi-hub are you still working on this? @patricoferris has this issue been resolved or at work in progress level? Please let me know. Thank you

**Comment by yashi-hub** [comment]
> I am looking for another issue to take up. @yashi-hub are you still working on this? @patricoferris has this issue been resolved or at work in progress level? Please let me know. Thank you

hey @dinakajoy . I've just finished the setup for the project and I am working on this issue now. it would be great if you could look for another one :)

**Comment by lindaokorie27** [comment]
@yashi-hub did you succeed in handling this issue? I am currently looking for an issue to take up. Please if so, let me know. Thank you.

**Comment by yashi-hub** [comment]
> @yashi-hub did you succeed in handling this issue? I am currently looking for an issue to take up. Please if so, let me know. Thank you.

Hey @LindieK , I'm working on this. 
Just few patches left before I make a PR. 
As soon as I close this issue, I'll try to open a new one if possible. 
By then you can work on other issues or observe the site and open an issue yourself :))

**Comment by mercybassey** [comment]
![Screenshot from 2021-04-03 01-15-56](https://user-images.githubusercontent.com/57226464/113462763-781a9280-941a-11eb-9396-097076068b7a.png)

a quick fix to the success stories page.
@patricoferris  can i go ahead with this?

**Comment by mercybassey** [comment]
![Screenshot from 2021-04-03 01-26-53](https://user-images.githubusercontent.com/57226464/113463164-41de1280-941c-11eb-8f81-79fa24048f44.png)
A quick fix for the Success Stories Page

**Comment by mercybassey** [comment]
with your approval @patricoferris  i can get this done

**Comment by patricoferris** [comment]
@mercybassey I'm not entirely sure what that's concerning, if this is an issue that needs fixed please open a separate issue thanks :)) 

@yashi-hub thanks for the PR closing now :))
