### ISSUE TITLE
GTK tutorial example generation is broken

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/v2.ocaml.org#1265]
See:

https://ocaml.org/learn/tutorials/introduction_to_gtk.html

The loading procedure fails, and so then do all the examples further down the page.

**Comment by patricoferris** [comment]
This would make a nice issue for Outreachy applicants looking for something a little harder to debug. In particular this is most likely linked to missing dependencies and/or something wrong with the build process. 

If anyone picks this up I'd be more than happy to help them with it.

**Comment by yashi-hub** [comment]
hey @patricoferris , can I give this issue a try?
as I've already submitted a PR for a good-first-issue and updated the contribution guide, I think this can be the time for me to take upon a harder issue for the outreachy contribution period :))

**Comment by patricoferris** [comment]
Sure @yashi-hub -- just to clarify, here we're trying to understand why this fails and how to make it not (the linked issue is about error reporting whenever things fail).

**Comment by gs0510** [comment]
@yashi-hub I see that you're also on #1402 (which is a medium issue). Can you pick either this issue or the other one so someone else can also be assigned a medium issue? Thank you!

**Comment by yashi-hub** [comment]
hey @gs0510, I have no problem if this issue is assigned to someone else, but I have already invested a major time in this issue as well as to #1402. 
#1402 is almost done, and this one is in process.
can you suggest what can be done now? :))

**Comment by gs0510** [comment]
@yashi-hub Sorry, this is our bad. Can you tell what progress you've made on this issue? Thanks!

**Comment by yashi-hub** [comment]
sure,
as I'm new to OCaml and not aware of how the compilation process and dependencies affect the running code and before this, I've just solved few frontend issues requiring no or less knowledge about the codebase. 
so I've followed the `getting started`  tutorial for running all the codes and compiling them with the dependencies (`lablgtk`) required at the local computer.
I also recently learned about scripts and how they work with an OCaml code block.

I'm yet to see why the code mentioned in this issue is breaking down and what can be done about it.
thank you:))

**Comment by gs0510** [comment]
@yashi-hub  Okay, in that case I will assign it to someone who hasn't worked on a medium issue yet. We'll open some other issues by the time you get done with a PR for #1402. Thanks! :)

**Comment by gs0510** [comment]
@Ndipbanyan Do you want to take a look at this issue since you were asking for a medium issue to take a look at? Thanks! :)

**Comment by Ndipbanyan** [comment]
@gs0510 Yes I will love to. I will dive right in. Thanks

**Comment by gs0510** [comment]
@Ndipbanyan this issue has been closed, I'll let you know about another medium one. Sorry about this!
