### ISSUE TITLE
Incorrect menu item name on the french page

### ISSUE THREAD

**Issue by nibble0101** [ocaml/v2.ocaml.org#1275]
# Description of the issue
Currently, there is a mismatch between the name of  one menu item on the navigation bar for the English page and the corresponding name after translating to French. On the [English page](https://ocaml.org/docs/), we have `packages` as the third menu item on the navigation bar linking to https://opam.ocaml.org/  however on the [French page](https://ocaml.org/docs/index.fr.html), we have `contributions` as the third menu item and it also links to  https://opam.ocaml.org/.
I don't speak french but google translates `Packages` to French as `Paquets` . Hopefully I am not missing anything.

**English**
![image](https://user-images.githubusercontent.com/52580190/111075413-f8736500-84f8-11eb-9b23-c04ac640ee82.png)

**French**
![image](https://user-images.githubusercontent.com/52580190/111075812-bb0fd700-84fa-11eb-8643-9c2900bcbea3.png)

# How to reproduce the issue

- Navigate to https://ocaml.org/docs/
- The third menu item is `Packages`
- Navigate to the French translation of the same page https://ocaml.org/docs/index.fr.html
- The third menu item is `Contributions`
- Translating the page to English still leaves you with `Contributions` as the third menu item

# Possible solution

Change [this](https://github.com/ocaml/ocaml.org/blob/master/translations/en_to_fr.txt#L3) translation from `"Packages" -> "Contributions"` to `"Packages" -> "Paquets"`. Though I am not quite certain.

**Comment by nibble0101** [comment]
@avsm  and @patricoferris. Let me know if this is an issue worth fixing.

**Comment by patricoferris** [comment]
Hi @nibble0101 thanks for raising this question,

My french is very rusty, but I don't think the direct translation from `packages` to `paquets` is correct. IIRC `paquets` is like the packages that arrive in the post 📦 ... But, let me double-check with people who actually know :))

**Comment by mattiasdrp** [comment]
The translations are fine
- `Packages > Paquets` is the correct translation
- `News > Nouvelles` could be replaced by `Actualités` which is more french

**Comment by Octachron** [comment]
Indeed `paquet` is the translation used by most linux distributions.

**Comment by patricoferris** [comment]
Learn something new everyday! Thanks @mattiasdrp and @Octachron. 

@nibble0101 feel free to make the PR for the suggested changes :))

**Comment by mattiasdrp** [comment]
When in doubt I just go on the english Wikipedia page (here for package manager) and switch to the french one to see if that's the way they translated it.
