### ISSUE TITLE
General layout and accessibility improvements

### ISSUE THREAD

**Issue by patricoferris** [ocaml/v2.ocaml.org#1276]
There are a few seemingly unrelated issues that could be solved together as a good first-issue.

1. On mobile devices there appears to be an empty white space on the right of all the pages. If you go to the [home page](ocaml.org) on a mobile device (or emulate the screen-size in the browser) and scroll right you will see a thin white margin. This probably shouldn't be there.
2. Also on mobile devices, the drop-down menu for the main navigation (`learn, documentation...`) is hidden by giving it a `0px` height. I'm wondering if there is a better way doing this as this actually still technically displays the content (you can see this if your go to `ocaml.org/learn` and run a Google Lighthouse test as it finds the contrast ratio to low). Happy to hear thoughts on this.

@jyotibalodhi would you like to work on this as part of #1245? Please let me know either way below, thanks :))

**Comment by jyotibalodhi** [comment]
Hello @patricoferris, yes I would definitely like to work on this issue. Right now I am still setting up the local project environment, so it would take a couple of days for me to progress with the issue, I hope that's fine. Thanks for the consideration.

**Comment by nibble0101** [comment]
> Also on mobile devices, the drop-down menu for the main navigation (learn, documentation...) is hidden by giving it a 0px height. I'm wondering if there is a better way doing this as this actually still technically displays the content (you can see this if your go to ocaml.org/learn and run a Google Lighthouse test as it finds the contrast ratio to low). Happy to hear thoughts on this.

Another common approach I have seen  is to remove the drop-down menu from taking up space by absolutely positioning it. You can give it an off-screen position and toggle it back in view on clicking the hamburger icon. I am not sure it is a better solution than concealing the drop-down menu by setting `height: 0px;` but I believe it will prevent google lighthouse from emitting the a11y warning if used as a substitute for `height: 0px`.

**Comment by jyotibalodhi** [comment]
> Hello @patricoferris, yes I would definitely like to work on this issue. Right now I am still setting up the local project environment, so it would take a couple of days for me to progress with the issue, I hope that's fine. Thanks for the consideration.

Hello @patricoferris I am working on this issue, but I am facing problems while building the site locally. I have installed all the dependencies but there's still some problem when I try `make`.  I have been looking for the solutions on my own, but every time it throws a warning or error. I am attaching a screenshot of that. I hope you can help me out with this and I can make the required changes at the earliest. Thank you!
![Err](https://user-images.githubusercontent.com/63946672/111657329-54a7f300-8831-11eb-805d-01294548b326.png)

**Comment by patricoferris** [comment]
Hi @jyotibalodhi -- this bug was fixed just a few days ago because of a new release of `Omd` https://github.com/ocaml/ocaml.org/pull/1280.

You need to repin the opam file or force install an older version of `omd` and try building again, you can try `opam install omd.1.3.1` which should fix things.

**Comment by jyotibalodhi** [comment]
> Hi @jyotibalodhi -- this bug was fixed just a few days ago because of a new release of `Omd` #1280.
> 
> You need to repin the opam file or force install an older version of `omd` and try building again, you can try `opam install omd.1.3.1` which should fix things.

Thanks a lot, @patricoferris !! I will do the needful!

**Comment by jyotibalodhi** [comment]
Hello @patricoferris, I have resolved the empty white space problem which was there, seems there was some padding issue with the footer. I am attaching the screenshots, kindly let me know if that is fine. 
![1](https://user-images.githubusercontent.com/63946672/111804367-06105c80-88f6-11eb-948e-d75e98330ad0.png)
![2](https://user-images.githubusercontent.com/63946672/111804425-14f70f00-88f6-11eb-9fac-bcc9cb349607.png)

Also about the Navbar drop down, I was wondering where do I need to make the required changes exactly. As the `ocaml.org` is in gitingnore and I am not able to find the right location of the file. And whether we want any particular solution for that, or I can just try various things to solve the issue. 
Also, it would be really great if you can tell me, whether I should raise the PR separately for both the points or combine them in a single PR. Thanks!

**Comment by patricoferris** [comment]
@jyotibalodhi great!

You can do a separate or combined PR, it's up to you :)) 

> As the ocaml.org is in gitingnore and I am not able to find the right location of the file

That's right -- ocaml.org is the build directory which changes every time someone pushes new code so it doesn't make much sense to commit it. 

As for the navbar it is pieced together by a few different files: 
  - The navbar items live here https://github.com/ocaml/ocaml.org/blob/master/template/navbar.mpp
  - The rest of the navbar is mostly in this file https://github.com/ocaml/ocaml.org/blob/master/template/main.mpp#L42-L64 
  
These files are mostly a "weird" looking HTML because they are processed by OCaml scripts, but should be close enough to OCaml (and quite declarative) to build up an intuition as to how it builds itself. Hopefully that's enough information to help, if not feel free to ask some more questions.

**Comment by jyotibalodhi** [comment]
> @jyotibalodhi great!
> 
> You can do a separate or combined PR, it's up to you :))
> 
> > As the ocaml.org is in gitingnore and I am not able to find the right location of the file
> 
> That's right -- ocaml.org is the build directory which changes every time someone pushes new code so it doesn't make much sense to commit it.
> 
> As for the navbar it is pieced together by a few different files:
> 
> * The navbar items live here https://github.com/ocaml/ocaml.org/blob/master/template/navbar.mpp
> * The rest of the navbar is mostly in this file https://github.com/ocaml/ocaml.org/blob/master/template/main.mpp#L42-L64
> 
> These files are mostly a "weird" looking HTML because they are processed by OCaml scripts, but should be close enough to OCaml (and quite declarative) to build up an intuition as to how it builds itself. Hopefully that's enough information to help, if not feel free to ask some more questions.

@patricoferris Thanks, I will try to do the Navbar issue change, else I will make the PR with the already made changes for sure and then try to work on the rest.

**Comment by pitag-ha** [comment]
@jyotibalodhi, how is it going? Do you need some help? Or have you already submitted a PR for this and I haven't seen it?

**Comment by jyotibalodhi** [comment]
> @jyotibalodhi, how is it going? Do you need some help? Or have you already submitted a PR for this and I haven't seen it?

Hello @pitag-ha , yes I have already made a PR for this issue #1300 , which has been merged just 3 days ago! Thanks! 

Also I was wondering whether this will be considered as a contribution? as PR was made before the contribution period started and merged while the contribution period.

**Comment by pitag-ha** [comment]
> yes I have already made a PR for this issue #1300 , which has been merged just 3 days ago! Thanks!

Perfect, thanks for letting me know!

> Also I was wondering whether this will be considered as a contribution?

The one-liner good-first-issues are a good way to get into touch with the code base. I don't think it matters much if the contribution is "officially considered" or not. Now, you could work on issues that aren't tagged as good-first-issue or come up with some issue yourself that you want to work on. That will all be more important for consideration anyways.

If your question was if you should add this contribution to the Outreachy application system: I'm not sure to be honest. That's probably something we would have to ask the Outreachy organizers. But if you do good further contributions, it's ok not to add it. Not adding it won't be a problem for sure.

**Comment by jyotibalodhi** [comment]
> The one-liner good-first-issues are a good way to get into touch with the code base. I don't think it matters much if the contribution is "officially considered" or not. Now, you could work on issues that aren't tagged as good-first-issue or come up with some issue yourself that you want to work on. That will all be more important for consideration anyways.

Actually, I am working on another first issue #1306 , I was not aware that we shall not work on one after our first contribution. As I am getting a few errors there while making the file, it's taking longer than required. 

> If your question was if you should add this contribution to the Outreachy application system: I'm not sure to be honest. That's probably something we would have to ask the Outreachy organizers. But if you do good further contributions, it's ok not to add it. Not adding it won't be a problem for sure.

Yes, okay thanks! :)

**Comment by pitag-ha** [comment]
> Actually, I am working on another first issue #1306 , I was not aware that we shall not work on one after our first contribution.

Ok, thanks for pointing that out! That's on us for not noticing. Since it's already assigned to you, you can keep on working on it now. But please, don't work on a third first-good issue :)

**Comment by jyotibalodhi** [comment]
> > Actually, I am working on another first issue #1306 , I was not aware that we shall not work on one after our first contribution.
> 
> Ok, thanks for pointing that out! That's on us for not noticing. Since it's already assigned to you, you can keep on working on it now. But please, don't work on a third first-good issue :)

Thanks ! :)

**Comment by patricoferris** [comment]
The issues here seem to be fixed the live site so closing now :))
