### ISSUE TITLE
Use of a filled triangle pointing right to display unordered list is misleading.

### ISSUE THREAD

**Issue by nibble0101** [ocaml/v2.ocaml.org#1279]
# Issue description

Currently, on the [ocaml manual page](https://ocaml.org/manual/index.html) and a few other related pages, ▶ symbol is used to display unordered list of items. I find this usage quite misleading  because the same symbol also appears if one displays collapsible content in HTML  using  [`details` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details). I have clicked the symbol a couple of times expecting a collapsed content to open but to my surprise there wasn't any. You can check what I am talking about in the illustration below.

<details>
   <summary> Something is hidden here. Click to reveal </summary>
    See. I am hiding right here 
</details>

It becomes confusing if unordered list is styled to look like the above collapsible content.

# How to reproduce the issue

Navigate to each of the following pages.
- [Manual page](https://ocaml.org/manual/index.html)
- [Foreword section of manual page](https://ocaml.org/manual/foreword.html#start-section)

You should be able to see the following.
**Manual page**
![image](https://user-images.githubusercontent.com/52580190/111279533-d76f5900-864b-11eb-8591-b9158f60389e.png)

**Foreword section of manual page**
![image](https://user-images.githubusercontent.com/52580190/111279638-f2da6400-864b-11eb-955b-de4c862fa7d5.png)

# Possible solution
Possible solution is to have the default symbol for unordered list, • ,instead of  ▶.

**Comment by nibble0101** [comment]
@avsm  and  @patricoferris,  let me know what you think.

**Comment by patricoferris** [comment]
Hi @nibble0101,

Thanks for the suggestion. I agree with you that the triangle is a little misleading. It is also used to [indicate what chapter you are on](https://ocaml.org/manual/objectexamples.html) so it's meaning is a little overloaded. 

The actual code for the manual lives with the compiler not on ocaml.org and is part of the post-processing stage. The styles are generated from https://github.com/ocaml/ocaml/blob/trunk/manual/src/html_processing/scss/manual.scss I believe so it would have to incorporated there, if there's agreement. OCaml.org just gets the output from that process.

Maybe @Octachron has more insight or has a desired way for collecting feedback on the manual?

**Comment by Octachron** [comment]
If triaging such issues is not too much trouble, it does seem easier for people to report issue at `ocaml.org`.

In a perfect world, fixing the manual source in the compiler repository would be ideal. But this has undoubtedly a quite high barrier to entry (even if in this specific case, just modifying the `manual.scss` file sounds doable).

Thus, if it is easier for people to draft improvement to the manual on the post-processed html directly, I am happy to take care of the backporting to the manual source.

**Comment by sanette** [comment]
before digging too much into the details of the manual let me mention that the current version on ocaml.org is not exactly what it should be, due to incompatibilities with the new version of Hevea, see https://github.com/ocaml/ocaml/issues/10254. This should be corrected very soon.

Concerning the triangle in lists, I'm not opposed to using a filled disc, however for indicating the current chapter I find that the triangle works better.

**Comment by sanette** [comment]
for chapters, one could put the triangle on the right, like this:
![Screenshot_20210316_110020](https://user-images.githubusercontent.com/7536536/111291072-164ee000-8647-11eb-9d1e-a66ce831e603.png)

**Comment by sanette** [comment]
for other lists, here is a try with discs instead of triangles. It's a bit less "dynamic", but I find it acceptable. 
![Screenshot_20210316_111019](https://user-images.githubusercontent.com/7536536/111292495-85790400-8648-11eb-950b-8a869e3a9ac9.png)

**Comment by nibble0101** [comment]
@sanette  Are you working on it? Or should I fork the Ocaml repository and start working on it. From the pointers given by  @patricoferris  and @Octachron  above, it doesn't look complex.

**Comment by sanette** [comment]
@nibble0101 before working on this we'd better get an agreement on what to do. Let's see that @Octachron thinks. If what I did above is enough, it's probably not worth for you duplicating the work, I can just request a pull. If there is something else to do, or simply if you want to experiment other ideas, feel free, I'm happy to let you do it!

**Comment by Octachron** [comment]
Using a disc for the unordered list seems fine to me.
The triangle on the right feels slightly strange: it breaks the alignment and it requires some small time (ms?) to get that is supposed to be read right-to-left.
However, for question of graphical designs, my opinion should not have too much weight.

**Comment by nibble0101** [comment]
@sanette . You will work on it then. I don't believe I can add anything very different from what you are proposing. Regarding the triangle on the right, why should we have a triangle in the first place?  I believe  its purpose is to convey to the user which of the items is active (Correct me if I am wrong). If that is the case, why don't we just underline the active item so that with the already existing dark font color (which is different from the surrounding items), the "active" part becomes obvious.

Something like:
![image](https://user-images.githubusercontent.com/52580190/111300888-9e8eae80-8662-11eb-82d1-2e54053aa3bb.png)

**Comment by sanette** [comment]
of course it's just my taste, but for chapters I think that the triangle is visually nicer than underlining. (on the left is probably better than on the right, as Octachron said). I don't think it's misleading, but that's just me. 
For other in-text lists, I agree it can be a bit misleading.

**Comment by sanette** [comment]
I would be OK using a diamond◆ for chapters

**Comment by Octachron** [comment]
A diamond sounds good to me: it is a small marker that is less invasive than underlining, and it does not have any strong implicit meaning (or any that that I am aware of).

**Comment by sanette** [comment]
ok, then if everybody agrees I can switch to diamonds for chapters, and filled discs for other former uses of triangles.
I will make a PR as soon as https://github.com/ocaml/ocaml/pull/10282 is merged

**Comment by IIITM-Jay** [comment]
Hi @Octachron,
while going through the manual from the [website](https://ocaml.org/releases/4.12/htmlman/index.html), I found  that the bottom navigations are missing from the [Ocaml API pages](https://ocaml.org/releases/4.12/api/index.html) and unknowingly I felt that the appropriate changes has to made here in this repo to fix those, but thanks to @patricoferris for suggesting me the exact location of the required [branch](https://github.com/ocaml/ocaml/tree/trunk/manual)  of the coreeponding [repository](https://github.com/ocaml/ocaml). 

i have done the appropriate changes in the post processed HTML in this [PR](https://github.com/ocaml/ocaml.org/pull/1273), of whose changes can be seen below, ***changes made are highlighted in green***
![Webp net-gifmaker(1)](https://user-images.githubusercontent.com/65283880/111730741-0c6feb80-8898-11eb-977f-587c6d92ea52.gif)

***Hence, I have a request that, If don't have any problem, may I open the issue for the same and do a PR making the changes as above at this [location](https://github.com/ocaml/ocaml/tree/trunk/manual).***

**Comment by Octachron** [comment]
Please ping me in the corresponding subject to avoid polluting unrelated discussion.
