### ISSUE TITLE
99 Problems: crossword puzzle image does not show

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#128]
On our [99 Problems](http://ocaml.org/tutorials/99problems.html) page, the image in the "Crossword puzzle" problem does not show up. It does show up fine when I test that page from my local working copy of the repo.

I'm not sure it matters, but the only difference I see is that the link to this image:

https://sites.google.com/site/prologsite/prolog-problems/7/p99.gif?attredirects=0

has the attredirects attribute set. None of the other embedded images have this.

**Comment by Chris00** [comment]
I went to the [original site](https://sites.google.com/site/prologsite/prolog-problems/7/) and copied the link.  Hopefully that should work.

**Comment by agarwal** [comment]
This appears to be working now.
