### ISSUE TITLE
Improve accessibility on ocaml.org landing page for keyboard users.

### ISSUE THREAD

**Issue by nibble0101** [ocaml/v2.ocaml.org#1282]
# Issue description

Currently a user who relies exclusively on keyboard to navigate [ocaml.org](https://ocaml.org/) landing page wouldn't have the best user experience. This is primarily because some interactive elements (links, buttons and form elements) do not have styling to indicate that they are in focus. For example, the `install ocaml` button may be in focus but there is nothing to indicate that it is. A user should be able to tab to a specific interactive element on the page and any interactive element which is in focus should be styled to indicate so. To illustrate what I am talking about, I have made a screencast while  tabbing through  one of the pages on mozilla website. 

https://user-images.githubusercontent.com/52580190/111598601-7462fb00-87e0-11eb-8a14-e62aefc3a00a.mp4

I think it would be better if the [ocaml.org](https://ocaml.org/) landing page was made more accessible for key board users just like the page in the above screencast. 

# How to reproduce the issue

Navigate to the [ocaml.org](https://ocaml.org/) landing page. Put the cursor in the search bar and start tabbing backwards (SHIFT + TAB) or forwards (TAB ). Some links will be underlined to show that they are in focus but others do not have such styling which affects the user experience for those who are using only the keyboard (for one reason or another) to access the website. For further insights, tab through [this  page on mozilla website ](https://developer.mozilla.org/en-US/) and compare it with your experience on  [ocaml.org](https://ocaml.org/) landing page.

**Comment by nibble0101** [comment]
@patricoferris  and @avsm. Let me know what you think of this.

**Comment by patricoferris** [comment]
@nibble0101 this would be amazing! A lot of the problems might be solved just by not having things like: 

```css
a:focus {
  outline: none;
}
```

I'm personally not against having outlines on focused items if it improves the accessibility for keyboard users. I'm particularly interested in improving the "long-form content" too. Tabbing through https://ocaml.org/learn/tutorials/up_and_running.html for example is not a great user experience. A hidden `skip to content` might not be bad thing, I might give this to a separate Outreachy applicant if you want to work on the rest? Thanks again for taking the initiative and contributing to ocaml.org :))

**Comment by nibble0101** [comment]
Thanks @patricoferris. I agree removing `outline:none` will fix most of the problems. I am quite certain this issue affects most web pages on ocaml.org. My plan was to start fixing from the landing page and then move on to other pages. Feel free to assign other pages or other related issues to others who may be interested.
