### ISSUE TITLE
Typos and grammatical errors on https://ocaml.org/learn/companies.html page

### ISSUE THREAD

**Issue by nibble0101** [ocaml/v2.ocaml.org#1287]
# Issue description

There are a couple of typos and grammatical errors in `Companies using OCaml` section of https://ocaml.org/learn/companies.html page. Below are the annotated screenshots of the specific sections.

**TrustInSoft, France**
![image](https://user-images.githubusercontent.com/52580190/112029055-e4a7ae80-8b49-11eb-82dc-1e6bde539f1c.png)

**Digirati dba Hostnet, Brazil**
![image](https://user-images.githubusercontent.com/52580190/112029126-f5f0bb00-8b49-11eb-811b-226f9d0bf9fb.png)

**CACAOWEB, United Kingdom and Hong Kong**
![image](https://user-images.githubusercontent.com/52580190/112029198-09038b00-8b4a-11eb-8923-90be63057fee.png)
 
# How to reproduce the issue

Navigate to  `Companies using OCaml` section of https://ocaml.org/learn/companies.html page. Read about the following companies. You will notice a couple of typos and grammatical errors.
- TrustInSoft, France
- Digirati dba Hostnet, Brazil
- CACAOWEB, United Kingdom and Hong Kong

**Edit**
It would be a good idea to make general improvements to the page as well.

**Comment by ChitvanRamani22** [comment]
@nibble0101 can i work on this

**Comment by nibble0101** [comment]
Hi @ChitvanRamani22 . Welcome to ocaml.org. That issue already has a PR linked. @patricoferris  should be able to create an issue for you soon or else I can create one and ping him for approval before you can start working on it.

**Comment by ChitvanRamani22** [comment]
@nibble0101 thanks a lot i have to start it as soon as possible.
Could you please create a one and let me know.
