### ISSUE TITLE
99 Problems

### ISSUE THREAD

**Issue by green-gecko** [ocaml/v2.ocaml.org#129]
Here's a simpler solution to #10 (Run-length encoding of a list.)
that builds on the previous problem.

Also, it would be handy if you numbered the problems :)
.a

let encode list =
  let rec aux = function
    | hd :: tl -> ((List.length hd), (List.hd hd)) :: (aux tl)
    | [] -> []
  in
  aux (pack list)
;;

**Comment by Chris00** [comment]
Right, your solution is shorter but also uses more memory.  Maybe one should add some motivation for the solution chosen?

About the numbering: do we number problems consecutively or do we use the original numbering (which is a bit messy)?
