### ISSUE TITLE
Fix news section spacing

### ISSUE THREAD

**Issue by patricoferris** [ocaml/v2.ocaml.org#1291]
Currently on ocaml.org/community the `news` section seems to have some odd spacing compared to a similar looking component for the `meetings`. It would be good if they looked the same. 

More concretely: 

<img width="393" alt="Screenshot 2021-03-22 at 20 20 38" src="https://user-images.githubusercontent.com/20166594/112053450-45d08180-8b4c-11eb-896c-d11d78a53e9d.png">

The spacing between `OCaml Weekly News` and `Release of Frama-Clang 0.0.10` looks wrong.This might affect other similarly styled components so double-checking these would be good too. 

@lead4013 would you like to look into this as part #1245? Let me know either way below please :))

**Comment by lead4013** [comment]
Hi @patricoferris!
Thanks for assigning this issue to me.
I've made some changes and this is the final look.
Should I move ahead with committing the changes ?

BEFORE
![Screenshot from 2021-03-23 12-55-10](https://user-images.githubusercontent.com/80776193/112112402-7c091200-8bdb-11eb-8158-cadef33c329d.png)

AFTER 
![Screenshot from 2021-03-23 12-54-06](https://user-images.githubusercontent.com/80776193/112112340-6a276f00-8bdb-11eb-9b3f-377088ebdbcf.png)

**Comment by lead4013** [comment]
Hey @patricoferris!
I closed the above PR because it had some issues 
I'll submit a fresh PR very soon :)

**Comment by ChitvanRamani22** [comment]
@patricoferris i want to work on this it seems to be a good issue to start my journey.

**Comment by patricoferris** [comment]
Hi @ChitvanRamani22,

I really do appreciate your eagerness but you have now commented on an issue someone is already working on, an open issue that you are now assigned to, and two issues (this one included) which have pull requests open for them. Keeping track of this many issues seems hard. Can I suggest you focus on #1312 to begin with?

**Comment by patricoferris** [comment]
Fixed in #1298
