### ISSUE TITLE
videos.html: needs more content

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#13]
Videos page currently has only 3 videos. There are many more OCaml videos out there (such as all the ones from previous OCaml Users Meetings). All should be organized nicely in a youtube account and linked from here.

**Comment by eelsther** [comment]
The ocamlorg@gmail.com account that I created then deleted last week is still not available... 
Do you have an idea on how much time is needed to have the username back ?

I am wondering if the username is really important. What will matter is the YouTube username which can be different from the GMail username.

We could think about something like ocamlwebsite@gmail.com or ocamlcommunity@gmail.com.

What do you think ?

**Comment by Chris00** [comment]
On Thu, 23 Aug 2012 06:27:37 -0700, Esther wrote:

> I am wondering if the username is really important. What will matter
> is the YouTube username which can be different from the GMail
> username.

If the youtube username can be chosen independently of the gmail one,
then I am fine with taking another name.

> We could think about something like ocamlwebsite@gmail.com or 
> ocamlcommunity@gmail.com.

Sound good to me.

**Comment by agarwal** [comment]
I'd move ahead with getting any account. Maybe ocamlweb@gmail.com. Although
we're thinking that name would change if we publish on ocaml.org, it is
short and is the current name of the project. And we may retain the forge
project with this name for the sake of the mailing list.

**Comment by eelsther** [comment]
"ocamlweb" is already taken. I'll create ocamlwebsite@gmail.com then.

**Comment by eelsther** [comment]
Account created! I sent you a mail from the new account.

**Comment by eelsther** [comment]
I added a playlist to the Youtube account : OUD 2012, collecting videos of all presentations.

**Comment by dbuenzli** [comment]
John's videos for beginners could be linked to http://ocaml-book.com/videos/

**Comment by avsm** [comment]
Also see Dan Ghica's Foundations of Computer Science lectures at http://vimeo.com/user8856528/videos

There a lot of excellent lectures there all use OCaml

**Comment by amirmc** [comment]
I notice that Vimeo provide feeds for users.  That might be a good way to automatically get content into the site.  Would be better if there were feeds for specific collections but I couldn't see any at first glance.
