### ISSUE TITLE
Make click-ability of texts visible

### ISSUE THREAD

**Issue by pitag-ha** [ocaml/v2.ocaml.org#1307]
This would be a **good first issue** for anyone looking to get started improving and contributing to OCaml.org.

The two texts " Got a question? Ask OCaml experts!" and "Learn OCaml in your browser with TryOCaml " are clickable. At the moment visually that's not obvious, particularly on the phone. I suggest to improve the design in a way that it becomes obvious that they can be clicked, e.g. by marking them as a link (blue and underlined) or by making them a button or similar.

**Comment by nayaldivya** [comment]
I'll be working on this issue shortly.

**Comment by gurleennsidhuu** [comment]
Hi. Can I work on this issue?

**Comment by nayaldivya** [comment]
Since the text is very long, I guess making them a button won't look much appealing. @pitag-ha What do you think of these changes? I changed the font color keeping the overall theme of the page in mind and added the underline effect as you suggested.
![ocaml index](https://user-images.githubusercontent.com/73695161/112941849-dad70a00-914c-11eb-99b9-78c866c4f0de.png)
.

**Comment by pitag-ha** [comment]
@nayaldivya, I'm no UX-expert, but to me that looks great, thanks! Don't hesitate to open a PR for it when you feel comfortable. That way we can have a look at the code. Did you use the same color as used for other links on ocaml.org?

**Comment by nayaldivya** [comment]
@pitag-ha, I've made the PR. Also, I was thinking of adding some hovering effect to the elements but was not able to decide what? Any ideas or hints will be appreciated.

**Comment by pitag-ha** [comment]
@nayaldivya , I like the idea! And great to see your initiative! :) What about explaining in the hovering what the links are about? For example, `Got a question? ...` links to the OCaml Discourse, the main platform to discuss OCaml. If you'd like, you can open an issue for that (which you can work on yourself).

**Comment by nayaldivya** [comment]
Thanks again @pitag-ha. I'll start working on this soon.
