### ISSUE TITLE
Improve the footer section

### ISSUE THREAD

**Issue by nibble0101** [ocaml/v2.ocaml.org#1313]
Currently when you navigate to the `footer` section of any page, you will notice the following.

1. All the headings of the different `footer` sections are `links` except the last section whose heading is `Website`. Since all the other sections have headings that link somewhere, it would be better to have the last one be a link  given the fact that  all of them have the same styling. I would suggest linking it to the landing page of `ocaml.org` or somewhere appropriate. 
2. There are  a couple of external links in the footer section that do not pass the [lighthouse best practices audit ](https://web.dev/external-anchors-use-rel-noopener/?utm_source=lighthouse&utm_medium=devtools) especially those that open on new browser window. This is true for most external links with `target = _blank` attribute on [ocaml.org](https://ocaml.org/). According to google's lightouse,

> Add `rel="noopener"` or `rel="noreferrer"` to any external links to improve performance and prevent security vulnerabilities 

Though modern browsers have started implementing `rel="noopener"`  by default for `a` tags with `target = _blank` attribute, it would be great to have this `link` issue fixed for older versions of browsers and best practices.

**Comment by nibble0101** [comment]
@patricoferris  and @avsm . I think this would be a good first issue for #1245. What do you think?

PS. I am not an applicant.

**Comment by dinakajoy** [comment]
Hi, I am an outreachy applicant and I would like to work on this task

**Comment by nibble0101** [comment]
Hi @dinakajoy. Welcome to ocaml.org. You can start exploring and investigating how to come up with a fix but it would be best to first get the opinion of either @patricoferris  or @avsm to be sure the issue is:
1. Worth fixing
2. Within scope of #1234 

That is why I pinged them. It will avoid wasting lots of time on an issue which might be out scope for beginners among other reasons. I am not very familiar with the code base as well.

**Comment by patricoferris** [comment]
Thanks @nibble0101 this is great👍 

@dinakajoy feel free to submit a PR for this :))

**Comment by dinakajoy** [comment]
Sure, thank you

**Comment by dinakajoy** [comment]
Hi @patricoferris is there a way to view project in browser development mode to see changes without building it out please?
I have to build on every change and it's time consuming.
Thank you.
