### ISSUE TITLE
Resize icons in Community

### ISSUE THREAD

**Issue by pitag-ha** [ocaml/v2.ocaml.org#1317]
At the bottom of Community we have the OCaml around the World section. The icons there are all sized differently. Furthermore, all items but one are in the first line and the only icon in the second line is bigger than the others:

![Screenshot from 2021-03-30 11-19-21](https://user-images.githubusercontent.com/39061003/112965632-b88fbd00-9149-11eb-9c94-40f5db1eee8c.png)

I suggest to resize the icons. For example (but could also be done differently) as follows:
- put the same number of icons into the first line as into the second line
- and/or: give them all the same size; make sure that more than one icon is in the second line

**Comment by TildaDares** [comment]
This looks interesting. Can I work on this?

**Comment by pitag-ha** [comment]
@TildaDares , sure, go ahead :)

**Comment by pitag-ha** [comment]
Notice that I've just opened another issue that is related to this one: #1318. I'm just mentioning that so that you can take into account that there will be one more icon soon.

**Comment by TildaDares** [comment]
> Notice that I've just opened another issue that is related to this one: #1318. I'm just mentioning that so that you can take into account that there will be one more icon soon.

Noted.

**Comment by TildaDares** [comment]
@pitag-ha How does this look?

![image](https://user-images.githubusercontent.com/63427719/112970883-934d7f80-9146-11eb-92d8-e7f11580a72d.png)

**Comment by pitag-ha** [comment]
@TildaDares , I'm no design expert, but to me that looks great, thanks! Don't hesitate to open a PR for it when you've implemented it and feel comfortable. That way we can have a look at the code.

**Comment by nibble0101** [comment]
@pitag-ha  Isn't this issue a duplicate of #1270? Looks like someone is already working on it.

**Comment by pitag-ha** [comment]
@nibble0101 , thanks a lot for noting that! @TildaDares , I'm very sorry I missed #1270. Do you think you could find another issue you're interested in?

**Comment by pitag-ha** [comment]
@TildaDares, would you be interested in #1320? Sorry again for the duplicate. I'm closing this.
