### ISSUE TITLE
Add discourse to OCaml Around the World

### ISSUE THREAD

**Issue by pitag-ha** [ocaml/v2.ocaml.org#1318]
This would be a **good first issue** for anyone looking to get started improving and contributing to OCaml.org.

At the bottom of Community we have the OCaml around the World section. 

![Screenshot from 2021-03-30 11-19-21](https://user-images.githubusercontent.com/39061003/112967908-0b6a7400-914c-11eb-864f-178d6be8fc2c.png)

I suggest to also add a discourse icon to it linking to [discuss.ocaml.org](https://discuss.ocaml.org/) .

**Comment by gurleennsidhuu** [comment]
Hi. Can I work on this issue?

**Comment by pitag-ha** [comment]
Hi @gurleennsidhuu, sure, go ahead :)

**Comment by gurleennsidhuu** [comment]
> Hi @gurleennsidhuu, sure, go ahead :)

![discourse](https://user-images.githubusercontent.com/64313783/112978922-898f4080-9175-11eb-9790-c7edad8fe238.png)
Is this discourse icon fine?

**Comment by gurleennsidhuu** [comment]
I am first time using the 'make' command on bash and it's showing some error. Can you please me?

**Comment by gs0510** [comment]
@gurleennsidhuu  Can you post the errors here? It will be helpful for us to debug if you post the error you see. Additionally, please add what operating system you are running on. Thanks!

**Comment by gurleennsidhuu** [comment]
> @gurleennsidhuu Can you post the errors here? It will be helpful for us to debug if you post the error you see. Additionally, please add what operating system you are running on. Thanks!

![error](https://user-images.githubusercontent.com/64313783/113015737-768f6700-919b-11eb-848d-88f436f5c185.png)
Thanks in advance! :)

**Comment by gurleennsidhuu** [comment]
> > @gurleennsidhuu Can you post the errors here? It will be helpful for us to debug if you post the error you see. Additionally, please add what operating system you are running on. Thanks!
> 
> ![error](https://user-images.githubusercontent.com/64313783/113015737-768f6700-919b-11eb-848d-88f436f5c185.png)
> Thanks in advance! :)

my directory is ~/ocaml.org

**Comment by pitag-ha** [comment]
@gurleennsidhuu , have you seen the [contribution document](https://github.com/ocaml/ocaml.org/pull/1241/files)?

**Comment by gurleennsidhuu** [comment]
> @gurleennsidhuu , have you seen the [contribution document](https://github.com/ocaml/ocaml.org/pull/1241/files)?

Yes. I just read it again. I am quite confused about the makefiles.

**Comment by pitag-ha** [comment]
Hve you run `make deps`? Did it succeed?

It would be great if we could move this conversation to [irc](https://webchat.freenode.net/#ocaml) or to the [outreachy applicant issue](https://github.com/ocaml/ocaml.org/issues/1245) or similar. That way we'd leave the conversation on this issue about this issue and furthermore other applicatns who have already got the page up and running can try to give you a hand.

**Comment by gurleennsidhuu** [comment]
Hi.
![dis](https://user-images.githubusercontent.com/64313783/113282665-dce3c900-9304-11eb-95fc-5006e318b682.png)
This is how it looks. Is it okay? I changed the file for fr translation too.

**Comment by pitag-ha** [comment]
Great, thanks for your work! There is currently a [PR](https://github.com/ocaml/ocaml.org/pull/1272) open that improves the layout of the Community page quite a bit, including the OCaml Around the Web section. To avoid git conflicts later on, you might consider building your work upon the branch of that PR (and, if you do so, mention that when submitting your PR). But note that the other PR is still being worked on.

> I changed the file for fr translation too.

Which fr translation are you referring to?

**Comment by gurleennsidhuu** [comment]
I was referring to the fr translation of the above page. 
Also, I am quite unclear. Do I need to wait to make a PR?

**Comment by pitag-ha** [comment]
> I was referring to the fr translation of the above page.

Cool, that's a nice initiative! I would advice you to open a different issue and a different PR for that, since those two things are unrelated. They might even require different reviewers (not everyone speaks French).

> Also, I am quite unclear. Do I need to wait to make a PR?

That's up to you :) Depending on your git experience the problem here might be a bit challenging, sorry for that!

Let me explain a bit more: in general, you build your work upon the current `origin/master` branch. You also make a PR against `origin/master`. By the time your PR gets merged, the state of `origin/master` might already have changed (other changes from other PRs might have been merged in the meanwhile). Usually that's not a problem, since git knows how to merge those changes with your changes from your PR.

But unfortunately, here the situation is a bit different: you and @Kanak1081 are working on a similar part of the code base. [@Kanak1081's PR](https://github.com/ocaml/ocaml.org/pull/1272) is very likely to be merged before yours since it's already quite advanced. So if you build your work upon the current `master`, by the time your PR is ready to be merged into `master`, @Kanak1081's PR is probably already going to be merged into it. Since you two are touching a similar place of the code base, that might cause [merge conflicts](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-merge-conflicts).

So you can choose what to do:
- You can build your work upon @Kanak1081's PR by checking out their PR branch [as described here](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally). If @Kanak1081 still decides to change their commits, this option might require you to [rebase your branch](https://git-scm.com/docs/git-rebase) later. You could ask @Kanak1081 if they plan to do that. And you can also ask me if you have further questions about this option (again sorry you have to deal with this problem!).
- As you've suggested, you can wait until @Kanak1081's PR is merged and then build your work upon `origin/master`.
- You can take the risk and just go ahead as normal and later resolve the merge conflicts if they arise. 


In any of those cases (particularly in the last one): note that @Kanak1081's PR has improved the layout of the icons. So your contribution should be coherent with the new layout :)

**Comment by gurleennsidhuu** [comment]
I am really new to git and open source so this is quite a task for me but I am here to learn. :)
I chose to go with the 1st option and I got the following error.
![sv](https://user-images.githubusercontent.com/64313783/113344376-9e72fc00-934e-11eb-98f6-5dbad79aac2b.png)
Am I doing something wrong?

**Comment by Kanak1081** [comment]
Hi, @pitag-ha, hope you are doing great😊. As of now, I have closed my PR for the same issue. @gurleennsidhuu can feel free to contribute for the same.

**Comment by pitag-ha** [comment]
@Kanak1081, you were working on a different issue weren't you? Why have you closed the PR? :) I didn't mean to put any pressure on you!

**Comment by gurleennsidhuu** [comment]
> @Kanak1081, you were working on a different issue weren't you? Why have you closed the PR? :) I didn't mean to put any pressure on you!

Should I just make a PR or should I still follow the options you mentioned earlier?

**Comment by pitag-ha** [comment]
> Should I just make a PR or should I still follow the options you mentioned earlier?

If the other PR is closed and stays closed, you can open the PR as normal and can take the things you've read about git as a good learning experience :) I just hope I haven't very unintentionally put any pressure on anyone.

**Comment by Kanak1081** [comment]
> @Kanak1081, you were working on a different issue weren't you? Why have you closed the PR? :) I didn't mean to put any pressure on you!

Thats's so kind of you @pitag-ha and you didn't put up any pressure. Actually, I have worked upon the same issue but then my PR encountered some rendering error and since I was busy in some other work right now, couldn't focus on that issue as of now. I saw that new comers are currently working, so wanted to give them a clean way. Thanks!
