### ISSUE TITLE
Remove Google+ links

### ISSUE THREAD

**Issue by pitag-ha** [ocaml/v2.ocaml.org#1319]
This would be a **good first issue** for anyone looking to get started improving and contributing to OCaml.org.

On the News page we share blog posts and on their right have links to share them on social media:

![Screenshot from 2021-03-30 11-43-43](https://user-images.githubusercontent.com/39061003/112969010-22f62c80-914d-11eb-9a3a-21eab2adc304.png)

I suggest to remove the Google+ link from them, since Google+ has been shut down.

**Comment by Bhavika-Gianey** [comment]
Hello @pitag-ha  and  @patricoferris,I want to  fix this issue as part of my outreach contribution phase.

**Comment by pitag-ha** [comment]
@Bhavika-Gianey , sounds good, please go ahead.

**Comment by saniikakulkarni** [comment]
Hello @pitag-ha I would like to work on this issue.

**Comment by Bhavika-Gianey** [comment]
@saniikakulkarni I am already working on this issue, I don't think this task requires two duplicated same codes.

**Comment by Bhavika-Gianey** [comment]
Hello @pitag-ha and @patricoferris   ;
I am a bit confused about the linkage of code snippets in another folder as I am not able to find the required code lines in the index.md of the news section. Can you please help me understanding the marked red circle in that code?

![err](https://user-images.githubusercontent.com/63343906/113292802-9ac18400-9312-11eb-8bd5-070d3053112c.PNG)

**Comment by pitag-ha** [comment]
Hello @Bhavika-Gianey , that's a tough one. That line invokes the script defined [here](https://github.com/ocaml/ocaml.org/blob/master/script/rss2html.ml). It's written in OCaml. So working on this issue means working in OCaml. When saying this was a **good first issue**, I hadn't noticed that, sorry!

I've seen you're interested in the "Improve ocaml.org" project. Are you happy with working on an OCaml issue anyways? Or would you prefer us finding you another issue?

**Comment by pitag-ha** [comment]
It's still a pretty simple task. It's just that it requires OCaml.

**Comment by Bhavika-Gianey** [comment]
> Hello @Bhavika-Gianey , that's a tough one. That line invokes the script defined [here](https://github.com/ocaml/ocaml.org/blob/master/script/rss2html.ml). It's written in OCaml. So working on this issue means working in OCaml. When saying this was a **good first issue**, I hadn't noticed that, sorry!
> 
> I've seen you're interested in the "Improve ocaml.org" project. Are you happy with working on an OCaml issue anyways? Or would you prefer us finding you another issue?

Thanks, @pitag-ha for providing the reference link. I have resolved this issue :)) and I am eager to learn more about the OCaml language also :).

Is this fine now??

![news](https://user-images.githubusercontent.com/63343906/113339161-b3985c80-9347-11eb-8722-23176a862515.PNG)

**Comment by pitag-ha** [comment]
Nice, that's great! Without rush, don't hesitate to open a PR for that when you're ready.

**Comment by patricoferris** [comment]
Thanks @Bhavika-Gianey for the fix :))
