### ISSUE TITLE
 Link text is unclear

### ISSUE THREAD

**Issue by gs0510** [ocaml/v2.ocaml.org#1327]
The text "Learn" in the nav-bar and the footer is unclear without context and may be confusing to screen readers.  You can add a special screen reader text than can help with accessibility.

Relevant code:
```
<a href="/learn/">Learn</a>
```

**Comment by 0xull** [comment]
I will work on this right away, hope to increase the accessibility. But when you said without "context", can you be a little elaborate on that?

**Comment by gs0510** [comment]
@IkehAkinyemi  Since you already have a PR open for a `good-first-issue`, I'd prefer if you took on a harder issue now :)

**Comment by gs0510** [comment]
About context, I meant that the link just says "Learn" which can be harder to understand if someone is using a screen reader. If there's alt text that can help provide context for screen readers it will make the link more accessible.

**Comment by Srinithyee** [comment]
@gs0510 If @IkehAkinyemi is fine with me working on this issue, I'd love to start with this.

**Comment by patricoferris** [comment]
Yep, I agree with @gs0510 here. @IkehAkinyemi I think your have at least two separate things you are working on (the moving of the language selector, fixes to the contributing docs) both still in the works, let's focus on those :)) 

@Srinithyee please submit a PR for this whenever you're ready 👍

**Comment by Srinithyee** [comment]
@patricoferris Thanks a lot! I'll start working on this!

**Comment by 0xull** [comment]
> Yep, I agree with @gs0510 here. @IkehAkinyemi I think your have at least two separate things you are working on (the moving of the language selector, fixes to the contributing docs) both still in the works, let's focus on those :))
> 
> @Srinithyee please submit a PR for this whenever you're ready

Yes @patricoferris, already made a PR to the moving of the language selector, hoping to see your message on the recent discussion we're having. Once that's merged, I will make PR for the fixes to the contributing docs.

**Comment by Srinithyee** [comment]
@gs0510 On looking at the directory structure, I am not able to locate the index.html file. I am only able to view index.md. It would be super nice if you could provide the path to the index.html file. Thanks. 

I was planning on adding title tag in between a and href in the relevant code, to add relevant context
