### ISSUE TITLE
Issue and PR templates

### ISSUE THREAD

**Issue by patricoferris** [ocaml/v2.ocaml.org#1329]
It would be nice to have some good Issue and PR templates for contributors to use. There have been some stellar examples already from contributors that we could definitely borrow from as inspiration. For example

 - @nibble0101's PR for adding some borders https://github.com/ocaml/ocaml.org/pull/1262 -- the before and after screen shots are great in providing us with some notion that the work has been done and that locally it appears to be working. Also issues like https://github.com/ocaml/ocaml.org/issues/1315 go a long way in explaining the exact problem trying to be fixed.
 - @IIITM-Jay's PR for fixing the git log of contributors https://github.com/ocaml/ocaml.org/pull/1253 again the before and after along with careful explanations are fantastic and really help use understand what's going on. 
 - @nayaldivya's PR for improving accessibility https://github.com/ocaml/ocaml.org/pull/1252 follows the same idea and is very helpful.
 
I've just hand-picked a few here but hopefully you can see that by spending a little time on a PR's layout (or an issue) it can really help speed up the review process. 

--- 

We can use [Github's PR and Issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates) to do this.

**Comment by TildaDares** [comment]
@patricoferris Can I work on this?

**Comment by patricoferris** [comment]
Hi @TildaDares just saw that something you were working on got accidentally fixed, sorry about that. Could you work on the PR template and then I can find somebody else to work on the issue template? Does that sound okay? Thanks for you willingness to contribute :))

**Comment by TildaDares** [comment]
@patricoferris That's sounds good. Thank you.

**Comment by lindaokorie27** [comment]
I'd like to work on the issue template.

**Comment by 0xull** [comment]
@LindieK, I believe @TildaDares is still working on this issue. I suggest you look through the open issues available to contribute to.

**Comment by patricoferris** [comment]
Actually @LindieK if you would like to draft up an *issue template* that would be fantastic. A good one to have would be a front-end focused one. And could require information like:

 - Description of the visual bug (with optional but greatly appreciated screenshot)
 - What browser someone is using
 - What device they are on

**Comment by lindaokorie27** [comment]
@patricoferris Okay cool. Will work on that.
