### ISSUE TITLE
Resize and Realign Buttons on opam home page

### ISSUE THREAD

**Issue by lindaokorie27** [ocaml/v2.ocaml.org#1334]
The "Download and Install" button and the "How to use opam" button do not align on mobile and messes with the layout of the rest of the page. The buttons need to be vertically realigned on mobile devices.

Here's how it looks on mobile:
![Screenshot_20210331_021319_org mozilla firefox (2)](https://user-images.githubusercontent.com/38317939/113077124-7063af80-91c8-11eb-9953-ae752d26b8ba.jpg)

**Comment by 0xull** [comment]
Hello @LindieK, this issue has already been raised at [#1259](https://github.com/ocaml/ocaml.org/issues/1259). You could either ask @meenal06 if she's currently working on it, then propose to work on it if it's still available.

This would help to avoid duplication of issues, even PRs on the same issue. Thanks for your understanding.

**Comment by 0xull** [comment]
You can also scroll down to older open issues to see if there's any still available to work on, while newer issues get reported daily for fixes.

**Comment by patricoferris** [comment]
Thanks @IkehAkinyemi you're quite right, it also seems someone asked on that issue first. I'll double-check on that issue if neither of the people involved want to work on it and if that's the case you can definitely look into @LindieK.

In the meantime I'll close this as a duplicate.
