### ISSUE TITLE
Improve presentation of list of contributors

### ISSUE THREAD

**Issue by nibble0101** [ocaml/v2.ocaml.org#1337]
# Issue description

When you navigate to [contributors page](https://ocaml.org/contributors.html), there is a very long list of contributors arranged in alphabetical order. Check the screenshot below. As you can see there is one column leaving a lot of wasted space on the right in desktop view. Besides one will have to scroll all the way down to check the entire list. 

![image](https://user-images.githubusercontent.com/52580190/113116082-c90d6980-9215-11eb-9461-4e08018ca141.png)

 I believe the list can be presented in multiple columns like in the screenshot below and then change the number of columns using media query in smaller screens. This will make it easier to go through the list.

![image](https://user-images.githubusercontent.com/52580190/113116846-84360280-9216-11eb-871d-24e0fa5773f0.png)

**Comment by nibble0101** [comment]
@patricoferris  and @avsm. I am not sure if this will make a `good first issue` for #1245

**Comment by janekotovich** [comment]
Heya! My name is Jane, im an Outreachy applicant. Could I work on this issue? Btw - is it necessary to present with numbers or you are okay with just lining them horizontally? Kind regards, Jane

**Comment by PrernaSingh587** [comment]
Would love to work on this one.!

**Comment by shivanisinghnitp** [comment]
Hello,
I am an Outreachy Applicant!
Can I work on this?
@avsm

**Comment by gs0510** [comment]
@Jane-Kotovich  go for it! Just lining them horizontally sounds good!

**Comment by janekotovich** [comment]
@gs0510 Sounds great, thanks for that! Will dive in!

**Comment by SowmyaSv** [comment]
@avsm @patricoferris @gs0510 I would like to work on this as my good first issue.

**Comment by patricoferris** [comment]
Hi @SowmyaSv,

Thank you so much for your eagerness to contribute, we're very grateful. If I could just point you in the direction of https://github.com/ocaml/ocaml.org/issues/1245#issue-821019972 where you can register your interest. 

@Jane-Kotovich please take as much time as you need, there's no pressure to rush a PR.

**Comment by janekotovich** [comment]
@patricoferris Hey there! Thanks heaps, I was stuck a bit with installation of the whole repo. If I want to change CSS I don't really need make whole app running am I? Sorry for been a bit silly :) 
I managed easy to apply something like this, however I figured out that there are 4 css files in repo in total 
<img width="1440" alt="Screen Shot 2021-04-01 at 5 20 14 pm" src="https://user-images.githubusercontent.com/76935202/113258098-d78b7c00-930e-11eb-9f6c-b51d2938e259.png">
Would love to hear back from you, 
Kind Regards, 
Jane

**Comment by janekotovich** [comment]
or I easy can make a numbers if you'd like :) The little issue is that some of CSS rules are crossing each other. If you would like I can tell about it more ;)

**Comment by patricoferris** [comment]
Hi @Jane-Kotovich that already looks much better, thank you :)) (I would go ahead and submit a PR)

> The little issue is that some of CSS rules are crossing each other

What do you mean by this? Is it that some rules are redefined in different `.css` files? I think this is intentional, the site vendors an old version of bootstrap and (I think) this is then modified by over-ruling rules in the other `.css` files.

**Comment by lindaokorie27** [comment]
@gs0510 I also noticed some names are duplicated in the list. Should that be handled here or can I create a new issue pointing out the names I noticed were duplicated?

**Comment by gs0510** [comment]
@LindieK can you point out some names that were repeated. Since the names are taken from a git log, I think it's possible there's two people with similar names. B

**Comment by lindaokorie27** [comment]
![Screenshot_20210404_193755](https://user-images.githubusercontent.com/38317939/113518331-98af2d80-957d-11eb-8015-ecea967a1d15.jpg)

@gs0510 this is one example. The names are different - yes - but refer to the same person. I noticed 3 other people from observing conversations in the issues and cross checking their github usernames and full names.

**Comment by gs0510** [comment]
@LindieK Nice catch, you can open another issue and work on it! :)
