### ISSUE TITLE
Issue running make deps

### ISSUE THREAD

**Issue by gurleennsidhuu** [ocaml/v2.ocaml.org#1339]
![make](https://user-images.githubusercontent.com/64313783/113143629-fa079180-9249-11eb-96e3-833255d76d79.png)
I have installed ocaml and opam and also changed the directory but still I can't run  `make deps`. Please help me out.

**Comment by patricoferris** [comment]
Hi @gurleennsidhuu thanks for opening an issue to handle this. 

Could you provide the following please:
 - What operating system are you using
 - The output of running `ls` in this directory

**Comment by gurleennsidhuu** [comment]
I am using windows (64 bit).
The output is:
![ls](https://user-images.githubusercontent.com/64313783/113148259-486b5f00-924f-11eb-9003-8b3be91eec9e.png)

**Comment by 0xull** [comment]
Hello @gurleennsidhuu, check this discussion on the discourse.ocaml.org, [#7567/2](https://discuss.ocaml.org/t/error-while-trying-to-set-up-ocaml-project-on-windows-10-via-cygwin-terminal/7567/2). It might be helpful to resolve the current errors you're getting.

**Comment by patricoferris** [comment]
Okay (I'm not a windows expert or user) the easiest way to build the site is using WSL, this will make your life a lot easier (in fact the site *will not build on native windows*).

It also looks odd that there are no other folders here such as `scripts` and most importantly the `Makefile` hence you are getting the error that there is `no rule to make target deps`. Did something go wrong when you `git clone`-d the repository?

Thanks @IkehAkinyemi but this is not the same problem as far as I can tell.

**Comment by 0xull** [comment]
Okay @patricoferris, it was a suggestion.

**Comment by gurleennsidhuu** [comment]
> Okay (I'm not a windows expert or user) the easiest way to build the site is using WSL, this will make your life a lot easier (in fact the site _will not build on native windows_).
> 
> It also looks odd that there are no other folders here such as `scripts` and most importantly the `Makefile` hence you are getting the error that there is `no rule to make target deps`. Did something go wrong when you `git clone`-d the repository?
> 
> Thanks @IkehAkinyemi but this is not the same problem as far as I can tell.

No. I didn't face any kind of errors while cloning the repository.

**Comment by patricoferris** [comment]
Appreciate your help @IkehAkinyemi it's been awesome having you around to help other applicants :))

@gurleennsidhuu interesting, can you see the Makefile in the directory that you `git clone`-ed the ocaml.org repository into?

**Comment by gurleennsidhuu** [comment]
![makefile](https://user-images.githubusercontent.com/64313783/113159221-0f84b780-925a-11eb-966e-017de16ebd12.png)
These are the makefiles that are visible to me.

**Comment by patricoferris** [comment]
Hmm very interesting. Do you think you can start again using WSL from the very start and following the WIP guidance over here: https://github.com/ocaml/ocaml.org/blob/dfecc2d82746dea740e0e4fe635c96656fd24e31/CONTRIBUTING.md#errors-faced-while-building-the-site-using-wsl ?

**Comment by gurleennsidhuu** [comment]
Yes sure. I'll give it a try. Thanks for you help. :)

**Comment by Bhavika-Gianey** [comment]
Hello @patricoferris, I followed the steps given in [(https://github.com/ocaml/ocaml.org/blob/dfecc2d82746dea740e0e4fe635c96656fd24e31/CONTRIBUTING.md#errors-faced-while-building-the-site-using-wsl)]



When I tried to use  opam init --disable-sandboxing -a after doing rm -rf /home/bhavika/.opam;
it is showing errors while installing the OCaml compiler.

Kindly help me out as I am getting a bit confused about what to do next :(.

![error](https://user-images.githubusercontent.com/63343906/113179508-4fa16580-926d-11eb-8019-9b7e94577163.PNG)

**Comment by patricoferris** [comment]
Hi @Bhavika-Gianey this is slightly different to this issues topic but I'm going to answer it here anyway (this is just to let other people know that this isn't related in case they read this issue some time in the future). 

The error you are getting says you do not have a C compiler installed (or at the very least, opam cannot find one). Can you check that you have a C compiler such as GCC installed?

**Comment by gurleennsidhuu** [comment]
I am now working on WSL and installed opam and ocaml. But when I run `make deps` now, the following error occurs.
![Screenshot 2021-04-01 114130](https://user-images.githubusercontent.com/64313783/113191224-e9234400-927a-11eb-8d56-b065fe342108.png)

**Comment by gurleennsidhuu** [comment]
I am quite confused about how to proceed :(

**Comment by patricoferris** [comment]
I think we're close @gurleennsidhuu, don't worry -- can you try running something like `opam switch create 4.10.2 4.10.2` then if that doesn't fail,  run `make deps`.

**Comment by gurleennsidhuu** [comment]
I tried running `opam switch create 4.10.2 4.10.2`. Now, the following error occurs. I have tried disabling the sandox using `--disable-sandboxing` and the command runs without any error.
![Screenshot 2021-04-01 124654](https://user-images.githubusercontent.com/64313783/113198921-1fb18c80-9284-11eb-8995-a1b428663eba.png)

**Comment by gurleennsidhuu** [comment]
The `make deps` ran successfully. Now, when I run `make` or `make local`, the following error occurs.
![m](https://user-images.githubusercontent.com/64313783/113253283-a7c67f00-92e2-11eb-84aa-848d7bca05fc.png)

**Comment by Bhavika-Gianey** [comment]
> Hi @Bhavika-Gianey this is slightly different to this issues topic but I'm going to answer it here anyway (this is just to let other people know that this isn't related in case they read this issue some time in the future).
> 
> The error you are getting says you do not have a C compiler installed (or at the very least, opam cannot find one). Can you check that you have a C compiler such as GCC installed?

Thank You @patricoferris , the error was due to gcc and now everything is resolved :)).

**Comment by patricoferris** [comment]
@gurleennsidhuu this is good news, this is a known error so we're close.

I think the easiest thing to do here is to do a `git pull` and get the fix from #1309.

**Comment by gurleennsidhuu** [comment]
Thank you @patricoferris. It worked. :)
I just have one last question. When I run the HTML file on browser, I can't see the images. Am I doing something wrong?

**Comment by gurleennsidhuu** [comment]
I made all the changes and ran `make local`. The following error occurs, even though a new ocaml.org folder is created.
![Screenshot 2021-04-01 135910](https://user-images.githubusercontent.com/64313783/113266207-a1400380-92f2-11eb-8091-6e128bac4cb9.png)

**Comment by patricoferris** [comment]
Hmm, seems `rsync` is having some trouble. When you switched over to WSL did you do a fresh `git clone` of the repository? I'm not quite sure what's going on here, but one thing to try is to delete the repository then from **within WSL** `git clone` it again and try running `make`.

**Comment by gurleennsidhuu** [comment]
Thank you so much for helping and being so patient! @patricoferris  :) Cloning the repository again worked for me. Should I close this issue?

**Comment by patricoferris** [comment]
Fantastic, you are very welcome. I think everyone on this thread is up and running now so I'll close it :))

**Comment by ChitvanRamani22** [comment]
@gurleennsidhuu is the repo running successfully?

**Comment by gurleennsidhuu** [comment]
> @gurleennsidhuu is the repo running successfully?

Hi @ChitvanRamani22. Yes, it is. Are you facing any issue?

**Comment by ChitvanRamani22** [comment]
When i ran make after make deps i got this error then i tried running opam init and got this could you please help me.
![20210402_103152.jpg](https://user-images.githubusercontent.com/68965499/113382274-bffbd400-939e-11eb-9b0c-f9abae4bdb38.jpg)

**Comment by gurleennsidhuu** [comment]
> When i ran make after make deps i got this error then i tried running opam init and got this could you please help me.
> ![20210402_103152.jpg](https://user-images.githubusercontent.com/68965499/113382274-bffbd400-939e-11eb-9b0c-f9abae4bdb38.jpg)

It's not an error. You can choose Yes/No. In my case, I chose Yes so I pressed y.

**Comment by ChitvanRamani22** [comment]
Again yes??

**Comment by ChitvanRamani22** [comment]
![20210402_110002.jpg](https://user-images.githubusercontent.com/68965499/113383944-980e6f80-93a2-11eb-9b46-dd5c0c17db88.jpg)

**Comment by ChitvanRamani22** [comment]
Getting this 
![20210402_112253.jpg](https://user-images.githubusercontent.com/68965499/113385601-0ef93780-93a6-11eb-8665-6531f658a25d.jpg)

**Comment by ChitvanRamani22** [comment]
How to solve this switch note??

**Comment by ChitvanRamani22** [comment]
@gurleennsidhuu please help

**Comment by Bhavika-Gianey** [comment]
Hello @ChitvanRamani22  , you can go through this doc  (https://github.com/ocaml/ocaml.org/blob/dfecc2d82746dea740e0e4fe635c96656fd24e31/CONTRIBUTING.md#errors-faced-while-building-the-site-using-wsl), It might help .

**Comment by ChitvanRamani22** [comment]
@Bhavika-Gianey already tried that and so many other things since 3 days

**Comment by gurleennsidhuu** [comment]
> @gurleennsidhuu please help

Can you please show the output for the command `whereis ocaml`?

**Comment by ChitvanRamani22** [comment]
@gurleennsidhuu ![20210402_115309.jpg](https://user-images.githubusercontent.com/68965499/113387483-073b9200-93aa-11eb-88d1-5a5ed58d64cf.jpg)
I am getting this for make deps

**Comment by ChitvanRamani22** [comment]
@gurleennsidhuu ![20210402_115421.jpg](https://user-images.githubusercontent.com/68965499/113387579-32be7c80-93aa-11eb-9006-3c2f95104481.jpg)

**Comment by ChitvanRamani22** [comment]
@patricoferris could you also help please

**Comment by gurleennsidhuu** [comment]
@ChitvanRamani22 I am sorry. I am not sure why this is happening. I guess, you should try installing ocaml and opam again.

**Comment by patricoferris** [comment]
Hi everyone, thanks for helping each other :))

@ChitvanRamani22 I think you got a hold of me elsewhere. As a general rule, commenting on a closed issue is not a good strategy for getting help. I don't think Github notifies any of the maintainers about it. Even if the issue seems related, you are better opening a fresh issue and maybe referencing the closed one if you think they are related. Thanks :))

**Comment by ChitvanRamani22** [comment]
@patricoferris okay sorry for the mistake i didnt know it earlier.

**Comment by ChitvanRamani22** [comment]
@gurleennsidhuu how much time did you make command took to run completely.

**Comment by gurleennsidhuu** [comment]
> @gurleennsidhuu how much time did you make command took to run completely.

It takes some time. I think more than 5 mins.

**Comment by ChitvanRamani22** [comment]
@gurleennsidhuu which code editor are u using?

**Comment by gurleennsidhuu** [comment]
> @gurleennsidhuu which code editor are u using?

I edited the file on notepad itself.

**Comment by ChitvanRamani22** [comment]
@gurleennsidhuu 
Actually my make command is showing output as follows
![IMG-20210402-WA0113.jpeg](https://user-images.githubusercontent.com/68965499/113433942-bc4b6a00-93fd-11eb-82da-6944cbef8fe1.jpeg)

**Comment by gurleennsidhuu** [comment]
I think you are good to go. You should go to the newly created ocaml.org folder and locate your file and it will run on browser.

**Comment by ChitvanRamani22** [comment]
@gurleennsidhuu 
Are u talking about this? 
![20210402_221009.jpg](https://user-images.githubusercontent.com/68965499/113435353-3c72cf00-9400-11eb-91e4-62ee1fc39e87.jpg)

**Comment by gurleennsidhuu** [comment]
> @gurleennsidhuu
> Are u talking about this?
> ![20210402_221009.jpg](https://user-images.githubusercontent.com/68965499/113435353-3c72cf00-9400-11eb-91e4-62ee1fc39e87.jpg)

No. The one above this, 'ocaml.org'.

**Comment by ChitvanRamani22** [comment]
@gurleennsidhuu i meant that only rest all folder names are white in color but that one is greyish something like muted text .

**Comment by ChitvanRamani22** [comment]
@gurleennsidhuu hope u can see it in this ss![Screenshot_20210402-222450_WhatsApp.jpg](https://user-images.githubusercontent.com/68965499/113436394-4564a000-9402-11eb-9f34-94c9965bde57.jpg)

**Comment by gurleennsidhuu** [comment]
> @gurleennsidhuu hope u can see it in this ss![Screenshot_20210402-222450_WhatsApp.jpg](https://user-images.githubusercontent.com/68965499/113436394-4564a000-9402-11eb-9f34-94c9965bde57.jpg)

Are you able to open any file from the newly create ocaml.org folder?

**Comment by ChitvanRamani22** [comment]
@gurleennsidhuu ![20210402_223030.jpg](https://user-images.githubusercontent.com/68965499/113436851-17339000-9403-11eb-87cc-72a6a4db2e25.jpg)
All the files are like this.

**Comment by ChitvanRamani22** [comment]
![20210402_223150.jpg](https://user-images.githubusercontent.com/68965499/113436923-43e7a780-9403-11eb-975f-77ee5dc8a9c7.jpg)
And when i do open with live server.

**Comment by gurleennsidhuu** [comment]
> @gurleennsidhuu ![20210402_223030.jpg](https://user-images.githubusercontent.com/68965499/113436851-17339000-9403-11eb-87cc-72a6a4db2e25.jpg)
> All the files are like this.

I guess you can now run them on browser. Are you facing any issue while running them? Try running the file you edited and check if the changes are visible or not. :)

**Comment by gurleennsidhuu** [comment]
I don't know how to use VSC but you can check the newly created ocaml.org folder in the directory you cloned it. It will directly open it in the browser. This is what I did.
I hope it makes sense.

**Comment by ChitvanRamani22** [comment]
@gurleennsidhuu 
![20210402_223650.jpg](https://user-images.githubusercontent.com/68965499/113437277-fc155000-9403-11eb-9c93-9c9161ba07cd.jpg)
I copied the path of index.html and ran it this is what is showed.

**Comment by gurleennsidhuu** [comment]
> @gurleennsidhuu
> ![20210402_223650.jpg](https://user-images.githubusercontent.com/68965499/113437277-fc155000-9403-11eb-9c93-9c9161ba07cd.jpg)
> I copied the path of index.html and ran it this is what is showed.

Nice. :) I think you should be able to see the changes that you made.

**Comment by ChitvanRamani22** [comment]
@gurleennsidhuu is this the right page 
I mean the same is appearing on ur screen too while running this address?

**Comment by ChitvanRamani22** [comment]
@gurleennsidhuu as till now i havent made any changes.

**Comment by gurleennsidhuu** [comment]
> @gurleennsidhuu is this the right page
> I mean the same is appearing on ur screen too while running this address?

This address can run on your local device only and yes, this is the right page. :)
Just make some changes and run `make` or `make local` again, and you'll be able to see the changes that you made.

**Comment by patricoferris** [comment]
Thanks @gurleennsidhuu for your help. A little disappointed to see the conversation carry on here after my comment https://github.com/ocaml/ocaml.org/issues/1339#issuecomment-812481664 but I'm glad to see applicants helping each other and for your problem to get resolved :))

**Comment by gurleennsidhuu** [comment]
> Thanks @gurleennsidhuu for your help. A little disappointed to see the conversation carry on here after my comment [#1339 (comment)](https://github.com/ocaml/ocaml.org/issues/1339#issuecomment-812481664) but I'm glad to see applicants helping each other and for your problem to get resolved :))

I am really sorry. I should have reopened this issue. Will keep that in mind from now onwards. :)

**Comment by ChitvanRamani22** [comment]
@patricoferris as i was having very small doubts so i thought to discuss with other participants instead of disturbing you again and again .
Was a bit more impatient as i was trying to make the project run since 4 days.
Sorry for that.

**Comment by ChitvanRamani22** [comment]
Thankyou so much @gurleennsidhuu for helping out.
