### ISSUE TITLE
Improve https://opam.ocaml.org/doc/Install.html on mobile view

### ISSUE THREAD

**Issue by Ndipbanyan** [ocaml/v2.ocaml.org#1340]
# Issue description
When you navigate to doc/install page on mobile view, you will notice that the list on `Opam releases on Github` are overflowing

<img width="367" alt="Screenshot 2021-03-31 at 13 54 53" src="https://user-images.githubusercontent.com/67186679/113148550-de8c8e80-9229-11eb-866b-36775b73ca88.png">

**Comment by Ndipbanyan** [comment]
@patricoferris I will love to work on this

**Comment by patricoferris** [comment]
Looks like a good bug to fix thanks @Ndipbanyan

**Comment by Ndipbanyan** [comment]
@patricoferris So I have installed OCaml, and Opam and used `make` to build the project and everything seem to work fine on my local machine but I looked into the opam.ocaml.org folder and can't seem to find the the install page so I can work on it.  Please can you help with pointing where I can possibly find the install page in the project directory?

**Comment by Ndipbanyan** [comment]
@patricoferris still waiting for help on this.

**Comment by Ndipbanyan** [comment]
@patricoferris Going by the help from the discord community, I suppose this issue can be closed since it isn't part of the ocaml.org website but opam.ocaml.org.
