### ISSUE TITLE
Issue building site locally

### ISSUE THREAD

**Issue by lindaokorie27** [ocaml/v2.ocaml.org#1341]
I have successfully installed ocaml and opam on a windows 64 bit OS, initialized it and ran `make deps` and `make production`. 

I'm stuck on how to run build locally. I have a wamp server installed already but I don't know if this will be suitable to run the site.

**Comment by patricoferris** [comment]
Hi @LindieK thanks for opening the issue -- the [contributing doc]() should already help you out with this. To quote from it: 

>  - make local: this is the default target (i.e. if you run make it will be doing make local) the main difference between this command and the one used for production is that an extra step is run that "relativises" the URLs. Instead of links being /learn they could be ../../learn depending on which page you are in. This means you can just open the index.html page in your browser without having to run any server.

To summarise, if you run `make local` you should just be able to open `./ocaml.org/index.html` in your browser.

> - make production: This make target builds the production website, this won't "relativise" the URLs. If you want to test this site you will have to run a web-server on your machine, of which there are plenty of options. One of the dependencies of this site is cohttp-lwt-unix which actually provides just this functionality. You can build the site as production, then run cohttp-server-lwt ./ocaml.org and navigate to http://localhost:8080/ to see the site live.

So long as you start a simple file server in the build directory (`ocaml.org`) then this should be fine too. Let me know if this helps and you get the site running locally :)

**Comment by lindaokorie27** [comment]
Hi @patricoferris  I tried running make local but it didn't work. Here is the error I get. 
![make local error](https://user-images.githubusercontent.com/38317939/113170997-fe7a7d00-923e-11eb-9fd6-b727afb4c5e4.JPG)

**Comment by patricoferris** [comment]
Ah, are you using Windows Subsystem for Linux (WSL)? The problem here is that `cohttp-lwt-unix` (which we depend on) is not installed or cannot be found, I don't know if it can be installed on native windows. Using WSL should fix this. What happens if you run `make deps` right now, does it install `cohttp-lwt-unix`?

**Comment by lindaokorie27** [comment]
Oh no it skips it but runs everything else. I should try the WSL now.

**Comment by lindaokorie27** [comment]
@patricoferris I have successfully installed WSL and set ubuntu running on it. How do I now install `cohttp-lwt-unix` and build the site with it?

**Comment by patricoferris** [comment]
Great @LindieK ! Make sure you install opam (following similar guidance to the WIP doc https://github.com/ocaml/ocaml.org/blob/dfecc2d82746dea740e0e4fe635c96656fd24e31/CONTRIBUTING.md#errors-faced-while-building-the-site-using-wsl). Then it should be as simple as running `make deps`.

**Comment by lindaokorie27** [comment]
@patricoferris  Almost done. I ran `make deps` successfully following the updated docs but `make local` brings up this error. Thank you for your help so far.

![local error 2](https://user-images.githubusercontent.com/38317939/113206685-ac9a1d00-9267-11eb-96a1-d03e97dfc856.JPG)

**Comment by lindaokorie27** [comment]
> @patricoferris Almost done. I ran `make deps` successfully following the updated docs but `make local` brings up this error. Thank you for your help so far.
> 
> ![local error 2](https://user-images.githubusercontent.com/38317939/113206685-ac9a1d00-9267-11eb-96a1-d03e97dfc856.JPG)

@avsm any ideas

**Comment by patricoferris** [comment]
Hi @LindieK -- can you try running `eval $(opam env)` and then `make`. Do you get the same result. In that list of installed packages it should say `ocamlfind`, is that the case?

**Comment by lindaokorie27** [comment]
Yes the list says `ocamlfind`  in the list of installed packages. I ran `eval $(opam env)` and `make`. It brings up a different error now

![local error](https://user-images.githubusercontent.com/38317939/113258799-4ee7ee00-92c4-11eb-9e96-a9726ef77f21.JPG)

**Comment by patricoferris** [comment]
Getting different errors usually means we're making progress. I think there are some artefacts lying around from a previous build with an older compiler. Can you try `make clean` and then `make` again? Sorry this is taking some time.

**Comment by lindaokorie27** [comment]
Now make is running. Majority of the things it is trying to download  either fails or ends up as a bad request. It has gone on for a while. I now looks like a cycle

![make cycle 1](https://user-images.githubusercontent.com/38317939/113262279-590beb80-92c8-11eb-8ed8-f276a24266b0.JPG)

**Comment by patricoferris** [comment]
First of all, you are now building the site which is brilliant 🎉 

Secondly, I think you've found a bug! You can see that for all of the URLs it is trying to get, they have `%0D` at the end which is a newline character. A recent change may have introduced this, I'm going to double check with some Windows/WSL experts and get back to you soon :))

**Comment by patricoferris** [comment]
@LindieK okay, so I think the problem is that you might be running commands from WSL on the repository you got when you started from native Windows which uses [CRLF](https://en.wikipedia.org/wiki/Newline)? When we read [the plant feed file](https://github.com/ocaml/ocaml.org/blob/master/planet_feeds.txt) we strip the `\n` but not the `\r`. 

The easiest way to resolve this is to delete the ocaml.org repository and then **from within WSL** `git clone` it again, then run `make`. Running `git clone` from within WSL should autotranslate the file endings to `\n`.

**Comment by lindaokorie27** [comment]
Okay doing that now

**Comment by lindaokorie27** [comment]
The build is running better now. Here are some of what it I see. Am I on track?
![next build](https://user-images.githubusercontent.com/38317939/113277703-ec4d1d00-92d8-11eb-8516-d2a1833a25c0.JPG)

![second build](https://user-images.githubusercontent.com/38317939/113277778-ff5fed00-92d8-11eb-8b7f-ba050170ecac.JPG)

**Comment by patricoferris** [comment]
Yes! Looks like it's building just fine from those images. Thank you for your patience and persistence to get this running!

**Comment by lindaokorie27** [comment]
Thank you so much for your help. I just wanted to clarify some things.

1. The initial build process is still running till now. There are some files that I see it has looked over more than once. Is this normal?
2. On opening up the build directory, I see it has not built the entire css, img and js directories (amongst other things) so opening index.html, I have to manually edit the paths to point to the site directory. What could be the reason for that?

**Comment by patricoferris** [comment]
Thanks for wanting to dig deeper on this, could provide some more information on each? 

1. Still running? How long has it been running, I wouldn't expect running `make` to take more than about 5 minutes the first time you do it. Which files are being looked at more than once? I think it might retry the HTTP requests but only so many times. A log here might be useful. 
2. What do you mean it has "not built the entire css" are there missing files? Missing parts of the files? Just to double check, by "build directory" we're both talking about the generated `ocaml.org` one right? You shouldn't have manually edit any paths (provided if you are opening it in the browser directly you ran `make local`). 

Thanks :))

**Comment by lindaokorie27** [comment]
By the the build directory, yes I mean ocaml.org. The changes I made were from within the browser after waiting for 40 minutes for the build process to complete (and it still didn't complete). From what I noticed, it kept looping through the files in the learn directory.

**Comment by lindaokorie27** [comment]
Hi @patricoferris so I ended the build process and started again. It seems not to be looping anymore. I'll be patient and keep watching to see if it completes.

Thanks

**Comment by lindaokorie27** [comment]
I did a thorough check. All the folders were created this time. These are the last lines I see, does it signify the end of the build?
![build end](https://user-images.githubusercontent.com/38317939/113322832-16203700-930d-11eb-9ce4-fa9a5c9ca527.JPG)

Also can I delete the cgwin64 terminal I previously installed to conserve disk space? It isn't being used anymore is it?

**Comment by patricoferris** [comment]
Yep that's everything built - the last parts are `rsync`-ing the static files and then (I'm guessing this is `make local`) "relativising" the URLs so you can view it directly in the browser without having to worry about running a server locally. 

I'm not a windows expert, but I don't believe Cygwin is involved in any way anymore so it should be safe to remove it. Glad we got there in the end, thanks for your patience :)) I'm closing this now.

**Comment by Srinithyee** [comment]
@patricoferris Sorry to continue the conversation here. But, since I am facing difficulty in building the site again, it would be great if you could reopen this issue, so that all the problems in building site locally is in one place and this issue might be all that is essential for any other applicant to build the site locally, in the future.

**Comment by Srinithyee** [comment]
@patricoferris This is the issue I am facing when I run make deps:
![image](https://user-images.githubusercontent.com/34683520/113468930-0d437880-9467-11eb-80dc-54d36bdbebc5.png)

Could you please help me with this? It worked just fine a few days back :/
