### ISSUE TITLE
Improve Books and Paper section in https://ocaml.org/docs/ on screen sizes less than 768px

### ISSUE THREAD

**Issue by TildaDares** [ocaml/v2.ocaml.org#1344]
On screen sizes less than 768px, the sizes of the book images are not equal. I'd like to improve that section by making the first book image be the same size as the last two.

![image](https://user-images.githubusercontent.com/63427719/113172354-3660d080-91fd-11eb-9bb7-e3613ff44d3a.png)

**Comment by TildaDares** [comment]
@patricoferris I'd like to work on this if this is approved.

**Comment by patricoferris** [comment]
@TildaDares good catch, this looks like a good bug to fix 👍  I had a quick look and couldn't find any open issues that are the same so go right ahead :))
