### ISSUE TITLE
News Page: Create two or three columns on tabs for Syndications 

### ISSUE THREAD

**Issue by dinakajoy** [ocaml/v2.ocaml.org#1346]
Going through the news page on my tablet, the Syndications  section was right aligned and very lengthy.
There is a lot of space on the left area. So I suggest making it two or three columns on tablet rather that one column to make scrolling easier  for users.
### Issue
![screencapture-ocaml-org-community-planet-2021-03-31-18_12_30](https://user-images.githubusercontent.com/39722740/113184856-9e3f0780-924d-11eb-9ae7-88a78aae1fcd.png)

### Fix Proposed
![ddd](https://user-images.githubusercontent.com/39722740/113186079-1eb23800-924f-11eb-91e1-1dd648eb9e9f.jpg)

If it's a good issue, then I would love to work on it.

**Comment by gs0510** [comment]
Hey @dinakajoy! Good catch! You can go ahead and work on this :)
