### ISSUE TITLE
Replace sharing icons on News page with Font Awesome icons

### ISSUE THREAD

**Issue by dldisha** [ocaml/v2.ocaml.org#1352]
While going through the news page, I noticed various icons to share the news like Twitter, Facebook, etc were added through the internal image's link which adds up extra space, lacks consistency, and relies on image extensions. Therefore, I suggest we should replace these icons with Font Awesome icons.

**Issue:**
![Screenshot from 2021-04-01 13-43-32](https://user-images.githubusercontent.com/26017359/113268709-4bb92600-92f5-11eb-9e14-bf4d6deb3ed9.png)

![WhatsApp Image 2021-04-01 at 2 36 00 PM](https://user-images.githubusercontent.com/26017359/113270961-a489be00-92f7-11eb-9782-19c98db68a3a.jpeg)

**Fix proposed:**
![Screenshot from 2021-04-01 14-05-43](https://user-images.githubusercontent.com/26017359/113268888-8458ff80-92f5-11eb-9a5a-e55462fca45f.png)

Going forward we can do a similar thing on the rest of the pages.
If it's a good issue, then I would like to work on it!

**Comment by pitag-ha** [comment]
That seems like a great idea! Are you an Outreachy applicant? If so, do you know that that part of the code is written in OCaml?

**Comment by dldisha** [comment]
Yes, I'm an Outreachy applicant. That part is not in OCaml, I'll replace the img tags only.

**Comment by pitag-ha** [comment]
> That part is not in OCaml, I'll replace the img tags only.

Ok. The New page has been confusing to other applicants due to invoking OCaml scripts. So I wanted to give you a heads-up in case that would be the same here. But I was wrong then :)

Anyways, you've explained well why Font Awesome better. So you can go ahead and work on this. 

When submitting the PR, it might be a good idea to also mention that Font Awesome complies the licensing (providing a link).

**Comment by dldisha** [comment]
Hey, @pitag-ha I guess, earlier I was navigating to the wrong file and you were right, that part of the code is in OCaml. 
And currently, we can't integrate Font Awesome with OCaml, it's supported with HTML/CSS. So sorry for the confusion.
