### ISSUE TITLE
Issue with focus on clickable image

### ISSUE THREAD

**Issue by Goodiec** [ocaml/v2.ocaml.org#1357]
Noticed an issue in the Books column on the learn page. Clicking on the first image applies the style for focus on the second image. Clicking on the second image applies to the second and also the outline from the style displays off the outline of the images. This issue is shown in the images below:

![issue2](https://user-images.githubusercontent.com/15726413/113289215-d85ce780-92e7-11eb-8af7-5c4a5f85cc9f.PNG)
![issue2 1](https://user-images.githubusercontent.com/15726413/113289221-da26ab00-92e7-11eb-9a89-df2b816256c6.PNG)

This can cause users to be confused and actually doubt if they clicked on the right image and doesn't give the best user experience. If this issue is approved, I can go ahead to try to fix this.

**Comment by gs0510** [comment]
This is a really good catch @Goodiec ! You can go ahead and fix this. Thank you!

**Comment by pitag-ha** [comment]
How is it going @Goodiec? :) Are you still working on this?

**Comment by Goodiec** [comment]
> How is it going @Goodiec? :) Are you still working on this?

Yes @pitag-ha, will open a pull request for it shortly. Thank you

**Comment by Goodiec** [comment]
@pitag-ha, @gs0510, I am trying to see if I can come up with layout improvements/new layout suggestions for some of the website pages especially those with a lot of content, is that within the scope of the contribution period? Also, I would be glad if you could point me to medium and more challenging issues relating to the project I am interested in working on (Improving the Ocam,org website), thank you

**Comment by gs0510** [comment]
@Goodiec I tagged you on this `medium` issue: #1321 :)
