### ISSUE TITLE
Spacing Sections on landing page

### ISSUE THREAD

**Issue by lindaokorie27** [ocaml/v2.ocaml.org#1360]
On the landing page, the different sections - learn, documentation, packages and community are closely packed together on large screens and not properly aligned on mobile.

![landing desktop](https://user-images.githubusercontent.com/38317939/113321616-ad848a80-930b-11eb-9263-6d0dc849de4d.JPG)

To improve readability as well as the general flow of the page, I would suggest moving the "home-learn" section below the news section and allowing the 4 other sections to span the space created. I made a sketch of how it would look like when done to illustrate:

![IMG_20210401_170058 1](https://user-images.githubusercontent.com/38317939/113322201-4ca98200-930c-11eb-96f1-26382e56f051.jpg)

@patricoferris What do you think of this? If it's alright, I could work on this.

**Comment by lindaokorie27** [comment]
@gs0510 would this be alright to work on now?

**Comment by gs0510** [comment]
@LindieK thanks for openinng this issue. I think it's not a meaningful change at this point in time and since you're already working on a `good-first-issue` you can pick up more challenging issues. Thanks! :)

**Comment by patricoferris** [comment]
I agree with @gs0510 -- thanks for the effort you put into the issue @LindieK
