### ISSUE TITLE
Improving the Contribute.md file to include help with WSL

### ISSUE THREAD

**Issue by Srinithyee** [ocaml/v2.ocaml.org#1365]
@patricoferris @pitag-ha @gs0510 I was thinking of adding the relevant steps to contribute to this repo, using a Windows Machine. Having seen myself and the other Outreachy applicants face trouble with installing WSL and the building on that, I thought having a well documented section for Windows Users in the Contribute.md file will be beneficial in the long run.

If this seems to be a good idea, do let me know, so that I can start working on it. Thanks!

**Comment by gs0510** [comment]
Hi @Srinithyee! This is indeed a good idea, there's a PR already open for this here: https://github.com/ocaml/ocaml.org/pull/1343/files. Once that's merged you can add anything that's missing :) Thanks!

**Comment by Srinithyee** [comment]
Okay! Thanks @gs0510
