### ISSUE TITLE
Issue in running eval $(opam env)

### ISSUE THREAD

**Issue by ChitvanRamani22** [ocaml/v2.ocaml.org#1366]
I am facing this issue .
It has been 2 hours since i had run this command but its not getting completed.![20210402_090820.jpg](https://user-images.githubusercontent.com/68965499/113377799-ff242800-9392-11eb-9211-3003cbac468b.jpg)
Please help me out.
![20210402_090820.jpg](https://user-images.githubusercontent.com/68965499/113379240-98087280-9396-11eb-88f1-24fb228770c0.jpg)
These lines are being displayed in every command .

**Comment by patricoferris** [comment]
Hi @ChitvanRamani22,

This is strange but there's a few things you can try. First of all I would try starting from scratch by (a) removing `~/.opam` and (b) double-checking what state your `~/.profile` is in, that might be where those `eval` statements are coming from. 

When you try init-ing again don't specify a compiler for now (incidentally `4.07.1` is too old for this project).

**Comment by ChitvanRamani22** [comment]
@patricoferris ![IMG-20210402-WA0049.jpeg](https://user-images.githubusercontent.com/68965499/113406206-b6876180-93c8-11eb-9677-605be406fc43.jpeg)
That error has gone but when i do create switch it shows this

**Comment by redianthus** [comment]
Try `opam update`.

**Comment by ChitvanRamani22** [comment]
@patricoferris i will ask everything here only sorry for making noise

**Comment by ChitvanRamani22** [comment]
@patricoferris @zapashcanon 
![IMG-20210402-WA0063.jpeg](https://user-images.githubusercontent.com/68965499/113407835-c3f21b00-93cb-11eb-8973-a4c770289fe6.jpeg)
This is the output
What next should i do.

**Comment by redianthus** [comment]
You have OCaml 4.05 installed, if you want 4.07 you can do `opam switch create 4.07.1`. Otherwise, you're good to go.

**Comment by ChitvanRamani22** [comment]
@zapashcanon what should i do next to run the project

**Comment by patricoferris** [comment]
Hmm, it also looks like you are using an old version of opam, I don't know if this is going to be a problem or not. Moreover, if you want to contribute to ocaml.org you will need a compiler `>= 4.08.0` https://github.com/ocaml/ocaml.org/blob/master/ocamlorg.opam#L9 as I said above. Thanks @zapashcanon for the help :))

There's a contributing guide: https://github.com/ocaml/ocaml.org/blob/master/CONTRIBUTING.md

**Comment by ChitvanRamani22** [comment]
@patricoferris then how could i upgrade to 4.08.0

**Comment by ChitvanRamani22** [comment]
@patricoferris @zapashcanon ![20210402_161054.jpg](https://user-images.githubusercontent.com/68965499/113409015-09afe300-93ce-11eb-853c-0210eea40567.jpg)
I ran opam upgrade again and now this is the output

**Comment by patricoferris** [comment]
You will need to install a new "switch" with a later version of OCaml. The following steps should help: 

1. Install a switch with the compiler version we use for deployment: `opam switch create 4.10.2 4.10.2`. You might then need to run `eval $(opam env)`. 
2. With this new switch you can then follow the contributing guide. From the root of the project you can run `make deps` to install the dependencies and then `make` or `make local` to build the site in `ocaml.org`. There's more information in the contributing guide about these commands.

Hopefully that will get you up and running, let me know if not :))

**Comment by ChitvanRamani22** [comment]
@patricoferris is it now safe to move inside the folder and run make deps?
![20210402_162455.jpg](https://user-images.githubusercontent.com/68965499/113409975-fc93f380-93cf-11eb-89e3-880302645f96.jpg)

**Comment by patricoferris** [comment]
Looking good to me - you should be able to `cd` into the repository and run `make deps` and the `make` 👍

**Comment by ChitvanRamani22** [comment]
@patricoferris should i write y here 
![20210402_163332.jpg](https://user-images.githubusercontent.com/68965499/113410503-2dc0f380-93d1-11eb-8e05-7ed67153c907.jpg)

**Comment by patricoferris** [comment]
Yep, that'll get the `opam-depext` tool which will install any non-ocaml, external dependencies

**Comment by ChitvanRamani22** [comment]
@patricoferris again the same
![20210402_163614.jpg](https://user-images.githubusercontent.com/68965499/113410659-9019f400-93d1-11eb-976e-1cd08c0be380.jpg)

**Comment by patricoferris** [comment]
Yep, that's asking to install the external dependencies 👍

**Comment by ChitvanRamani22** [comment]
I think it done successfully.

![20210402_170209.jpg](https://user-images.githubusercontent.com/68965499/113412193-416e5900-93d5-11eb-8d89-3ef49937ba82.jpg)

**Comment by patricoferris** [comment]
That's looking really good, seems it got all of the dependencies successfully. The next step is to run `make` (or `make local`) and have a look at the built site (if it hopefully builds!). Let me know if it builds and then we can close this issue. Thank you for your perseverance :))

**Comment by ChitvanRamani22** [comment]
@patricoferris it is running till now does this really takes so much time.
![20210402_180323.jpg](https://user-images.githubusercontent.com/68965499/113415905-cf4e4200-93dd-11eb-9a89-10c2b2e63644.jpg)

**Comment by patricoferris** [comment]
Hmm someone else experienced exactly this problem https://github.com/ocaml/ocaml.org/issues/1341#issuecomment-811830523

You could try: 

1. Stopping it, running `make clean` and trying again. 
2. Remove the repository entirely, re-`git clone` it from here and run `make`.

Not sure where this weird looping behaviour is coming from... seems only to impact WSL...

**Comment by ChitvanRamani22** [comment]
@patricoferris it has reached here![IMG-20210402-WA0099.jpeg](https://user-images.githubusercontent.com/68965499/113417042-3a991380-93e0-11eb-9980-55001518c878.jpeg)

**Comment by patricoferris** [comment]
Yes, I'm pretty sure that's it finished. The last build step, IIRC, is that it `rsync`s over the static files (like `css` ones etc.). Can you serve the site locally (i.e. something like `cohttp-server-lwt ./ocaml.org` and got to `localhost:8080` (I don't think this is `make local` so you will have to use a server rather than opening `./ocaml.org/index.html` in a browser).

**Comment by ChitvanRamani22** [comment]
![20210402_183731.jpg](https://user-images.githubusercontent.com/68965499/113418132-81880880-93e2-11eb-86a1-dcc4644ed29c.jpg)
@patricoferris as finally it has reached here do i need to do that step u told earlier.

**Comment by ChitvanRamani22** [comment]
![20210402_184057.jpg](https://user-images.githubusercontent.com/68965499/113418376-007d4100-93e3-11eb-9fe6-5d0037885123.jpg)
@patricoferris 
Have i landed on the right page?

**Comment by patricoferris** [comment]
It looks like it had managed to build the site (now with `make local`). But the screenshot is the "actual site" I think (because of the URL bar, I think that's just https://ocaml.org). You should be able to open the file path to `<some-file-path>/ocaml.org/ocaml.org/index.html` in your browser? (the first `ocaml.org` being the cloned repo, the second being the build folder)

**Comment by ChitvanRamani22** [comment]
@patricoferris could you please tell what should i write in my chrome browser.

**Comment by ChitvanRamani22** [comment]
@patricoferris are u taking about this.
![20210402_205025.jpg](https://user-images.githubusercontent.com/68965499/113428815-1a278400-93f5-11eb-9914-c3cea38a427f.jpg)

**Comment by patricoferris** [comment]
Sure, if you ran `make local` you need to get the full, absolute path to `ocaml.org/index.html`.

You will most likely have cloned the repository into a directory called `ocaml.org`. After running `make local` there should be a directory inside that one called `ocaml.org` and inside that a file called `index.html`. You need to get the path to that and paste it into your browser (on most modern machines if you can find the file in a file viewer like finder on macOS, you should also just be able to "double-click" on that file and have it open in a browser).

**Comment by ChitvanRamani22** [comment]
@patricoferris do i need to run make again before running the path as i exited that command

**Comment by ChitvanRamani22** [comment]
![Screenshot_20210402-222450_WhatsApp.jpg](https://user-images.githubusercontent.com/68965499/113436516-7513a800-9402-11eb-92da-71c470077ecd.jpg)
@patricoferris this is how it is appearing in vs code. Why that folder is muted?

**Comment by ChitvanRamani22** [comment]
@patricoferris its working!! 
I made the change for testing i.e replaced new packages with old packages and could see it.
![20210402_232442.jpg](https://user-images.githubusercontent.com/68965499/113440794-bad46e80-940a-11eb-8b70-e8885f14fd52.jpg)

**Comment by patricoferris** [comment]
Hi @ChitvanRamani22 I'm glad you got everything working 👍

Just for future reference (and for anyone else who comes to this issue) much of the conversation happened on this closed issue https://github.com/ocaml/ocaml.org/issues/1339#issuecomment-812504315 

Looking forward to your contributions :))

**Comment by ChitvanRamani22** [comment]
Thank you so much for helping and being so patient and handling an impatient child like me @patricoferris :).
