### ISSUE TITLE
Improve Videos section in https://ocaml.org/learn/ and https://ocaml.org/docs/

### ISSUE THREAD

**Issue by guptadiksha307** [ocaml/v2.ocaml.org#1367]
On screen sizes less than 764px, when we navigate to Learn section, the videos are not aligned properly.

![image](https://user-images.githubusercontent.com/53967592/113377730-c421f480-9392-11eb-9512-e66ff335484b.png)

Similary in the documentation section, one video is not in order with the other two.

![image](https://user-images.githubusercontent.com/53967592/113377781-efa4df00-9392-11eb-964a-4423deee4e92.png)

I would like to fix this as

![image](https://user-images.githubusercontent.com/53967592/113377912-46aab400-9393-11eb-82ed-d5cbbf1bdeb4.png)
![image](https://user-images.githubusercontent.com/53967592/113377966-680ba000-9393-11eb-9851-e49347a74b4e.png)

**Comment by guptadiksha307** [comment]
@patricoferris I think this issue can be part of the "good-first-issue" and I would like to work on this.

**Comment by gs0510** [comment]
This is a good catch @guptadiksha307! You can go ahead and work on this :)

**Comment by pitag-ha** [comment]
@guptadiksha307 , how is it going? :) Are you still working on this?

**Comment by guptadiksha307** [comment]
@pitag-ha The PR related to this issue has been merged. Thank you :)

**Comment by gs0510** [comment]
Can you link the PR here? @guptadiksha307

**Comment by guptadiksha307** [comment]
@pitag-ha here is the link of the PR-
https://github.com/ocaml/ocaml.org/pull/1377#event-4558321957

**Comment by patricoferris** [comment]
Nice @guptadiksha307 thank you :))
