### ISSUE TITLE
Improve packages page in https://opam.ocaml.org/packages/ on small screens

### ISSUE THREAD

**Issue by TildaDares** [ocaml/v2.ocaml.org#1370]
On small screens the packages table causes an overflow and makes the entire screen have a horizontal screen.

![BEFORE](https://user-images.githubusercontent.com/63427719/113402730-67780700-939d-11eb-8457-84e1228ec028.gif)

I'd like to fix it by making only the packages table scrollable(horizontally). 

![after](https://user-images.githubusercontent.com/63427719/113402658-444d5780-939d-11eb-9256-532cdb00428d.gif)

**Comment by TildaDares** [comment]
@patricoferris If this is a good issue I'd like to fix it.

**Comment by gs0510** [comment]
@TildaDares This is a good catch! You can go ahead and work on this :)

**Comment by TildaDares** [comment]
@gs0510 I couldn't find this page in my local repo so I asked in the discord server and @patricoferris said that this site is a little outside of the scope of ocaml.org. Would you like me to go ahead with it?
