### ISSUE TITLE
Adding images in learn/books

### ISSUE THREAD

**Issue by Srinithyee** [ocaml/v2.ocaml.org#1371]
@patricoferris @gs0510 @pitag-ha
There are some books which are without their images. It looks slightly ugly here, https://ocaml.org/learn/books.html

![1](https://user-images.githubusercontent.com/34683520/113403872-f51b1d00-93c4-11eb-9864-0b1dc4dced37.png)
![2](https://user-images.githubusercontent.com/34683520/113403887-f6e4e080-93c4-11eb-81e1-fbf80d55b95f.png)
![3](https://user-images.githubusercontent.com/34683520/113403894-f9473a80-93c4-11eb-90d2-1c0b62a60f9e.png)
![4](https://user-images.githubusercontent.com/34683520/113403903-fba99480-93c4-11eb-9da9-adb5a5987262.png)

I'd like to add the relevant images here to make it look better.

Can I work on this issue, if it counts as a good fix?

**Comment by patricoferris** [comment]
Hi @Srinithyee, are you sure there are relevant images for these "books" I have a feeling these are all pdfs or github repositories. If you could share the images (or links to them) here first that would be great thanks :))

**Comment by Srinithyee** [comment]
@patricoferris Yeah, sure :)
1. Unix System Programming in OCaml : https://i0.wp.com/www.linuxlinks.com/wp-content/uploads/2019/08/Unix-System-Programming-OCaml.jpg?resize=166%2C218&ssl=1
2.  Using, Understanding, and Unraveling OCaml: 
![0001](https://user-images.githubusercontent.com/34683520/113418113-77fea080-93e2-11eb-8bbc-611661829d91.jpg)
3. Introduction to OCaml:( The book is actually called Introduction to objective OCaml Programming Language.I'll fix that as well in this issue, if approved)
![Picture1](https://user-images.githubusercontent.com/34683520/113418269-c449e080-93e2-11eb-8314-a8466e04ef76.jpg)
4. OCaml Book: This is actually a Github repo(oops!) How about placing the Github icon instead of leaving it blank? This might improve the accessibility for the user as well, giving a heads up that it is a Github repo and not a book. 

Do let me know if I can proceed with this. Thanks!

**Comment by Srinithyee** [comment]
@patricoferris could I work on this?

**Comment by pitag-ha** [comment]
@Srinithyee , do I understand correctly that your suggestion is for books without cover to replace the generic OCaml png by the book's first page? Why do you think that's better? :) The advantage of the generic OCaml png is:
- we don't load unnecessary data (we only load one for all)
- it looks better

**Comment by Srinithyee** [comment]
>The advantage of the generic OCaml png is:
> 
> * we don't load unnecessary data (we only load one for all)
> * it looks better

@pitag-ha yes, I do agree with you based on your points. 
But the book Unix System Programming in OCaml does have a cover. How about [linking]( https://i0.wp.com/www.linuxlinks.com/wp-content/uploads/2019/08/Unix-System-Programming-OCaml.jpg?resize=166%2C218&ssl=1) that alone?

@pitag-ha I've already contributed to 3 simple issues [#1441 ,#1440, #1369]. This does look simple to me. Would you suggest me taking this up or leaving it open for the others?

**Comment by gs0510** [comment]
@Srinithyee I think we can close this issue then :)

**Comment by Srinithyee** [comment]
@gs0510 Alright then! I'll close it :)
