### ISSUE TITLE
Adjusting spacing of books in books section

### ISSUE THREAD

**Issue by Bhavika-Gianey** [ocaml/v2.ocaml.org#1373]
There is one Italian book that is going out of order on the books page.

![fix2](https://user-images.githubusercontent.com/63343906/113407891-e6843400-93cb-11eb-88ba-8fc81ce42fa4.PNG)

**Comment by Bhavika-Gianey** [comment]
I would like to fix this if it is approved

**Comment by nibble0101** [comment]
Hi @Bhavika-Gianey. Thanks for opening the issue. It would be a lot easier for others who would love to investigate the issue out of pure curiosity or those who might possibly review your PR  if you provided a link to the affected page in addition to the screenshots.

**Comment by Bhavika-Gianey** [comment]
> Hi @Bhavika-Gianey. Thanks for opening the issue. It would be a lot easier for others who would love to investigate the issue out of pure curiosity or those who might possibly review your PR if you provided a link to the affected page in addition to the screenshots.

sure @nibble0101 :)).

This is the link of the affected page
https://ocaml.org/learn/books.html

**Comment by gs0510** [comment]
@Bhavika-Gianey  This is a good catch! :) You can go ahead and work on this :)
