### ISSUE TITLE
Repositioning of breadcrumbs on non top level pages and differentiate languages

### ISSUE THREAD

**Issue by dinakajoy** [ocaml/v2.ocaml.org#1378]
I suggest we move the breadcrumbs to the right of the page and also differentiate the languages

![Capture](https://user-images.githubusercontent.com/39722740/113443612-3c67d480-93ea-11eb-9b9f-dae9d2220727.PNG)

![bfore](https://user-images.githubusercontent.com/39722740/115245507-e77fca00-a11c-11eb-9354-046710559248.PNG)

If it's a good issue, I can make the fix

**Comment by pitag-ha** [comment]
> I suggest we move the breadcrumbs to the right of the page.

Why would you suggest that? We have the breadcrumbs on the left on all ocaml.org pages with breadcumbs. On other websites I've seen both, breadcrumbs on the left and breadcrumbs on the right, so I'm not sure there's a standard. Why do you prefer them on the right?

> Also the languages are to close, a little spacing or/and adding of | as separator will be a good accessibility solution for people that use large mouse icons.

That sounds like a great idea to me! Notice that there's currently a [PR open that's also touching the language selector](https://github.com/ocaml/ocaml.org/pull/1345). Do you have experience with working on the same part of the code someone else is working on (resolving git conflicts e.g.)? If so, you can go ahead and work on this already :) if not, it might be a good idea to wait for the other PR to get merged first.

**Comment by dinakajoy** [comment]
I am sorry @pitag-ha, that was an error. I meant that breadcrumbs should be on the left.
The pull request has been merged, so I will work on it right away.
Thank you.

**Comment by pitag-ha** [comment]
Which PR are you referring to?

**Comment by dinakajoy** [comment]
I meant this PR https://github.com/ocaml/ocaml.org/pull/1345, which has been merged

**Comment by pitag-ha** [comment]
Oh sorry, I misunderstood: I thought you referred to a PR referring the breadcrumbs. Sure then! On how many simple issues have you worked already? Take into account [this](https://github.com/ocaml/ocaml.org/issues/1245#issue-821019972) :)

**Comment by dinakajoy** [comment]
I have worked on:
1 'good first issue' here - #1313 
1 issue created by me - #1346 
Currently working on this one, which was also created by me
Lastly, I will try out - #505  
Hope I can go on please?

**Comment by pitag-ha** [comment]
Thanks for the overview! 

Ok, we've said max 3 simple issues and since #505 isn't simple and furthermore I had already told you you can work on this, you can go ahead :) but afterwards  don't work on more simple issues anymore, please.

**Comment by dinakajoy** [comment]
Noted, thank you

**Comment by dinakajoy** [comment]
@pitag-ha and @nibble0101 please how do you see this -
![Capture](https://user-images.githubusercontent.com/39722740/113786187-904b2400-9730-11eb-80f8-4ea001a437a5.PNG)

**Comment by pitag-ha** [comment]
Looks pretty good! :) Why is `fr` underlined and the other languages aren't? Are you hovering over it?

**Comment by dinakajoy** [comment]
I hovered it at that time. Thank you.

**Comment by pitag-ha** [comment]
Ok, to me it looks good :)Thanks for both the idea and the implementation!

**Comment by dinakajoy** [comment]
@pitag-ha can you take a look at this please - https://github.com/ocaml/ocaml.org/issues/1353#issuecomment-814762129.
I could not tag you directly on that issue.
