### ISSUE TITLE
Improve the https://www.ocaml.org/community

### ISSUE THREAD

**Issue by Ndipbanyan** [ocaml/v2.ocaml.org#1380]
# Issue Description
When you navigate to /community page, the icons/images reflecting `OCaml around the Web` look too large and occupy a lot of space. I think they can look better thus:
# Before::
<img width="1213" alt="Screenshot 2021-04-03 at 02 07 46" src="https://user-images.githubusercontent.com/67186679/113464110-4279a780-9422-11eb-8cde-f377840539f5.png">

# After::
<img width="1207" alt="Screenshot 2021-04-03 at 02 07 21" src="https://user-images.githubusercontent.com/67186679/113464153-810f6200-9422-11eb-8c41-d814f372cf2a.png">

**Comment by Ndipbanyan** [comment]
I will love to work on this if it is worth fixing

**Comment by dinakajoy** [comment]
Someone has made a fix on this here #1317 and #1270, do check them out

**Comment by Ndipbanyan** [comment]
@dinakajoy thank you. Didn't see that earlier. I am closing this now.
