### ISSUE TITLE
Issue with ssl installation as a part of make deps

### ISSUE THREAD

**Issue by Srinithyee** [ocaml/v2.ocaml.org#1381]
@patricoferris 
I tried checking issue #1341, but I still seem to run into this error while running make deps.
This is the issue I am facing when I run make deps:
![image](https://user-images.githubusercontent.com/34683520/113468930-0d437880-9467-11eb-80dc-54d36bdbebc5.png)

Could you please help me with this? It worked just fine a few days back :/

On following the updated [document](https://github.com/ocaml/ocaml.org/blob/dfecc2d82746dea740e0e4fe635c96656fd24e31/CONTRIBUTING.md#errors-faced-while-building-the-site-using-wsl) for WSL installation, I still seem to get this error on running apt install libssl-dev
![image](https://user-images.githubusercontent.com/34683520/113469307-39acc400-946a-11eb-8030-4925129a005f.png)

**Comment by patricoferris** [comment]
Hi @Srinithyee, did you manage to get this resolved?

I'm not very familiar with windows/WSL but it doesn't appear to look like you are using WSL from these screenshots, you can tell this from `opam`'s output of `win32/x86_64`. I'm pretty sure when running WSL it should all appear to be a Linux machine (this could also be the reason there's no `sudo` and no `apt`?). Please let me know if this is the case and if you've managed to get it to work, thanks :))

**Comment by Srinithyee** [comment]
@patricoferris I was using WSL1. I updated to WSL2 and was able to deploy the site. Thanks a lot!
issue #1341  was extremely helpful too.
I'll close the issue :)

**Comment by patricoferris** [comment]
Okay great, glad you got it building, thanks I'll close it now 👍
