### ISSUE TITLE
Images not displayed

### ISSUE THREAD

**Issue by hitblunders** [ocaml/v2.ocaml.org#1383]
Images are not getting displayed in ocaml.org/site/learn/tutorials/99problems.md .

Screenshot -

![Screenshot from 2021-04-03 12-08-07](https://user-images.githubusercontent.com/72441280/113470779-b4c7a780-9475-11eb-9a6a-f027ff59d7f5.png)

**Comment by pitag-ha** [comment]
Good catch, thanks!

**Comment by patricoferris** [comment]
Looks like this was just a difference between Github rendering and our deployment, thanks for looking into this @hitblunders :))
