### ISSUE TITLE
unable to see changes after building the site using WSL

### ISSUE THREAD

**Issue by yashi-hub** [ocaml/v2.ocaml.org#1391]
I built the site locally , but when I'm running `make local` and then on my browser adding the path of the file such as 
: `C:\Users\user\Desktop\ocaml.org\site\meetings\ocaml\index.html` 
I see `Your file couldn’t be accessed`.
I also tried running it by first doing `make production` and then `cohttp-server-lwt ./ocaml.org ` i see the site built on localhost:8080 successfully. but then if I do some code changes, again run `make production` followed by `cohttp-server-lwt ./ocaml.org` I see no changes implemented.

I followed https://github.com/ocaml/ocaml.org/issues/1366  and https://github.com/ocaml/ocaml.org/issues/1341 but nothing seems to work.
I also noticed that a few applicants have a similar issue and instead of answering it in between another issue, I preferred opening a new one. hoping to get it resolved soon :)

**Comment by patricoferris** [comment]
Hi @yashi-hub,

Thanks for opening this, I think I'll need a little more information to help you out here. In particular if you could add/try doing:

 - What files are you changing between `make production` calls?
 - What are the changes?
 - In a file explorer does the file "`C:\Users\user\Desktop\ocaml.org\site\meetings\ocaml\index.html`" exist?
 - If you run `make clean` and then `make` do you see the changes? 
 
Hopefully we can get this resolved soon :))

**Comment by yashi-hub** [comment]
hey @patricoferris .
1. I'm changing the success.md file between make production call.
2.  for seeing the changes , I've tried multiple things like - 
        1. removed a text paragraph to check if the editing is displayed in the site.
        2. made some changes to the UI (like changing the border length etc.) (nothing worked)
 3.  sorry for the wrong information , I run  `C:\Users\user\Desktop\ocaml.org\site\learn\success.md` after running make local .
       this file exists in the file explorer and I made changes to the same file , but on running it the explorer just shows it's code without any styling.
4.   no , it didn't work either. 

being unable to see the changes on my local website , i have to change the code in notepad and then create a PR.

hoping to get it resolved soon :))

**Comment by yashi-hub** [comment]
hey @patricoferris , i figured out that I was using the wrong link to open the site.
I got it working perfectly now, apologies for opening this :))

to anyone facing this issue and came here to check, you can look for the solution here: https://github.com/ocaml/ocaml.org/issues/1245#issuecomment-815165431 
closing this issue now :)
