### ISSUE TITLE
Hovering over the green buttons does not change/animate the button clearly

### ISSUE THREAD

**Issue by CQW-Code** [ocaml/v2.ocaml.org#1393]
On the green buttons that take you to additional resources/information, when I hover over it - the cursor does change to a hand but the change in color is so slight I couldn't tell if it was a true button to click.  This would be an issue for low vision/vision impaired people.  On actually clicking the button, the border does change to a thin orange (?) line.
   If this is a good issue, I'd like to work on it. 

-Chris

**Comment by pitag-ha** [comment]
@CQW-Code, sounds great to me. You can go ahead and work on this if you'd like.

**Comment by CQW-Code** [comment]
Thanks!  Right now I think I broke make- I had it working fine a day or two ago, now I can't get the local version of the site up.  No error messages at all that I can see.

**Comment by pitag-ha** [comment]
Ok, no hurries! These things happen all the time. If you have a concrete question, you can always open an issue asking about it :)
