### ISSUE TITLE
improve footer section

### ISSUE THREAD

**Issue by guptadiksha307** [ocaml/v2.ocaml.org#1397]
Initially, the footer section on mobile devices looks like-

![image](https://user-images.githubusercontent.com/53967592/113502046-43582980-9547-11eb-8196-cd6421638255.png)

I usually follow material design UI and according to that footer section should be-

![image](https://user-images.githubusercontent.com/53967592/113502097-99c56800-9547-11eb-97f9-487b29127592.png)

**Comment by guptadiksha307** [comment]
@patricoferris @gs0510 If this seems a good idea for you, please do let me know, I would like to work on this :)

**Comment by gs0510** [comment]
Hi @guptadiksha307! This is a good catch, but there's already an issue open to fix the footer view on mobile devices here: https://github.com/ocaml/ocaml.org/issues/1276 :)

**Comment by guptadiksha307** [comment]
oh okay. So should I close this issue now?

**Comment by gs0510** [comment]
Yes you can close it :) @guptadiksha307
