### ISSUE TITLE
Add Issue Template

### ISSUE THREAD

**Issue by TildaDares** [ocaml/v2.ocaml.org#1398]
@patricoferris This repo still doesn't have an issue template. Is @LindieK still working on it? If they aren't I'd like to take it up.

**Comment by pitag-ha** [comment]
@TildaDares , please notice that adding an Issue Template was marked as good-first-issue and you've already worked on a good first issue.

@LindieK, how is it going? Are you still working on the Issue Template? :)

**Comment by TildaDares** [comment]
I'm sorry, I forgot it was a good-first-issue.

**Comment by lindaokorie27** [comment]
@pitag-ha yes I am
