### ISSUE TITLE
Reduce the spacing between the Content Table and Contents in https://www.ocaml.org/learn/tutorials/up_and_running

### ISSUE THREAD

**Issue by Ndipbanyan** [ocaml/v2.ocaml.org#1400]
# Issue Description
When you view the `Up and Running` section in /learn/tutorials, you will see that the space between the content table and the content is quite large. 
# Suggestions
 The screenshots below give a suggestion that I will like to fix
 # Before
<img width="1436" alt="Screenshot 2021-04-04 at 14 53 15" src="https://user-images.githubusercontent.com/67186679/113511108-195a3380-9556-11eb-8764-a4aed606bd6e.png">

# After
<img width="1436" alt="Screenshot 2021-04-04 at 14 53 00" src="https://user-images.githubusercontent.com/67186679/113511126-2c6d0380-9556-11eb-950c-ccdfbeada8c8.png">

**Comment by patricoferris** [comment]
Hi @Ndipbanyan,

Thanks for opening this issue. As a general rule, it's always good to not only explain what you are changing, but to also justify the change. There are lots of little changes that *could* be made to the site regarding layout/design, but we also need to decide on changes that improve things or else we'd be inundated with PRs and issues.

> the space between the content table and the content is quite large

What do you think is being improved here?

Some other questions I have: 

1. Do you know how this impacts other pages which may have slightly longer entries in the ToC (e.g. https://ocaml.org/docs/papers.html)?
2. How does this look on small screen sizes? For example here is unchanged site on an `tablet` size screen (w: `768px`).
![tablet](https://user-images.githubusercontent.com/20166594/113733164-1f851700-96f2-11eb-9674-ae9458f91fd9.png)

Sorry if this comes across as nit-picky, I'm trying to understand you're thinking here to make sure this is worth your time :)) Thanks again for the contributions.

**Comment by Ndipbanyan** [comment]
Oh I see your point @patricoferris. I actually just took note of this page alone without considering other pages that can be affected if changes were to be made to it. Upon considering however that changes to this page can affect other pages in a manner that is not so good, I agree this change is not necessary so I will be closing this issue. Thanks.
