### ISSUE TITLE
Fix typos in https://ocaml.org/learn/tutorials/

### ISSUE THREAD

**Issue by TildaDares** [ocaml/v2.ocaml.org#1404]
'your are' should be 'you are'

![image](https://user-images.githubusercontent.com/63427719/113515628-91802380-956d-11eb-937a-10567ce72328.png)

There should be either a full stop after the 'Ocaml for Haskellers' or the sentence could be 'Ocaml for Haskellers provides some notes on the differences between OCaml and Haskell.'

![image](https://user-images.githubusercontent.com/63427719/113515663-bd9ba480-956d-11eb-9699-7ea5a362914a.png)

**Comment by poornimashrivastava** [comment]
Hi @TildaDares ! I'm Poornima, an Outreachy applicant. I'd like to contribute to this if no one's working on it.
