### ISSUE TITLE
Translation error in 'Learn' page.

### ISSUE THREAD

**Issue by gurleennsidhuu** [ocaml/v2.ocaml.org#1408]
The heading for 'Books' in the French translation of the page https://ocaml.org/learn/index.html is:
![h](https://user-images.githubusercontent.com/64313783/113539402-5d534400-95fb-11eb-8861-4df1070a4e2e.png)
which translates to 'English and French books' but there are books in other languages too. I think the heading should be 'Livres' according to the online translator.

**Comment by gurleennsidhuu** [comment]
I found one error in https://ocaml.org/community/index.fr.html too. 
![Screenshot 2021-04-05 130630](https://user-images.githubusercontent.com/64313783/113549872-c47af380-960f-11eb-9c5f-194c3c311138.png)
When we translate the French page to English, 'Rencontres et réunions' translates to 'Meetings and meetings'.

**Comment by patricoferris** [comment]
Hi @gurleennsidhuu thanks for opening the issue,

I think your initial suggestion makes sense. The second one, however, I think is just a limitation of whatever translation service is being used, I think there's nuance between `Rencontres` and `Réunions` the former being more like "meet-ups" and the latter, formal (business-like) "meetings". I checked with some people who can speak French and they confirmed this.

**Comment by gurleennsidhuu** [comment]
> Hi @gurleennsidhuu thanks for opening the issue,
> 
> I think your initial suggestion makes sense. The second one, however, I think is just a limitation of whatever translation service is being used, I think there's nuance between `Rencontres` and `Réunions` the former being more like "meet-ups" and the latter, formal (business-like) "meetings". I checked with some people who can speak French and they confirmed this.

Ok. Thanks. Will make a PR from the 1st suggestion. :)
