### ISSUE TITLE
functional_programming.html: broken link

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#141]
The [Functional Programming](http://ocaml.org/tutorials/functional_programming.html) tutorial has this broken link: [boxedarray.png](http://ocaml-tutorial.org/_bin/upload_image_form.cmo?name=boxedarray.png). Originally reported in #140.

Also in the [Garbage Collection](http://ocaml.org/tutorials/garbage_collection.html) tutorial there is this broken link: [users.bin.gz](http://ocaml-tutorial.org/_bin/upload_file_form.cmo?name=users.bin.gz).

Both point to an _bin/upload_image_form.cmo script with the name of the file as a parameter. Thus, the question is whether the target files exist on the [mirror](http://mirror.ocamlcore.org/ocaml-tutorial.org/index.html) from which the tutorials were imported.

@agarwal will ask Sylvain and/or Richard Jones whether these files are still available somewhere.

**Comment by agarwal** [comment]
Richard Jones was kind enough to send me an old CVS tree. The missing files are supposedly in there. There are two issues:
- Figuring out how to convert the tree, which is in SCCS format, to a functioning CVS repo. Something about using "cvs -d" and possibly starting an empty CVS repo and importing this tree into that repo are the way to go. @agarwal tried but was unable to figure out how to do this.
- Once the repo is working, we'd have to search through the history to find these files. They were deleted and will not be in the latest working directory.

Any CVS experts want to help?!

**Comment by avsm** [comment]
Send me the tree and I'll convert it to git.

**Comment by avsm** [comment]
Expanded and sent on via private email to Ashish.
