### ISSUE TITLE
Fix focus in https://ocaml.org/learn/success.html

### ISSUE THREAD

**Issue by TildaDares** [ocaml/v2.ocaml.org#1415]
When the brand image/logo is clicked in https://ocaml.org/learn/success.html, the focus is on the text beside the image instead of the image.

![image](https://user-images.githubusercontent.com/63427719/113577031-846c3e80-9618-11eb-89df-2e261b82dfcc.png)

I'd like to fix this.

**Comment by pitag-ha** [comment]
Good catch, thanks!
