### ISSUE TITLE
Unwanted line in OCaml Planet Syndication

### ISSUE THREAD

**Issue by gurleennsidhuu** [ocaml/v2.ocaml.org#1424]
I am not sure if this line is needed here because it is not an example for institutional feed.
![Screenshot 2021-04-06 111051](https://user-images.githubusercontent.com/64313783/113664227-0025c400-96c9-11eb-90e8-fb1a30417011.png)

**Comment by patricoferris** [comment]
Thanks for opening the issue @gurleennsidhuu. I'm actually okay with leaving this as is, I think it's meant to indicate that these are just examples and not an exhaustive list.
