### ISSUE TITLE
Map overflow on https://ocaml.org/learn/teaching-ocaml.html on mobile view

### ISSUE THREAD

**Issue by Bhavika-Gianey** [ocaml/v2.ocaml.org#1426]
There is map overflow on https://ocaml.org/learn/teaching-ocaml.html  which is causing extra right spacing on mobile view.

## Before

![i-5-new](https://user-images.githubusercontent.com/63343906/113665375-0157f080-96cb-11eb-964b-7e47f506c10f.gif)

## After

![newone](https://user-images.githubusercontent.com/63343906/113666883-978d1600-96cd-11eb-9604-313f5551d384.gif)

I would like to fix this spacing issue:).

**Comment by patricoferris** [comment]
That looks like a good bug to fix, thanks @Bhavika-Gianey
