### ISSUE TITLE
Hosting section seems missing from contributors in French translation

### ISSUE THREAD

**Issue by Riddhima23** [ocaml/v2.ocaml.org#1429]
<img width="926" alt="english" src="https://user-images.githubusercontent.com/58878761/113680911-01fa8200-96df-11eb-99c7-1b4ba3dcc417.png">
<img width="939" alt="french" src="https://user-images.githubusercontent.com/58878761/113680917-045cdc00-96df-11eb-8ea4-93c49601dd0f.png">
I would like to fix this :) !

**Comment by gs0510** [comment]
This is a good catch! You can go ahead and work on this @Riddhima23  :)

**Comment by Riddhima23** [comment]
Okay @gs0510 thanks! I will do it!😊
