### ISSUE TITLE
News section page can not be translated in french language

### ISSUE THREAD

**Issue by shreyaswikriti** [ocaml/v2.ocaml.org#1430]
![Screenshot from 2021-04-06 13-49-04](https://user-images.githubusercontent.com/57635473/113680933-06bf3600-96df-11eb-8b7f-bb2aaa7d883f.png)
while navigating to the news page I found the news articles are only available in the English language.
![Screenshot from 2021-04-06 13-47-51](https://user-images.githubusercontent.com/57635473/113681071-3110f380-96df-11eb-9960-95e6fea6af37.png)

**Comment by pitag-ha** [comment]
That's because the posts themselves are written in English, so it seems to me like there's not much we could do. Or do you think there is? :)

**Comment by shreyaswikriti** [comment]
ok got it. We need some french translator for this. Unfortunately, I don't know french. @pitag-ha Can you review my other issues so that I can start working on those. Thanks.

**Comment by pitag-ha** [comment]
In fact, I think there's nothing we can/should do in general. We're just fetching blog posts in whichever language they are written :)

**Comment by patricoferris** [comment]
Seems like there's not much value in a french page when we're just rendering the collection of news articles, thanks for bringing this to our attention anyway @shreyaswikriti :))
