### ISSUE TITLE
Improve user experience on https://www.ocaml.org/learn/tutorials/  on smaller screens

### ISSUE THREAD

**Issue by Ndipbanyan** [ocaml/v2.ocaml.org#1436]
# Issue Description
The navbar of most of the pages on the tutorial section remains static at the top on smaller screens view and this makes it difficult for a user to navigate to another page once they have scrolled down the page they are on.

# Suggestion
The user can have a better experience navigating to other pages if the navbar is set to a fixed or sticky position so that the user can easily click on the hamburger menu to navigate to any other page irrespective of how far down the user has scrolled to.
If it is worth fixing, I will love to do so.

**Comment by pitag-ha** [comment]
That sounds like a great idea! I'd say you can go ahead and work on it, if you'd like :)

**Comment by Ndipbanyan** [comment]
Alright I will get to it then.
