### ISSUE TITLE
Setting Ocaml in Windows

### ISSUE THREAD

**Issue by Srinithyee** [ocaml/v2.ocaml.org#1437]
@patricoferris 
I would like to add a new markdown file just to deal with all the steps to setting up the environment to contribute to OCaml using a windows machine.
While PR #1343 (has been merged) seems to deal with the errors faced while using WSL, there is no laid down steps right from how to install WSL to making "make deps" work. 

I thought of creating a new folder and putting Contribution.md and this markdown file into it.

That way, the whole installation process becomes seamless for the beginners. I would like to refer to issue #1341 for the same.
If this isn't too much of a change to the directory structure, I'd love to work on it.

This issue has been proposed instead of issue #1365

**Comment by pitag-ha** [comment]
Is the documentation of WSL not good enough? For example, is it not enough to follow [this](https://docs.microsoft.com/en-us/windows/wsl/install-win10)? I'm asking, since I don't use WSL and hence don't know. What would you add to that guide in addition to:
- how to install WSL
- run `make deps`
- run `make`?

**Comment by Srinithyee** [comment]
Yes, I've drafted the points to be added below:
1. Install WSL2 and launch a linux based distribution
2. Launch the WSL Terminal and create a password for the linux based distribution.
3. Run ```sudo apt-get install build-essential``` to be able to use make command
4. Install opam from [here](https://opam.ocaml.org/doc/Install.html)
5. cd to your directory using /mnt/ as the root
6. git clone the repository into your system in the WSL Terminal
7. cd to the cloned repository
8. run ```opam init --disable-sandboxing -a```
9. run ```make deps```
ends like this:
![image](https://user-images.githubusercontent.com/34683520/113804505-44be6780-977c-11eb-8be9-36f65a27d931.png)
10. run ```make```
ends like this:
![image](https://user-images.githubusercontent.com/34683520/113804539-556edd80-977c-11eb-99c1-2a01888d6eda.png)


This way, I felt any beginner would find it easy to set up the dev env on their local machine :)

**Comment by pitag-ha** [comment]
I'm not really convinced to be honest. From what I understand
- steps 1-3 is the WSL setup (I'd say that when you're running debian natively, you have `build-essentials` installed already). 
- steps 5-7 is cloning the repo and cd-ing into it.
- steps 4, 8, 9 and 10 are explained in CONTRIBUTION.md

Is that right?

**Comment by Srinithyee** [comment]
@pitag-ha  Yes, the steps are simple. But, there is no laid down procedure having it all together in one place. For instance, an Outreachy applicant @Muskan-sam  wasn't able to set up the dev env on windows although the steps are available out there, but in different places. But, the steps I've mentioned on my previous comment on this issue did help here. 

My intention was only to make things easier for other applicants, because I faced difficulty. But since I've put down the steps needed here, I'm happy this helped someone somehow. It's fine if you wouldn't like me to make a documentation for this :)

**Comment by gs0510** [comment]
@Srinithyee Writing down WSL steps is out of scope and also means that we might have a documentation debt when things change. If you want, you can write a blog post (which won't be linked to ocaml.org) but if/when someone runs into an error setting up WSL they can find your blog post when they google it. :)

**Comment by Srinithyee** [comment]
> @Srinithyee Writing down WSL steps is out of scope and also means that we might have a documentation debt when things change. If you want, you can write a blog post (which won't be linked to ocaml.org) but if/when someone runs into an error setting up WSL they can find your blog post when they google it. :)

@gs0510  yes, that sounds like a great idea! Thanks :) I'll close this issue.
