### ISSUE TITLE
The books on mobile view in the Documentation page needs to be positioned symmetrically

### ISSUE THREAD

**Issue by jyotibalodhi** [ocaml/v2.ocaml.org#1438]
On the page https://ocaml.org/docs/ the book's position is looking very unsymmetrical and out of proportion, as can be seen in the picture.
![Docs-page](https://user-images.githubusercontent.com/63946672/113710116-f15b0380-9700-11eb-8dc6-c683c63c6ded.jpg)

I would like to work on this issue! What do you think about this @patricoferris @pitag-ha @gs0510 ?

**Comment by jyotibalodhi** [comment]
By using flexbox in this section. I changed the positions like this. What do you think about this? 

![Docs-OCaml](https://user-images.githubusercontent.com/63946672/113716924-b230b080-9708-11eb-8813-3f4986101740.png)

**Comment by gs0510** [comment]
Hi @jyotibalodhi , this is indeed a good catch, but it's a duplicate for #1344 and there's a PR already open to fix it. :) You can close this issue.

**Comment by jyotibalodhi** [comment]
> Hi @jyotibalodhi , this is indeed a good catch, but it's a duplicate for #1344 and there's a PR already open to fix it. :) You can close this issue.

I am sorry I missed that, Thanks for confirming though! :)
