### ISSUE TITLE
Repositioning images in Contributors

### ISSUE THREAD

**Issue by Srinithyee** [ocaml/v2.ocaml.org#1440]
@patricoferris 
The images can be set a better positioning to make the page look symmetric. If this is something that you'd like to fix, I can work on it!
![image](https://user-images.githubusercontent.com/34683520/113710242-18193a00-9701-11eb-97e7-030fc4ed9487.png)

**Comment by gs0510** [comment]
@Srinithyee this is a good catch, you can go ahead and work on this :)

**Comment by Srinithyee** [comment]
@gs0510 Okay then!

**Comment by Srinithyee** [comment]
@patricoferris @gs0510  I've made the changes locally and it works. I am not able to push the changes to my cloned repository. After running make, I have the html files created and I've made changes to it. How do I convert that back to .md files so that it can be pushed?

Here is the change:
![image](https://user-images.githubusercontent.com/34683520/113974774-19ab4500-985c-11eb-9382-767e36a19f56.png)
