### ISSUE TITLE
Realigning links in Contributors

### ISSUE THREAD

**Issue by Srinithyee** [ocaml/v2.ocaml.org#1441]
@patricoferris 
I'd like to realign the two links to make them in line. It looks quite odd now.
![image](https://user-images.githubusercontent.com/34683520/113711551-b4900c00-9702-11eb-8c55-e4e32892654f.png)

Do let me know if I can fix this!

**Comment by pitag-ha** [comment]
Good catch, you can work on this :)

**Comment by Srinithyee** [comment]
Thank you @pitag-ha! I'll work on this :)

**Comment by Srinithyee** [comment]
@patricoferris  @pitag-ha I've made the changes locally and it works. I am not able to push the changes to my cloned repository. After running make, I have the html files created and I've made changes to it. How do I convert that back to .md files so that it can be pushed?

Here is the change
![image](https://user-images.githubusercontent.com/34683520/113974616-da7cf400-985b-11eb-9dcf-3d0d621c4300.png)
