### ISSUE TITLE
Center Align Acknowledgements in Learn

### ISSUE THREAD

**Issue by Srinithyee** [ocaml/v2.ocaml.org#1443]
@patricoferris 

Acknowledgement in the Learn page seems a bit left out. It would look better if it was center aligned, more like a  footer to a web page.
![image](https://user-images.githubusercontent.com/34683520/113715862-98db3480-9707-11eb-869d-3bf5fb2e155b.png)

If approved, I'll fix this :)

**Comment by pitag-ha** [comment]
To me _Acknowledgements_ doesn't actually seem left out. How would it look like if it was center aligned?

**Comment by Jay-Fred31** [comment]
Hello @pitag-ha, I think "acknowledgement" here will look better at bottom of the page because it doesn't necessarily talk about where help is needed but it is showing the list of contributors and the Hosting site.

I would also like to make the change if the need for change sounds well.

**Comment by Jay-Fred31** [comment]
Also, I can arrange the contributor's list can be arranged side by side to reduce scroll time.

**Comment by gs0510** [comment]
I think this isn't needed at the moment, and the reasoning doesn't convince me that change will be better. We can close this issue. @Jay-Fred31 I think you're already working on an easy issue, so you can pick up a harder one once you're done with that. Thanks!
