### ISSUE TITLE
Modifying UI for home page 

### ISSUE THREAD

**Issue by shreyaswikriti** [ocaml/v2.ocaml.org#1447]
![image](https://user-images.githubusercontent.com/57635473/113724574-1c008880-9710-11eb-8b45-580a8a9965d8.png)
 I have made some changes in the UI of the home page ( see the left side of the image -->learn, package blocks ) and see the right side without changes(documentation and community block). With Card-UI interface blocks look more beautiful. what's your view??
@gs0510 @patricoferris

**Comment by patricoferris** [comment]
Hi @shreyaswikriti,

Thanks for the issue. As a general rule it is important to try and explain *objectively* why an issue exists and makes sense to fix.  I wrote some of this here https://github.com/ocaml/ocaml.org/issues/1245#issue-821019972. Right now from this issue, I personally prefer the old styling as I think it's *easier to read* and *more coherent with the rest of the site*. Happy to hear other thoughts on this and have my mind changed :))
