### ISSUE TITLE
Untranslated header and footer content for some languages

### ISSUE THREAD

**Issue by TildaDares** [ocaml/v2.ocaml.org#1448]
Some pages like https://ocaml.org/learn/tutorials/index.de.html with translations apart from English and French do not have the footer and header content in that language.

<img width="1266" alt="Screenshot 2021-04-06 at 15 41 33" src="https://user-images.githubusercontent.com/63427719/113729071-93252500-96ee-11eb-836d-ce30aac697d0.png">

I'd like to fix this by translating the header and footer content.

**Comment by pitag-ha** [comment]
Do you know how to translate the content to all those languages?

**Comment by TildaDares** [comment]
Since the the header and footer content is mostly one or two words per link I think it'll be easy to use Google translate to translate them.

**Comment by pitag-ha** [comment]
To be honest, I think using Google translate might lead to wrong translations. I think it's better to leave it in English than running the risk of translating of wrongly. I think so for two reasons:

- if people don't speak English fluently, but the headers are in English, they can still guess what might be meant. If it's in wrong French, they will simply missunderstand
- having wrong translations on a site tends to make a bad impression.

Pleas, let me know if you don't agree and if so, why :)

**Comment by TildaDares** [comment]
Yeah, you're right.
