### ISSUE TITLE
Change all occurences of real-world-ocaml.jpg to real-world-ocaml.jpeg

### ISSUE THREAD

**Issue by TildaDares** [ocaml/v2.ocaml.org#1450]
Since I replaced real-world-ocaml.jpg with real-world-ocaml.jpeg in issue #1344, the real-world-ocaml image like the one in https://ocaml.org/learn/ is not being displayed.

<img width="461" alt="Screenshot 2021-04-06 at 16 03 32" src="https://user-images.githubusercontent.com/63427719/113732647-a84f8300-96f1-11eb-935b-f2bf1e98f769.png">

I'd like to change all img tags that are still referencing the old image to the new one.

**Comment by pitag-ha** [comment]
Good catch, go ahead :)
