### ISSUE TITLE
Mistake in positions of div in Documentation page in french language 

### ISSUE THREAD

**Issue by shreyaswikriti** [ocaml/v2.ocaml.org#1453]
![image](https://user-images.githubusercontent.com/57635473/113737875-0abd7900-971c-11eb-852f-5d53dc8041f3.png)

**Comment by shreyaswikriti** [comment]
below is English  version documentation page

![Uploading image.png…]()

**Comment by pitag-ha** [comment]
This is a duplicate of #1409 . Don't worry about that: it's hard for all of us to keep track at the moment with so many simple issues!

**Comment by patricoferris** [comment]
Thanks @shreyaswikriti! And thanks @pitag-ha for spotting the duplication, closing this issue now because of that.
