### ISSUE TITLE
'Content side menu ' is missing in learn/success stories in french page 

### ISSUE THREAD

**Issue by shreyaswikriti** [ocaml/v2.ocaml.org#1454]
french page 
![image](https://user-images.githubusercontent.com/57635473/113739705-aac7d200-971d-11eb-8650-ffea3247c9d3.png)

english page 
![image](https://user-images.githubusercontent.com/57635473/113739767-bc10de80-971d-11eb-82b7-3643ce3bbee4.png)
@gs0510

**Comment by pitag-ha** [comment]
This seems like a good issue. You can go ahead and work on it :) I'm not sure how easy/hard it will be.

**Comment by shreyaswikriti** [comment]
Thank you @pitag-ha. I'm working on it.

**Comment by shreyaswikriti** [comment]
@pitag-ha, kindly review the PR attached.
