### ISSUE TITLE
Error! Book not displaying on 'learn' page

### ISSUE THREAD

**Issue by dinakajoy** [ocaml/v2.ocaml.org#1457]
![error](https://user-images.githubusercontent.com/39722740/113753411-f8d0db80-9705-11eb-9c42-d1af737148db.PNG)
I think someone already made a contribution on this.
If the contributor cannot fix this, please let me know so that I can check it out.

**Comment by patricoferris** [comment]
Thanks @dinakajoy -- this should be fixed by https://github.com/ocaml/ocaml.org/pull/1456

**Comment by dinakajoy** [comment]
Okay, thanks. I will close it right away
