### ISSUE TITLE
Yet another solution to problem #23

### ISSUE THREAD

**Issue by jianingy** [ocaml/v2.ocaml.org#146]
This one is shorter, though it might take more time.

```
(* Extract a given number of randomly selected elements from a list.

   The selected items shall be returned in a list. We use the Random
   module but do not initialize it with Random.self_init for
   reproducibility.
*)

let rand_select list n =
  if List.length list < n then failwith "don't be greedy"
  else let rec aux acc rst seq =
     if List.length acc = n then acc
     else match seq with
       | [] -> aux acc [] rst
       | h :: t ->
         if Random.bool () then aux (h :: acc) rst t
         else aux acc (h :: rst) t in
       aux [] [] list ;;

rand_select [`a;`b;`c;`d;`e;`f;`g;`h] 3;;
                  val rand_select : 'a list -> int -> 'a list = <fun>
#   - : [> `a | `b | `c | `d | `e | `f | `g | `h ] list = [`f; `e; `c]
```

**Comment by nrlucaroni** [comment]
This will not create a uniformly distributed result. The answer should be reservoir sampling or randomly selecting indices of the list. Here is a version w/ reservoir sampling

```
let rand_select n list =
  let rec take i acc = function
    | lst when i = 0 -> rand_select (n+1) (Array.of_list acc) lst
    | []    -> acc
    | x::xs -> take (i-1) (x::acc) xs
  and rand_select i acc = function
    | []     -> Array.to_list acc
    | hd::tl ->
      let j = Random.int i in
      if j < n then acc.(j) <- hd;
      rand_select (i+1) acc tl
  in
  take n [] list
```

**Comment by agarwal** [comment]
Although the problem doesn't explicitly say it, I think the requirement of a uniformly distributed result can be assumed. That's usually what _random_ means. @nrlucaroni Are you claiming your solution is better than the one posted? Or do you agree with @jianingy closing this issue, implying we should leave it as-is.

**Comment by nrlucaroni** [comment]
I was just posting an alternative approach from drawing random indexes. I do think it's better. This solution passes over the list only once and does not try to randomly access elements of the list --which we all try to avoid in lists--, but I also understand in the context of the tutorial I don't see an issue keeping the current implementation. Yes, this can be closed.
