### ISSUE TITLE
increase the spacing of logos in footer in the packages section

### ISSUE THREAD

**Issue by yashi-hub** [ocaml/v2.ocaml.org#1476]
I personally feel that in the packages site (https://opam.ocaml.org/) , the footer logos are quite close to each other which makes it a bit clumsy between the three 
enclosing a screenshot here-
![image](https://user-images.githubusercontent.com/69522036/113934045-ea241a80-9812-11eb-8a99-a92921920ecb.png)

I feel only some extra padding around the logos is required (correct me if I'm wrong) and if approved it can be considered as a new good-first-issue.

considering the fact that I have already submitted a PR for one good-first-issue, I would like someone else (who hasn't already done a good-first-issue) to take this up :))

**Comment by gs0510** [comment]
Hi @yashi-hub, the opam.ocaml.org website is out of scope for now, so we can leave this issue for now.
