### ISSUE TITLE
CSS Overflow on opam.ocaml.org/doc/Install.html page

### ISSUE THREAD

**Issue by lindaokorie27** [ocaml/v2.ocaml.org#1478]
## Context

On the install.html page, there is a line of text that doesn't realign and wrap itself on mobile and tablet screens causing an overflow

## Process

To recreate the issue, visit the https://opam.ocaml.org/doc/Install.html on a mobile or tablet or visit the [url](https://opam.ocaml.org/doc/Install.html) on a larger screen and emulate a mobile or tablet view.

## Current result

![current result](https://user-images.githubusercontent.com/38317939/113946031-70cefc80-97ff-11eb-9780-e096142c69a4.JPG)

## Expected result

![Expected](https://user-images.githubusercontent.com/38317939/113945912-3a917d00-97ff-11eb-8ce3-dbd3c11984bc.JPG)

**Comment by ozmos** [comment]
Hi, I'd like to be assigned this issue please.

**Comment by gs0510** [comment]
Hi @LindieK, thanks for opening this ! The code for opam.ocaml.org resides in another repository and turns out is out of scope for now. You can leave this issue for now.
