### ISSUE TITLE
Improve Learn page various section alignment

### ISSUE THREAD

**Issue by dldisha** [ocaml/v2.ocaml.org#1487]
The 3 column layout design on the learn page can be improved. Currently, it's not properly aligned and consistent.

Before:
![Screenshot from 2021-04-09 05-07-39](https://user-images.githubusercontent.com/26017359/114111445-abb45b80-98f7-11eb-9c5a-bfb4fb6637da.png)

After:
![Screenshot from 2021-04-09 05-49-05](https://user-images.githubusercontent.com/26017359/114111488-c1c21c00-98f7-11eb-92ef-edb0a836a219.png)

Also, we can have a card design for them i.e background-color and border-radius for each part if suggested. :)
If it's a good issue, then I would love to work on it.

**Comment by gs0510** [comment]
@dldisha I think since you've already worked on a couple of `good-first-issue`s you can pick up a harder one. There's already been issues to fix the Industrial Users and making the size of the videos equal, and I think they address most of this issue :)

**Comment by dldisha** [comment]
Okay @gs0510, I'll look for some harder ones. Could you assign me any?

**Comment by patricoferris** [comment]
I think this issue is also just about which text justification somebody prefers. I'm quite happy with the current design so I'll close this for now. If anyone has a compelling reason to add it, happy to have my mind changed.
