### ISSUE TITLE
post News in reverse chronological order

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#150]
Should _New from the community_ on the frontpage be listed in reverse chronological order? I think that might make more sense.

**Comment by Chris00** [comment]
They used to be well sorted.  This is a consequence of https://github.com/zoggy/ocamlrss/commit/aa866a3b8ce9dc9ff780cadcea80428dc4e3fab8

**Comment by agarwal** [comment]
This behavior has reverted. Odd, since the fix 283e228f01f4aa233353c28780286921e44eda76 is in place still.

**Comment by Chris00** [comment]
Fixed by f88bddc.  Version 2.2.1 of the RSS module changed the order _again_.
