### ISSUE TITLE
disable github pages URL

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#151]
Although we are using a custom domain, github is still publishing our site at http://ocaml.github.io/ocaml.org/ (and also http://ocaml.github.com/ocaml.org/ redirects to this).

I think this is quite wrong. A website should not be published at 2 URLs. I contacted github support and they said the only way around this is to create an [organization page](https://help.github.com/articles/user-organization-and-project-pages), which could then [redirect](https://help.github.com/articles/setting-up-a-custom-domain-with-pages#automatic-redirects) to the desired http://ocaml.org.

**Comment by amirmc** [comment]
This means moving all the content to a new repo called `ocaml.github.io`.

We can do that without losing any history but would have to be careful with branches.  Github Pages uses the `gh-pages` branch of a project repo for making a website but for specific folders (i.e like those named above) I believe it will use the `master` branch.  I don't know if this is configurable though.  If not, whatever build scripts you have running would have to be tweaked.

**Comment by amirmc** [comment]
As an additional note, it would also mean that any `gh-pages` branch under another repo would be available under `http://ocaml.org/<name-of-repo>` You may not want this behaviour either.

**Comment by mk270** [comment]
This can be fixed by making the gh-pages branch serve up a single HTML file which does a client-side redirect to the desired URL.

This would have the additional benefit of getting rid of the daily commits to gh-pages, which are making it hard to track progress on the Github Network visualisation

**Comment by agarwal** [comment]
(After writing this, I realize you should read the last paragraph first.)

What I want is:
- ocaml.org - is the one true URL
- www.ocaml.org - redirects to ocaml.org
- www.ocaml.org/foo - redirects to ocaml.org/foo

All of the above are currently working. Now, in addition I want:
- all other URLs like http://ocaml.github.io, etc. to return 404 in the best case, or as a second option, redirect to ocaml.org

Moving the actual content to a new repo called `ocaml.github.io` won't accomplish this. I think http://ocaml.github.io will continue to serve the content, and there will be no way to specify that it should redirect instead.

What I meant was to create the repo `ocaml.github.io` with a single html file that specifies a redirect to ocaml.org, and to leave the current repo as-is. I think that will cause http://ocaml.github.io to serve this single page, doing what we want.

Now, an additional desire has also come up:
- stop polluting our commit logs with the pushes to gh-pages

I think we can possibly do this by creating yet another repo `ocaml.org-publish`, with only a gh-pages branch. That's where we publish, and we delete the gh-pages branch in the `ocaml.org` repo. Overall, 3 repos are needed!

The correct solution to all of this is to stop serving our website off GitHub. This was supposed to be temporary until OCaml Labs got a permanent server setup. Amir, any progress on that? We can avoid all this mess.

**Comment by mk270** [comment]
after writing what I wrote above, I realised I may have misunderstood you

**Comment by mk270** [comment]
The site is a bunch of static pages, therefore it's not very complex (but off github it will need to be able to receive Github's HTTP POST notification that there are new changes to pull).

I suggest decoupling the issue of moving off Github for HTTP hosting from the issue of getting a permanent server via OCaml Labs. The gh-pages service is a temporary arrangement; you can replace it with another temporary arrangement (e.g., Amazon S3), as the switching costs are very low for such a simple site.

The commit log pollution really is a problem for me, as I use the Network visn to navigate.

**Comment by avsm** [comment]
I can provision a server for this on Rackspace Cloud now, but I agree with @mk270 that it would be better to move to a ocaml.org-publish repo first, and then switch over to the cloud server.  I'll need to run a few load tests to see how much capacity we need on there too.  Do you have a preference for OS (Ubuntu?) Ashish?

**Comment by agarwal** [comment]
No preference on the OS. Whatever OCaml Labs prefers is fine.

I don't understand the benefit of separating the concerns. If you create
this VM and we start hosting there, we're all set. What's the benefit of
working through GitHub's convoluted hosting system?

**Comment by mk270** [comment]
@avsm, I think you're misconstruing me (and we've all been talking at cross-purposes a little).

Please just set up the VM, and that will unblock us.

**Comment by avsm** [comment]
Oh, I see now -- I thought there was more to it in terms of decoupling the scripts.  I'll set up a server shortly (I'm travelling at the moment, so it'll be best if I do this switch next week when I'm back in the UK and can keep an eye out for problems with the move).  In the meanwhile, Ashish, could you please send me a public SSH key so I can give you admin access to the VM?

-anil

**Comment by mk270** [comment]
how are we getting on with this?

**Comment by agarwal** [comment]
I've sent my public key to Anil, as he requested. We can proceed once the
new server is setup.

**Comment by avsm** [comment]
I'm flying back to Cambridge today, so I'll be back in the office on Thursday to finish all this setup.

-anil

**Comment by mk270** [comment]
Ah grand

**Comment by avsm** [comment]
Investigating further, it turns out that Rackspace Cloud Files will let us host it as a CDN.  I'm putting up an experimental version of this (it requires using `duplicity` to rsync the files to them).  If this works, it's my preferred option as it doesn't require a VM and the associated maintenance burden.

**Comment by agarwal** [comment]
Any progress on this? I've resigned my position at NYU, so may not have access to their servers much longer. I can find a workaround, but let's use this as an opportunity to implement the permanent solution.

**Comment by avsm** [comment]
I've just deployed a VM for opam.ocaml.org now, which should also be suitable for running the main ocaml.org website.  I've also got an SSL certificate for *.ocaml.org purchased, so we can run the website over HTTPS too.  Ipv6 connectivity is also available.

We're going to shake out issues with opam.ocaml.org first, and then we can swap ocaml.org over.

-anil

**Comment by agarwal** [comment]
Thanks. Let's chat more at CUFP.

**Comment by agarwal** [comment]
We've now deployed the site on VM hosted by OCaml Labs. This issue is thus moot. Closing.
