### ISSUE TITLE
add Whitington's new book

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#152]
It should at least be in books.html. Also would be nice to publicize on front page, but our design still doesn't support slow-aging news items.

**Comment by Chris00** [comment]
On Mon, 10 Jun 2013 06:57:34 -0700, Ashish Agarwal wrote:

> It should at least be in books.html. Also would be nice to publicize
> on front page, but our design still doesn't support slow-aging news
> items.

This is something not too difficult to do — say we put files into a
directory and they say when they expire (or how long they should be
displayed, knowing it may be longer if no new items are ready to
replace them).

I am reluctant to develop further the scripts however as long as no
clear road has been laid down.

**Comment by agarwal** [comment]
I was just thinking about where the news items should go. Already we have 2
news items in the right, and they mess up the look because too much
whitespace gets inserted in most of the page. Adding a 3rd news item there
would make the page look quite bad.

I'm not too concerned about automating the deletion of the news items. We
can do that manually for now.

**Comment by johnwhitington** [comment]
![cover](https://f.cloud.github.com/assets/1702581/716102/8295b986-df2f-11e2-9135-c14f05824085.png)

Thanks for opening this issue.

If someone wants a PDF of the book so they can take a look at it before adding it, I can provide one - just drop me an email...

I've attached a cover image to this issue. The List price is $39.99, Kindle $29.99, E-book $14.99.

The URL is ocaml-book.com

Here's the description from the website, but I assume you won't want to include it verbatim!

In "OCaml from the Very Beginning" John Whitington takes a no-prerequisites approach to teaching a modern general-purpose programming language. Each small, self-contained chapter introduces a new topic, building until the reader can write quite substantial programs. There are plenty of questions and, crucially, worked answers and hints.

"OCaml from the Very Beginning" will appeal both to new programmers, and experienced programmers eager to explore functional languages such as OCaml. It is suitable both for formal use within an undergraduate or graduate curriculum, and for the interested amateur.

**Comment by Chris00** [comment]
Fixed by 1c4a188.  I have added the description verbatim however — I thus leave this issue open until somebody changes it or decide it is good as is.

**Comment by agarwal** [comment]
I think the description is fine as-is. We still need to get news like this on the front page, but let's leave that to the more general issue of redesigning the front page.
