### ISSUE TITLE
the new package release announcement looks quite uneven.

### ISSUE THREAD

**Issue by yashi-hub** [ocaml/v2.ocaml.org#1526]
in the site https://opam.ocaml.org/blog/opam-2-1-0-beta4/
everytime a new package is released , the decleration and the link to that package says different things.
![opam packages](https://user-images.githubusercontent.com/69522036/114835200-f3068480-9dee-11eb-928e-b0805e00e4e8.png)

the initial excitement for a package release is much understood, but as time passes and new packages are released, the declaration looks uneven and odd to me.

instead, we can just name the package 
for eg: 
![opam packages final](https://user-images.githubusercontent.com/69522036/114837312-3104a800-9df1-11eb-9c94-67ca7549c20b.png)
 
or every package name can be followed by - released!

In my opinion, this will make the site look more symmetric and professional ( let me know if I understood it wrong :))

thanks :)

**Comment by gs0510** [comment]
The opam.ocaml.org code is out of scope for now, so we can't do much about it at the moment.  You can close this issue for now.

**Comment by yashi-hub** [comment]
okay @gs0510, I was unaware of it. 
sorry for opening this.

**Comment by gs0510** [comment]
@yashi-hub  No worries! Not your fault at all! :)
