### ISSUE TITLE
fixed left div of the Mailing Lists and Forums page

### ISSUE THREAD

**Issue by yashi-hub** [ocaml/v2.ocaml.org#1535]
according to me the left div of the page should be fixed  - https://ocaml.org/community/mailing_lists.html
![error 1](https://user-images.githubusercontent.com/69522036/114925768-24ae3880-9e4d-11eb-90a5-8b5e608307cc.png)
the main purpose of the left div is to help users to scroll directly down to the content they are interested in (correct me if I understood it wrong) but if the div itself scrolls down, then at the bottom the purpose of it is not achieved.

for example :
if a user is at the bottom of the page and wants to go to IRC channel-English , they have to scroll upwards and then find it. 

**solution:**
keep the left div fixed as in 
![image](https://user-images.githubusercontent.com/69522036/114926773-5f64a080-9e4e-11eb-9e0b-c9d3fec80f3e.png)

let me know if I understood the problem correctly.
thankyou :))

**Comment by Lontchi12** [comment]
Hello @yashi-hub  is this a medium issue?? i would like to work on this if it is one Thank You

**Comment by yashi-hub** [comment]
Hey @Lontchi12 , thanks for showing your interest in this issue. 
But before working on this, let us wait for the mentors to approve this issue or get some suggestions about it.  
Thanks. :))

**Comment by gs0510** [comment]
@yashi-hub  Good catch, but it's been fixed by #1423  so it can be closed. Thanks!

**Comment by yashi-hub** [comment]
thank you @gs0510 . closing it now :)
