### ISSUE TITLE
repetition of words in the success stories page

### ISSUE THREAD

**Issue by oma16** [ocaml/v2.ocaml.org#1540]
![of](https://user-images.githubusercontent.com/48384861/115145644-7c65c300-a04a-11eb-8553-b55199f43c18.png)

![on](https://user-images.githubusercontent.com/48384861/115145656-8daecf80-a04a-11eb-8410-58e45b39cb52.png)

One of the words has to be removed

**Comment by patricoferris** [comment]
Sure, thanks for catching this 👍
