### ISSUE TITLE
OCaml Tutorial Basic page not displaying

### ISSUE THREAD

**Issue by dinakajoy** [ocaml/v2.ocaml.org#1541]
I just noticed that this link https://ocaml.org/learn/tutorials/basics.html is displaying 'Not Found' but it is available on my local build. Also the link contains // - https://ocaml.org/learn//tutorials/basics.html when clicked from the google link (see image).

![Capture](https://user-images.githubusercontent.com/39722740/115255123-de472b00-a125-11eb-9ffb-9ce1935bdc52.PNG)

I just wanted to raise awareness to confirm if the page was removed intentionally and not an error.

**Comment by CQW-Code** [comment]
I just tried this on my local build after doing a pull to update my local repo and after entering the url above I got a Not Found page.  I couldn't see where the "Basics" link would be on the tutorials page though so directly entered it.

**Comment by dinakajoy** [comment]
> I just tried this on my local build after doing a pull to update my local repo and after entering the url above I got a Not Found page. I couldn't see where the "Basics" link would be on the tutorials page though so directly entered it.

Yea, that's my point. This page was supposed to be the first link before `Up and Running`  on learn page. That was why I asked to know if it was intentionally removed. Also, some other tutorial pages made reference to it. I will post a screenshot if I come across another of such again

**Comment by gs0510** [comment]
[This](https://github.com/ocaml/ocaml.org/pull/1303/files) PR got rid of `basics.md` from `index.md` and it got replaced with `A first hour for OCaml`. @dinakajoy Do you want to investigate more and see if there are other pages that reference this tutorial and fix them if they do? You can also investigate why the link shows up as `https://ocaml.org/learn//tutorials/basics.html`.

**Comment by dinakajoy** [comment]
> @dinakajoy Do you want to investigate more and see if there are other pages that reference this tutorial and fix them if they do? You can also investigate why the link shows up as `https://ocaml.org/learn//tutorials/basics.html`.

I am working on #1483 currently. If no other person indicates interest, I will check it once I am done.

**Comment by gs0510** [comment]
@jyotibalodhi Do you want to take a look at this? Thanks!

**Comment by oma16** [comment]
Hi @gs0510, I would like to take a look

**Comment by jyotibalodhi** [comment]
> @jyotibalodhi Do you want to take a look at this? Thanks!

Hi @gs0510 yes I would like to look into the issue! 
Thanks for mentioning.. :)

**Comment by johnwhitington** [comment]
A few days ago I submitted https://github.com/ocaml/ocaml.org/pull/1497 which removes any internal references to tutorials which have been deleted, including the translations.

So this should be sorted soon, I think.

**Comment by gs0510** [comment]
Ah cool, thanks @johnwhitington ! 

@dinakajoy This issue will be fixed by #1497, you can close it :)

**Comment by jyotibalodhi** [comment]
@gs0510  Yesterday, I made the request here - https://search.google.com/search-console/remove-outdated-content, to remove it from the Google's cache. It looks issue is solved now. Also, I checked all other URLs of https://ocaml.org/learn/tutorials/. They are looking good :)

<img width="980" alt="Screenshot 2021-04-21 at 7 26 08 PM" src="https://user-images.githubusercontent.com/63946672/115566052-8d773400-a2d7-11eb-8315-b76ed461680c.png">

**Comment by gs0510** [comment]
Perfect, thanks @jyotibalodhi!
