### ISSUE TITLE
Cheatsheet link is broken

### ISSUE THREAD

**Issue by roddyyaga** [ocaml/v2.ocaml.org#1561]
The standard tools and emacs shortcuts cheatsheet links at https://ocaml.org/docs/cheat_sheets.html are broken.

I think the correct links can be found here https://github.com/OCamlPro/ocaml-cheat-sheets

There is also an opam cheatsheet that might be nice to add

**Comment by yashi-hub** [comment]
I would like to work on this issue :)) 
Thank you

**Comment by teodorlu** [comment]
Can confirm that neither of the cheat sheet links are working on ocaml.org/docs/cheat_sheets.html.

Thanks for the alternative links, @yashi-hub!

**Comment by teodorlu** [comment]
@yashi-hub - if you want to fix this, https://github.com/ocaml/ocaml.org/blob/master/site/docs/cheat_sheets.md seems to be the relevant file. I would expect the maintainers to be interested in a PR!

**Comment by teodorlu** [comment]
@yashi-hub I just made a PR: https://github.com/ocaml/ocaml.org/pull/1621

I would have added you as reviewer - but I don't seem to have the permission to do that :)
