### ISSUE TITLE
Refrain from using lowercase polymorphic variants

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/v2.ocaml.org#159]
I think [this page](http://ocaml.org/tutorials/99problems.html) should refrain from using lowercase polymorphic variants. Lowercase polymorphic variants make it less easy to distinguish data constructors from identifiers and on that page they are easily confused with character constants. Besides lowercase polymorphic variants are discouraged by the OCaml manual.

**Comment by Chris00** [comment]
It comes from the original solutions by [Victor Nicollet](https://github.com/VictorNicollet/99-Problems-OCaml).  I think it would be better to use another type such as chars (polymorphic variants are an advanced topic that not everybody coming to this page will understand).

**Comment by Chris00** [comment]
Fixed by dc8cd5d6ec971a35a41e659043dca2d9eccc900b
