### ISSUE TITLE
Programming guidelines page is barely readable

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/v2.ocaml.org#160]
The formatting of the programming guidelines [page](http://ocaml.org/tutorials/guidelines.html) is barely readable compared to the [original](http://caml.inria.fr/resources/doc/guides/guidelines.en.html) (not that it's excellent but still better).

**Comment by dbuenzli** [comment]
To be more specific, lack of vertical rhythm, unclear sectioning, too much identation (e.g. the justification boxes).

Also I'd remove these yellow boxes, they put emphasis on the _justifications_ while emphasis on this page should be on the _rules_.

**Comment by Chris00** [comment]
A pull request is welcome! ;-)

**Comment by dbuenzli** [comment]
On preview.ocaml.org the page is broken. Besides I think it would be nice to give the programming guidlines a little bit more visibility on the site. I see too much OCaml code floating on the internet that hurt my eyes.

**Comment by amirmc** [comment]
In the markdown for that page I think that ````tryocaml` should be ````ocaml` (or even ````text`).  I'll try it locally and push if it fixes it.

**Comment by Chris00** [comment]
I close it as it refers to the old site.  Comment on https://github.com/ocaml/ocaml.org/issues/299 for the new one.
