### ISSUE TITLE
All OCaml code evaluated in a single session

### ISSUE THREAD

**Issue by mauny** [ocaml/v2.ocaml.org#162]
There is a problem with all OCaml code evaluated in a single top-level; session, as it is currently done: if you modify the syntax (with camlp4) in one file, you may then get syntax errors in a subsequent file.

I had the problem with tutorials/camlp4_3.10/foreach_tutorial.html being processed before tutorials/if_statements_loops_and_recursion.html. The former experiments a syntax extensions of for loops, that makes 'for i = 0 to 10' fail with

  Parse error: [ipatt] or "in" expected (in [expr])

at the first occurrence of i.

Fortunately (or not), the problem disappeared after re-initializing my .opam directory: now processing of foreach_tutorial.html fails because camlp4o.cma needs dynlink.cma to be loaded (and it is not).

Processing files separately would help in preventing interferences.
- Michel

**Comment by Chris00** [comment]
Fixed in 5606c2197bda19b967ec89c06f399e55091cf28b

@mauny dynlink.cma exists on your system right?  Dynlink is required to compile the builder, so I am surprised that the processing is taking place.
