### ISSUE TITLE
OCaml meetings started in 2008

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#172]
[This page](http://ocaml.org/meetings/ocaml/2013/) says the OCaml Meetings started in 2010. Searching the mailing list, I find the first one was in 2008 in Paris. There also appears to have been one in 2009 in Grenoble, though I can't find a page for it. Then 2010 and 2011 were again in Paris.

Can anyone confirm this? @gildor478?

**Comment by dbuenzli** [comment]
Well this [page](http://ocaml.org/meetings/) confirms what you say.
