### ISSUE TITLE
Error in community news box 

### ISSUE THREAD

**Issue by heidihoward** [ocaml/v2.ocaml.org#174]
I've noticed an error message in the community news box on the current
ocaml.org site
" The function associated to $(news http://planet.ocaml.org/rss20.xml)
raised the exception
"Http_client.Http_protocol(Http_client.Timeout(\"direct connection to
planet.ocaml.org:80\"))" 

![ocamlorg](https://f.cloud.github.com/assets/1835251/916114/dd06e026-fe82-11e2-91cb-9be2114a3cd0.png)

**Comment by amirmc** [comment]
Thanks for catching this!  I've emailed the [infrastructure list](http://lists.ocaml.org/listinfo/infrastructure) to make sure this gets more attention.

I'm wondering if it's related to https://github.com/ocaml/ocaml.org/commit/ae65980dd4b61372021185d9d80c05da8d4abbfc but I can't be sure.

**Comment by amirmc** [comment]
now fixed. See thread at http://lists.ocaml.org/pipermail/infrastructure/2013-August/000243.html

(was a transient upstream issue)

**Comment by Chris00** [comment]
One may wonder whether the build should fail in such cases.  It was decided that it should go as far as possible in order to catch many mistakes at once.  But maybe this should be changed for the automatic publishing script?

**Comment by amirmc** [comment]
I guess in a case like this (where it's trying to draw something in from upstream), having the build abort would appear to be sensible.  It would avoid an issue like this.  However, having it fail when I'm trying to build locally, could become be a little tiresome (I'd personally want it to go as far as it can).

I'm not familiar with the auto-publish scripts but if they separate and could catch errors like this, then adapting them seems like a good idea.

**Comment by Chris00** [comment]
The commit 6df512ada2fb59970786cb2370683308a6e2ff10 implements that (the make target is `web-stop-on-error` and is used by default for `publish` but not for the simple `make`).
