### ISSUE TITLE
typo: news box renders "05 AUg 2013"

### ISSUE THREAD

**Issue by avsm** [ocaml/v2.ocaml.org#175]
AUg -> Aug

**Comment by Chris00** [comment]
Actualy the typo is in [Netdate](https://godirepo.camlcity.org/wwwsvn/trunk/code/src/netstring/netdate.mlp?rev=1835&root=lib-ocamlnet2&view=auto).  I sent an email to Gerd.

**Comment by Chris00** [comment]
I have released a temporary fix 18acc3b74f73ca7974ea0714c0bd2ac6f59bcf85 and published it.  Please let me know when a new version of OCamlnet lands in opam so I can revert that commit.

**Comment by Chris00** [comment]
Fixed in the latest ocamlnet 4caa0a98bd23d384788471b8bac54294747101e2
Reverted the fix b3f3c3a440063b35faa1606657562693645a2f9e
