### ISSUE TITLE
missing LICENSE or COPYING file?

### ISSUE THREAD

**Issue by dch** [ocaml/v2.ocaml.org#177]
Hi,

I'd love to re-use some of this site while I learn ocaml; what license is this published under?

**Comment by agarwal** [comment]
@dch Sorry we don't have an immediate answer for this. It requires some discussion with the various stakeholders. We'll make it a priority.

**Comment by OrelSokolov** [comment]
@agarwal, can I publish translated (into Russian) tutorials on ru.wikibooks.org?

**Comment by agarwal** [comment]
@OrelSokolov I would like the answer to be yes, but we haven't officially attached a license yet, and I cannot make a legal judgement on this.

Also, perhaps you'd like to incorporate this directly into the ocaml.org site, which is meant to be multi-lingual. However, the site is currently undergoing a [complete revision](http://lists.ocaml.org/pipermail/infrastructure/2013-October/000312.html), so you would need to hold off on this till we make the transition.

**Comment by amirmc** [comment]
Hi Folks, I think we might need to do something similar to the opam-repository (https://github.com/ocaml/opam-repository/issues/955). We'd essentially have to choose a license and then check that all contributors are ok with it. 

I'll kick off a discussion thread on the infrastructure list sometime after we've merged the new site design.

**Comment by agarwal** [comment]
@OrelSokolov The new site is up and it is now possible to submit pull-requests for translated pages. We would prefer that translations are kept within this repo. It will be much easier to make sure content remains in sync with the primary English pages. Does that sound okay for you? If yes, note the naming scheme for non-English files is foo.XX.md, where XX is the two-letter language code. For example, in site/learn/tutorials, you'll find basics.fr.md, which is the French version of the Basics tutorial. You could provide the Russian translation in basics.ru.md.

Unfortunately, we still haven't settled on a license. We'll try to make a decision soon. See also #375.

**Comment by Chris00** [comment]
@OrelSokolov I see that the translation on http://ru.wikibooks.org/wiki/OCaml is ~~scheduled~~ proposed to be removed.  Please submit pull requests to add your translations to this site.  The license is **CC BY-SA 4.0** for the content and for **UNLICENSE** the code examples.

**Comment by amirmc** [comment]
The repo now has a LICENSE file so I propose to close this issue.  Any objections?
https://github.com/ocaml/ocaml.org/blob/master/LICENSE.md

**Comment by Chris00** [comment]
Go ahead.
