### ISSUE TITLE
import download page for OCaml release 4.01.0

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#179]
Unfortunately, updates are still being made to a supposedly deprecated website. We need to import the new [4.01.0 release](http://caml.inria.fr/download.en.html) page, and work on #115.

**Comment by Chris00** [comment]
Moreover, the link `OCaml 4.00.1` on http://preview.ocaml.org/docs/install.html leads to a 404 error.  IMO, the install page should be improved before the site goes online...

**Comment by amirmc** [comment]
The 404 is because it links to a (non-existent) releases page (see #270).  I was planning to put a simple list of releases there for the time-being.

**Comment by pw374** [comment]
It leads to 404 because it's /releases and not /doc/releases 
Let's just fix that 404 in https://github.com/ocaml/ocaml.org/blob/redesign/site/docs/install.md for now (I'll do it now)

edit: done in f3a68b06e6e370c8e594e44de0c6d0d113cbcf24

**Comment by amirmc** [comment]
I'll import this page before I get back to the 99problems one.

**Comment by amirmc** [comment]
Done.  I made a couple of updates to the release too (i.e link to ocaml-java and also removed mention of GODI as it doesn't support 4.01.0).  I'd be grateful if someone else can update the symlink `releases/index.md` to point at this page.

Closing this now.
