### ISSUE TITLE
OCaml API search: implement as service on server

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#18]
The Use > OCaml API search menu item currently points to an external server. Would perhaps be better to run this server directly on the ocamlweb server if the tool is stable. Could then make sure it is configured to search over a large set of libraries.

**Comment by amirmc** [comment]
This might be useful as part of the Opamalot work for the OCaml Platform (and would be sensible to keep with the package stuff) .  ccing @avsm and @samoht so they're aware of this thread.

**Comment by agarwal** [comment]
There is also now [OCaml◎Scope](http://ocamloscope.herokuapp.com).

**Comment by agarwal** [comment]
This is an entire project and beyond the scope of the ocaml.org project. Thus, closing this issue.
