### ISSUE TITLE
Broken links in News feed. Use `<link>` instead of `<id>`

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#181]
There are broken links in the news feed. This seems to be because the feed uses the `<id>` field instead of the `<link>` field to link back to the original post.

For example you can see on http://ocaml.org/planet/
1. @avsm's recent camlpdf post links to `http://anil.recoil.org/2013/09/16/camlpdf-the-end-of-sucky-pdf-tools` which is from the the `<id>` field of the feed and returns a 404.  The `<link>` field has the correct url (with `.html` appended - @avsm, maybe you want to change the `id` to be the correct url?)
2. Richard Jones' OCaml 4.01.0 Rawhide post links to `http://rwmj.wordpress.com/?p=4580`, which is from the `<guid>` field, which I also notice says `isPermaLink="false"`.  The `<link>` field in the feed has the url `http://rwmj.wordpress.com/2013/09/14/ocaml-4-01-0-entering-rawhide/` (though the `guid` does actually resolve to the right page)

I checked http://planet.ocamlcore.org and it seems to use the `<link>` field.

I've no idea what the correct convention is but we should avoid broken/fragile links.

**Comment by avsm** [comment]
It should not be using the <id> tag, which is just a UUID and not a link.

-anil

**Comment by Chris00** [comment]
Nomally the guid is only used if `isPermaLink="true"` or if no link is present and the GUID looks like an URL.  If everybody respected the standard, there would be no need for this crazy logic.

I will take a look.

**Comment by avsm** [comment]
Heh, the logical flow through Atom is indeed a bit crazy...

**Comment by Chris00** [comment]
The intent was the one above but the implementation did not respect it.  Fixed in 7ba052e
