### ISSUE TITLE
add blog for ocaml.org

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#185]
This is for consideration.

The site already has a Planet feed but a specific ocaml.org blog enables an additional route for notifications to go out.  It could also provide a place for those who'd like to write content but don't want to maintain their own blogs.

This should be revisited _after_ the site redesign work is largely complete.

**Comment by amirmc** [comment]
This is related to (basically the same as?) #233

**Comment by amirmc** [comment]
Since platform related posts are now going on opam.ocaml.org I don't see a need for a specific blog on OCaml.org

**Comment by Chris00** [comment]
OK, closing then.
