### ISSUE TITLE
Facebook is missing Hack

### ISSUE THREAD

**Issue by yminsky** [ocaml/v2.ocaml.org#192]
The Facebook entry discusses Pfff but not Hack.  A link to the CUFP talk about Hack would be a good addition, since it's a big success story for OCaml.

**Comment by Chris00** [comment]
I found a video at http://www.youtube.com/watch?v=gKWNjFagR9k but the quality is average — in particular one does not really see the slides — one has to open them separately — not the code demo.  I hope a better version of it will appear on http://cufp.org/videos

**Comment by Chris00** [comment]
I completed the "Learn" page 01b4bdf1f0b62d28fbcb52a9f8f020758e1d4da1  Hope you like it!

One could add an entry on the page _Success Stories_ once they release their code in the open.
