### ISSUE TITLE
planet.html styling is bad

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#195]
It is hard to tell where one post starts and the other starts. The Read More button is too large.

**Comment by amirmc** [comment]
Planet page now looks great :)

http://preview.ocaml.org/community/planet.html

**Comment by samoht** [comment]
indeed! Would be also nice to either redirect to the original blog when you click "Read More" or to add a button "Read on the blog" which redirects to the right place.

**Comment by amirmc** [comment]
Clicking on the article title takes you to the original site.  Perhaps we can make that more discoverable but this is the same behaviour as on the current ocaml.org site.

**Comment by Chris00** [comment]
That is why I added the icon ![rss](https://f.cloud.github.com/assets/1255665/1524221/145aa142-4bc3-11e3-8083-a4c4b1cf3441.png) but it does not seem to attract attention enough...

**Comment by avsm** [comment]
It's looking much better now!  The "read more" button is still a bit awkward and large.  Would simply bold text suffice there?

**Comment by agarwal** [comment]
The [image: rss]https://f.cloud.github.com/assets/1255665/1524221/145aa142-4bc3-11e3-8083-a4c4b1cf3441.png
icon
sometimes is above the title underline and sometimes below. It varies by
post and changes as you resize the window. Overall, it looks great!

**Comment by Chris00** [comment]
@agarwal Not sure exactly what to do (the image if floating right, feel free to play with the CSS).

**Comment by Chris00** [comment]
On Tue, 12 Nov 2013 11:29:24 -0800, Anil Madhavapeddy wrote:

> It's looking much better now! The "read more" button is still a bit awkward and large. Would simply bold text suffice there?

I made them lighter d4959531df30f7d77540f8aadd1675b8fe1fe259 As you suggest, one may also remove the button altogether (a button was used so it is clearly different from the post but that may not be necessary)

**Comment by Chris00** [comment]
On Tue, 12 Nov 2013 11:33:48 -0800, Ashish Agarwal wrote:

> The [image: rss]<https://f.cloud.github.com/assets/1255665/1524221/ 145aa142-4bc3-11e3-8083-a4c4b1cf3441.png> icon sometimes is above the title underline and sometimes below. It varies by post and changes as you resize the window. Overall, it looks great!

Fixed 8efe4a3a5b50a9f86dd0458b8face2b2de5bb15e
