### ISSUE TITLE
serif font not nice/appropriate for websites

### ISSUE THREAD

**Issue by zacchiro** [ocaml/v2.ocaml.org#199]
Whereas heading/titles on the new website use a sans-serif font, the actual textual paragraphs use a serif font. Aside from the aesthetic glitch due to that difference, sans-serif fonts are generally considered better for the web. I suggest dropping the serif font from textual paragraphs.

**Comment by Chris00** [comment]
Unless somebody submit a PR with a different set of fonts, I think we should close this.

**Comment by amirmc** [comment]
I concur.
