### ISSUE TITLE
description.html: content needs to be improved

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#2]

**Comment by agarwal** [comment]
Consider incorporating content from Inria site [here](http://caml.inria.fr/about/index.en.html).

**Comment by agarwal** [comment]
Also content [here](http://caml.inria.fr/about/overview.en.html).

**Comment by eelsther** [comment]
commit fc5d776 includes "About Caml" and "An overview of the Caml language  and tools" pages.

**Comment by Chris00** [comment]
The content of the two links has been incorporated.  Closing.
