### ISSUE TITLE
integrate OCaml Planet

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#20]
The Community > Blogs currently links to an external site. Would be better to serve on ocamlweb's server, and unify styling with ocamlweb.

**Comment by Chris00** [comment]
Talking with Sylvain, the simpler for now is to use the ocaml planet feed.  One could use OCamlRSS http://zoggy.github.com/ocamlrss/  but that adds one more dependency to the project and the feed will not be updated automatically.

Actually the page news.html renders the feed from OCaml Planet.  It is just not nice to read.  We have to generate that page (maybe with a cron job if we do not want to use/write javascript).

**Comment by agarwal** [comment]
How is ocaml_planet.html being generated from OCaml Planet? I guess right now you did it once by hand, but can the command be added into our build script?

**Comment by Chris00** [comment]
On Fri, 17 Aug 2012 16:35:03 -0700, Ashish Agarwal wrote:

> How is ocaml_planet.html being generated from OCaml Planet? I guess right now you did it once by hand, but can the command be added into our build script?

This is the goal.  I will use OCamlRSS for that and try to make a nice presentation...

**Comment by agarwal** [comment]
So the previous news.html, which has been renamed ocaml_planet.html, is to be generated directly from planet.ocamlcore. So in this case, isn't the ocaml_planet.html page redundant to planet.ocamlcore? Why not have the "More news -->" button link directly to planet.ocamlcore?

**Comment by Chris00** [comment]
On Sat, 18 Aug 2012 12:40:41 -0700, Ashish Agarwal wrote:

> So the previous news.html, which has been renamed ocaml_planet.html 
> , is to be generated directly from planet.ocamlcore. So in this cas 
> e, isn't the ocaml_planet.html page redundant to planet.ocamlcore?  
> Why not have the "More news -->" button link directly to planet.oca 
> mlcore?

Well, this issue is about to _integrate_ ocamlplanet to the site.  Th 
is is almost done http://ocamlweb.forge.ocamlcore.org/www/planet/ $B!=(B I 
 think it is even better than the current planet ;).  What I still ha 
ve to do is to add the list of contributors (another XML file to pars 
e) and to make another output for the "News" on the front page (ATM w 
e rely on an external site JS, I do not think this is nice).

**Comment by Chris00** [comment]
Front page news generated — http://ocamlweb.forge.ocamlcore.org/www/

(Sorry for the layout o the previous message, it seems github does not cope well with all kinds of emails...)

**Comment by Chris00** [comment]
Commit 7989a9be59ee5e57fa16e9519bd3757f247b76e2 adds the "Subscriptions" tab.  See http://ocamlweb.forge.ocamlcore.org/www/planet/   This closes the issue.
