### ISSUE TITLE
`Description` issues

### ISSUE THREAD

**Issue by Kakadu** [ocaml/v2.ocaml.org#200]
1) Link `Read more` on `http://preview.ocaml.org/learn/` is broken (no `.html` postfix)
2) About `http://preview.ocaml.org/learn/description.html` .When  I use links on the left I am moved to HTML anchor but this anchor is hiding itself below our menu. I need to scroll a little bit up to see chapter's  title.

**Comment by pw374** [comment]
Thanks!

**Comment by pw374** [comment]
About your sub-issue number 2: can you please give details on your web browser? (I use OSX 10.8.5 and Safari 6.0.5 and I don't have this issue.)

**Comment by agarwal** [comment]
Regarding sub-issue number 2, actually I've always had this problem even in the current site. I just checked and it happens in Safari, Chrome, and Firefox. I thought maybe it's a problem with Bootstrap, but I'm not sure.

**Comment by pw374** [comment]
In Safari (6.0.5 on OSX 10.8.5), I've just retested: it only happens when the page's width is more than 985px.
Oh! It's because of that banner on the top of the page! :-/

**Comment by Chris00** [comment]
Possible solutions http://stackoverflow.com/questions/9047703/fixed-position-navbar-obscures-anchors  Since the code is generated, it is easy to modify all anchors if necessary.

**Comment by Kakadu** [comment]
the same issue there:
http://preview.ocaml.org/learn/taste.html#Higherorderfunctions

**Comment by Chris00** [comment]
Fixed for anchors thanks to c7cc491749138c1ab34e672f774fdfc4847aabbc
When table of contents use anchors instead of `id`, that will work for them as well.
