### ISSUE TITLE
Platform doesn't exist yet, so how to handle the Platform page

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#203]
The [Platform landing page](http://preview.ocaml.org/platform/) has lots of dummy text, by necessity since the Platform isn't actually released yet. How should we handle this page in the mean time? Perhaps add "Coming Soon" banner at the top, and direct people to go to "Install" for now.

**Comment by amirmc** [comment]
We shouldn't link to this page from the front page or navigation yet. We should keep it but link to it from elsewhere. 
That makes it less prominent but we can still send people to it. I'll submit a PR for consideration tonight.
