### ISSUE TITLE
learn/tutorials/index.html: link to Florent Monnier OCaml <-> C tutorial appears twice, with different description

### ISSUE THREAD

**Issue by zhenya1007** [ocaml/v2.ocaml.org#206]
To repro:

Search the text  of 

http://preview.ocaml.org/learn/tutorials/index.html

for the string

http://www.linux-nantes.org/~fmonnier/OCaml/ocaml-wrapping-c.html

Observe that the string appears twice with different descriptions

Expected:
For the tutorial to be linked to only once (I don't have a strong opinion on which of the two description is "better").

**Comment by Chris00** [comment]
Fixed in 2cd2842defee4cb0196ccb105e1cf6ebbefe5f65
