### ISSUE TITLE
meetings.html: add more content

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#21]
This page is quite sparse. List more meetings and regional groups (e.g. NYC OCaml Meetup). Consider listing ICFP and CUFP.

**Comment by eelsther** [comment]
Commit f6b67df

**Comment by eelsther** [comment]
Mentioned cufp in commit 0f239fe.
So I think this issue can be closed.

**Comment by Chris00** [comment]
Feel free to do it ;)
