### ISSUE TITLE
Consider removing GODI from the install instructions

### ISSUE THREAD

**Issue by yminsky** [ocaml/v2.ocaml.org#212]
Given that Gerd has announced that GODI is shutting down, it doesn't seem like it should be on the recommended installation route page.

http://blog.camlcity.org/blog/godi_shutdown.html

**Comment by Chris00** [comment]
Done in bf446b3948e8fd5deda1f89f38ccaab0ea7da596
I wonder however whether it is good to have a "quick install" that risks to become out of sync.
