### ISSUE TITLE
Problems with the "News" page

### ISSUE THREAD

**Issue by bienvenu** [ocaml/v2.ocaml.org#220]
- When on the community page, the "see full list" does not redirect to the news page
- The news page needs to be redesigned: the delimitation between news items is not clear enough. For instance, the titles are not big enough and there is not enough spacing after the "Read more" button. Moreover, maybe the titles of the different news items should be on a different background, which would then act as a vertical line to separate news items.

**Comment by Chris00** [comment]
News page redesigned. Main commits 79639d1b455a2fb67b9e2667c453769e4f698a73, 83c1912f6c0bb3cc8d9e1a0889daf8213914416f (several other ones tweak this).
