### ISSUE TITLE
Code syntax highlighting

### ISSUE THREAD

**Issue by bienvenu** [ocaml/v2.ocaml.org#221]
I know that this is a subjective, but I've seen it mentioned elsewhere, yet there doesn't seem to be a specific issue for this.

I think the syntax highlighting and code formating could be greatly improved:
- The colors for syntax highlighting are two bright. For instance, on my screen, the green is hardly readable. The orange can be read but is quite aggressive (in my opinion). Finally, this is a matter of personal taste but so far all of the (two) persons to whom I've shown the site agree that the results looks a bit strange.
- The space between lines is much bigger than what is found in most text editors, and as a result it looks a bit weird

**Comment by Chris00** [comment]
- The color scheme was discussed on the mailing list.  Like several other people, I do prefer the old palette.
- For the code spacing, see also https://github.com/ocaml/ocaml.org/issues/211

**Comment by Chris00** [comment]
I have tried to improve the syntax highlighting in 4c1c99b90bc031db43bbe2655223d8b1782fea0c.  There is still much to do (e.g. function names and arguments, labels,... should be colored).  I think one should first base the syntax highlight on the compiler libs.

**Comment by bienvenu** [comment]
Much easier on the eyes (in my opinion) =)

However, for some reason, the font looks a bit blurry on my computer. The other fonts of the site are not affected.

**Comment by Chris00** [comment]
I used Inconsolata — I prefer Consolas but they are not free.  I reverted (commit eec97166c28c856f478182d4281db7acc7ab8d7d) to Lato to avoid having too many fonts on the same page.  It is easy enough to change again later.

**Comment by pw374** [comment]
> I think one should first base the syntax highlight on the compiler libs.

Yes, I think that would be the best.

My initial idea was to extract https://github.com/ocaml/ocaml.org/blob/master/src/app/code.ml to have an ocamltohtml that works the same way as the current ocaml.org's one. It was just quicker to use the current ocamltohtml just because I had it somewhere.

**Comment by Chris00** [comment]
For the font, I changed again my mind.  I think a monospaced font is better.  I changed that in 7bce46d9a4148834cdec066e73a37c3decf49543

**Comment by pw374** [comment]
I concur that we should use a monospace font for code.

**Comment by bienvenu** [comment]
Yes, monospace AND sans-serif. I think it looks nice as it is right now.

**Comment by Chris00** [comment]
Syntax highlighting using compiler libs: will it also work when the code does not parse?  It is rare but one wants to show errors (and how to deal with them).

**Comment by Chris00** [comment]
I think the issues raised here have been addressed.  For a better highlighting library, see https://github.com/ocaml/ocaml.org/issues/286
