### ISSUE TITLE
Weird spacing in "cheat sheets" page

### ISSUE THREAD

**Issue by bienvenu** [ocaml/v2.ocaml.org#222]
This is a minor problem but the design of the page is slightly confusing: the spacing is bigger between the link to a cheat-sheet and its description than between the description and the link to the next cheat sheet.

Being a bit tired, I found myself opening the wrong cheat sheet because, after reading a description, I clicked on the nearest link without really reading it.

**Comment by amirmc** [comment]
There are explicit `<br />` tags and the line breaks in a bulleted list don't help matters.  Straightforward to fix (will do after we've restructured the repo a bit).
