### ISSUE TITLE
100-lines → Markdown

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#223]
http://preview.ocaml.org/learn/100-lines.html should be rewritten in Markdown (or maybe should disappear?).

**Comment by Chris00** [comment]
I actually removed the page. cac08cd5e78f67dd11f32dacae1f252f83b041d0

**Comment by agarwal** [comment]
In our current site, taste.html _is_ the Hundred Lines of OCaml page. And indeed, it seems taste.md has the contents of taste.html. The 100-lines.html page seems to be subset of the former taste.html. I don't know where this page came from.
