### ISSUE TITLE
Merge Industrial users & companies

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#225]
The page http://preview.ocaml.org/learn/industrial.html is far from being as complete as http://ocaml.org/companies.html 
It should be merged with http://preview.ocaml.org/learn/companies.html

**Comment by amirmc** [comment]
I'll take this one.  I need to find logos for companies anyway (#131)

**Comment by amirmc** [comment]
fixed by 1955a717e078f9d55d866a5026790464ebc5b297
