### ISSUE TITLE
support.html: remove link to Inria site

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#23]
The `follow this link` part refers to Inria site, which is mostly the same content as this page. Remove this link, add the "How to become a member?" section directly to this page, along with the links therein. But the PDFs are in en and fr language and there is a form, so need to make sure these will work in our site.

**Comment by Chris00** [comment]
I do not think that we need to copy/port/... the PDF and form on our site.  The site is concernend with the community.  It is OK to refer to another site for the consortium I guess.

**Comment by Chris00** [comment]
Done.  885c19bb265dd1dca4e0e2580f610efd006d992b
