### ISSUE TITLE
Preview is dead

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#230]
http://preview.ocaml.org/ displays an empty page.  This is likely because `rss2html` is extensively used and depends on `netclient` (as was advertised in `src/README .md` before I made the changes).  The preview works perfectly on my machine.

**Comment by amirmc** [comment]
Other pages still work so it's just the front page. 
- http://preview.ocaml.org/learn/
- http://preview.ocaml.org/docs/
- http://preview.ocaml.org/community/
- http://preview.ocaml.org/platform/

**Comment by Chris00** [comment]
Is `ocamlnet` installed on the machine that compiles the preview?

**Comment by amirmc** [comment]
In https://github.com/ocaml/ocaml.org/commit/19e6648221f7dc21887dd58053365b8a41f2a05b, you changed the page so it didn't pull the relevant html snippet from the `tpl/front_news.mpp` file.  Could this be related?  Was there a reason to make the change directly in the `index.md` file?

Note that the same code snippet is used on the community page (linked above) and is working ok.

**Comment by amirmc** [comment]
> Is `ocamlnet` installed on the machine that compiles the preview?

According to the wiki, it should be.

https://github.com/ocaml/infrastructure/wiki/OCaml.org

**Comment by Chris00** [comment]
On Sun, 10 Nov 2013 14:21:03 -0800, Amir Chaudhry wrote:

> In 19e6648, you changed the page so it didn't pull the relevant html
> snippet from the tlp/front_news.mpp file. Could this be related? Was
> there a reason to make the change directly in the index.md file?

Well, I did not see the point of a separate file since the script is
now one line long.  I was thinking to remove altogether
tlp/front_news.mpp as it is no longer needed.

One thing may be that $TMP (aka Filename.temp_dir_name) is not
writable (the script makes a cache there to compile the site faster).

> Note that the same code snippet is used on the community page
> (linked above) and is working ok.

The news should point to the Planet page and not directly leaving the
site.  Thus the front page news and the Planet page must agree on what
are the link/anchors.

Did you try `make preview` on your machine?  Does it work?

**Comment by amirmc** [comment]
> Did you try `make preview` on your machine?  Does it work?

Just tried and the front page is blank.  The others display ok.  I've put the output on a gist at https://gist.github.com/amirmc/7405042

**Comment by Chris00** [comment]
Thanks for the output, I got it.  Fixed in 568139319aefef70ddfa03972bda7fbef3580e6b

**Comment by amirmc** [comment]
> The news should point to the Planet page and not directly leaving the
> site.  Thus the front page news and the Planet page must agree on what
> are the link/anchors.

Sorry, I'm not sure I understand what you mean by this.  Do you mean that the links in the news items should point to the relevant story on the Planet page?  If so, that seems reasonable.  

However, that same snippet of html may be used on several parts of the site (currently two) so I would much prefer that we keep the code that generates it in one place, even if it is only one line.  I've taken the same approach with the code that will produce the opam table (which will appear on both the front page and the platform page).

Would you prefer we reproduce the same code in different places?

**Comment by amirmc** [comment]
> Thanks for the output, I got it. Fixed in `5681393`

Thanks, but something is missing `Error: Cannot find file utils.cmx`  

``` text
AmirMacBook:src amir$ make preview
make all
cd app && ocamlfind ocamlopt -package netstring,netclient,rss -c http.ml
ocamlfind ocamlopt -package netstring,netclient,rss -linkpkg \
      -I app/ http.cmx utils.cmx -annot "rss2html.ml" -o "rss2html"
File "rss2html.ml", line 1:
Error: Cannot find file utils.cmx
make[1]: *** [rss2html] Error 2
make: *** [preview] Error 2
```

(I haven't run `opam update` in a while so I'm not sure if this is just my machine)

**Comment by Chris00** [comment]
> However, that same snippet of html may be used on several parts of the site (currently two) so I would much prefer that we keep the code that generates it in one place, even if it is only one line. I've taken the same approach with the code that will produce the opam table (which will appear on both the front page and the platform page).

I started doing this but it seems to me that the number of headlines may be different on the front page (more room) than on the community page.  The code is really one line:

```
{{! cmd ./rss2html -n 6 --headlines http://planet.ocaml.org/rss20.xml !}}
```

**Comment by amirmc** [comment]
http://preview.ocaml.org/ is still blank.  It should have updated by now so unfortunately I don't think the fixed work.  Can we revert back to the original method until we figure out what's wrong?

**Comment by Chris00** [comment]
It's difficult to figure out what is wrong when it works on your machine...

**Comment by amirmc** [comment]
> It's difficult to figure out what is wrong when it works on your machine…

:) I completely understand.  I'm sorry I can't be more help with debugging but if you can tell me how/when `utils.cmx` is supposed to be generated perhaps I can give you more output to look at.

**Comment by amirmc** [comment]
I've just pulled your recent commits and `make preview` is now working again.  Will wait a few mins and the website should be back up too.

**Comment by Chris00** [comment]
This time I got it — sorry for taking so long to catch it.  There is still the fact that the code for the news is factorized in `tpl/front_news.mpp` or not.  Not doing it allows to have different values for `-n` (the number of headlines).

**Comment by amirmc** [comment]
The site is up! Thanks!

Yes, I'd restricted myself to the fact that we'd only have the same number of news items no matter where that snippet is used (same for the OPAM table).  Let's continue this tomorrow and @pw374 can catch up with this thread too.  We can discuss in a new issue.

**Comment by Chris00** [comment]
OK — I need some sleep too! ;-)

**Comment by pw374** [comment]
Wow, this issue got closed just when I got back home...

You may now access to http://preview.ocaml.org/stdout.log and http://preview.ocaml.org/stderr.log if you need the logs. I can give you direct access to the machine if you give me your ssh key. (I've just limited the size of the log to 3MB, previously it was 100MB.)

**Comment by avsm** [comment]
This is why I keep suggesting using Travis to build the website.  It requires that you wrap all dependencies in a single shell script, and it rebuilds/installs everything from scratch on every single commit, with the logs publiclly displayed for anyone to debug.

**Comment by Chris00** [comment]
I agree it should be done — that would avoid stupid mistakes like mine!
