### ISSUE TITLE
tpl/front_news.mpp needed ?

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#231]
Is the front page template `tpl/front_news.mpp` needed given that it reduces to a single line:

```
{{! cmd ./rss2html -n 6 --headlines http://planet.ocaml.org/rss20.xml !}}
```

It is (was actually) also used in `site/community/index.md` but this prevents from fixing a different value for `-n`.  Let me know what you prefer.

**Comment by Chris00** [comment]
Maybe we want to use `tpl/front_news.mpp` for news staying a longer time such as "Commercial Users of Functional Programming 2013" (using the icon ![announcement](https://f.cloud.github.com/assets/1255665/1511646/29932444-4ab5-11e3-8331-cf70219c8d23.png)).

**Comment by amirmc** [comment]
I don't have any strong opinions on keeping `tpl/front_news.mpp`.  I have a mild preference for reducing the amount of rewritten code across the site from a maintenance point of view i.e if we want to change how the feed looks, we do it one place.  However, that's already captured by Christophe's change. If no-one objects, I'd say we can get rid of the file.

**Comment by amirmc** [comment]
For the longer lasting and 'official' announcements, I was thinking we could create a separate ATOM feed.  That way we could still send news out via Planet but also highlight it differently on the news summary.  We would use the icon above as well as make those items appear at the top of the list (limited to 2).  I haven't thought particularly deeply about this but it seems like it should be workable.  

It does mean creating a feed  somewhere that we can push official announcements into and those posts should be infrequent (i.e OCaml release announcements and major meetings).

**Comment by Chris00** [comment]
I have added an option `--img` d7325be95c748b3170ab081471c78ab1806747aa to `rss2html`, so an easy way is to add, say,

```
{{! cmd ./rss2html -n 2 --img  /img/announcement.png--headlines http://ocaml.org/rss20.xml !}}
```

before the current feed in `index.md`.

**Comment by amirmc** [comment]
Wouldn't this produce duplicates at the time of the posts?  The rss feed should still go out via Planet so the posts would reappear in the feed below.

**Comment by Chris00** [comment]
If you connect the "announcement" RSS channel to the planet, yes.  Otherwise a selection function in `rss2html` will do.

**Comment by Chris00** [comment]
Let us discuss this again (in a new issue) when the announcement feed is in place.  Some other questions must indeed be settled: do we always want to put announcements to the top or the darker icon is enough?  How many announcements do we want to keep?  Is the planet feed keeping the announcements for long enough?  If not, we may want to filter them out from the feed and use a direct RSS link as I suggested before.
