### ISSUE TITLE
Reconsider the location of 'Edit this page'

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#238]
Now that the annoying footer is fixed to the bottom of the content (hooray!), we've lost the very handy 'Edit this page' link all the way to the end of the page.

I'm wondering whether it's possible to move it into the nav bar somewhere.  Or perhaps have a ribbon that says the same thing [1].

[1] https://github.com/blog/273-github-ribbons (the PSD files are available so we can change the text)

**Comment by agarwal** [comment]
The ability to edit a page doesn't have to be too prominent in my opinion, so I think it's okay all the way at the bottom.

**Comment by amirmc** [comment]
The benefit of an 'edit' button is two-fold (1) send a clear signal to visitors that they can contribute and (2) make it really easy to go directly to the content they wish to improve -- where they can make changes and submit PRs without leaving the browser [1].  

A few people independently asked me about this feature and I'm glad we have it and I think it deserves to be more visible.  In fact, I've used it several times today to get to the right file in the repo so I can look at the 'blame' view (to see what changed and when).  Since it's now at the bottom of the screen, I have to scroll all the way down.

In time, we should also look at using travis, which would mean people can see their changes without having to build locally (see #230).

[1] https://help.github.com/articles/creating-and-editing-files-in-your-repository

**Comment by Chris00** [comment]
I basically feel like Ashish.  There are two separate questions:
- Is the bottom of the page — that will have more links soon if I understood well — visible enough for potential contributors to discover the feature?  Since there are many things in the nav bar already, is an icon there with a tooltip better?
- Is it really so problematic to go to the bottom of the page — a single click — when you know the button is there?

**Comment by amirmc** [comment]
> - Is the bottom of the page — that will have more links soon if I understood well — visible enough for potential contributors to discover the feature? Since there are many things in the nav bar already, is an icon there with a tooltip better?

Something at the top of the page (or a ribbon on the bottom right?), would be fine with me.  I agree that putting it in the nav bar probably won't work -- unless it's an icon, but even then I'm not sure. 

> - Is it really so problematic to go to the bottom of the page — a single click — when you know the button is there?

Yes, I found it sufficiently irritating on the longer pages that I opened this issue :)  -- I can't see how anyone would discover such a feature by chance if we bury it at the bottom, especially new visitors.  I think the value here is greater than the ability to simply edit something as having such a button invites people to explore as well as demonstrate that it's a community site where visitors create the content.

(Also: is it a single click to go to the bottom of the page?  I have to scroll -- or move to keyboard.)

**Comment by Chris00** [comment]
On Mon, 11 Nov 2013 13:26:56 -0800, Amir Chaudhry wrote:

> (Also: is it a single click to go to the bottom of the page? I have to scroll -- or move to keyboard.)

Put your mouse at the bottom of the scrollbar and middle click — at least on Linux...

**Comment by pw374** [comment]
I feel like saying that on a laptop, middle-clicks are very rare...

**Comment by agarwal** [comment]
Don't you guys have a scroll wheel?  :)  If you're on Mac, you really need
the Apple mouse.

**Comment by pw374** [comment]
haha, well I don't mind using my keyboard or the mouse "wheel" or the trackpad "wheel", I only meant that middle-clicks are tricky to do on most laptops (PC or Mac).

**Comment by Chris00** [comment]
@pw374 On Linux, you can push the two buttons together to emulate a middle click.  I have used Laptops without a middle button for a long time and this works well.

**Comment by Chris00** [comment]
Back to the original concern: do you mean something like the following (the ribbon could disappear when one clicks on the search form):
![ocaml-ribbon1](https://f.cloud.github.com/assets/1255665/1520892/aa6bff3e-4b85-11e3-9788-fb0db246ec18.png)

Some ideas:
- http://css-tricks.com/snippets/css/corner-ribbon/
- http://stackoverflow.com/questions/19489664/css-3-corner-ribbon
- http://stackoverflow.com/questions/18627676/how-to-make-slanted-ribbon-with-css-and-html-only

**Comment by Chris00** [comment]
More discrete: 
![ocaml-ribbon2](https://f.cloud.github.com/assets/1255665/1520926/d8f864e0-4b86-11e3-9ef5-7ff3318260c4.png)

**Comment by Chris00** [comment]
I have created a branch `ribbon` to experiment with this are port the final solution to `redesign`.

BTW, the ribbon was created with http://oojits.com/info/img/corner-ribbons/ (75, 30, Edit, `#8eaf20`, `#ffffff`, `#d5cbb1`)

**Comment by Chris00** [comment]
BTW, this solution does not work on small screens as it prevents to click on the menu icon.  In any case, I think I would prefer a small white icon (a pen?) to the right of the search box — with a tooltip.  What do you think?

**Comment by agarwal** [comment]
How prominent should the edit button should be? On the one hand, I agree we
should make it very clear that editing is possible, and I want anyone
reading a page to realize they can submit a pull request. On the other
hand, I want to let users focus on reading, since presumably a page will be
read much more than it will be edited.

With that tradeoff in mind, I feel the green ribbon is too prominent. It
takes your attention completely, even more than the menu items. The upper
right corner seems like a good location though. So perhaps the pen you
mention, or a lighter color ribbon will work.

**Comment by amirmc** [comment]
Nice images!  Thanks for producing them.  

I think an edit icon with a tooltip might be more subtle and appropriate.  I've used the Font Awesome icons on another site so they might be easy to use here.  Some possibilities are below

[1] http://fontawesome.io/icon/pencil-square-o/
[2] http://fontawesome.io/icon/pencil

**Comment by Chris00** [comment]
Here are two screenshots, the default one and the one with hovering the icon.  See the `ribbon` banch.
![oo1](https://f.cloud.github.com/assets/1255665/1524049/3f5a5e08-4bc0-11e3-8416-a96888b777a7.png)

![oo2](https://f.cloud.github.com/assets/1255665/1524055/4ac2cd84-4bc0-11e3-80ed-b8548e4af173.png)

**Comment by amirmc** [comment]
Nice! Almost exactly how I pictured it.  I like the orange highlight on hover.  However, I think the pen itself isn't particularly clear so I prefer the one I linked earlier ([pencil-square-o](http://fontawesome.io/icon/pencil-square-o/)).  Specifically, because it's a more obvious pencil and on a 'page'.  Thoughts?

**Comment by Chris00** [comment]
It is just a matter of changing the image.  I let you change it (or ask the design firm to produce one).  The other icons of the site are rather sober — this one should be even more so (it is less important than the other ones).

**Comment by amirmc** [comment]
I think you can merge this one into the redesign branch and I'll make a separate issue to revist the icon.  Is that ok?

**Comment by Chris00** [comment]
Done 762e91912ff0234c49ca45fe7878329668247e25

**Comment by amirmc** [comment]
Fabulous, thank you!
