### ISSUE TITLE
add link to old Inria site

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#24]
We should somewhere link to caml.inria.fr as the "old Inria site", but not sure where to put it. Ideally, old Inria site would have banner added to top saying the site is deprecated.

**Comment by eelsther** [comment]
I suggest to add it at the bottom of the home page.

**Comment by agarwal** [comment]
A good place for this might be the proposed About page. See #265.

**Comment by agarwal** [comment]
I'm not sure why I proposed this. This seems wrong since the Inria site is deprecated.
