### ISSUE TITLE
Please keep URIs stable, don't break links to existing site

### ISSUE THREAD

**Issue by edwintorok** [ocaml/v2.ocaml.org#240]
Just recently I've linked to a few places on OCaml.org from a discussion on HN, and I've checked preview.ocaml.org where the same links give me a 404:
preview.ocaml.org/tutorials/
preview.ocaml.org/books.html

I understand that the new site may rearrange the content, but please put some forwarding in place so that you don't break all the old links to the existing ocaml.org site.
Relevant:
http://www.w3.org/Provider/Style/URI
http://www.w3.org/TR/cooluris/

**Comment by agarwal** [comment]
We can do this selectively when it makes sense. However, we're not aiming for strict backwards compatibility.

**Comment by amirmc** [comment]
Perhaps we should set redirects for the following three pages (which I've seen linked recently).  It's possible these have been used to advertise outside the OCaml community so if possible we should avoid 404s.  In general, I agree that we're not aiming for strict backward compatibility.
- ocaml.org/tutorials/ -> ocaml.org/learn/tutorials/
- ocaml.org/companies.html -> ocaml.org/learn/companies.html
- ocaml.org/books.html -> ocaml.org/learn/books.html

**Comment by amirmc** [comment]
a `.htaccess` file might be more appropriate than placing redirect pages.

**Comment by edwintorok** [comment]
Maybe you could check the server logs of ocaml.org, and see which are the pages that are linked most from the outside, and put in redirects for those only. (i.e. sites with a referer other than ocaml.org, or no referer).

**Comment by amirmc** [comment]
The site used to be served from GitHub Pages so I don't think we have access to server logs.  There is Google Analytics which might be useful.

**Comment by pw374** [comment]
I've just added these redirection rules:

```
       "^/tutorials/(.*)" => "/learn/tutorials/$1",
       "^/companies.html" => "/learn/companies.html",
       "^/books.html" => "/learn/books.html",
```

**Comment by pw374** [comment]
I believe the current status of redirections covers everything.

```
   "^/tutorials/(.*)" => "/learn/tutorials/$1",
   "^/companies.html" => "/learn/companies.html",
   "^/books.html" => "/learn/books.html",
   "^/planet/" => "/community/planet.html",
   "^/support.html" => "/community/support.html",
   "^/mailing_lists.html" => "/community/mailing_lists.html",
   "^/install.html" => "/docs/install.html",
   "^/cheat_sheets.html" => "/docs/cheat_sheets.html",
   "^/license.html" => "/docs/license.html",
   "^/logos.html" => "/docs/logos.html",
   "^/debug.html" => "/learn/tutorials/debug.html",
   "^/portability.html" => "/learn/portability.html",
   "^/libraries.html" => "/learn/libraries.html",
   "^/description.html" => "/learn/description.html",
   "^/history.html" => "/learn/history.html",
   "^/taste.html" => "/learn/taste.html"
```

There's however no guarantee that those permanent redirections will be kept for long, they're mostly useful to tell Google et al. that those pages have moved. Pages that link to stuff that has moved should be updated, or they'll end up having broken links eventually.

I'm closing this issue.
