### ISSUE TITLE
add Google Analytics code

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#242]
Our old template, which you can see in 915be7ca2b9dd83b95fd66ca04b3f6fccfdea419, has the necessary code for Google Analytics. This needs to be added to our new template.

Note that we actually push site statistics to two Analytics accounts due to the issue discussed [here](http://lists.ocaml.org/pipermail/infrastructure/2013-January/000113.html). Now might be a good time to decide if we still want to do this. We could stop pushing to the ocamlpro account.

**Comment by amirmc** [comment]
My inclination is to stop the old tracking and keep the ocamlwebsite one.  However, at what point do we add the tracking code?  It seems as though it should happen at the deployment step (#184) so that it appears on the new site and not on the preview site.  

Thoughts?

**Comment by agarwal** [comment]
Ah good point. We don't want the preview stats to mess up the real stats.
Actually, that would be an ongoing problem. I'll have to check how Google
Analytics works. There should be a way to make sure only things under a
certain domain are getting tracked. Otherwise, anybody could take this code
and start messing up with another website's statistics.

**Comment by amirmc** [comment]
I was thinking that if the analytics are for `ocaml.org` then code on `preview.ocaml.org` might still get counted.  It probably depends on the settings in Google Analytics, but I'm not familiar with the options.  Let me know what you discover.

**Comment by avsm** [comment]
You can configure Google Analytics to filter by subdomain. It's probably best to keep the same code for all the *.ocaml.org and do the work on the Analytics site.

-anil

**Comment by agarwal** [comment]
Okay, so I'll try to set the configuration to include all *.ocaml.orgexcept for
preview.ocaml.org.

**Comment by agarwal** [comment]
All I can find is an option to enable tracking of all subdomains of ocaml.org. Thus, there is no way to exclude preview.ocaml.org. Instead, we could modify our build such that `make preview` doesn't include the tracking code while `make`, which builds the production site, does.

Also note that tracking isn't automatic. The tracking code has to be added to each page that should be tracked, so the opam.ocaml.org implementation has to incorporate it.

**Comment by amirmc** [comment]
> The tracking code has to be added to each page that should be tracked...

Yup, this is usually achieved by adding it to the end of the template file.  In our case, that's: 
https://github.com/ocaml/ocaml.org/blob/redesign/template/main.mpp

It's probably not an issue to put the code straight in the template directly as only the visits to the VM will count (i.e where the DNS points to).  I can't imagine the tracking to be at all reliable if it counts stats from any random place where the code pops up (e.g if I set up a clone elsewhere).

> … so the opam.ocaml.org implementation has to incorporate it.

The opam.ocaml.org site already seems to have a tracking code: `UA-22552764-5`.  Who has access to this?

**Comment by avsm** [comment]
That's an OCamlpro number... @altgr or Fabrice will have admin rights.

**Comment by amirmc** [comment]
@agarwal d'you have the code you want to add to the template? This issue should be easy to close so I'm not too concerned about (unless someone knows something I don't)

**Comment by agarwal** [comment]
I have the code and can add it now, but I was hoping for a reply to #287.

**Comment by agarwal** [comment]
Done in 568839b752d398dd75250221d1690a02baa1533b and 3d017d04bc7197077af03d57ee33ef368b5fdd4f.
