### ISSUE TITLE
too many links to GitHub in footer

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#243]
The footer contains 4 links, all of them to GitHub. The _Feedback_ and _Contact us_ are actually identical (both go to issues). This seems unnecessary. Maybe _Feedback_ should link to the infrastructure list, and _Contact us_ and _Find us on GitHub_ could be merged to _Submit an Issue on GitHub_.

**Comment by amirmc** [comment]
We're (at some point) going to be adding a lot more links in the footer to parts of the site.  I feel that Contact us should lead to the mailing list whereas the GitHub link can just be a link to the issues page.

**Comment by agarwal** [comment]
The links seem fine to me now.
