### ISSUE TITLE
provide OCaml licenses

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#25]
Inria site describes [availability](http://caml.inria.fr/ocaml/index.en.html) of OCaml with links to licenses, the normal one and the one for Consortium members. We should import these and link to them from description.html.

**Comment by Chris00** [comment]
I believe this should be on the download page (maybe a slightly shorter text in a floating box to the right of the page).

**Comment by Chris00** [comment]
Box added.  6d7fe1a51e22c878090101aed2bb03b4efcfa06d
Full text of the license added. 4f0b6b767429e26ade70fc190aa2eae457f7b093
