### ISSUE TITLE
The pictogram for the "Edit this page" link

### ISSUE THREAD

**Issue by pw374** [ocaml/v2.ocaml.org#250]
Is it normal that https://github.com/ocaml/ocaml.org/blob/762e91912ff0234c49ca45fe7878329668247e25/site/img/edit-hover.png has black corners?

**Comment by Chris00** [comment]
Yes, the corners are the same color as the nav bar so the orange button seem to have rounded corners (exactly like those in the main area).

**Comment by pw374** [comment]
on my laptop, they don't have the same color at all...

**Comment by pw374** [comment]
![](http://philippewang.info/tmp/Screen%20Shot%202013-11-12%20at%2020.45.28%20PM.png)

and it's the same on your screenshot, i.e., ![](https://f.cloud.github.com/assets/1255665/1524055/4ac2cd84-4bc0-11e3-80ed-b8548e4af173.png)

the 4 corners of the square are plain black while the nav bar is grey...

**Comment by Chris00** [comment]
It is not the case on my machine.  In any case I made d9721216cc8d5d04a11cd844531215588d6649dc the background transparent.

**Comment by pw374** [comment]
thanks, that's a lot prettier this way on my machine :)
