### ISSUE TITLE
The "Edit this page" img-link doesn't seem to work when the window is narrow

### ISSUE THREAD

**Issue by pw374** [ocaml/v2.ocaml.org#251]
I can't click the pencil on Safari (OSX) when the window is narrow. Same on my iPhone (Safari/iOS7).

**Comment by Chris00** [comment]
Should be fixed in 7989a9fefddbaa77420ce9f258e694cb0d75648f

**Comment by Chris00** [comment]
BTW, wait for 2 (?) hours the time that the entire site be regenerated from scratch because some modifications affect the template.

**Comment by pw374** [comment]
> BTW, wait for 2 (?) hours the time that the entire site be regenerated from scratch because some modifications affact the template.

what do you mean, is this a question?

**Comment by Chris00** [comment]
On Tue, 12 Nov 2013 13:57:41 -0800, Philippe Wang wrote:

> | BTW, wait for 2 (?) hours the time that the entire site be regenerated from scratch because some modifications affact the template.
> 
> what do you mean, is this a question?

No — the collapsed state will look slightly better when the whole site will be rebuild with the new template.  If my memory serves, it is every 2 hours.

**Comment by pw374** [comment]
Oh, ok :)

The whole site is regenerated every 20 pulls (including pulls that return "everything up to date").
There is at least 200 seconds between 2 pulls.
So, most of the time there's less than 2 hours between 2 full builds. :)

Running `touch /home/buildpreview/flag/force-build.flag` on the machine forces the next build to be a full build and it starts within 2 seconds (unless it's already building, in which case it's 2 seconds after the end of the current build).

**Comment by Chris00** [comment]
OK, good to know.

Is the edit button working fine for you now?

**Comment by pw374** [comment]
> Is the edit button working fine for you now?

yes, thanks :)
