### ISSUE TITLE
Add code to generate a package table

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#253]
Moved from from https://github.com/ocamllabs/sandbox-ocaml.org/issues/31
@pw374 is looking at this.

---

This is used on the front page and the platform page. Currently has placeholder text.

I'm hoping we can take existing code from opam2web which generated the tables at https://opam.ocaml.org

**Comment by pw374** [comment]
@dsheets wrote:

> I have a branch of opam2web that is awaiting merge which can easily generate the needed HTML fragment.
> 
> How would you like to integrate this?

Now http://preview.ocaml.org has a package table! :)
However it's generated by a bash script and from [opam-repository](https://github.com/ocaml/opam-repository)'s git-log instead of opam2web using I-don't-know-which-database.
So now I'd like to use opam2web to generate this table. How can I do that?

**Comment by dsheets** [comment]
Build the master branch of opam2web, get a copy of the apache logs if you'd like popularity statistics, edit the file `content/home.xhtml` to contain the boilerplate you desire (the table insertions are at the end in the `t` namespace) and `content/template.xhtml` to contain further boilerplate (or just `t:seq`), then run `mkdir -p www && opam2web -o www -c content` to generate `www/index.html` which will contain the statistics tables.

**Comment by Chris00** [comment]
Remark: It would be nice if the site does not stop to build when one does not have access to the logs.  A "fallback" table should be generated in this case (does not matter what information it contains, this is to ensure the page can be previsualized fine).

An alternative possibility is to couple the two project through a feed (ICS?).  People may like to connect to that feed too.

**Comment by dsheets** [comment]
The site still builds without the logs. A fallback is provided. Also, the `t:insert` widget for the download statistics can be omitted without issue.

There should be a feed eventually. I'd prefer Atom to ICS. Scripted generation is simpler than feed emission/consumption in the mean time.

**Comment by amirmc** [comment]
Since we now have a table on the site, I'm removing the 'blocking' tag from this issue.  I'll leave it open in case there's more to discuss.
