### ISSUE TITLE
Add sitemap-style links into footer

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#257]
Add links into footer to help people get to content quicker.  

Examples (scroll to footers):
- http://www.citrix.com
- http://www.microsoft.com
- http://investor.google.com
- http://www.ibm.com (though we don't want this many!)

**Comment by Chris00** [comment]
I changed to footer.  Let us now fill it with the proper links! ;-)

**Comment by samoht** [comment]
That's nice, but the columns are not centred correctly due to:

```
# ocamlorg.css:328
media="screen"
#footer {
font-size: 95%;
text-align: right;
}
```

**Comment by Chris00** [comment]
On Mon, 30 Dec 2013 12:32:12 -0800, Thomas Gazagnaire wrote:

> That's nice, but the columns are not centred correctly due to:
> 
> # ocamlorg.css:328
> 
> media="screen"
> #footer {
> font-size: 95%;
> text-align: right;
> }

I meant that — but one can change it if there is a consensus that cen 
tered columns are better looking.

**Comment by samoht** [comment]
Hum. That just feels weird. All the website cited in the first post have all more-or-less centered footers (or at least they have margins and sometimes big buttons on a side to not be too symmetric)

**Comment by Chris00** [comment]
Do we want the footer to be the same on all pages or be different on [pages with a menu](http://ocaml.org/learn/tutorials/comparison_of_standard_containers.html) (the reason why it was off centered).
