### ISSUE TITLE
Book section is a bit messy

### ISSUE THREAD

**Issue by yminsky** [ocaml/v2.ocaml.org#259]
The book images vary pretty widely in size.  In addition, some images are broken.  I think in general, the images would be better if they were aligned to the right or left and the text flowed around them.   Right now they come before the title, which is pretty confusing.  It looks like the "Real World OCaml" image belongs to the standard OCaml library, as one example.

**Comment by amirmc** [comment]
This page can probably be reformatted to be more like the companies page [1].  That's a table which makes it easier to keep content together (and constrains images sizes too).  

http://preview.ocaml.org/learn/companies.html
