### ISSUE TITLE
Videos of OUD 2013

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#266]
Are there videos of OUD 2013?

**Comment by mauny** [comment]
Hi,

Not yet. I got the tapes, and I need time and hardware to process
them. I am still looking for the hardware (tried in my institution,
but the hardware couldn't extract the videos).

OUD 2012 had the videos processed and posted by the ICFP
organization. No help in 2013.

Hopefully in a few weeks.
- Michel

Christophe Troestler écrit/writes [14/11/2013 10:06] :

> Are there videos of OUD 2013?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/ocaml/ocaml.org/issues/266.

## 

Michel Mauny
ENSTA ParisTech
828, boulevard des Maréchaux
91762 Palaiseau Cedex
+33 1 8187 2032

**Comment by agarwal** [comment]
@mauny Do you know how you want to host the videos? Please do not add the videos directly to this repo. We're avoiding putting large media files here to make sure the repo doesn't explode in size. We have a YouTube account we can use and a separate ocaml.org-media repo. We can think about the correct solution when you have the videos ready.

**Comment by mauny** [comment]
Hi Ashish,

Ashish Agarwal écrit/writes [14/11/2013 14:14] :

> @mauny https://github.com/mauny Do you know how you want to host the videos? Please do not add the videos directly to this repo. We're avoiding putting large media files here to make sure the repo doesn't explode in size. We have a YouTube account we can use and a separate ocaml.org-media repo. We can think about the correct solution when you have the videos ready.

Ok, thanks,
- Michel

## 

Michel Mauny
ENSTA ParisTech
828, boulevard des Maréchaux
91762 Palaiseau Cedex
+33 1 8187 2032

**Comment by Chris00** [comment]
@mauny 

>  I am still looking for the hardware

Tell me what kind of tapes you have.  My institution may have the relevant ~~material~~ hardware.  Plus you can give a talk the day you come! ;-)

**Comment by Kakadu** [comment]
Any success about this issue?

**Comment by Kakadu** [comment]
Still no success?@mauny @Chris00 Are you going to release this videos before OUD 2014?

**Comment by Chris00** [comment]
On Tue, 20 May 2014 02:34:21 -0700, Kakadu wrote:

> Still no success?@mauny @Chris00 Are you going to release this videos before OUD 2014?

I do not have the videos.  I only offered some help.  I never received any answer.  There is nothing I can do about this.

**Comment by amirmc** [comment]
@mauny D'you still have the videos? Can you post anything here about the format they're in? Maybe I can look into my uni's facilities and see if there's a service that can help.  

For the sake of clarity for everyone on the thread, I cannot promise anything. I am simply offering to look into this particular option.

**Comment by Chris00** [comment]
@mauny Do I have to leave the _wontfix_ or can we find a resolution of this?

**Comment by Kakadu** [comment]
I'm afraid that this problem can appear this year...

**Comment by agarwal** [comment]
I won't be able to attend the meeting this year, and am really really hoping I'll be able to watch the videos after. I hope we can get them up this time (and I still hope we can get last year's up too).

**Comment by Kakadu** [comment]
It will be great to have live stream too. There are plenty of streaming services, only problem is to get a laptop powerful enough and a movie camera. And streaming services are able to auto save recordings.

**Comment by amirmc** [comment]
Just had a brief chat with @Chris00 about this. I'll email the organisers this weekend and see if there is actually a plan to record anything this year.  If not, then perhaps we can ask on the caml-list for volunteers to do the recording and Christophe is willing to do the post-processing.

I'm inclined to stick with just recorded video, otherwise we might complicate things for ourselves. These things are rarely as simple as they seem. :-/

**Comment by Chris00** [comment]
Any news?

**Comment by Kakadu** [comment]
@Chris00, do you still have a hope that we will get them?

**Comment by amirmc** [comment]
> Any news?

Apologies, I completely forgot to do this as I got wrapped up in the platform work at OCaml Labs. I've opened a new issue to track this (#527), so let's keep discussion/progress over there.
