### ISSUE TITLE
release index

### ISSUE THREAD

**Issue by pw374** [ocaml/v2.ocaml.org#270]
a real index page is missing at http://preview.ocaml.org/releases/

(related to #197 )

**Comment by pw374** [comment]
note that, currently, index.md is a symbolic link to 4.00.1.md 
One should be careful when editing index.md (i.e., don't edit 4.00.1.md instead)...

**Comment by agarwal** [comment]
FYI, the reason we don't have an index page for releases is that there were just two. We only had a page for 3.12.1 and 4.00.1. It didn't seem worth it to have an index page, but maybe we should now for the sake of uniformity. The links it could have are: 4.01.0, 4.00.1, 3.12.1, and "earlier" which goes to http://caml.inria.fr/pub/distrib/.

Note that pub/distrib remains a non-deprecated subset of the caml.inria.fr website. It consists only of raw files, not html pages.
