### ISSUE TITLE
simplify Makefiles

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#271]
In #227, we discussed simplifying the Makefiles but didn't decide how to do it. Possibilities are:
- Merge into one Makefile. This doesn't actually work because the rules in Makefile.from_html and Makefile.from_md would conflict.
- Move Makefile.{common, from_html, from_md} to a sub-directory. This isn't great because it so happens that Makefile actually just includes Makefile.common. Thus, the file we leave most prominent isn't informative, and you'd have to go look into the file that we've now hidden.

Need to make main rules of importance appear in Makefile, and then moving the other files into a sub-directory might make sense.

**Comment by Chris00** [comment]
I did dome splitting of `Makefile.common` 691afce621196deea4998f4b5ad077ade63aa78f  That should clarify what are the common rules (basically those to build the executable program).  Not sure that one can do better.

**Comment by agarwal** [comment]
I tried moving all makefiles except the main one into a sub-directory, but that just causes more problems. It's not worth it. As [mentioned in another issue](https://github.com/ocaml/ocaml.org/issues/184#issuecomment-28819495), I think the build system could be improved overall. This is not a priority, so I'll close this issue and we can revisit later.
