### ISSUE TITLE
Consider increasing font size (and typeface itself)

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#275]
A number of people commented (a while ago) that the font size should be increased (and maybe changed).  Now would be the time to discuss that.  I know that @Chris00 has made some font choices for code (and maybe other things) so that's probably fine.

Are there any remaining questions about typography?  I'm extremely wary of beginning a protracted debate but I would like comments to be aired.

(#274 is relevant and increases the contrast of text)

**Comment by avsm** [comment]
I would be in favour of increasing the font size slightly, but it needs to be tested on mobile devices to ensure its not weird.  The color changes are much more important in my opinion.

**Comment by amirmc** [comment]
I concur. Looking at preview from my phone, the font size is ok but could afford to be a bit bigger. 

Best wishes,
Amir

## 

sent via mobile

**Comment by Chris00** [comment]
@amirmc I only chose a font for code — that was not done.  The other fonts were put in place with the new template.

**Comment by Chris00** [comment]
Is it still an issue or do we close it?

**Comment by amirmc** [comment]
3 year with no further activity.  Time to close. :)
