### ISSUE TITLE
Create `staging` environment for ocaml.org site

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#277]
(continuing discussion from #276)

@avsm said

> Two VMs then, one of which is running preview and one live.

**Comment by amirmc** [comment]
Fine with me but we should call the other VM `staging`.  `preview` is only meant to be temporary for the duration of the review and `staging` is a more appropriate name going forward.

I'm imagining the following arrangement.
- a `master` branch, which the live site is built from (I'd use the current VM for this)
- a `staging` branch, which the staging site is built from.

We'd need special conditions for the staging site as we don't want it to be be indexed by search engines and probably not bother with analytics code (esp since it's under the same domain).  

It's not immediately clear to me what the actual workflow would be.  My guess is that people will still submit PRs to the master branch and we'd be using staging to try out new features/integrations before making them 'live'.

**Comment by avsm** [comment]
Typically all changes will first be pushed to the staging tree for a health check, and then pushed to the live site if it passes those checks. It's easiest if there are no hardcoded names for staging.ocaml.org and www.ocaml.org for this to work

**Comment by amirmc** [comment]
In practice I don't see many people submitting PRs to a branch other than `master`.  That would mean treating `master` as the staging area and then merging changes into some other branch to be pushed to 'production' if they're ok.  I'm fine with this although @agarwal should comment (it's similar to the arrangement the existing site has with a `publish` branch).

I don't understand what you mean by 'easiest if there are no hardcoded names'.  If we want to see the staging site, we have to call it something (I don't mind if it's not of the form `*.ocaml.org` but it does need to be stable).  This is what I mean when I say I'm not clear about the workflow.

**Comment by agarwal** [comment]
@amirmc What is the decision on this? Is an additional VM being setup? (As a minor note, I think the name `preview.ocaml.org` is fine, but don't care too much. Change it to `staging.o.o` if you prefer.)

**Comment by amirmc** [comment]
Since we don't (yet) have a second VM, we're still going to use the current one as production.  Once we have a second one set up, then we'll use that as the staging.  I'd like the name to be changed as `preview` just has different connotations to `staging` and I have a preference for signalling things appropriately.  However, it's not actually that important.

**Comment by avsm** [comment]
I've just set up staging.dev.ocaml.org and am configuring accounts on it.  This should be a more general shell account for all the www development (the VM is quite underpowered, but that's ok since it's not intended to handle load).

-anil

**Comment by amirmc** [comment]
Thanks!  I've run through the merges on a fresh fork so I'm aware of the conflicts (and 

I'm just waiting for @pw374 to check the scripts on the current VM and @avsm to tell me when he's ready to do the DNS.  I've spotted a few last minute changes too.

**Comment by avsm** [comment]
DNS switched! Congratulations!

**Comment by Chris00** [comment]
Do we still want to do this or are we happy with the current way the site functions?

**Comment by amirmc** [comment]
I think we should close this.  We can open a new issue if this need arises.  In time, I'll want to raise the possibility of unikernel-based sites but that will be somewhat different to a staging server.
