### ISSUE TITLE
No favicon on Safari

### ISSUE THREAD

**Issue by pw374** [ocaml/v2.ocaml.org#278]
Was: "`favicon.ico` should be in `/` (not in `/img/`) according to http://en.wikipedia.org/wiki/Favicon#Use_of_favicon"

Edit: actually it's not because of favicon.ico not being in /.

**Comment by Chris00** [comment]
I do not see how the section you point to supports your claim.  Before in the article, they say ”_Originally_, the favicon was a file called favicon.ico placed in the root directory [...]” (emphasis mine).  I do not think there is still any restriction nowadays.

**Comment by dbuenzli** [comment]
@Chris00 is right you can just put the link to the icon in a `meta` tag. However what happens in practice is that some of the browsers/bots out there arbitrarily query the directory structure of an URL for favicon up to the root. This results in a lot of 404 in your logs. To remove that noise I added the following rewrite to my own site:

```
RewriteCond $0 !images/e-small.png
RewriteRule ^([^/]+/)*favicon\.ico$ /images/e-small.png [L,R=permanent]
```

**Comment by pw374** [comment]
Sorry it's the next section http://en.wikipedia.org/wiki/Favicon#How_to_use
"favicon.ico located in the website's root: yes yes optional optional yes"

> I do not think there is still any restriction nowadays.

I investigated that because on Safari there is currently no working favicon for me.

Perhaps it's just my Safari that's broken for some obscure reason.

**Comment by pw374** [comment]
Now I'm suspecting that it's because we're using rel="shortcut icon" instead of rel="icon".

opam.ocaml.org uses `<link rel="icon" type="image/png" href="ext/img/favicon.png"/>` and it works with my browser.

**Comment by Chris00** [comment]
> "favicon.ico located in the website's root: yes yes optional optional yes"

I think it means that, if you put it in the root directory, you do not need to put the `<link>`.  Accoding to the page, the `<link>` that we have should work for safari.

**Comment by pw374** [comment]
> > "favicon.ico located in the website's root: yes yes optional optional yes"
> 
> I think it means that, if you put it in the root directory, you do not need to put the `<link>`.  Accoding to the page, the `<link>` that we have should work for safari.

Sorry for the wrong diagnostic.

p.o.o is using `<link href="/img/favicon.ico" rel="shortcut icon"/>`
Now I suppose it's either `rel="shortcut icon"` that's not working, or `type=something` that's missing...

**Comment by Chris00** [comment]
What happens if you point your browser to http://preview.ocaml.org/img/favicon.ico ?  Do you see the icon?

**Comment by pw374** [comment]
> What happens if you point your browser to http://preview.ocaml.org/img/favicon.ico ?  Do you see the icon?

This works and I see the icon.

I didn't expect this:

```
$ file ocaml.org/img/favicon.ico 
ocaml.org/img/favicon.ico: MS Windows icon resource - 1 icon
```

**Comment by pw374** [comment]
On my other machine (still using Safari), it works, but I don't know if it's thanks to `type="image/x-icon"` or if it already worked before... Thanks anyway.
