### ISSUE TITLE
fix link to jobs mailing list

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#28]
Link to [subscribe](https://sympa-roc.inria.fr/wws/info/ocaml-jobs) to ocaml-jobs mailing list is asking for username and password. This must be an error. Contact server maintainer and provide link again, which was removed in commit b3e084bfddefa0942caddb27d29881648e597976.

**Comment by eelsther** [comment]
I contacted Maxence Guesdon which announced the newly created mailing list back in 2007.
I hope I will get an answer soon.

**Comment by eelsther** [comment]
I got an answer. The link is fixed: commit 1e9100c
