### ISSUE TITLE
Learn page typos and layout

### ISSUE THREAD

**Issue by avsm** [ocaml/v2.ocaml.org#280]
"OCaml is a general purpose industrial-strength programming language with an emphasis on expressiveness and safety. Used in environments".  The "Used" is at the start of a sentence and is a bit of an awkward hyperlink.

The layout is also not very nice here, since the bottom border of "Code Examples" and "Tutorial" don't have enough of a bottom margin to put the border above the text.

**Comment by amirmc** [comment]
Agree about the sentence. Don't quite understand the last comment though ("...to put the border above the text").  Which border above what text?  I can see that there isn't enough space between the horizontal rule under "Code Examples" and the code block beneath (same issue for "Tutorials and FAQ" and "Books").  Is that what you meant?

**Comment by avsm** [comment]
Yep. The layout at the top is also odd -- the "Learn" seems to take up a lot of space and the OCaml logo and "What is OCaml" don't line up.  Also the Download button is a little lonesome on the right and also doesnt line up.  Where's the grid? :-)

**Comment by Chris00** [comment]
I tried to improve the layout.  I also used the font page logo (as for the community page) because there are already many colors on the "Learn" page.  Finally, I put the two book covers next to each other (was not the case for certain page widths).

There is still the sentence to modify.  I leave that to a native English speaker.

**Comment by Chris00** [comment]
@avsm Are there points still to be dealt with or can we close the issue?

**Comment by agarwal** [comment]
I think it's complete.

**Comment by avsm** [comment]
That looks really excellent now, thanks!

**Comment by agarwal** [comment]
Okay, so I'm closing it.
