### ISSUE TITLE
Syntax highlighting: parsing error

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#281]
The second solution on the page http://preview.ocaml.org/learn/tutorials/99problems.html shows the error

<pre>
Characters 2:9 - 2:11 :
Error: Lexical error while reading an operator
</pre>

instead of the colored code.

**Comment by Chris00** [comment]
Note it does not occurs in https://github.com/ocaml/ocaml.org/tree/pbm because I used the old engine.  Eventually though, the two must merge.

**Comment by pw374** [comment]
`ocamltohtml` can be easily replaced, and I don't mind replacing it (with the "old engine" or something else).

**Comment by Chris00** [comment]
I propose to use the "old engine" for now.  An OCaml library to syntax highlight the code could be nice (possibly based on compiler libs).

**Comment by pw374** [comment]
I concur.

**Comment by Chris00** [comment]
OK.  I will close this issue then and open one for the library.

**Comment by pw374** [comment]
thanks!
