### ISSUE TITLE
Track the use of ```tryocaml

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#282]
The code blocks

``````
```tryocaml
``````

(which requests the code to be evaluated by the toploop) have been misused at many places which implies (currently in the `pbm` branch, were the code is actually eval) that many of these blocks are marked with some red syntax error.  One must track down the use of such blocks and fix them.

Note that the following languages have been used:

``````
```C
```assembly
```shell
``````

**Comment by amirmc** [comment]
`````` text
AmirMacBook:site amir$ grep '```tryocaml' -R . | wc -l
grep: ./caml-light/releases/index.md: No such file or directory
     921
AmirMacBook:site amir$
``````

I think we should wait until `pbm` is merged and then figure out how to resolve this one.  tryocaml was something that @pw374 was working on (to have an interactive toplevel on the page).

**Comment by amirmc** [comment]
Essentially we're going to need three variants of OCaml code blocks
1. One that just does syntax highlighting (i.e  ````ocaml`)
2. One that runs the code through toplevel and pulls in the output (currently  ````tryocaml`)
3. One that gives you an interactive toplevel in the browser a la try.ocamlpro.com (e.g  ````ocamlapplet`)

**Comment by samoht** [comment]
This sounds a bit weird. The tryocaml tag should be the 3. and 2. should be called something like "toplevel" (and you might want to execute some consecutive tryocaml and toplevel blocks in the same session)

## 

Thomas

**Comment by pw374** [comment]
I agree. The current _real_ problem is that 2. and 3. are using the same tag.
The naming is just a minor issue.

**Comment by amirmc** [comment]
:) Yes, tryocaml was meant to be 3 but is now being used as 2.  

I'd much rather we create a clear separation between the three use cases, regardless of names, and then do a find/replace to things that make sense in the long term.

**Comment by Chris00** [comment]
Well, I kept it for 2 because one can do an automatic transformation later (when building the site, I do not mean changing the files).  Now, if some evaluations should remain static (that may make sense for the tutorial pages), one can do the transformation in the `pbm` branch which incidentally will show that the use has been verified (I propose to use `ocamltop` for the toplevel which is precise and short).

**Comment by Chris00** [comment]
I enabled 2eb449dd985b24f89e922205a78e38d0ff080e0c

``````
```ocamltop
``````

At the moment both

``````
```tryocaml
``````

 and

``````
```ocamltop
``````

are passed through the toplevel but that is just a matter of changing `md_preprocess`.

**Comment by Chris00** [comment]
I think enough cases have been corrected to remove the  _blocking_ flag.  The bug is not completely fixed yet though.

**Comment by amirmc** [comment]
Fantastic! Then the only thing left is to merge branches and alter the DNS.  We'll do that around 10:30am UK time .
