### ISSUE TITLE
Black bars on the banner sides

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#283]
When the browser window is "large", the banner has black bars on each side.
![oo](https://f.cloud.github.com/assets/1255665/1567356/03b4ae44-509d-11e3-92d9-21dc18d84924.png)
Is this desired?

**Comment by amirmc** [comment]
Nope, but I think it's due to the image itself (i.e that's how big it is -- if we stretched it to fit, then it might look odd due to the camel).

**Comment by Chris00** [comment]
I guess one should glue 3 versions of it, flipping those to the left and right of the original one.  In the meantime I changed the bg of the image so that the bars are the same color as the navbar 76fd5e38dbbf159c313ad6ab2b671a7c18c1bf7e

**Comment by pw374** [comment]
> In the meantime I changed the bg of the image so that the bars are the same color as the navbar 76fd5e38dbbf159c313ad6ab2b671a7c18c1bf7e

Hmmm... Before, it was kind of wrong... Now it's kind of weird. I'm not sure which one is worse.

**Comment by amirmc** [comment]
Christophe's suggestion to glue 3 versions of it is probably the best one.  I suspect we'll get a new image eventually.

**Comment by Chris00** [comment]
See the branch `banner` and let me know what you think.  If it is still odd (I think it is a little), one may want to ask the design company to work on it a little more ([very high resolution screen](http://shop.lenovo.com/us/en/laptops/thinkpad/w-series/w540/?tt=c#techspecs) are coming on laptops)

**Comment by pw374** [comment]
It's nicer than both previous versions :)
However it's indeed a little odd, especially on the right side.

**Comment by pw374** [comment]
![screen shot 2013-11-18 at 23 36 23 pm](https://f.cloud.github.com/assets/3776012/1568540/9717c602-50b2-11e3-9b59-aabcd65d8f21.png)

**Comment by amirmc** [comment]
Camels everywhere!  Way better than the current version. I say merge it.

**Comment by pw374** [comment]
> Camels everywhere!  Way better than the current version. I say merge it.

I agree.

**Comment by agarwal** [comment]
Now, can you make them walk across the screen.  :)

**Comment by amirmc** [comment]
Careful. @lpw25 may hear you (pretty sure that's been his most requested feature)

_edit: oops_ ;)

**Comment by Chris00** [comment]
Merged 87c01eededa781a52674e0b660f7a1db2f30ac75
