### ISSUE TITLE
Installation instructions are out of date

### ISSUE THREAD

**Issue by yminsky** [ocaml/v2.ocaml.org#284]
- [x] Wrong reference to _latest_ release. Done in a3193542c74d840d35584a466d7370dbfe84c714.
- [x] Remove references to GODI since it is discontinued. Done in 5e887e4c4a373062aa12662a0bec9bba21939b59.
- [x] Fix broken images at the bottom. Done in d2cd121145dbbec72ae77ad4f9277b1705ed235b.
- [x] Restructure to make sections more clear. Done in 30386eabe1256e90d493bfaffe954541e67f19fc.
- [ ] Mac section should have a Homebrew sub-section.

@yminsky Original report:
Right now they mention 4.00.1 rather than 4.01.0.  It also has a bunch of broken image links at the bottom.

It also spends a ton of time on fink, without spending any time on homebrew, which is pretty much the best option on the mac.

It's possible a complete rewrite is in order... I wonder if the install instructions from RWO might be of some use to steal information from:

https://github.com/realworldocaml/book/wiki/Installation-Instructions

**Comment by XDeschuyteneer** [comment]
this page: http://preview.ocaml.org/docs/install.html
got some deadlinks: http://preview.ocaml.org/docs/img/under_construction_icon.gif
it begin from Oasis-DB til the end. The under construction icon return a 404 not found error.

**Comment by agarwal** [comment]
I've made a few minor improvements and editing the main description of this issue to track what else can be done.

**Comment by dbuenzli** [comment]
I think this issue can be closed.

**Comment by dbuenzli** [comment]
(By https://github.com/ocaml/ocaml.org/pull/829)
