### ISSUE TITLE
support multiple targets in Makefile

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#287]
It seems we need the following 3 Makefile targets:
- `all` - Generates the site as needed for pushing to the production server.
- `preview` - Generates site for previewing locally. Differs from `all` because it modifies URLs to be relative.
- `staging` - Generates site as needed for pushing on `staging.ocaml.org` (or whatever domain name we decide). This differs from the production site in the following ways:
  - Should include a robots.txt file telling robots to ignore entire site.
  - Should exclude Google Analytics tracking code. There is no other way to configure Analytics to avoid tracking a subdomain, except to not include the tracking code ourselves.

Does this sound right?

**Comment by amirmc** [comment]
Sounds reasonable to me.  We don't have a staging server yet but will need that target when we do.  We'll continue with the current VM as the production server for now.

**Comment by agarwal** [comment]
Okay, so I prefer the following target names instead of what I said above: `production`, `local`, `staging`. These correctly reflect the point of each target.

I don't know yet how to implement `staging` as it requires some MPP skills I don't have yet. @pw374 It'll be great if you can give me some hints.

**Comment by pw374** [comment]
> I don't know yet how to implement `staging` as it requires some MPP skills I don't have yet. @pw374 It'll be great if you can give me some hints.

I would edit main.mpp and add 

```
((! ifndef staging
<here the code for google analytics>
!))
```

and then when generating "staging", call mpp with the additional option `-set staging`.

**Comment by Chris00** [comment]
I guess `local` should be the default target to ease contributing — the other targets will be used in specific contexts only.

**Comment by agarwal** [comment]
Yes, I was just thinking that too. I'll put at the top.
Edit: done in c9ff90e4b13feeaf5a1f62cbdfd7110f5c8a808a.

**Comment by agarwal** [comment]
Done in 3d017d04bc7197077af03d57ee33ef368b5fdd4f, 1ad1d006893a45594e579113d64e6b4202187513, and cbf339adf2956cfbfb79ab1d7708b6ce042dcf74.
