### ISSUE TITLE
build of `caml-light/releases/index.html` fails

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#289]
I just noticed this error, which I think was happening all along. Redirect stdout to see it:

```
$ make local 1> /dev/null 
make[2]: *** No rule to make target `site/caml-light/releases/index.md', needed by `ocaml.org/caml-light/releases/index.html'.  Stop.
```

**Comment by Chris00** [comment]
One additional reason to have the build system fail early!

**Comment by pw374** [comment]
This has something to do with `site/caml-light/releases/index.md' being a symbolic link I guess...

Philippe Wang
(mail sent from a phone)

**Comment by Chris00** [comment]
@pw374 the problem was not that it was a symlink but that the symlink was pointing to a non-existent file!
