### ISSUE TITLE
titles are broken in many places

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#292]
e.g http://preview.ocaml.org/community/support.html

I've seen this kind of error in a couple of places (e.g taste.md) and it's sometimes related to ToC.

cc @pw374 in case this is an omd/mpp thing

**Comment by pw374** [comment]
It should be fixed as soon as omd.0.7.3 is installed and used.

**Comment by pw374** [comment]
I believe it's been fixed now.

**Comment by amirmc** [comment]
Yup! Fixed in another place I just saw so closing this now. Thanks!

**Comment by Chris00** [comment]
It was fixed in d07e71e86c968c74e81c3e023874a190a437d168 (adjusting the trick so that anchors do not get hidden underneath the navbar).
