### ISSUE TITLE
make clean and tools

### ISSUE THREAD

**Issue by pw374** [ocaml/v2.ocaml.org#295]
It should be easier to delete the generated binaries for tools (`make clean` or `make mrproper` or whatever)

**Comment by Chris00** [comment]
May you be more specific?  What generated binaries are left after `make clean`?

**Comment by pw374** [comment]
sorry for the noise, I guess I didn't see https://github.com/ocaml/ocaml.org/commit/b3fbab945cfe200c70710fa371c44de6596935b6

**Comment by Chris00** [comment]
No problem.
