### ISSUE TITLE
some company logos broken

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#296]
In companies.html, some of the links to company logos are broken.

**Comment by amirmc** [comment]
That's frustrating. I thought I'd added as many logos as I could find and then used a faded OCaml logo as a 'default' for the few companies remaining.

**Comment by amirmc** [comment]
They got changed in https://github.com/ocaml/ocaml.org/commit/ef98fa63dc4535592f8b8307bd58fc7da6c504e2 So changing them back is probably best. I couldn't find logos for those (though Psellos does have one it was really small by comparison).

**Comment by pw374** [comment]
Sorry, my bad, I thought I undid those bad changes!

**Comment by pw374** [comment]
I've just [undone](https://github.com/ocaml/ocaml.org/commit/4eb60d4984bc71cb6b26d1400d105c1620ef7f6d) my bad changes, and then [fixed a link](https://github.com/ocaml/ocaml.org/commit/dfcf8b7c8a11b44126a083ab7838bf095dfd076c).

Now there's no more broken logos on that page.
