### ISSUE TITLE
Clickable section headers

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/v2.ocaml.org#298]
I'm just going through preview.ocaml.org and it looks really good, congratulations for all the work on the site. 

On [this](http://preview.ocaml.org/docs/) page, in the _Video_ section a link _See more videos_ is needed as it's not obvious that the header is clickable. 

More generally the site is very inconsistent with header clickability. E.g. on [this](http://preview.ocaml.org/learn/) page why is the _Books_ header non clickable while _Videos and slides_ is ? I think some convention should be enforced. I would suggest to aways have the header clickable, leading to the same page as the _More of this_ link ending the corresponding section.

**Comment by amirmc** [comment]
I agree with your main point and I've (slowly) been adding links. However, that 'Books' links should read 'Books and Papers' which should each be linked elsewhere. I don't know why this hast appeared on preview.

**Comment by amirmc** [comment]
I've gotten myself confused between the. Learn and Docs page.  I'll  update the former.

**Comment by agarwal** [comment]
Only item remaining here is: on the Documentation page, the Videos section should end with a "See more videos" link that goes to the same place the Videos header does.

**Comment by agarwal** [comment]
I think this is complete now, so closing.
