### ISSUE TITLE
30mins.html: page is empty

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#3]
Unless we have a readily available 30 minute tutorial, we should probably delete this empty page. The link to try.ocamlpro.com kind of covers the intended purpose of this page already.

**Comment by Chris00** [comment]
I do not (and do not have time to write one).  I think the page should go.

**Comment by Chris00** [comment]
There is this http://www.csc.villanova.edu/~dmatusze/resources/ocaml/ocaml.html  Maybe it is OK with some adaptations?

**Comment by agarwal** [comment]
I think this link could go in the tutorials page, and we should just delete the 30mins.html page.

**Comment by Chris00** [comment]
I have done so.  Commits 019a308 and 7fe823a7cd
