### ISSUE TITLE
link to Inria's RSS feed

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#30]
Should the Inria [RSS Channel](http://caml.inria.fr/news.en.rss) be displayed on front page somewhere? Unlike current News section, it has only small news items. Alternatively, perhaps it should just be added to the Planet, which it currently appears not to be.

**Comment by Chris00** [comment]
See commit 6dd291b8e111bcb610ee99c790da165cac88fd44 and http://ocamlweb.forge.ocamlcore.org/www/
There was no real change for this — the code developed was general enough.

If you agree with the modification, I'll close the issue.

**Comment by agarwal** [comment]
Looks great!

**Comment by Chris00** [comment]
BTW, even if it was added to the planet, it would be good to have it separately on the front page because there are few of Inria news and they would quickly get lost in the other news — they are important enough to be visible for a longer time...

**Comment by agarwal** [comment]
Agreed.

**Comment by Chris00** [comment]
It seems Inria is in the subscritions http://ocamlweb.forge.ocamlcore.org/www/planet/
If duplicate news turn out to look "nonprofessional" one can easily filter out Inria.
