### ISSUE TITLE
automatic building process stopped until we make `redesign` live (or until something else)

### ISSUE THREAD

**Issue by pw374** [ocaml/v2.ocaml.org#302]
Just to let you know that I've stopped the automatic building process.

It should be reactivated in less than 2 hours no matter what happens (i.e., even if redesign is not merged to master).

**Comment by amirmc** [comment]
ref #184

**Comment by agarwal** [comment]
I've also stopped auto-building to gh-pages. It was about to get run and the new site would have been live before @amirmc intended!

**Comment by pw374** [comment]
preview.ocaml.org is not and will not be updated anymore.
(Note that preview.ocaml.org does not and shall never have the Google Analytics code.)

The automatic build process on 166.78.252.20 (i.e., the VM serving preview.ocaml.org and the future ocaml.org) is now building the website from the master branch (not the redesign one). If you connect to 166.78.252.20:80 using preview.ocaml.org then you get a website that's not updated anymore. Else, you have the new site.

This means that as soon as the DNS entry for ocaml.org is updated, ocaml.org will be serving the new site!

**Comment by agarwal** [comment]
Hasn't made it to this side of the ocean yet. I'll let you know as soon as it does!

**Comment by pw374** [comment]
I edited my /etc/hosts for convenience...

**Comment by Chris00** [comment]
Maybe one can delete the `gh-pages` branch and close this issue?

**Comment by agarwal** [comment]
@amirmc wanted to leave the gh-pages branch for a few days to make sure DNS propagation completes. I think it should be good by now. @amirmc if you confirm, I'll delete the branch.

**Comment by amirmc** [comment]
I think it's been long enough and we can get rid of the gh-pages branch. I've looked back at the commit logs for `master` and I _believe_ the last commit before merging the `redesign` branch was https://github.com/ocaml/ocaml.org/commit/bdb40490ddb1a5316fba0446d81a094507f61229 (on 1 Nov 2013)

In other words, if we ever need to go back and look at the previous website, cloning the repo and resetting to the above commit should be sufficient.

**Comment by amirmc** [comment]
In any case, this issue can be closed (so I'll do that now) but both #184 and #151 can be closed once the `gh-pages` branch is actually gone.
