### ISSUE TITLE
sharing news on twitter?

### ISSUE THREAD

**Issue by pw374** [ocaml/v2.ocaml.org#303]
I was asked why we didn't have Twitter sharing buttons to go with the news...
(e.g., http://ocaml.org/community/planet.html)

**Comment by agarwal** [comment]
We should.. and we have taken [ownership of social media accounts](https://github.com/ocaml/ocaml.org/wiki/Assets) in anticipation of this.

**Comment by agarwal** [comment]
But also I don't think we need such accounts to add certain such features.

**Comment by amirmc** [comment]
For sharing, we shouldn't need the ocamlorg accounts.  However, I do feel we should have a two-click system of some kind.

http://ux.stackexchange.com/questions/20751/why-did-they-use-two-stage-social-media-sharing-buttons

**Comment by pw374** [comment]
We could also use simple links (to pop-ups) that can't be automatically tracked.
http://www.facebook.com/share.php?u=http://ocaml.org/name_of_the_page.html
http://www.twitter.com/home?status=http://ocaml.org/name_of_the_page.html

**Comment by Chris00** [comment]
The solution of @pw374 look the easiest to me.  The question is more: which link do we share next to the user stories?  It would be nice to share ocaml.org link but the problem is that the link disappears after some time.

**Comment by pw374** [comment]
Is it normal that the link to share on G+ shares the URL of the original post, whereas the FB and Twitter ones share the ocaml.org link?

**Comment by Chris00** [comment]
> Is it normal that the link to share on G+ shares the URL of the original post, whereas the FB and Twitter ones share the ocaml.org link?

This is wanted (for now).  I did it this way so it is discussed (and also because the G+ link does not allow to set a title).
