### ISSUE TITLE
Validator.w3.org compliance failures

### ISSUE THREAD

**Issue by avsm** [ocaml/v2.ocaml.org#305]
There are quite a few (minor looking) failures from running the W3C validation service. See:

http://validator.w3.org/check?uri=http%3A%2F%2Fwww.ocaml.org&charset=%28detect+automatically%29&doctype=Inline&group=0

**Comment by Chris00** [comment]
I fixed the images in the HTML generated by the script `rss2html`. 199aaed1ca4158f41577ad83f6907e9189292277
