### ISSUE TITLE
docs/papers.html is broken

### ISSUE THREAD

**Issue by samoht** [ocaml/v2.ocaml.org#307]
Everything is in the title. The broken page: http://ocaml.org/docs/papers.html

**Comment by Chris00** [comment]
1st: upgrade `omd` on the server.

**Comment by pw374** [comment]
At first sight, I don't understand that output, since `omd` is up-to-date on the server.

```
$ omd -version
This is version 0.7.4 of Tue Nov 19 22:04:16 UTC 2013.
```

**Comment by Chris00** [comment]
On my local copy, I do not have the same output.  In any case I am going to transform them to lists as it is easier to spot the different items.

**Comment by pw374** [comment]
I suspect that you have a tool that uses omd, but isn't recompiled using current version of omd...

**Comment by pw374** [comment]
It was `script/md_preprocess` that wasn't recompiled...
