### ISSUE TITLE
Implement a link checker

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#309]
This has come up on several occasions (see below).

Some considerations are: 
- At what point do we run the checker? During the build process makes sense as we'd be alerted to any content that disappears elsewhere.  However, it seems impolite and wasteful to hit a potentially large number of external sites on _every_ build.
- To whom do these broken links get reported to and how?  If it's part of the build then it's just console output.  If not (i.e lives and runs elsewhere), then someone needs to be notified.

Mentioned in issues #12, #90 and #305 and probably others.

**Comment by dsheets** [comment]
#111 ?

**Comment by amirmc** [comment]
> - To whom do these broken links get reported to and how?

If we're getting fancy then we could have a bot make a comment on a Pull Request/Commit with a list of any broken links in files that are part of that commit.

**Comment by amirmc** [comment]
Thanks @dsheets!  Complete brain-freeze when looking for an existing issue. :)  Closing this as a duplicate.
