### ISSUE TITLE
import Hundred Lines of OCaml

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#31]
[A Hundred Lines of OCaml](http://caml.inria.fr/about/taste.en.html) could be good to include under the Discover section. This perhaps nicely fills the role of the previously desired Ocaml in 30 Minutes page.

**Comment by Chris00** [comment]
Done: d9e19e6fd307c2798518f9b76d1fb2798326b15b and 11262abd340797ebe57c04151d4444b8e2c517bc

However, ti would be nice if the output was generated directly by OCaml when compiling the site.

**Comment by agarwal** [comment]
Do you mean a feature like this one:
http://zoggy.github.com/stog/posts/displaying-evaluated-ocaml-code.html

**Comment by Chris00** [comment]
Exactly.  I'll see what I can do to have the same functionality without introducing new tags (they may be messed up by visual editors).

**Comment by Chris00** [comment]
Code evaluation in place.  52e1a276cdcfbc53ba8414aa02a626295361166d
Requires the the latest weberizer (constraint in _oasis).
