### ISSUE TITLE
Should we find a place for articles about OCaml?

### ISSUE THREAD

**Issue by yminsky** [ocaml/v2.ocaml.org#311]
I think it might be a nice place for articles on the "Learn" page.

OCaml for the masses: http://queue.acm.org/detail.cfm?id=2038036
Xen and the art of OCaml (slides): http://cufp.org/archive/2008/slides/MadhavapeddyAnil.pdf
Programming the Xen cloud using OCaml: http://oud.ocaml.org/2012/abstracts/oud2012-paper14.pdf
Ocaml for an industrial strength static analysis framework:
http://dl.acm.org/citation.cfm?id=1596591
Caml Trading: http://journals.cambridge.org/action/displayAbstract?fromPage=online&aid=1899164
Industrial uses of OCaml: examples and lessons from the smart card industry: http://dl.acm.org/citation.cfm?id=1362704

Not sure what else would be worth linking to.

**Comment by avsm** [comment]
Some more, from polling CUFP talks

From OCaml to Javascript at Skydeck (Jake Donham)
http://cufp.org/archive/2008/slides/DonhamJake.pdf

Acunu and OCaml status report:
http://www.slideshare.net/acunu/acunu-ocaml-experience-report-cufp

Some uses of Caml in industry
http://cufp.org/archive/2007/slides/XavierLeroy.pdf

CUFP Camlp4 metaprogramming tutorial
https://github.com/jaked/cufp-metaprogramming-tutorial

Functional Programming in Freebase
http://cufp.org/videos/functional-programming-freebase-warren-harris-metaweb

**Comment by agarwal** [comment]
The page exists [here](http://ocaml.org/docs/papers.html) and is linked from the [Documentation](http://ocaml.org/docs/) landing page. I think there's a general issue about deeper pages not being so easy to find. I'll open a separate issue about that, and leave this issue open so we remember to add all the extra papers mentioned.

**Comment by agarwal** [comment]
Regarding the issue of not being able to find the page, I think #257 will be the solution, so not opening a new issue about this.
