### ISSUE TITLE
Uncentered content pages

### ISSUE THREAD

**Issue by Drup** [ocaml/v2.ocaml.org#313]
The content page (like [this one](http://ocaml.org/learn/tutorials/)) are badly centered, which feel weird. They may be supposed to be aligned to right, but it would probable be even worse for readability.

Also, the reactive part is done in a very strange way, the left margin grows with the screen size. 
Basically, it needs checking, since I don't think it's the intended behavior.

**Comment by Chris00** [comment]
Not completely happy with the changes — but open for comment.

**Comment by Chris00** [comment]
For the [OCaml tutorials](http://ocaml.org/learn/tutorials/) page, I think this is because the long list was on a single column.  I feel that putting it in two columns solves the weirdness problem.
