### ISSUE TITLE
Quick access to internal sections

### ISSUE THREAD

**Issue by Drup** [ocaml/v2.ocaml.org#314]
It may be good to add some quick access to internal sections by adding an submenu unrolled by a button next to the main section.
I think it would simplify the navigation quite a lot, and make it quicker.

**Comment by agarwal** [comment]
Issue #257 proposes adding a sitemap to the footer. Would that resolve this issue? If so, please close this one as a duplicate.

**Comment by Drup** [comment]
I would find it more convenient to have it into some menu in the navbar. Clutter each page with a huge footer is not a great solution.

**Comment by agarwal** [comment]
There is significant opposition to having any dropdown menus. I'll leave
this issue open, so it can be kept in mind, but I suspect there will not be
consensus on this.

**Comment by Drup** [comment]
Care to explain why ? If it's an accessibility issue for phone/tablets, you already have a different menu layout for them, so it doesn't change anything.

**Comment by agarwal** [comment]
There was some discussion in [this thread](http://lists.ocaml.org/pipermail/infrastructure/2013-August/000239.html). You can see there were people strongly opposed and some who didn't understand the opposition (like me). Those opposed felt more strongly about not having them than those in favor did about having them. Thus, in the end, the decision was made to avoid dropdowns entirely.

**Comment by Drup** [comment]
The argument I gave about drop down converted to list in phone layout was already made in this thread ... and not answered. :/ 
@avsm @amirmc ?

**Comment by agarwal** [comment]
Links have been added to the footer, and there is still opposition to dropdown menus. Thus, I consider this issue closed.
