### ISSUE TITLE
Recent opam packages updates

### ISSUE THREAD

**Issue by Kakadu** [ocaml/v2.ocaml.org#317]
Can be found at the bottom of http://ocaml.org page

1) Maybe, it will be great to have link to longer list of recent updates
2) If we will click in tab header `Recent updates`  we will be redirected to the top of the page using anchor. Now, if we will scroll down we will see that tab header is visible only when mouse is hovering it. If we move mouse out --- it is invisible.

**Comment by pw374** [comment]
@Kakadu  Thanks for your feedbacks, I hope I've fixed the issues. If not, please reopen this issue.
