### ISSUE TITLE
Problem with "follow in new tab" (Firefox)

### ISSUE THREAD

**Issue by bienvenu** [ocaml/v2.ocaml.org#320]
Sorry for noticing it only now, but I have a problem with the new website.

I first noticed this problem because when using Vimperator, following a link in a new tab (by pressing `F`) doesn't work. However, following the link in the same tab (by pressing `f`) works all right.

I thought it was a Vimperator related issue, but:
- The OCaml website is the only website on which I'm experiencing this problem (except for a few flash laden websites which do not work well in Vimperator anyway).
- Further testing led me to try using my mouse and it turns out that "follow in new tab" by pressing the middle mouse button doesn't work either.

This is obviously a really minor issue, but still, it can be annoying for people who make extensive use of tabs.

If someone wants to confirm the problem and/or see whether it has to do with my browser, I'm using  Iceweasel 17.0.10.

PS: I've just tested and the problem is not present in the Debian-shipped version of Chromium. Still, if it is present in the Debian-shipped version of Firefox, it's likely that many people are going to experience it. And even if the problem comes from Firefox, there is still the question of why I'm having it only on the OCaml website.

**Comment by bienvenu** [comment]
I have just checked on my room-mate's computer and it works fine with the middle-button click in Firefox 25.0.1 (on Windows)

I'll ask more friends to see if it's an "old version of Firefox" issue, or a "Debian-induced" or "Vimperator-induced" problem with Firefox.

Sorry if it turns out to be a browser-related issue.

**Comment by lamarqua** [comment]
I have exactly the same problem on Firefox ESR (17.0.11): middle-click doesn't work (but right-click, open in new tab does). It's very annoying.

**Comment by amirmc** [comment]
> Sorry if it turns out to be a browser-related issue.

Even if it turns out to be a browser issue, it's helpful for others to know (and find) this thread :)

FWIW we're using Bootstrap v2.3.1 so a quick search led me to https://github.com/twbs/bootstrap/issues/7118.  Is this relevant?

**Comment by amirmc** [comment]
Skimming the issue linked above, I think this is a bootstrap issue, so it's something we should fix here.  Since we don't use dropdowns anywhere on the site (and I don't think we should) I suspect we can comment out the following line without ill effects.

``` js
.on('click.dropdown-menu', function (e) { e.stopPropagation() })
```

@Chris00, @agarwal do you have any comments?

**Comment by lamarqua** [comment]
According to the issue you linked, they fixed this in 2.3.2: https://github.com/twbs/bootstrap/issues/7118#issuecomment-18075260

**Comment by agarwal** [comment]
I don't have a middle mouse button, but I tried the Command-left click on my Mac with Safari, Chrome, and Firefox. In all cases, the link opens in a new tab without problems.

**Comment by Chris00** [comment]
@bienvenu Does it happen when you compile the site locally on your machine?  If so, may you test the above suggestion?

**Comment by bienvenu** [comment]
@Chris00 I'll try to help but I'll need some instructions because I've no idea about what's bootstrap and how it works.

So, here is what I did:
- I compiled the site locally on my machine. Everything went fine but the middle-click didn't work.
- I tried to comment out the line mentioned. Since it wasn't present in the ocaml.org-master folder, I assumed it must be somewhere in bootstrap, so:
- I downloaded bootstrap 2.3.1 source code from git, commented out the `.on('click.dropdown-menu', function (e) { e.stopPropagation() })` line of bootstrap-dropdown.js, and then installed bootstrap as indicated in the doc
- I recompiled the site. Middle-click didn't work, so I assumed I hadn't used bootstrap correctly
- Tried various, not-so-rational stuff such as pasting the modified bootstrap-dropdown.js file in the js folder of ocaml.org-master
- Thought I'd ask your advice since you know how bootstrap should  be used

**Comment by Chris00** [comment]
This project does not depend on an external bootstrap file — the requirements are listed in the README file.  What comes from the bootstrap project is the file `site/css/bootstrap.css`.  You can start by commenting out the whole file and then uncomment progressively until the problem shows up.

**Comment by bienvenu** [comment]
@Chris00 Ok, I'll try to do that over the weekend.

So far, I've commented out every single element containing `dropdown` (since `click` and `stopPropagation` are not in the file) but it didn't work.

**Comment by bienvenu** [comment]
I've just deleted bootstrap.css (and then bootstrap_mod.css) and it's still not working

**Comment by Chris00** [comment]
Then try with `site/css/ocamlorg.css`...

**Comment by bienvenu** [comment]
Removing the `<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>` line in index.html seemed to solve the problem. Removing the .css files or anything else I tried did not.

**Comment by Chris00** [comment]
Thanks for your help!

I am not sure it has any use but I let the others comment as it is in the template since the beginning.

**Comment by Chris00** [comment]
BTW, one could wonder the same for `<!--[if lt IE 9]>`...

**Comment by bienvenu** [comment]
Hi, 

I think the problem has reappeared. Could someone confirm ?

**Comment by Chris00** [comment]
The problem is that, without the Google Ajax code, the collapsed menu does not open which is even worse.  One should isolate the part that is required and host it ourselves.  Your help is welcome!

**Comment by Chris00** [comment]
I changed the URL of `jquery` — let me know if it makes a difference.

**Comment by bienvenu** [comment]
I'm afraid it does not.

I'll try to help as soon as I have some spare time !

**Comment by Chris00** [comment]
Please test again.

**Comment by bienvenu** [comment]
It's working ! =)
