### ISSUE TITLE
robots.txt

### ISSUE THREAD

**Issue by pw374** [ocaml/v2.ocaml.org#327]
http://ocaml.org/robots.txt is missing

edit: summary of the discussion: **we won't have any robots.txt**

**Comment by agarwal** [comment]
That's correct. We want the entire site indexed, so no need for one. It should be present on our staging site, which I see it is [here](http://preview.ocaml.org/robots.txt).

**Comment by agarwal** [comment]
Ah but, the one on preview.ocaml.org is the wrong one. I guess it's okay since we're getting rid of that URL (hopefully soon before Google picks it up).

**Comment by pw374** [comment]
> That's correct. We want the entire site indexed, so no need for one. It should be present on our staging site, which I see it is [here](http://preview.ocaml.org/robots.txt).

I think it's considered a bad thing not to have a robots.txt file, in any case.

> Ah but, the one on preview.ocaml.org is the wrong one. I guess it's okay since we're getting rid of that URL (hopefully soon before Google picks it up).

I'm going to put a (permanent) redirection from preview.ocaml.org to ocaml.org in the next few minutes.

**Comment by amirmc** [comment]
> I'm going to put a (permanent) redirection from preview.ocaml.org to ocaml.org in the next few minutes.

Was just typing to recommend we do that :)

(from [Google Webmaster](https://support.google.com/webmasters/answer/156449?hl=en))

> You need a robots.txt file only if your site includes content that you don't want search engines to index. If you want search engines to index everything in your site, you don't need a robots.txt file (not even an empty one).

So we don't need a robots.txt

**Comment by pw374** [comment]
> > I'm going to put a (permanent) redirection from preview.ocaml.org to ocaml.org in the next few minutes.
> 
> Was just typing to recommend we do that :)

Done (a few minutes ago).

I also added a bunch of redirections because I found it very annoying that most entries from https://www.google.com/search?q=site:ocaml.org were leading to 404.

Eventually (e.g., in a few weeks), I believe we can (and perhaps should) get rid of the redirections.

**Comment by pw374** [comment]
Google says not to put any robots.txt when it's meant to be either empty or 

```
User-agent: * 
Allow: /
```

but what about other search engine robots?

**Comment by agarwal** [comment]
Why is redirecting preview.o.o to ocaml.org a good thing? Now we've mixed up two sites that had very different purposes. Shouldn't we just delete preview.o.o right away.

**Comment by amirmc** [comment]
If anyone _has_ linked to preview, they shouldn't have, and now should be directed to the live site intsead.  Yes, we should get rid of the DNS record for it but in the meantime redirecting makes sense.  Preview was always meant to be temporary. Anil's set up a different domain and VM for staging purposes

**Comment by pw374** [comment]
The thing that convinced me of redirecting preview.o.o to o.o is that the former does appear on google.

@avsm can you please delete the DNS entry for preview.o.o?

**Comment by agarwal** [comment]
I'm not too concerned about this, but actually both reasons are to me greater justification for not doing the forward. Google's robot should ASAP start getting 404s for preview.o.o, rather than thinking the URL is still valid. And anyone who linked to preview.o.o should have their link broken because they should never have done that.

**Comment by amirmc** [comment]
I suspect that giving Google 404s is worse than telling them that the site has permanently moved (301 redirect?).   Webmaster tools can help clarify this. (I'm not really bothered about people who may have used the link).

**Comment by pw374** [comment]
If there's a permanent redirect for everything on p.o.o, robots will follow and should record the move.
If it's 404 instead, there's no way of telling if the page has disappeared for good or if it moved or else.
So I'm more in favour of "permanent redirect" than "not found".

**Comment by agarwal** [comment]
"permanent redirect"... Now I am concerned. That sounds completely wrong to me. Why would we want to make preview.o.o a valid URL forever? This is contradictory to your own request that Anil remove the DNS entry, which would make the URL disappear. Am I just misunderstanding something?

**Comment by pw374** [comment]
The "permanent redirect" does not mean that the URL is valid forever.
As soon as the DNS entry is deleted, preview.o.o becomes completely unreachable (and that's very different from 404).

Having a "permanent redirect" tells the bots that they should stop using that URL and use the new location instead. So, it gives a chance to the bots to adjust their data until they realise that p.o.o no longer exists.

**Comment by agarwal** [comment]
Okay, I didn't realize the distinction between 404 and not-reachable was significant here. Got it!

**Comment by amirmc** [comment]
@agarwal You're over-thinking this one ;)

**Comment by agarwal** [comment]
Somebody close this issue, so I can stop wasting my time.  :)

**Comment by amirmc** [comment]
done!
