### ISSUE TITLE
Jane Street entry on success.html should be about Core

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#329]
_(feedback via email)_  
On http://ocaml.org/learn/success.html, Jane Street's entry should be about Core (or other technologies built on/for OCaml).

The rest of the page is product/project oriented so Jane Street as a company seems out of place.

**Comment by agarwal** [comment]
I'm not so sure. The point of the Success Stories is not to emphasize that something good has been done _for_ OCaml but rather _because of_ OCaml. What did Jane Street get out of OCaml? Note Core, that's what they gave.

**Comment by yminsky** [comment]
While we're at it, should we add XenServer work to the list?

**Comment by avsm** [comment]
Definitely.  @djs55 @jonludlam @mcclurmc, could you suggest some text for the ocaml.org website and the Xapi project?

**Comment by jonludlam** [comment]
Good idea. We'll get our heads together and come up with something.

**Comment by avsm** [comment]
I've opened #338 for the XenServer entry, rather than overloading this one about Jane Street

**Comment by Chris00** [comment]
Fixed via 098aba245349f244c97065d59bb0d6831b5c8dfd
