### ISSUE TITLE
import Success Stories

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#33]
Import [Success Stories](http://caml.inria.fr/about/successes.en.html) page from Inria.

**Comment by Chris00** [comment]
A more recent unison screenshot is needed.

**Comment by Chris00** [comment]
A more recent screenshot of Coq is needed.

**Comment by Chris00** [comment]
Several links nedded corection.

**Comment by Chris00** [comment]
Objective Caml → OCaml (was not corrected by Inria).

**Comment by Chris00** [comment]
Done.  22c4697302bc0a1aad2f35521b485c523d7b231f
