### ISSUE TITLE
Get Hack compiler added as success story

### ISSUE THREAD

**Issue by yminsky** [ocaml/v2.ocaml.org#335]
See if we can get Julien Verlaguet to produce some text to describe their project.  It's a pretty great success story for OCaml, after all (even if it does support programming in PHP....)

**Comment by agarwal** [comment]
I sent an email to @pikatchu.

**Comment by agarwal** [comment]
I didn't hear back yet from Julien. I've sent a follow up email just now.

**Comment by agarwal** [comment]
Julien replied and requested that this story not be added at this time. They will reconsider in a few months.
