### ISSUE TITLE
Integration of the Caml Weekly News

### ISSUE THREAD

**Issue by brabalan** [ocaml/v2.ocaml.org#336]
Hello,

The generation process of the Caml Weekly News creates a small file that is automatically integrated in the resources page of the Caml site (at http://caml.inria.fr/resources/index.en.html). Would you be interested in such an integration for the ocaml.org site?

**Comment by agarwal** [comment]
Caml Weekly News is subscribed to the [Planet](http://ocaml.org/community/planet.html), which thus gets picked up on ocaml.org. I think this covers it, but let us know if you think it should also be linked from an additional page?

**Comment by brabalan** [comment]
Indeed, the integration on the caml web site predates ocaml's Planet, so it may not be necessary. The one place that may be useful could be on the mailing list page http://ocaml.org/community/mailing_lists.html, alongside "Subscribe | Inria Archives | Google Groups Archives" for the official mailing list, under the heading "weekly summary".

**Comment by agarwal** [comment]
How is the Weekly Summary generated? It appears to have significant overlap with items in the Planet. Is it superseded by the Planet?

**Comment by amirmc** [comment]
I see the Weekly Summary as complementary to the Planet.  It surfaces discussions from the caml-list that others who are not subscribed wouldn't know of, so I see it a valuable addition to the community.  Of course, overlap between the two may occur when (a) major announcements are made or (b) if people email the list _and_ write blog posts (ahem :) -- but neither of those should be a surprise.

I think adding it to the lists page [1] makes a lot of sense but I'm also wondering if it can be an RSS feed in it's own right.  It's something people might like to subscribe to independently of Planet but at the moment, only the headlines make it in to the CWN feed, which feels like a missed opportunity to me.  If it were an RSS feed, I'd consider making the content more visible on the website, somehow.

[1] http://ocaml.org/community/mailing_lists.html

**Comment by brabalan** [comment]
> How is the Weekly Summary generated? It appears to have significant overlap with items in the Planet. Is it superseded by the Planet?

The CWN includes at the end the feed from the planet, but it's a selection of messages from the Caml mailing list. (Note that the first destination of this letter is the development page of the Linux Weekly News; there are people who directly receive it by email and others who subscribe to the RSS feed.)

> It's something people might like to subscribe to independently of Planet but at the moment, only the headlines make it in to the CWN feed, which feels like a missed opportunity to me. If it were an RSS feed, I'd consider making the content more visible on the website, somehow.

I create the RSS feed programatically, so I could change its format. However, I'm not sure I understand what format you would prefer. Do you want the full contents in the feed?

**Comment by amirmc** [comment]
> Do you want the full contents in the feed?

Yes, that's what I was referring to.  @agarwal @Chris00, if the CWN were a complete feed do you think we could incorporate it into the site?  I mean beyond having it in the Planet feed, as it's a regular, curated set of content which helps to bring more visibility to the mailing list.  I'm imagining it as the equivalent of a weekly blog post.  Thoughts?

@brabalan Have you considered moving your list to `lists.ocaml.org`? I understand it wouldn't be a trivial undertaking but if it makes sense, then perhaps it's something else we could do. @avsm, I'm assuming this wouldn't be an issue.

**Comment by Chris00** [comment]
@brabalan It would be nice if the planet feed contained at least links — and not only the headers.

@amirmc there is not problem to incorporate the feed with the full content.  One just has to define the layout (and what we do with older posts in the feed).

**Comment by agarwal** [comment]
So the CWN consists of 1) manually selected threads from the OCaml List and 2) some of the most recent posts from the Planet.

We have previously discussed the idea of having slow aging news items. We would somehow mark blog posts that are more important, and let those show up on the front page for longer. Since the OCaml List is also a feed, we could apply the same tool to it. Mark some of the the threads as more important, and have those show up mixed in with the front page News. That would effectively provide what the CWN does.

However, that doesn't provide the CWN as an email, so not sure this meets the needs of @brabalan. It's just a thought. Maybe we could somehow merge the two tasks.

**Comment by brabalan** [comment]
Sorry for the delay in my answers, I'm about to travel to London so there might be some latency during the next few days.

@amirmc Migrating the list should be possible: I have access to the list of subscribed users.

@Chris00 What links would you see there? It can be a link to the CWN page (http://alan.petitepomme.net/cwn/2013.11.26.html#2) or a link to the first email of the thread (https://sympa.inria.fr/sympa/arc/caml-list/2013-11/msg00172.html). Both are easy to generate. Regarding older content, I can reboot the RSS feed (or regenerate old entries). I can also easily create a second RSS feed just for ocaml.org.

@agarwal A little bit of context: the CWN is quite old, I've been in charge of it since 2001. It was initially a handcrafted email summarizing what happened on the OCaml mailing list, and I've since automated a bit of contents transformation to generate an HTML page, a RSS feed and a XML description for the Caml web site. Since 2009, the CWN includes links to the recent entries of the (then called) Planet OcamlCore. If I create a feed just for ocaml.org, I could skip the part scrapped from Planet and only include things from the mailing list.

By the way, I'm not particularly attached to the current format of the CWN, or the CWN itself. The only part I would be sad to see go is the weekly presence of Caml news on the LWN development page.

**Comment by avsm** [comment]
Agreed about the weekly presence on LWN, as that's how I've read it for a very long time!  Another query: I can create a mirror of it on lists.ocaml.org if you'd like.  I just need the mbox of the archives back to 2001 and I can then subscribe it to the mailing list to keep subsequent threads live on our archives.

-anil

**Comment by amirmc** [comment]
@brabalan If you'd like to visit ~~sunny~~ Cambridge while you're in London, let me know!  

I agree about keeping the presence on LWN, having news about OCaml reaching a wider community is A Good Thing.

@avsm If Alan is happy to migrate the list (as he seems to be), do we need a mirror?  It may be useful in the short term as a migration path.  Let me know if I'm missing something.

**Comment by Chris00** [comment]
@brabalan [Here](http://alan.petitepomme.net/cwn/2013.11.26.html#2) the headers:
1.    New OCaml.org design is now live!
2.   extlib 1.6.0 released
3.  Other Caml News

are links (granted, inside the page) while [on the planet](http://ocaml.org/community/planet.html#2bd36e1a33f7aaf14c98d4fac4ccb55d) one has to click on the title to go to the links (it would be nice id the headers were links directly to the proper sections of your page):
1.    [New OCaml.org design is now live!](http://alan.petitepomme.net/cwn/2013.11.26.html#1)
2.   [extlib 1.6.0 released](http://alan.petitepomme.net/cwn/2013.11.26.html#2)
3.  [Other Caml News](http://alan.petitepomme.net/cwn/2013.11.26.html#3)

**Comment by brabalan** [comment]
@Chris00 I changed the RSS generation so that it now creates link. Please let me know if this is what you want. I can also replace the '/' by breaking tags, to make things prettier (edit: I tweaked it a bit with an ordered list; but it's easy to change). I have plans to change the generation process to make things nicer (including syntax highlighting of the ocaml code), but I still need to find time to do it.

@amirmc Thank you for the invitation, but it was a really short two days trip to Imperial College. Some next time maybe.

Regarding the mailing list migration: what would be needed? The list is currently hosted at http://lists.idyll.org/listinfo and it's easy to get the list of subscribed members (digest or not). Would it require an action from the members?

**Comment by Chris00** [comment]
@brabalan I think it is much better.  Note that the title does not need to contain the date as it is already present in another field.

**Comment by brabalan** [comment]
@Chris00 It's redundant when the date is chosen to be shown (in fact, the whole title is redundant if both the date and the feed are shown, which is the case on Planet). I like to have the date when I look at the feed with only the titles shown.

**Comment by Chris00** [comment]
@brabalan I pushed a slight modification 30fe29e72c4218645601b423de6dc120719995b0 os that the title is changed.  Let me know if you dislike the change.  (BTW, “__O__Caml weekly news” may be preferable since it is the official name.)

**Comment by brabalan** [comment]
Thanks, the change is fine. Regarding the name, I can change it in some places, but changing it everywhere is going to be a pain (especially in URLs). I see that the caml-list is still called that ...

**Comment by Chris00** [comment]
> Thanks, the change is fine. Regarding the name, I can change it in
> some places, but changing it everywhere is going to be a pain
> (especially in URLs). I see that the caml-list is still called that ...

I was thinking in the title & name.  URLs can stay as they are.

**Comment by brabalan** [comment]
OK, I changed it in some places. Next week's edition should be better.

**Comment by Chris00** [comment]
I think this has been resolved, so closing.
