### ISSUE TITLE
consider importing A Serious Contender page

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#34]
The [OCaml: a serious contender](http://caml.inria.fr/about/programming-contest.en.html) page lists past ICFP competitions in which teams using OCaml were winners. This is probably not a good static page to add to ocamlweb. Consider if it should be imported somewhere. If it is check, whether list is up to date.

**Comment by agarwal** [comment]
There is no clear place for such a page on the current site, so closing this issue.

**Comment by Chris00** [comment]
I think it could go into the "Community" section.  The problem is that it is not up to date so some work is required before adding it.

**Comment by agarwal** [comment]
But is it worth it? The fact that OCaml was used in a student competition, albeit a very respectable one, doesn't make it a "serious contender". The fact that the likes of Facebook use it already trumps this point.

**Comment by Chris00** [comment]
On Tue, 8 Jul 2014 04:19:03 -0700, Ashish Agarwal wrote:

> But is it worth it? The fact that OCaml was used in a student competition, albeit a very respectable one, doesn't make it a "serious contender". The fact that the likes of Facebook use it already trumps this point.

I agree.  I think this is the real reason for closing the issue.
