### ISSUE TITLE
Bloomberg entry for companies page

### ISSUE THREAD

**Issue by shayne-fletcher** [ocaml/v2.ocaml.org#343]
Hi y'all,

We (Bloomberg) would be delighted if we might also be listed on the companies page (http://ocaml.org/learn/companies.html). I have a little blurb and logo ready to ship for this purpose - if acceptable, how should I proceed? Attach them to this ticket or...?

Best regards,

-- Shayne Fletcher (sfletcher13@bloomberg.net)

**Comment by agarwal** [comment]
If you're willing, you can also submit a pull request, but please feel free to attach logo and text in this ticket. We'll take care of it. Thanks!

**Comment by shayne-fletcher** [comment]
We've submitted a pull request (https://github.com/ocaml/ocaml.org/pull/344). Happy days and thanks!

**Comment by pw374** [comment]
It's now online :)

**Comment by pw374** [comment]
I'm reopening because it doesn't seem to be in the right place (the last place doesn't look right, given that most items of the list is in alphabetical order).

**Comment by agarwal** [comment]
We really should add some Javascript to randomize the order in which the list is shown on each refresh. Such code would come in handy in a few places. Or we can place all in alphabetical order, except randomly put a different one first (which is what used to be done on the old version of the site).

**Comment by dbuenzli** [comment]
I think alphabetical order makes more sense when you want to refer to that page for telling someone/check for yourself that entity XXXX uses OCaml. Especially now that the list seems to be growing.

**Comment by pw374** [comment]
Ok let's track this issue on #345.
