### ISSUE TITLE
bug in Recent email threads

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#346]
We currently have this:

![image](https://f.cloud.github.com/assets/112173/1667626/9252676a-5c58-11e3-8076-6baae7028392.png)

**Comment by pw374** [comment]
There's

```
<lastBuildDate>03 déc. 2013 at 21:27:48</lastBuildDate>
```

in https://sympa.inria.fr/sympa/rss/latest_arc/caml-list?count=40

**Comment by pw374** [comment]
https://github.com/ocaml/ocaml.org/commit/d4e94fbadb1c6a0bc3a27e212f3154ae41999088 should remove the issue for the ocaml.org side.
