### ISSUE TITLE
OPAM packaging page.

### ISSUE THREAD

**Issue by Kakadu** [ocaml/v2.ocaml.org#347]
I have found some issues on Firefox and Chromium.
If we go http://opam.ocaml.org/doc/Packaging.html and scroll down you will see
1) Page footer overlaps contents block. Maybe it was done intentionally, but it doesn't look nice for me.
2) Contents block blinks when we scroll near bottom of the page.

**Comment by agarwal** [comment]
Issue moved to ocaml/opam.ocaml.org#4.
