### ISSUE TITLE
http://ocaml.org/community/ is a blank page

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/v2.ocaml.org#349]
Don't know if it's a transient issue but it is right now.

**Comment by amirmc** [comment]
Thanks for reporting! Trying to reproduce locally.

**Comment by pw374** [comment]
I did see that blank page... But it's not blank anymore.
I was about to make some changes but it went back to normal before I could do anything.

http://ocaml.org/community/

**Comment by amirmc** [comment]
It appears to be back, so it may have been transient.  Not sure what happened.

**Comment by dbuenzli** [comment]
Yes it's back for me aswell. FWIW the page just had the `<!DOCTYPE HTML>` and then nothing.

**Comment by amirmc** [comment]
Something must have broken somewhere and I suspect one of the scheduled rebuilds fixed it (I'm just speculating here). I was seeing a blank page too and after repeated refreshes it intermittently started appearing (the intermittent behaviour is likely due my browser caching).

In any case, this is interesting and one reason why having a staging setup would make it easier to go back through builds to see what happened (#277).  Or even better, have the whole OCaml.org site running as a Mirage Unikernel and keep each VM :-P 

Amir :)
