### ISSUE TITLE
import A Few Papers on OCaml

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#35]
Import [A few papers on OCaml](http://caml.inria.fr/about/papers.en.html) page. Put content in a new papers.htm page, and split Advanced tutorials & Papers menu item into two.

**Comment by pveber** [comment]
I've started something on this one: https://github.com/pveber/ocaml.org/tree/ec0bc6e9e1b2f59eef2b0159fa18fbdd39aad93e

I'm nearly done but for one thing: some papers are hosted on the inira ocaml website. Should we host them on ocaml.org, or should we have links to inria, or something else?

**Comment by agarwal** [comment]
For now, keep links to Inria as-is. As soon as we have the site hosted at
OCaml Labs, we'll have a place to put static media. It won't be too hard to
update the links because we can easily grep for caml.inria.fr. Thanks for
the contribution.

**Comment by pveber** [comment]
just sent a pull request (#79) for this.

**Comment by agarwal** [comment]
The new page was not linked from anywhere. I think it justifies a menu
item; added in e21e13b5469b248d443137b18a4d0f21a4f97349.
