### ISSUE TITLE
guidelines: "disease"

### ISSUE THREAD

**Issue by pw374** [ocaml/v2.ocaml.org#351]
In http://ocaml.org/learn/tutorials/guidelines.html we can read

> The programmer that suffers from this disease carefully avoids to use arrays and assignment. In the most severe forms, one observe a complete denial of writing any imperative construction, even in case it is evidently the most elegant way to solve the problem.

"disease"? really? Am I the only one who feels that it's insulting some people?
Perhaps it was intended to be humorous... or perhaps it's poor translation, I don't know. Someone please rephrase this or explain why it's fine to have something like that.

**Comment by amirmc** [comment]
Came from the original site but wasn't easily found there [1].  I agree that it's not an appropriate phrase. 

Could rephrase to "programmer that believes this carefully"

[1] http://caml.inria.fr/resources/doc/guides/guidelines.en.html

Best wishes,
Amir

## 

sent via mobile

**Comment by dbuenzli** [comment]
Ah political correctness... If you want to change it, since this is about "Style dangers", why not "programmers that suffer from this style" ? 

Or if "suffer" is still too insulting and politically incorrect for this site, "programmers that stick to this style" ? 

Or maybe "programmers (peace be upon them) that, while they are doing something wrong we still respect, stick to this style".

**Comment by dbuenzli** [comment]
That said I think "disease" is very apt in the context since it talks about "severe forms" and "symptoms", it's clearly a style that was taken here. Oh and if you supress it then you should also suppress the third bullet since it attributes and mocks thoughts of this imaginary programmer and that is very very mean. It could hurt some feelings.

**Comment by avsm** [comment]
Rather than political correctness, this just isn't a very useful section. It doesn't explain the resource usage (e.g. extra allocations) vs safety/modularity (e.g. lack of persistence) tradeoffs that should drive this style decision.

**Comment by dbuenzli** [comment]
Le vendredi, 6 décembre 2013 à 11:43, Anil Madhavapeddy a écrit :

> Rather than political correctness, this just isn't a very useful section. It doesn't explain the resource usage (e.g. extra allocations) vs safety/modularity (e.g. lack of persistence) tradeoffs that should drive this style decision.

I don't think so, this is (or should) be covered in other sections. Resource usage is not the point here, this section is about code _readability_: use the idiom that naturally fits the problem, don't stick to one idiom for ideological reasons. _If_ that body of code becomes a bottleneck then the points you mention come in action.  

Daniel

**Comment by amirmc** [comment]
> That said I think "disease" is very apt in the context since it talks about "severe forms" and "symptoms", it's clearly a style that was taken here. Oh and if you supress it then you should also suppress the third bullet since it attributes and mocks thoughts of this imaginary programmer and that is very very mean. It could hurt some feelings

I agree that it was written in that style.  I disagree with the style being here.  It's _unnecessarily_ antagonistic and while it would be totally fine in a blog post (where it's clearer who the author is and may fit within their general style of writing), it _is_ inappropriate for this particular page on ocaml.org that purports to be overall guidelines for the language.  

This has nothing to do with political correctness, but more to do with how we as a community present the language to others looking to find out more and learn.

**Comment by agarwal** [comment]
After reading the whole context, I ended up not finding it as extreme as I first thought when seeing this issue. Nonetheless, there's no reason to take the risk of being offensive when we can just as easily rephrase it. How about "The programmer that follows this dogma ..."?

**Comment by amirmc** [comment]
Dogma is a much better word.

**Comment by pw374** [comment]
> On Dec 6, 2013, at 07:50 AM, Amir Chaudhry notifications@github.com wrote:
> Came from the original site but wasn't easily found there [1]. I agree that it's not an appropriate phrase. 
> Could rephrase to "programmer that believes this carefully" 
> [1] http://caml.inria.fr/resources/doc/guides/guidelines.en.html

In [French](http://caml.inria.fr/resources/doc/guides/guidelines.fr.html), it's different: "Le programmeur frappé de ce syndrome…" clearly doesn't me give the same feeling as "The programmer that suffers from this disease…"

I can only guess that it was a poor translation.   

> On Dec 6, 2013, at 11:42 AM, Amir Chaudhry notifications@github.com wrote:
> I agree that it was written in that style. I disagree with the style being here. It's _unnecessarily_ antagonistic and while it would be totally fine in a blog post (where it's clearer who the author is and may fit within their general style of writing), it _is_ inappropriate for this particular page on ocaml.org that purports to be overall guidelines for the language. 
> This has nothing to do with political correctness, but more to do with how we as a community present the language to others looking to find out more and learn. 

Yes, that's precisely what worries me: the image that we give as a _community_. I wouldn't care at all if it were a blog post or if it were signed by a precise set of authors.

(edited for formatting issues)

**Comment by agarwal** [comment]
FYI, notice that your first comment gets lost within the quoted text on the GitHub interface. GitHub doesn't handle markdown that comes from an email, so I avoid email replying if any formatting is needed. (There's a little icon in the title of each comment that tells you the source of the comment, an email or directly typed on GitHub.com.)
