### ISSUE TITLE
extra horizontal rules in Books page

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#352]
The books page [Books](http://ocaml.org/learn/books.html) page has extraneous horizontal rules between books in a few places.

**Comment by pw374** [comment]
Indeed (it's not due to omd, it's the source, there are several places with consecutive lines with `****`)

**Comment by pw374** [comment]
https://github.com/ocaml/ocaml.org/commit/1e1189087040d892648bd231c0cc86678b026139 closes this issue.
