### ISSUE TITLE
Can't access menu when the page is too narrow

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/v2.ocaml.org#353]
When the page is too narrow the top menu turns into an icon, clicking it is supposed to bring up the menu in the page. This doesn't work on firefox/chrome osx.

**Comment by amirmc** [comment]
Doesn't work from my phone either (narrow viewport -- mobile safari).  This _used_ to work so there must have been a regression at some point.

**Comment by Chris00** [comment]
Please confirm it works on your devices.

**Comment by agarwal** [comment]
Works for me on iPhone and laptop.
