### ISSUE TITLE
OCaml books in Japanese

### ISSUE THREAD

**Issue by camlspotter** [ocaml/v2.ocaml.org#355]
Do you mind adding some OCaml book information written in Japanese at http://ocaml.org/learn/books.html ? We have such 3 good books and I could provide some short information in English.

**Comment by Chris00** [comment]
Sure.  Please submit a pull request.

**Comment by agarwal** [comment]
@camlspotter Please let us know if you plan to do this still. Otherwise this issue will be closed due to insufficient information.

**Comment by Chris00** [comment]
Feel free to reopen if you have more information — or, better, submit a PR.
