### ISSUE TITLE
opam.ocaml.org: edit link is wrong

### ISSUE THREAD

**Issue by avsm** [ocaml/v2.ocaml.org#356]
e.g. see:
http://opam.ocaml.org/pkg/cohttp/cohttp.0.9.13/

```
Edit    https://github.com/home/opam/www-new/packages/cohttp/cohttp.0.9.13/opam
```

**Comment by dsheets** [comment]
Need to know the invocation used to generate the site.

**Comment by AltGr** [comment]
@dsheets: see https://github.com/ocaml/opam.ocaml.org
(specifically: https://github.com/ocaml/opam.ocaml.org/blob/master/update-opam-repo.sh#L61)

**Comment by dsheets** [comment]
I don't have access to that repository. I get 404.

**Comment by avsm** [comment]
There doesn't appear to be anything private in there.  However @AltGr, could this repository please be removed and merged with ocaml/ocaml.org-scripts, in an `opam/` subdirectory?  It would be good to unify all our deployment scripts in one place (that repo has the SVN->Git scripts).

**Comment by dsheets** [comment]
I'm having a hard time reproducing this issue. Fundamentally, the problem is that `OpamFilename.to_string (OpamPath.Repository.opam repo prefix pkg)` is returning an absolute path even after `let repo = { repo with repo_root=OpamFilename.Dir.of_string "" } in`. Then, this absolute path clobbers the GitHub path. I don't get this behavior with recent `opam-lib`, `opam2web`, and `uri`. @AltGr, could you check the installed versions on the server?

**Comment by AltGr** [comment]
The versions on the server have been automatically updated every night without trouble. Note that we use `make libinstall` from opam trunk rather than the opam package. The OPAM packages required by opam2web aren't auto-updated either: may that be the cause ?

Currently we got:

```
Installed packages for 4.00.1:
base-bigarray            base  Bigarray library distributed with the OCaml compiler
base-threads             base  Threads library distributed with the OCaml compiler
base-unix                base  Unix library distributed with the OCaml compiler
cmdliner                0.9.2  Declarative definition of command line interfaces for OCaml
cow                     0.7.0  XML, JSON, HTML, CSS, and Markdown syntax and libraries
cudf                    0.6.3  CUDF library (part of the Mancoosi tools)
deriving-ocsigen          0.5  Extension to OCaml for deriving functions from type declarations
dose                    3.1.2  Dose library (part of Mancoosi tools)
dyntype                 0.9.0  syntax extension which makes OCaml types and values easier to manipulate programmatically
extlib                  1.5.4  A complete yet small extension for OCaml standard library
js_of_ocaml             1.3.2  Compiler from OCaml bytecode to Javascript
lwt                     2.4.3  A cooperative threads library for OCaml
ocamlclean                2.0  Reduce size of OCaml bytecode files by dead-code removing
ocamlfind               1.4.0  A library manager for OCaml
ocamlgraph              1.8.3  A generic graph library for OCaml
ocp-build         1.99.6-beta  Project manager for OCaml
optcomp                   1.4  Optional compilation with cpp-like directives
ounit                   2.0.0  Unit testing framework loosely based on HUnit. It is similar to JUnit, and other XUnit testing fram
re                      1.2.1  RE is a regular expression library for OCaml
type_conv           109.47.00  Library for building type-driven syntax extensions
typerex           1.99.6-beta  Set of tools and libraries for OCaml, developed by OCamlPro and INRIA
ulex                      1.1  lexer generator for Unicode and OCaml
uri                    1.3.11  RFC3986 URI parsing library
xmlm                    1.2.0  Streaming XML codec for OCaml
```

**Comment by dsheets** [comment]
This was a problem with my understanding of `OpamPath.Repository.opam` that was fixed in the referenced commit. GitHub seems to have missed the merge but it definitely happened and the edit link is now correct. Closing as fixed.
