### ISSUE TITLE
Visibility of the bug tracker

### ISSUE THREAD

**Issue by Drup** [ocaml/v2.ocaml.org#357]
I didn't find any link to the bug tracker on ocaml.org, either there is none, and it should be added, or there is one but I didn't find it, which show that the visibility should be improved.

**Comment by avsm** [comment]
The Feedback link on the bottom of every page...

**Comment by Drup** [comment]
Hum, indeed, that's probably the one place I didn't try to look. :/

**Comment by Drup** [comment]
Actually, I'm talking about the [ocaml bugtracker](http://caml.inria.fr/mantis/my_view_page.php). The feedback button is for the ocaml.org bugtracker.

**Comment by agarwal** [comment]
It is linked from the [SVN](http://ocaml.org/releases/svn.html) and [FAQ](http://ocaml.org/learn/faq.html) pages, which is not particularly useful. It should be somewhere more intuitive, but we've had trouble thinking of where. On the old site, we had it as an item under the _More_ menu, which has no analog in the new design. Two options are:
- On the About page proposed in #265, and/or
- In the sitemap-style footer proposed in #257.

**Comment by Drup** [comment]
Maybe on the support page ? When I was looking for it, I was expecting to find it in the same area as the mailing list and the irc channel.

What is the logical way to this svn page ? I can't find any link to it.
Edit : Nevermind : Download > source.

**Comment by agarwal** [comment]
> Maybe on the support page ?

This page is about support at a higher level, not detailed issues and bugs.

> When I was looking for it, I was expecting to find it in the same area as the mailing list and the irc channel.

This could make sense, but then this page is no longer just about "Mailing lists". Actually, that's already true as there are links to IRC and groups. Maybe we can change the title of this page to something broader like "Forums".

> What is the logical way to this svn page ?

From the [Install page](http://ocaml.org/docs/install.html#FromSource), which is itself in terrible shape. See #136, #256, and #213. Sigh, lots of work still.

**Comment by amirmc** [comment]
I'd also put it on the releases page(s) if not already there. 

Best wishes,
Amir

## 

sent via mobile

**Comment by Chris00** [comment]
I added a link in the sitemap footer. ce4a3d8fdf2a885e49dcb08eb182781e64efdd7a

**Comment by agarwal** [comment]
The Mantis bug tracker is now linked from the footer and the [mailing lists page](http://ocaml.org/community/mailing_lists.html). I don't think it is necessary to link also from the new [About](http://ocaml.org/about.html) page. It could be listed in future release pages if desired. But I think this issue is resolved, so closing it.
