### ISSUE TITLE
Debian install instructions - ocaml-doc package unavailable

### ISSUE THREAD

**Issue by shayne-fletcher** [ocaml/v2.ocaml.org#364]
http://ocaml.org/docs/install.html

Debian section recommends installing ocaml-doc package but 

Package ocaml-doc is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

**Comment by agarwal** [comment]
I do vaguely recall such a package but can't find it now. We can just delete this comment from the install page as the manual is anyway available online.

**Comment by shayne-fletcher** [comment]
No issues here

**Comment by redianthus** [comment]
@Chris00, `ocaml-doc` package is available in Debian (and now I can't find any mention of it in the install page), so this can be closed.

**Comment by Chris00** [comment]
Thanks for letting me know.
