### ISSUE TITLE
Some videos for beginners

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/v2.ocaml.org#365]
Hi,

I made some little ocaml videos for beginners, which I wondered if you might like to add to the videos page.

https://vimeo.com/user20888710/videos

(I did them for the ocaml-book.com website, but they don't actually require or depend on the book)

The plan is to record a few more when I can find time, but I'd like some feedback on the early ones from as wide an audience as possible.

**Comment by dbuenzli** [comment]
Related to #13
