### ISSUE TITLE
Hundred Lines of OCaml page content and title

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#367]
Regarding the [Hundred Lines of OCaml](http://ocaml.org/learn/taste.html) page:
- Why is the title _A Hundred Lines of OCaml_? The file name is _taste.html_ and 8d99210f77a1dc49b61098961de6dcf6bd28845c linked to it on the Learn page as _Code examples_. Should we title this page _Code Examples_ or _A Taste of OCaml_?
- If yes, we could treat this page as sort of a landing page about code examples. We then could add links to Pleac, Rosetta, langref.org, and 99 Problems. That would make the link added in 8d99210f77a1dc49b61098961de6dcf6bd28845c more accurate.

**Comment by Chris00** [comment]
I think the name is historical: http://caml.inria.fr/about/taste.en.html
One can change it if desired (adding a redirection page 873285f).
