### ISSUE TITLE
use capitalization consistently

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#368]
- [x] Some page titles are in all caps (e.g. [A Hundred Lines of OCaml](http://ocaml.org/learn/taste.html)) and some are not (e.g. [OCaml tutorials](http://ocaml.org/learn/tutorials/)). I think we should consistently use all caps.
- [x] Section headings on landing pages should consistently use all caps.

Sub-sections on various pages also are inconsistent in this regard. Try to fix them too.

**Comment by dbuenzli** [comment]
You can use this bit of css `h1 { text-transform: capitalize }`

**Comment by Chris00** [comment]
What is the rule in English?  Is it "Gen_server **in** OCaml" or "Gen_server **In** OCaml"?

**Comment by dsheets** [comment]
"small" words (articles, prepositions, etc) in the middle are lowercase but I don't think changing syndicated post titles makes sense. This is the rule for titling **works**. The rule for titling articles can be simply first word capitalized.

**Comment by agarwal** [comment]
I did this manually in several places. There are too many pages where leaving titles in lower case also makes sense. Thus, I don't think using a CSS style universally would work either.
