### ISSUE TITLE
Use RSS Icon Correctly

### ISSUE THREAD

**Issue by dsheets** [ocaml/v2.ocaml.org#370]
On the front page, in the News section header, the RSS icon is used but it goes to the same place the header links goes to and the "More..." link at the bottom of the widget.

Once you get to the planet page, each entry has a series of BigCorp share buttons and an RSS feed button but the RSS feed button link title says "Go to the original post" which is the same place that the link title goes.

I'd really like the RSS icons to link to actual feeds (RSS or Atom either is fine). The News RSS icon should link to the Planet feed and each entry's RSS icon should link to the feed for the blog being aggregated. If you want to retain a link icon to the original post, I suggest using a graphic of a chain link like top right of left-hand bar on http://maps.google.com/.

Thanks.

**Comment by Chris00** [comment]
Do you think it would be useful before or after the title of the post — which links to the original one — to attract the reader's attention?

**Comment by dsheets** [comment]
I think it's fine where it is. If you want to move it next to the post title, I guess I would favor after the date and then after the title text.

**Comment by Chris00** [comment]
To be more clear: is the title being a link to the original post clear enough or is an additional mark¹ desirable.

¹ If you have such a chain icon free of rights, that will be nice.

**Comment by dsheets** [comment]
Oh, I understand now. The title link is pretty good. If you want to add an icon that is explicit that might be nice. I think there is a bookmark icon in the glyphicons set 4 from the left and 3 from the top in the spritesheet. It should be in /bootstrap/img/glyphicons-halflings.png from http://getbootstrap.com/2.3.2/getting-started.html

**Comment by Chris00** [comment]
OK, I've done so 7750d7c
