### ISSUE TITLE
Use "subscription" for receipt and "syndication" for transmission of news

### ISSUE THREAD

**Issue by dsheets** [ocaml/v2.ocaml.org#372]
I think all of the instances of "subscription" and "subscribing" new news feeds to the OCaml Planet aggregator should be changed to "syndication" and "syndicating" your feed to the Planet.

Unless there are objections, I will make this change globally within the week. This will include changing the `/community/planet_subscription.html` page to `/community/planet_syndication.html`.

**Comment by Chris00** [comment]
I let you handle the rest. ;-)

**Comment by Chris00** [comment]
If a native English speaker could check that I did not make any mistakes, that would be nice.

**Comment by dsheets** [comment]
Thanks for doing this! Sorry I dropped the ball... :-/

**Comment by agarwal** [comment]
All the changes look fine to me.
