### ISSUE TITLE
OCaml.org Chinese Translation License Issue.

### ISSUE THREAD

**Issue by forhappy** [ocaml/v2.ocaml.org#375]
Hi all, I'm a big fan of OCaml, But I find it‘s hard to get Chinese tutorials for the beginners when I try to learn OCaml. After months of hard struggle in learning OCaml, I have decided to translate some learning materials in OCaml.org. Since OCaml.org is a great learning hub for the English speakers, but for the Chinese who don't know much about English, it's a giant obstacles in learning OCaml. In order to spread OCaml to more Chinese programmers, I want to do some translation work, which will lower the basic requirements a lot for the Chinese OCaml beginners I suppose.

My Question is: What license should I obey, I have registered a new domain (camltech.com) for my translations, iis it OK to put the translated documents on my website(non-commercial profit of course), if it's not applicable, where should I put my translated documents?.

Thanks ;-)

**Comment by agarwal** [comment]
@forhappy Chinese translations would be a really great service to the community! We have unfortunately not yet settled on a license. We will prioritize this and make a decision soon. Regardless of the license, it would be best to keep the translated pages within this repo. That will assure they stay in sync with the primary English content. Thus, please feel free to start the translations and submit pull-requests.

The naming scheme for non-English files is foo.XX.md, where XX is the two-letter language code. For example, in site/learn/tutorials, you'll find basics.fr.md, which is the French version of the Basics tutorial. You could provide the Chinese version in basics.zh.md. Thanks!

**Comment by Chris00** [comment]
@forhappy Also, for the language selector, let us know which Chinese symbols we can use: 中文, 漢語 or 華語 ?

**Comment by forhappy** [comment]
The language selector would be: 中文

On Sat, Dec 28, 2013 at 6:29 AM, Christophe Troestler <
notifications@github.com> wrote:

> @forhappy https://github.com/forhappy Also, for the language selector,
> let us know which Chinese symbols we can use: 中文, 漢語 or 華語 ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ocaml/ocaml.org/issues/375#issuecomment-31283112
> .

## 

## 责任与感恩

祝好

中国科学院计算技术研究所
中关村科学院南路6号
北京市海淀区
邮编100190

**Comment by Chris00** [comment]
Thanks. I have pushed to code to have laguage selectors. You can thus start to submit pull requests!  (The license will likely be something like [CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/), you'll have to agree with it.)

P.S. Just in case an explanation is needed, `zh` is the [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) symbol.

**Comment by forhappy** [comment]
OK, I agree with the license CC BY-SA 4.0. Thank you for reminding me of that  ;-)

**Comment by Chris00** [comment]
Good!  Looking forward to your contributions (please split them is small commits).

**Comment by Chris00** [comment]
The tutorial pages that were translated to Chinese have been imported.  See the
[Chinese index](http://ocaml.org/learn/tutorials/index.zh.html).

**Comment by Chris00** [comment]
Since this issue is about the license and this has been decided, I am closing it.  
@forhappy Let me reiterate that you are very welcome to submit your translations to this site directly.
