### ISSUE TITLE
Bug in site generator

### ISSUE THREAD

**Issue by OrelSokolov** [ocaml/v2.ocaml.org#378]
I am trying to make Russian translation for this site. Placing `index.ru.md` in `site/` and running `make` should generate appropriate links, but:
![learn ocaml - google chrome_002](https://f.cloud.github.com/assets/2205407/1817729/4a6f1004-6fbf-11e3-9336-ba4f26b715c8.png)

`[ru]` link has href `index.ru.md` instead of `index.ru.html`, which works perfect. Please, fix this issue.

**Comment by Chris00** [comment]
I noticed that too! :-(  It is fixed in de5ee690cf1ccd997393b86095130b3192b216d1

**Comment by Chris00** [comment]
@OrelSokolov Please confirm that it works for you so I can close this bug.

**Comment by OrelSokolov** [comment]
@Chris00, bug fixed. I am sorry for late.
