### ISSUE TITLE
Image missing in GTK tutorial

### ISSUE THREAD

**Issue by Kakadu** [ocaml/v2.ocaml.org#391]
This URL: http://ocaml.org/img/graphtest.gif
On this [tutorial](http://ocaml.org/learn/tutorials/introduction_to_gtk.html)
Look near chapter `Structure of lablgtk`.

**Comment by Chris00** [comment]
I can't generate the image until this is solved: https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1366&group_id=220&atid=1032

**Comment by dmbaturin** [comment]
After pull request #628 someone should be able to generate this image again I hope. :)
