### ISSUE TITLE
Enable https

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#399]
It would be nice to be able to connect to https://ocaml.org

**Comment by agarwal** [comment]
Why?

**Comment by Chris00** [comment]
On Wed, 12 Feb 2014 09:00:50 -0800, Ashish Agarwal wrote:

> Why?
1. Some browser extensions try to switch to https for all sites.
2. It is better that Piwik passwords are not transmitted in plain text.

**Comment by pw374** [comment]
I tend to bend to the side of "all HTTP connections should be S".
Having both HTTP and HTTPS would allow people to choose.

Then the question is: how will we get a ssl certificate?

**Comment by dbuenzli** [comment]
I recently got a free certificate for erratique.ch [here](https://www.startssl.com/). These certificates are recognized by the major browsers. The disadvantage is that you will have to renew it every year and that it needs to be tied to an email address (besides you will have to prove ownership over one of these address `{webmaster,hostmaster,postmaster}@ocaml.org`).

**Comment by pw374** [comment]
```
$ dig ocaml.org mx |grep MX
;ocaml.org.         IN  MX
ocaml.org.      10755   IN  MX  50 mx.cam.ac.uk.
```

(Is this field any useful at all?!)

It wouldn't be as trivial as setting some `postfix` on ocaml.org and reading an email then.

**Comment by dbuenzli** [comment]
You only need it for the validation process to get the website's certificate. If there's a mail server that handles `@ocaml.org` addresses just redirect one of the address mentioned to whoever's in charge of handling the validation process. 

Also these free certificates are tied to an individual so someone will have to provide its personal details.

**Comment by avsm** [comment]
I already have a wildcard ocaml.org SSL certificate available.  It's what drives opam.ocaml.org for instance.

**Comment by pw374** [comment]
Great, we just need to install it then :)

**Comment by dsheets** [comment]
When can this happen?

**Comment by dsheets** [comment]
I'll take care of this. Could you assign this issue to me?

**Comment by amirmc** [comment]
@dsheets added you to the relevant GitHub team and assigned this to you.

**Comment by dsheets** [comment]
Initial configuration completed. Please see http://lists.ocaml.org/pipermail/infrastructure/2014-August/000469.html. I will leave this issue open until we are satisfied that TLS has been successfully and correctly deployed.

**Comment by dsheets** [comment]
Content to mirror:
From https://ocaml.org/learn/:
http://caml.inria.fr/about/successes-images/unison-thumb.jpg
http://caml.inria.fr/about/successes-images/lexifi-thumb.png

**Comment by dsheets** [comment]
This is complete and follow-up issues are being tracked by #513, #514, and #515.
