### ISSUE TITLE
companies.html: verify that list is up-to-date

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#4]
Add companies using OCaml that are not already on this list. Possibly we are missing several since this page has not been updated in a while.

**Comment by eelsther** [comment]
I am contacting by email companies which have a website where it is not clear whether they use OCaml or not.

Concerning finding new companies, I suggest to send a message to the Caml-list asking for employees in companies using OCaml (not already in the list of known companies) to get their company's name in the list. What do you think ?

**Comment by Chris00** [comment]
On Sat, 18 Aug 2012 10:51:03 -0700, Esther wrote:

> I am contacting by email companies which have a website where it is 
> not clear whether they use OCaml or not.
> 
> Concerning finding new companies, I suggest to send a message to 
> the Caml-list asking for employees in companies using OCaml (not 
> already in the list of known companies) to get their company's name 
> in the list. What do you think ?

Good idea.  You may want to upload your changes to 
http://ocamlweb.forge.ocamlcore.org/www/ and refer to that site on 
the list (as a temporary location).

Maybe, at the end of your mail, you can welcome other (potential) 
contributors... ;)

**Comment by eelsther** [comment]
> > Good idea.  You may want to upload your changes to
> > http://ocamlweb.forge.ocamlcore.org/www/ and refer to that site on
> > the list (as a temporary location).

Yes, I could do that ! Is there a script to upload the changes on ocamlcore ? If not, how do I do that ?
I was more thinking about giving a simple list of already known companies (without all the detailed explanations).

**Comment by Chris00** [comment]
On Sat, 18 Aug 2012 12:06:49 -0700, Esther wrote:

> ```
>     Good idea. You may want to upload your changes to
>     http://ocamlweb.forge.ocamlcore.org/www/ and refer to that site on
>     the list (as a temporary location).
> ```
> 
> Yes, I could do that ! Is there a script to upload the changes on ocamlcore ?

make publish

> I was more thinking about giving a simple list of already known companies
> (without all the detailed explanations).

This would be OK too.  But maybe some companies will want to change
their description, it is also a good opportunity to ask them.

**Comment by agarwal** [comment]
I also think it would be okay to polish up this page as best as possible
right now without contacting any companies, and defer contacting companies
till the site is live. It might be less confusing, and people will be more
inclined to take the request seriously if the page you refer to is a
published one.

**Comment by eelsther** [comment]
'make publish' doesn't work for me, I get some "Permission denied (publickey)"...
Do I have to copy my ssh key somewhere on ocamlcore ? I already have done it before.

**Comment by agarwal** [comment]
I get the same error.

**Comment by Chris00** [comment]
On Sat, 18 Aug 2012 12:50:07 -0700, Esther wrote:

> 'make publish' doesn't work for me, I get some "Permission denied
> (publickey) "...  Do I have to copy my ssh key somewhere on
> ocamlcore ? I already have done it before.

You have to go to "My account", bottom of the page, "SSH Shared
Authorized Keys" and upload your public key.

**Comment by eelsther** [comment]
My public key is already there since a long time now. It still doesn't work...

**Comment by agarwal** [comment]
In the past, this update has taken over an hour. Maybe needs sometime still.

**Comment by Chris00** [comment]
On Sat, 18 Aug 2012 13:31:43 -0700, Esther wrote:

> My public key is already there since a long time now. It still doesn't work...

Can you ssh to the box ?

**Comment by agarwal** [comment]
No. I get the same error.

**Comment by Chris00** [comment]
Esther: note thta I modified the page to include a TOC.

**Comment by eelsther** [comment]
commit db3cec0

**Comment by eelsther** [comment]
commit 0fe72a8

**Comment by eelsther** [comment]
commit 7a5a0ca

**Comment by eelsther** [comment]
A JaneStreet employee asked me a relevant question.
Why do we sort the companies by country ?

When I created the page, I followed the former COCAN page display, but we could also sort companies alphabetically. It would solve the problem of companies having offices in different countries, like JaneStreet.

What do you think ?

**Comment by agarwal** [comment]
> Why do we sort the companies by country ?
> 
> I was going to bring this up at some point... I actually don't like it.
> Sorting alphabetically would be good, but that is also very stagnant and
> possibly the companies on the top of the page won't be the best examples,
> but they'll be the most prominently displayed. So then I thought, maybe
> randomize the order of the list every time you refresh the page, but that
> would be too much change. It would be frustrating to have the page look
> completely different every time.

So finally, my recommendation is: list the companies alphabetically, but
randomly select one to be listed at the very top, i.e. to showcase a
different company each time you visit the page. (I guess this would require
some javascript.)

Knowing the location is useful, and I wouldn't delete the information
completely, but just display it less promptly after each company's name.

-Ashish

**Comment by Chris00** [comment]
On Wed, 22 Aug 2012 07:56:53 -0700, Ashish Agarwal wrote:

> So finally, my recommendation is: list the companies alphabetically,
> but randomly select one to be listed at the very top, i.e. to
> showcase a different company each time you visit the page. (I guess
> this would require some javascript.)

That will probably require to duplicate the information (once in HTML,
once inside the JS) if we want the page the show even with JS
disabled.

Maybe I can try to parse the page to get the list of companies and
generate some JS.  For that we need to agree on a way to delimit
companies, e.g. <div class="company">$B!D(B</div>.  The content of that tag
will be the HTML the JS displays (possibly with specific CSS rules).

> Knowing the location is useful, and I wouldn't delete the information
> completely, but just display it less promptly after each company's name.

Fine with me.

**Comment by Chris00** [comment]
In this case, it may be even better that the JS processes the page itself.

**Comment by samoht** [comment]
can weberizer do that statically ? ie. we give it a well-formated list of companies, and it output the different HTML (and optionally the world map) ?

**Comment by agarwal** [comment]
I was thinking JS code that traverses the DOM to find all <div
class="company"> elements, and displays the contents of a randomly selected
one of these at the top.

**Comment by agarwal** [comment]
Weberizer could do it, but then it is not really dynamic as you only get a
new company showcased each time we compile the site, not each time you
refresh the page.

On Fri, Aug 24, 2012 at 4:41 PM, Thomas Gazagnaire <notifications@github.com

**Comment by samoht** [comment]
Well I meant to generate the data used by JS to display the random showcased companies. But I scanning the DIVs will be good enough :-)

## 

Thomas

**Comment by Chris00** [comment]
We have to check that the CSS code I use for the presentation of companies is OK with IE.  If not, we have to add the CSS "content" directly to the HTML.

**Comment by Chris00** [comment]
Some minimal JS added.

**Comment by agarwal** [comment]
Disclaimer added in commit 94770b03fb29423eb7046a1f71e604b843a1169f.

**Comment by Chris00** [comment]
Argh.  Again, does not seem to appear in https://github.com/agarwal/ocamlweb/commits/master

**Comment by Chris00** [comment]
I have re-added the change 8735bfcbf9c6b5de0bf648bcc3172ec138937580

**Comment by agarwal** [comment]
The original commit is there now. This is quite strange. I've emailed
github support about the other missing commit, which is still missing.

**Comment by agarwal** [comment]
> We have to check that the CSS code I use for the presentation of companies
> is OK with IE. If not, we have to add the CSS "content" directly to the
> HTML.
> 
> Just tested it on IE. Seems ok.

**Comment by Chris00** [comment]
Is there still someting to do on this issue?

**Comment by agarwal** [comment]
The page looks okay to me now. I'm assuming Esther has added all the
information she gathered for this by now. There was still the idea of
generating a world map. I'll create a separate Issue for that and label it
as a feature request.
