### ISSUE TITLE
Add URL to planet

### ISSUE THREAD

**Issue by dlobraico** [ocaml/v2.ocaml.org#405]
Hello!

We at Jane Street have moved our tech blog to a new location (blogs.janestreet.com) along with this comes a change in the location of our RSS feed.

We now have three feeds.

https://blogs.janestreet.com/feed/  -- All posts to the site.
https://blogs.janestreet.com/category/ocaml/feed/ -- All posts to the site in the OCaml category.
https://blogs.janestreet.com/category/systems/feed/ -- All posts to the site in the Systems category.

The posts in the OCaml category are roughly what used to be posted at ocaml.janestreet.com. The posts in the Systems category are roughly what used to be posted at systems.janestreet.com. 

Can you please replace our existing feed in Planet with the "OCaml" feed? Additionally, if you think it fitting, please add the "Systems" feed as well. This feed will often contain posts about using OCaml in a more systems-y light (in addition to some posts that don't use OCaml), so that one may be classified as a "personal" feed by the guidelines on ocaml.org.

Let me know if you have any questions!

Thanks,
Dominick

**Comment by agarwal** [comment]
Looking through the `Systems` feed, I see that some of the posts are very much about OCaml and some are not at all. It seems you tag posts exclusively as `Systems` or `OCaml`, but not both. Can you tag as both when appropriate? That would allow including just the `OCaml` feed.

**Comment by dlobraico** [comment]
Yes, I think we can do that. Including just the OCaml feed seems fine. Thanks!

Ashish Agarwal writes:

**Comment by agarwal** [comment]
The OCaml feed is subscribed, so closing this issue.
