### ISSUE TITLE
import Using the Format Module

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#41]
Inria's [Using the Format Module](http://caml.inria.fr/resources/doc/guides/format.en.html) page can be considered a tutorial. Import it as a new page under the tutorials/ directory and add a link from tutorials.html.

**Comment by Chris00** [comment]
Done. 6f159d86ee6d16c43f139df53aea24552cede94b

Probably want to eval the OCaml code on the page with the new engine.

**Comment by Chris00** [comment]
I have done that (and removed a section with bugs that, to correct, was going to look a lot like the next section).  56942d07430d4953f50dd59cef0fbf917096e023
