### ISSUE TITLE
import OCaml Programming Guidelines

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#42]
Inria's [OCaml Programming Guidelines](http://caml.inria.fr/resources/doc/guides/guidelines.en.html) can possibly be considered a tutorial or possibly documentation. Decide which, and either way import directly into ocamlweb.

**Comment by Chris00** [comment]
There is also http://www.seas.upenn.edu/~cis341/programming_style.html

**Comment by Chris00** [comment]
Done.  ae55ec688ae30ba4ffed633caf6b98d8a33d32ff
May need to be revised though.

**Comment by agarwal** [comment]
Closing this issue. It regards just the import. Improvements can be considered as separate issues.
