### ISSUE TITLE
add page for list of contributors

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#420]
Page could be be at ~~community/contributors.md~~ `ocaml.org/contributors.html` and should be linked from the [about page](http://ocaml.org/about.html) (and maybe in the footer under 'contact'?)

Content should include:
- note that file is auto-generated from the git log
- link to the [tutorials acknowledgements](http://ocaml.org/learn/tutorials/acknowledgements.html) (or perhaps just move that list?)
- output of `$ git log --format="%aN" | sort | uniq` (or something like it)

I accept that the list of names contains oddities but I have a strong preference for keeping things automated (with minimal maintenance burden), even if the results in this case aren't very aesthetically pleasing.

**Comment by agarwal** [comment]
I'd put this page at the root of the site. It's not about the _community_ section specifically, but all contributors.

Also, I recommend merging in the tutorial acknowledgments page. No benefit to having things in multiple places.

**Comment by amirmc** [comment]
All sounds good to me.  In general, I'm wary of putting too many pages under root but in this case it does make sense.

**Comment by amirmc** [comment]
Wow, that was quick! Thanks :)
