### ISSUE TITLE
Agreement on the licenses

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#429]
The license scheme for this site have been discussed on the infrastructure list and are summarized in [LICENSE.md](https://github.com/ocaml/ocaml.org/blob/master/LICENSE.md).

If you have contributed to this repository (i.e., if your name appears below), please add a comment to this issue saying that you agree that your contributions to this repository are licensed as detailed in [LICENSE.md](https://github.com/ocaml/ocaml.org/blob/master/LICENSE.md).  If you do not agree, please say why.
- [x] Ashish Agarwal (_repo_)
- [ ] Ionuț Arțăriși (_repo_)
- [ ] Doug Bagley (_ocaml-tutorial.org_) — _email?_
- [x] Yotam Barnoy (_repo_)
- [x] Esther Baruk (_repo_)
- [x] Çagdas Bozman (_repo_)
- [x] Nicolas Braud-Santoni (_repo_)
- [x] Daniel Bünzli (_cocan.org_)
- [ ] Nicolas Cannasse (_ocaml-tutorial.org_)
- [ ] Benjamin Canou (_repo_)
- [x] Amir Chaudhry (_repo_)
- [ ] Eric C. Cooper (_ocaml-tutorial.org_) — _email?_
- [x] Josh Davis (_repo_)
- [x] Emmanuel Delaborde (_repo_)
- [ ] Richard Donkin (_ocaml-tutorial.org_) — _email?_
- [x] Jim Farrand (_ocaml-tutorial.org_)
- [x] Shayne Fletcher (_repo_)
- [x] Jacques Garrigue (_repo_ & _ocaml-tutorial.org_)
- [x] Thomas Gazagnaire (_repo_)
- [x] Louis Gesbert (_repo_)
- [x] Stephen Gilmore (_ocaml-tutorial.org_)
- [ ] Flavio Grossi (_ocaml-tutorial.org_) — _email?_
- [ ] Damien Guichard (_ocaml-tutorial.org_) — _email?_
- [ ] Steve Hiemstra (_repo_)
- [ ] Brian Hurt (_ocaml-tutorial.org_)
- [x] Martin Jambon (_repo_)
- [x] Richard Jones (_cocan.org_ & _ocaml-tutorial.org_)
- [x] Martin Keegan (_repo_)
- [x] Siraaj Khandkar (_repo_)
- [x] Neel Krishnaswami (_ocaml-tutorial.org_)
- [x] Michel Levy (_ocaml-tutorial.org_)
- [x] Christos KK Loverdos (_repo_)
- [ ] Sven Luther (_ocaml-tutorial.org_)
- [x] Marek Kubica (_repo_)
- [x] Fabrice Le Fessant (_repo_ & _ocaml-tutorial.org_)
- [x] Sylvain Le Gall (_repo_)
- [x] Ronan Le Hy (_repo_)
- [x] Anil Madhavapeddy (_repo_)
- [ ] John Gerard Malecki (_ocaml-tutorial.org_)
- [ ] Luc Maranget (_ocaml-tutorial.org_)
- [x] John Martin (_repo_)
- [x] Erick Matsen (_repo_)
- [x] Michel Mauny (_repo_)
- [x] Mike McClurg (_repo_)
- [x] Yaron Minsky (_repo_)
- [ ] Jean-Francois Monin (_ocaml-tutorial.org_)
- [x] Florent Monnier (_repo_)
- [ ] Markus Mottl (_ocaml-tutorial.org_)
- [x] Thomas Mraz (_ocaml-tutorial.org_)
- [x] Philipp Muller (_repo_)
- [ ] Wolfgang Müller (_ocaml-tutorial.org_) — _email?_
- [x] Adrien Nader (_repo_)
- [x] Victor Nicollet (_repo_)
- [x] Lars Nilsson (_ocaml-tutorial.org_)
- [x] Tong Niu (_repo_)
- [x] Jose Manuel Nunes (_ocaml-tutorial.org_) — _email?_
- [x] Shawn Otis (_repo_)
- [x] Stefano Pacifico (_repo_)
- [ ] Frédéric van der Plancke (_ocaml-tutorial.org_)
- [x] Quentin Pradet (_repo_)
- [x] Raphaël Proust (_repo_)
- [x] Tim Ruffles (_repo_)
- [x] Gabriel Scherer (_repo_)
- [ ] Stanislav Sedov (_repo_) — _email?_
- [x] David Sheets (_repo_)
- [x] Paul Steckler  (_ocaml-tutorial.org_)
- [ ] Fabian Sturm (_ocaml-tutorial.org_) — _email?_
- [ ] Roman Tereshin (_repo_)
- [ ] Ryan Tarpine (_ocaml-tutorial.org_) — _email?_
- [x] Christophe Troestler (_repo_)
- [x] Rémi Vanicat (_ocaml-tutorial.org_)
- [x] Philippe Veber (_repo_)
- [x] Philippe Wang (_repo_)
- [x] Leo White (_repo_)
- [x] Yoriyuki Yamagata (_ocaml-tutorial.org_)
- [x] Jason Yosinski (_repo_)
- [ ] Stefano Zacchiroli (_ocaml-tutorial.org_)
- [x] Éric Zhiqiang Ma (_repo_)

**Comment by dsheets** [comment]
I agree that my contributions to this repository are licensed as detailed in [LICENSE.md](https://github.com/ocaml/ocaml.org/blob/master/LICENSE.md).

**Comment by avsm** [comment]
I agree that my contributions to this repository be licensed as detailed in [LICENSE.md](https://github.com/ocaml/ocaml.org/blob/master/LICENSE.md)

**Comment by agarwal** [comment]
I agree that my contributions to this repository are licensed as detailed in [LICENSE.md](https://github.com/ocaml/ocaml.org/blob/master/LICENSE.md).

**Comment by gasche** [comment]
I agree that my contributions are licensed as detailed in [LICENSE.md](https://github.com/ocaml/ocaml.org/blob/8561943e67f9f789f86cd3bbc6049a6bbfc9fe4e/LICENSE.md).

I think letting authors retain their rights for slides is the right choice, but it would also be nice if there was a reference license to use to avoid unnecessary variation and, in the general case, authorize free rediffusion of the material -- my freetard self would appreciate CC-BY-SA, but I suppose -ND may be a reasonable addition for a more consensual licence.

**Comment by jdmartin86** [comment]
I agree that my contributions are licensed as detailed in [LICENSE.md](https://github.com/ocaml/ocaml.org/blob/8561943e67f9f789f86cd3bbc6049a6bbfc9fe4e/LICENSE.md).

**Comment by amirmc** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md

**Comment by Chris00** [comment]
I agree that my contributions to this repository be licensed as detailed in [LICENSE.md](https://github.com/ocaml/ocaml.org/blob/8561943e67f9f789f86cd3bbc6049a6bbfc9fe4e/LICENSE.md).

**Comment by VictorNicollet** [comment]
I agree that my contributions to this repository be licensed as detailed in [LICENSE.md](https://github.com/ocaml/ocaml.org/blob/8561943e67f9f789f86cd3bbc6049a6bbfc9fe4e/LICENSE.md).

**Comment by yminsky** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md.

**Comment by mrnt0810** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md.

**Comment by pw374** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md.

**Comment by zma** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md.

**Comment by mcclurmc** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md.

**Comment by lehy** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md.

**Comment by pquentin** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md.

**Comment by Leonidas-from-XIV** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md.

**Comment by xandkar** [comment]
I agree that my contributions to this repository are licensed as detailed in [LICENSE.md](https://github.com/ocaml/ocaml.org/blob/8561943e67f9f789f86cd3bbc6049a6bbfc9fe4e/LICENSE.md).

**Comment by raphael-proust** [comment]
I agree that my contributions to this repository are licensed as detailed in LICENSE.md.

**Comment by vanicat** [comment]
I agree that my contributions to this repository are licensed as detailed in [LICENSE.md](https://github.com/ocaml/ocaml.org/blob/8561943e67f9f789f86cd3bbc6049a6bbfc9fe4e/LICENSE.md)

**Comment by chamaeleon** [comment]
I agree that my contributions to this repository are licensed as detailed in LICENSE.md

**Comment by dbuenzli** [comment]
I agree that my contributions are licensed as detailed in [LICENSE.md](https://github.com/ocaml/ocaml.org/blob/8561943e67f9f789f86cd3bbc6049a6bbfc9fe4e/LICENSE.md).

**Comment by jdavis** [comment]
I agree that my contributions to this repository are licensed as detailed in LICENSE.md

**Comment by SGilmore** [comment]
I agree that my contributions to this repository are licensed as detailed in LICENSE.md.

**Comment by shayne-fletcher** [comment]
I agree that my contributions to this repository are licensed as detailed in LICENSE.md

**Comment by mjambon** [comment]
I agree that my contributions to this repository are licensed as detailed in LICENSE.md.

**Comment by psteckler** [comment]
I agree that my contributions to this repository are licensed as detailed in LICENSE.md.

**Comment by StefPac** [comment]
I agree that my contributions to this repository are licensed as detailed in LICENSE.md

**Comment by voila** [comment]
I agree that my contributions to this repository are licensed as detailed in LICENSE.md.

**Comment by lpw25** [comment]
I agree that my contributions are licensed as detailed in LICENSE.md.

**Comment by eelsther** [comment]
I agree that my contributions to this repository are licensed as detailed in LICENSE.md.

**Comment by ml1948** [comment]
I agree that my contributions to this repository are licensed as detailed in LICENSE.md.

**Comment by mauny** [comment]
I agree that my contributions to this repository are licensed as detailed in LICENSE.md.
- Michel Mauny

**Comment by yosinski** [comment]
I agree that my contributions are licensed as detailed in [LICENSE.md](https://github.com/ocaml/ocaml.org/blob/8561943e67f9f789f86cd3bbc6049a6bbfc9fe4e/LICENSE.md).

**Comment by Chris00** [comment]
@ml1948 Could you identify yourself more clearly?  Thanks.

**Comment by ShawnOtis** [comment]
I agree that my contributions are licensed as detailed in LICENSE.md.

**Comment by loverdos** [comment]
I agree that my contributions to this repository be licensed as detailed in [LICENSE.md](https://github.com/ocaml/ocaml.org/blob/946241a291f81466195d9805d57657533cd87193/LICENSE.md).

**Comment by ml1948** [comment]
On 04/03/2014 07:22, Christophe Troestler wrote:

> @ml1948 https://github.com/ml1948 Could you identify yourself more
> clearly? Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ocaml/ocaml.org/issues/429#issuecomment-36595594.
> 
> Yes, I was thinking that it was possible to find my email adress under
> ml1948 (= michel levy born 1948).
> I am michel.levy@imag.fr, previously MCF at university UJF grenoble, now
> retired teacher.

```
Sincerely yours.
```

## 

email : michel.levy@imag.fr
http://membres-liglab.imag.fr/michel.levy

**Comment by Chris00** [comment]
On Tue, 4 Mar 2014 01:51:50 -0800, ml1948 wrote:

> Yes, I was thinking that it was possible to find my email adress under
> ml1948 (= michel levy born 1948).
> I am michel.levy@imag.fr, previously MCF at university UJF grenoble, now
> retired teacher.

Thanks.  That is what I thought but I sent you an email for
confirmation to which you did not answer.  I prefer to be sure that my
guesses are correct in this situation.

**Comment by agarwal** [comment]
In private email to me:

> From: Jim Farrand jim.farrand@...
> Date: Sat, Mar 8, 2014 at 9:48 AM
> To: Ashish Agarwal agarwal1975@...
> 
> Hi Ashish,
> 
> I agree that my contributions to this repository be licensed as detailed in LICENSE.md within the ocaml.org repo.
> 
> Kind regards,
> Jim

**Comment by yoriyuki** [comment]
I agree that my contributions to this repository are licensed as detailed in LICENSE.md.

**Comment by samoht** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md

**Comment by lefessan** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md

**Comment by fccm** [comment]
I agree that my contributions to this repository are licensed as detailed in [LICENSE.md](https://github.com/ocaml/ocaml.org/blob/8561943e67f9f789f86cd3bbc6049a6bbfc9fe4e/LICENSE.md#readme).

**Comment by cagdasbozman** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md

**Comment by mk270** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md (and heartily endorse @cago 's use of the subjunctive; half you people are French anyway, surely!)

**Comment by t8m** [comment]
I agree  that my contributions to this repository are licensed as detailed in LICENSE.md. Tomas Mraz

**Comment by nicoonoclaste** [comment]
I agree that my contributions to this repository be licensed as detailed in [LICENSE.md](https://github.com/ocaml/ocaml.org/blob/master/LICENSE.md).
Nicolas Braud-Santoni

**Comment by gildor478** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md.

**Comment by pveber** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md

**Comment by j-m-nunes** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md

**Comment by garrigue** [comment]
I agree that my contributions to this repository are licensed as detailed in LICENSE.md.

**Comment by AltGr** [comment]
I agree that my contributions to this repository are licensed as detailed in LICENSE.md.

**Comment by timruffles** [comment]
I agree that my contributions to this repository are licensed as detailed in LICENSE.md.

**Comment by matsen** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md.

**Comment by phimuemue** [comment]
I agree that my contributions to this repository be licensed as detailed in LICENSE.md.

**Comment by Chris00** [comment]
On Tue, 8 Jul 2014 09:00:05 -0700, phimuemue wrote:

> I agree that my contributions to this repository be licensed as detailed in
> LICENSE.md.

Thanks Philipp.

**Comment by agarwal** [comment]
---

From: Adrien Nader adrien@notk.org
Date: Thu, Jul 31, 2014 at 4:16 AM
Subject: [ocaml-infra] Statement of acceptance to the ocaml.org relicensing
To: infrastructure@lists.ocaml.org

Hi,

I hereby agree that my contributions to the ocaml.org website be
relicensed as detailled in the file
https://github.com/ocaml/ocaml.org/blob/8561943e67f9f789f86cd3bbc6049a6bbfc9fe4e/LICENSE.md

Some background: I contributed to the website but without going through
github myself and therefore couldn't agree through github (there would
be absolutely no link between the commits, the commiter and that
account); so here is my statement. If a stronger proof is wanted, I can
probably do it too.

Regards,
Adrien Nader

---

Infrastructure mailing list
Infrastructure@lists.ocaml.org
http://lists.ocaml.org/listinfo/infrastructure

**Comment by dbuenzli** [comment]
Shouldn't there be a last round to close this ?

**Comment by Chris00** [comment]
@bluddy I noticed you never agreed to this.  OK with you?

**Comment by bluddy** [comment]
I agree that my contributions to this repository are licensed as detailed in LICENSE.md.

**Comment by Chris00** [comment]
- Ionuț Arțăriși → d8be288d025e7d7b4554552b973ed50d3b4f6e32 (minor).
- Benjamin Canou → 45189fd42c56df84cddf8e2c43f09695d505f4af (typo).
- Steve Hiemstra → 00db06484a58fa3f5f9e111bdae06f124770b274 (move “Modules” tutorial up).
- Stanislav Sedov → c53588ffebd7bba354b0db60ec66cb2c2fbc5b85 and 9489dda16d14ef5d6044839280d02b18702aefd0 (FreeBSD installation).
- Roman Tereshin → dd630abdcfab03708888ff0c9d6210b5eaf9f1b4 (typo).
- ocaml-tutorial.org: Doug Bagley, Nicolas Cannasse, Eric C. Cooper, Richard Donkin, Flavio Grossi, Damien Guichard, Brian Hurt, Sven Luther, John Gerard Malecki, Luc Maranget, Jean-Francois Monin, Markus Mottl, Wolfgang Müller, Frédéric van der Plancke, Fabian Sturm, Ryan Tarpine, Stefano Zacchiroli (no actual commit)

Given the above, I think we can say everybody agrees with the license and move on.
