### ISSUE TITLE
import Debugging facilities in OCaml

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#43]
Inria's [Debugging facilities in OCaml](http://caml.inria.fr/resources/doc/guides/debug.en.html) page can be considered as either a tutorial or documentation. Decide which and import content directly into ocamlweb.

**Comment by Chris00** [comment]
It can also be linked from the "development tools" webpage.

**Comment by agarwal** [comment]
Done in 2ccb9e7e4854f04ba1abcd4c20173a92934e6ce1. French version of page not ported since most of this page is code, and we need a better way to support multi-lingual pages.
