### ISSUE TITLE
Package list on ocaml.org not the same as opam.ocaml.org

### ISSUE THREAD

**Issue by yminsky** [ocaml/v2.ocaml.org#439]
and is also in a bizarre order.  Right now, zero, version 109.15.00 is at the top, a package that hasn't been updated in many months, and is in fact obsolete.

**Comment by dsheets** [comment]
#440 fixes this. I recommend to close.

**Comment by dsheets** [comment]
#447 has now been merged which should fix this. @pw374, I think this issue can be closed. @yminsky, please re-report if there are further issues with the "New Packages" widget. A broader integration is Coming Soon.

**Comment by pw374** [comment]
Thanks, I had the feeling there was something left to close and then I forgot...
