### ISSUE TITLE
The new logo in the header looks blurry on hidpi displays.

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/v2.ocaml.org#444]
To solve, either provide an image with higher resolution or use an SVG image directly.

**Comment by pw374** [comment]
related to https://github.com/ocaml/ocaml.org/issues/44

**Comment by Chris00** [comment]
On Wed, 19 Mar 2014 17:01:16 -0700, Daniel Bünzli wrote:

> To solve, either provide an image with higher resolution or use an SVG image
> directly.

I think the better is to use SVG with some Javascript to check whether the browser supports it.  The PNG would then be a fallback.

**Comment by Chris00** [comment]
Please tell whether the pushed code fixes your problem.

**Comment by pw374** [comment]
wow, it does and it's beautiful! :)
Thank you @Chris00!

**Comment by pw374** [comment]
Even though it's a lot less important (since it's less obvious and it's only on a single page), http://ocaml.org/img/header.jpg looks blurry... Although now I wonder if we can make infinite images in SVG!

**Comment by dbuenzli** [comment]
Absolutely !

**Comment by Chris00** [comment]
@dbuenzli @pw374 You may want to open a new issue for the header.  I suppose it should not be that hard for the people having the source of the header to make a SVG version.  @amirmc ?

**Comment by dbuenzli** [comment]
Actually my comment was referring to the fact that it was working. The header is less severe though it's true that looking at closer you do see the JPEG compression artefacts. I thought it was the remains of the sandstorm. Note that SVG is not the only solution [here](http://www.html5rocks.com/en/mobile/high-dpi/)'s a survey of different techniques, the simplest being to simply double the resolution of images and serve that to everybody.

**Comment by Chris00** [comment]
BTW, what about the 4 square icons (e.g. http://ocaml.org/img/learn-large.png)?  Shouldn't we use SVG as wall when supported?

**Comment by dbuenzli** [comment]
Yeah they also don't look so great, some jaggies.

**Comment by Chris00** [comment]
All logos (except the RSS one) are now in SVG (when your browser supports it).

**Comment by dbuenzli** [comment]
Yes all smooth ! Besides the RSS logo there are also still the JPEG compression artefacts around the camel and at the dune edges in the background image.
