### ISSUE TITLE
New Package widget not updating

### ISSUE THREAD

**Issue by dsheets** [ocaml/v2.ocaml.org#448]
Need to see the logs to be able to diagnose this problem. Might be that the cron job hasn't been set up?

Here's ocaml.org:

```
xtmpl   0.9     Mar 20, 2014
typerep     111.06.00   Mar 20, 2014
textutils   111.06.00   Mar 20, 2014
stog-writing    0.11.0  Mar 20, 2014
stog-rdf    0.11.0  Mar 20, 2014
stog    0.11.0  Mar 20, 2014
```

And opam.ocaml.org:

```
stog 0.11.1     Mar 21
higlo 0.3   Mar 21
ocp-ocamlres 0.2    Mar 20
irrlicht 0.0.3  Mar 20
stog-writing 0.11.0     Mar 20
stog-rdf 0.11.0     Mar 20
```

**Comment by pw374** [comment]
Thank you @dsheets!

(given what the logs say) I suspect I have to update opam... which is weird... I'll keep you posted.

**Comment by pw374** [comment]
So, there was a problem with the opam-package-list updating process: it said something about the opam version (1.1.0) being outdated. I've installed 1.1.1 and now it seems it works fine.

However the list of packages on ocaml.org and opam.ocaml.org seem to be sorted differently, I don't know if it's normal or if it hides yet another bug.

**Comment by pw374** [comment]
I'm closing this issue, please reopen if necessary.

**Comment by dsheets** [comment]
There is another bug somewhere. The datetimes are not correct for a number of packages which clearly effects the sort. What is the script that is doing the repository update?

**Comment by pw374** [comment]
``` bash
# begin opam package list matter
(cd ~/opam-repository && timeout 1h git fetch && git reset --hard origin/master && timeout 1h opam update)
# end opam package list matter
```

The whole building script is there: https://github.com/pw374/pw374.github.io/blob/master/sync/build_ocaml.org.bash (just so I can easily keep history)
N.B. It's not here (in https://github.com/ocaml/ocaml.org/) because it has some paths specific to the machine running ocaml.org. I'm not against moving it here if some people think it's relevant.

**Comment by dsheets** [comment]
Could you please post the output from

``` sh
git --version
```

and

``` sh
git log --name-only --diff-filter=A --reverse --pretty=format:%ct -- */opam
```

**Comment by dsheets** [comment]
and

``` sh
opam remote
```

**Comment by pw374** [comment]
On 21 Mar 2014, at 21:12 pm, David Sheets notifications@github.com wrote:

> Could you please post the output from
> 
> git --version

git version 1.7.10.4

> and
> 
> git log --name-only --diff-filter=A --reverse --pretty=
> format:%ct -- */opam

http://pastebin.com/fsVFK4sr

**Comment by pw374** [comment]
```
buildpreview@ocaml:~/opam-repository$ opam remote
   0 [local]    default     /home/buildpreview/opam-repository
```

**Comment by pw374** [comment]
```
buildpreview@ocaml:~/opam-repository$ cat .git/config|grep url
    url = https://github.com/ocaml/opam-repository.git
```

**Comment by dsheets** [comment]
I haven't yet tracked down the parsing/sorting issue but the box has gone stale again.

**Comment by pw374** [comment]
The reason why the list isn't regenerated at least once every 20 iterations is that the file(s) generated for that list is (are) never removed. https://github.com/ocaml/ocaml.org/commit/0c2170578d0fd4779825bb0622121a66418dc37d should fix this.

I think once every 20 iterations should be enough.

**Comment by dsheets** [comment]
`generate_opam_update_list` is the program that generates `opam_update_list`. Should this be the file that is cleaned?

**Comment by pw374** [comment]
Actually both should be. That's why I added https://github.com/ocaml/ocaml.org/commit/4f4a69ebd075eb4d288bd1edf6af771eab914f48.

However cleaning `generate_opam_update_list` should force the regeneration of `opam_update_list` anyway.

Still, it seems that it's not enough... I'm investigating.

**Comment by pw374** [comment]
I hope https://github.com/ocaml/ocaml.org/commit/0a01aa42209317c66e02aeef3de600ebddd7a1ee is going to be enough...

**Comment by dsheets** [comment]
There is https://github.com/dsheets/ocamlweb/blob/7a0d3fe48de410b186806eb0689fc9fc86f03122/Makefile.from_md#L7 as well.

**Comment by pw374** [comment]
On 25 Mar 2014, at 12:00 pm, David Sheets notifications@github.com wrote:

> There is https://github.com/dsheets/ocamlweb/blob/7a0d3fe48de410b186806eb0689fc9fc86f03122/Makefile.from_md#L7 as well.

That line seemed enough but then it was still not generating generate_opam_update_list
but perhaps I had the environment wrong somehow.

Then since all those scripts are listed in DEP_CONTENT_GEN, it doesn’t seem bad to put it (generate_opam_update_list) there anyway…

**Comment by dsheets** [comment]
Could you post again the output from `git log --name-only --diff-filter=A --reverse --pretty=format:%ct -- */opam`? I am having a hard time reproducing the mis-sorting.

**Comment by pw374** [comment]
here it is: http://pastebin.com/942qmR7h

**Comment by dsheets** [comment]
Most likely the logs contain a message that looks like:

```
[WARNING] Date retrieval for opam:local-file using
[WARNING] git log --name-only --diff-filter=A --reverse --pretty=format:%ct -- */opam
[WARNING] failed with:
# opam-version         1.1.1
# os                   linux
# command              git log --name-only --diff-filter=A --reverse --pretty=format:%ct -- */opam
# path                 /home/dsheets/.opam/repo/local-file
# exit-code            128
# env-file             /home/dsheets/.opam/log/log-7922-5a61c5.env
# stdout-file          /home/dsheets/.opam/log/log-7922-5a61c5.out
# stderr-file          /home/dsheets/.opam/log/log-7922-5a61c5.err
### stderr ###
# fatal: Not a git repository (or any of the parent directories): .git
[WARNING] Couldn't retrieve creation date for:
```

followed by a huge list of packages. I believe this is because the repository kind is set to `local` rather than `git`. I.e.:

```
$ opam remote
   0 [local]    default     /home/buildpreview/opam-repository
```

Please change the repository to use opam's git backend with the `-k git` flag.

**Comment by pw374** [comment]
Ok, I've just done that:

```
opam remote remove default
opam remote -k git add default /home/buildpreview/opam-repository
```

**Comment by dsheets** [comment]
It appears to be fixed now. Thanks!

**Comment by pw374** [comment]
great! thanks for your help!
