### ISSUE TITLE
import OCaml Sidebar for Mozilla

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#45]
Import Inria's [OCaml Sidebar for Mozilla](http://caml.inria.fr/resources/mozilla-sidebar.en.html) page directly into ocamlweb, perhaps into documentation.html.

**Comment by Chris00** [comment]
Did you check it is still working on recent versions of firefox?

**Comment by voila** [comment]
Does not work in the latest Firefox (18)

**Comment by agarwal** [comment]
Probably this code is bit-rotten. Closing this issue.
