### ISSUE TITLE
Use "replace" in hashtables tutorial

### ISSUE THREAD

**Issue by talex5** [ocaml/v2.ocaml.org#452]
The [Hash Tables](http://ocaml.org/learn/tutorials/hashtbl.html) tutorial uses "Hashtable.add" in its examples:

```
Hashtbl.add my_hash "h" "hello";
Hashtbl.add my_hash "h" "hi";
Hashtbl.add my_hash "h" "hug";
Hashtbl.add my_hash "h" "hard";
```

Everything seems normal, until the end where it suddenly reveals that all the old values are still there (using `Hashtable.find_all`). To anyone familiar with other languages, this looks like a memory leak.

I think the tutorial should first introduce the `replace` function, which works the way most people would expect, before giving the current `add` example.

**Comment by Chris00** [comment]
What you ask amounts to rewrite the whole tutorial.  I mentioned `replace` at the end, hoping that it is enough, at least for the medium term.  (If you do not feel so, please reopen this issue.)

**Comment by talex5** [comment]
I think that's fine - thanks!
