### ISSUE TITLE
Table formatting problem in Data Types and Matching tutorial

### ISSUE THREAD

**Issue by talex5** [ocaml/v2.ocaml.org#456]
This should be a table or a `<pre>` block:

http://ocaml.org/learn/tutorials/data_types_and_matching.html#Listsstructuresandvariantssummary

**Comment by Chris00** [comment]
Not sure what you mean.  It **is** a `<pre>` block.

**Comment by talex5** [comment]
Hmm, that's strange. Maybe it's some browser setting then, but `<pre>` blocks normally render in a monospace font for me. This is what it looks like here:

![table](https://cloud.githubusercontent.com/assets/554131/2588097/663bfdec-ba33-11e3-9b54-982875031365.png)

**Comment by Chris00** [comment]
The font for `<pre>` blocks is declared here: https://github.com/ocaml/ocaml.org/blob/master/site/css/bootstrap.css#L831

**Comment by pw374** [comment]
This is how it looks like on my browser (Safari on OS X.9.2).
The font is also different for the header “Lists, …”.
Is your browser doing something weird with style sheets?
I wonder if other parts of the website are also affected.

**Comment by Chris00** [comment]
Here is how it looks in my browser (Firefox, Debian):
![lists-summary](https://cloud.githubusercontent.com/assets/1255665/2588357/2b450bd8-ba39-11e3-8d90-14ec1af6199a.png)

**Comment by pw374** [comment]
It seems my screenshot didn't make it via email, here it is for sure:
![screen shot 2014-04-02 at 08 14 41 am](https://cloud.githubusercontent.com/assets/3776012/2588373/56a1e8f0-ba39-11e3-93fe-d1437d3b37d0.png)

**Comment by talex5** [comment]
I think the problem is here, in ocaml.css:

```
code, .gutter pre { font-family: "Droid Sans Mono", sans-serif; }
```

This rule for `<code>` overrides the `monospace` rule for `<pre>`.

**Comment by Chris00** [comment]
Thanks.  I required a mono-space font.  Please reopen if the problem subsists.

**Comment by talex5** [comment]
It's fixed for me now - thanks!
