### ISSUE TITLE
SVG graphics for the site

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#459]
@Chris00 pointed out that we need SVG icons for the site.  I think it's also worth getting a couple more made.  Please let me know if I missed any or if you think we need any more.  I'll be informing the design firm today about these.

**Existing icons**
- [x] ![Learn](http://ocaml.org/img/learn-large.png) (learn)
- [x] ![Docs](http://ocaml.org/img/documentation-large.png) (docs)
- [x] ![Platform](http://ocaml.org/img/platform-large.png) (platform/packages)
- [x] ![Community](http://ocaml.org/img/community-large.png) (community)
- [x] ![try ocaml](http://ocaml.org/img/learn-ocaml.png) (try ocaml)
- [x] ![announcement](http://ocaml.org/img/announcement.png) (announcement)
- [x] ![news](http://ocaml.org/img/news.png) (news)
- [x] ![manual](http://ocaml.org/img/manual.png) (manual)
- [x] ![license](http://ocaml.org/img/license.png) (license)
- [x] ![package docs](http://ocaml.org/img/documents.png) (package docs)
- [x] ![cheat sheets](http://ocaml.org/img/cheat.png) (cheat sheets)
- [x] ![edit](http://ocaml.org/img/edit.png) (edit)
- [x] ![edit hover](http://ocaml.org/img/edit-hover.png) (edit hover)
- [x] ![news go](http://ocaml.org/img/news-announcement-go.png) (news go)
- [x] ![search](http://ocaml.org/img/search.png) (search)

**To create**
- [x] Calendar item (to replace those on the [community page](http://ocaml.org/community/))
- [x] Email item (to replace those on the [community page](http://ocaml.org/community/))

**Comment by avsm** [comment]
one for iocaml perhaps? see andrewray/iocaml#15 , /cc @andrewray

**Comment by amirmc** [comment]
FYI This is now with the design firm.

**Comment by amirmc** [comment]
I have all these icons as SVG files now. @Chris00, you should be able to [download them here](https://dl.dropboxusercontent.com/u/486678/svg-icons.tar.bz2).

**Comment by Chris00** [comment]
One that we forgot is `rss.png` ![RSS](http://ocaml.org/img/rss.png) — not a big deal I think.

**Comment by Chris00** [comment]
SVG logo used 462baeb

**Comment by Chris00** [comment]
The RSS icon is now SVG (when the browser supports it).
