### ISSUE TITLE
The main documentation page is missing a link to install

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/v2.ocaml.org#461]
Came to `ocaml.org` seeking for ocaml install instructions, immediately clicked on the toplevel `Documentation` expecting to find links for installing ocaml on that page. Nothing. There should be a link to this in the `References` section. In the fat footer aswell it should be the _first_ thing in the documentation section. Install, install, install, install, install it should be available from quickly from any page everywhere.  I would even suggest that it should be an entry in the toplevel menu.

Besides on that main `Documentation` page the section `Summary` is useless and only losing my time. The first paragraph paraphrases what this page should be. The second one seems to go into nitty gritty details unimportant at that point: you're talking me about packages I don't even know what these packages are yet.

**Comment by amirmc** [comment]
I agree that the `Documentation` should contain a download link (in the reference section). 
Also concur that the 'Summary' section is not particularly useful but I'm not sure what I could write there (suggestions welcome).  I tried playing around with some changes but hit other issues so will revisit this once I get past those.

Having said the above, I'm curious about whether you noticed the 'Download OCaml' button on the front page?

**Comment by dbuenzli** [comment]
Le dimanche, 13 avril 2014 à 19:20, Amir Chaudhry a écrit :

> I agree that the Documentation should contain a download link (in the reference section).  
> Also concur that the 'Summary' section is not particularly useful but I'm not sure what I could write there (suggestions welcome). I tried playing around with some changes but hit other issues so will revisit this once I get past those.  
> Having said the above, I'm curious about whether you noticed the 'Download OCaml' button on the front page?

Mmmh absolutely not… blindspot. Maybe if the button had been 'Install OCaml' I would have seen it as I was looking for windows install _instructions_, not downloading ocaml.

Best,

Daniel

**Comment by amirmc** [comment]
I've no objection to renaming that button to "Install OCaml" if that's better.  We should still make an effort to put more such links in sensible places (i.e on the Docs page, as you suggest, and maybe the footer too).

**Comment by dbuenzli** [comment]
About the button not sure, I think most people look for 'download', my use of the website was "non standard", but yes having docs/footer links should be done.

**Comment by Chris00** [comment]
On Sun, 13 Apr 2014 10:50:32 -0700, Amir Chaudhry wrote:

> I've no objection to renaming that button to "Install OCaml" if that's better.

I am fine with that too.

> We should still make an effort to put more such links in sensible places (i.e on the Docs page, as you suggest, and maybe the footer too).

And write a good installation page!  Any help is appreciated!

**Comment by Chris00** [comment]
Maybe “Download & Install” (“OCaml” seems to be superfluous on the front page—which already mentions it clearly—and may be removed if the button gets too large).
Most [other](http://www.haskell.org/haskellwiki/Haskell) [sites](http://www.scala-lang.org/) [use](https://www.ruby-lang.org/en/) [download](https://www.python.org/), so I think that word should remain.

**Comment by agarwal** [comment]
I think we should also change the front button to say "Install OCaml". The page it links to barely mentions downloading all the way at the bottom. Also, I think "Install" still clearly indicates this is where you should go to figure out how to get OCaml running for yourself. "Download & Install" seems unnecessarily verbose to me.

@Chris00 if you don't object, I'll make this change, so we can close this issue.

**Comment by Chris00** [comment]
On Sun, 8 Jun 2014 13:21:26 -0700, Ashish Agarwal wrote:

> I think we should also change the front button to say "Install OCaml". The page it links to barely mentions downloading all the way at the bottom. Also, I think "Install" still clearly indicates this is where you should go to figure out how to get OCaml running for yourself. "Download & Install" seems unnecessarily verbose to me.
> 
> @Chris00 if you don't object, I'll make this change, so we can close this issue.

OK.

**Comment by agarwal** [comment]
I've added a link to the Install page on the main Docs page and the footer in 15c072397159456e49f95cf4068b81703bc4d279, and changed the front button to say Install in fd554f76aba7d13002b3758c07269af60673dad6. I think that reasonably addresses this issue.

**Comment by Chris00** [comment]
For the "documentation" header in the footer, wouldn't a better order be
- Install
- Manual
- Packages
- Compiler Sources

**Comment by dbuenzli** [comment]
Absolutely...
