### ISSUE TITLE
make fails locally

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#462]
I'm trying to build the site locally but can't figure out what I'm doing wrong. I run `make` from the root directory and somewhere it fails. The error output is below for `make production` (error is the same) but it doesn't help me find the underlying issue. @pw374, can you help?

```
Error: exception <Sys_error("/var/folders/gd/bdnlf1ld21g4ynlctmqgml5h0000gn/T/tmp02060fplop: Too many open files")>
make[2]: *** [ocaml.org/about.html] Error 3
rm template/front_code_snippet.html template/learn_code_snippet.html
make[1]: *** [gen_md] Error 2
make: *** [production] Error 2
```

Details:
- OSX 10.8.5
- XCode 5.1.1
- OPAM 1.1.1
- OCaml 4.01.0 (via homebrew)

**Comment by pw374** [comment]
This looks like the system needs to be rebooted (and it easily happens with OS X). I'll try and do further investigation later this evening.

Philippe Wang
(mail sent from a phone)

**Comment by amirmc** [comment]
I rebooted the system but have almost the same error. The only difference is the name of the `tmpXXXXXXplop` file in the folder.

**Comment by pw374** [comment]
Then there might be a more serious bug somewhere…
Does it happen with all versions of ocaml.org?

I’m going to try and build ocaml.org on my OSX now and see what it does...

**Comment by pw374** [comment]
Now I think I fully understand the issue.
1. OS X can't open many files
2. ocaml.org makes MPP open too many files for OS X. So I have to make MPP open fewer files.

So, I'm going to change how MPP handles some things...

**Comment by Chris00** [comment]
On Sun, 13 Apr 2014 10:46:02 -0700, Amir Chaudhry wrote:

> I rebooted the system but have almost the same error. The only difference is
> the name of the tmpXXXXXXplop file in the folder.

Do you compile with “make” or “make -j”?

**Comment by pw374** [comment]
MPP 0.1.5 (https://github.com/ocaml/opam-repository/pull/1895) should fix that bug.

**Comment by pw374** [comment]
On 13 Apr 2014, at 19:43 pm, Christophe Troestler notifications@github.com wrote:

> On Sun, 13 Apr 2014 10:46:02 -0700, Amir Chaudhry wrote:
> 
> > I rebooted the system but have almost the same error. The only difference is
> > the name of the tmpXXXXXXplop file in the folder.
> 
> Do you compile with “make” or “make -j”?

It could have been caused by `make -j` but it’s really a limitation of OS X combined with a poor implementation of a key function in MPP.
The only reasonable fix was to give a proper implementation of that key function in MPP.

And as a bonus we have 2 side-effects: speed up the build of ocaml.org and security improvement. :-)

**Comment by amirmc** [comment]
> Do you compile with “make” or “make -j”?

It was just `make` (but I did also try `make -j` just to see. It throws up _way_ more exceptions - all of the form "Too many open files").

**Comment by pw374** [comment]
It's very unlikely in any reasonable configuration that `make -j` raises fewer problems than `make`.

On my side, MPP 0.1.5 fixes this issue but @amirmc please close this issue when you can confirm that it works.

You can wait for MPP 0.1.5 to get to opam, or do something like 

``` bash
opam remote add pw374 https://github.com/pw374/opam-repository.git
opam install mpp.0.1.5
```

**Comment by amirmc** [comment]
I added the opam remote. Site now builds, thanks!

Aside: should `make -j` also work on OSX? I now get the following error:

```
++ Building the package infos: 2189 /2189
rm template/front_code_snippet.html template/learn_code_snippet.html
make[2]: *** [gen_md] Error 2
make[1]: *** [staging] Error 2
make: *** [local] Error 2
```

**Comment by pw374** [comment]
`make -j` should work. If it doesn't, it's a bug. On my machine, it works.

When you're in `ocaml.org/` (not `ocaml.org/ocaml.org`), do you have a `../opam-repository/`? If it's missing, it might be that (and if it's that, I guess it's because opam2web tries to build the list of packages and fails because it can't find `../opam-repository`)

**Comment by samoht** [comment]
Why not using `https://github.com/ocaml/opam-repository.git` as a repository instead of a local one ?

**Comment by amirmc** [comment]
I don't have an `opam-repository`repo alongside my `ocaml.org` repo. The script must use my opam install because the front page of the generated site tells me mpp 0.1.5 is the newest package (it wasn't merged at the time of build).

I need to figure out how that works so that I can continue with #463.

**Comment by pw374** [comment]
> Why not using `https://github.com/ocaml/opam-repository.git` as a repository instead of a local one ?

I guess it’s because you don’t want to clone the whole repository each time the list is generated, and instead just get the diff, also if you use a local repo it's easier to decide whether you need to update your list. However I don't know that well the opam2web part. @dsheets any thoughts?

**Comment by Chris00** [comment]
Yes, "make -j" should work everywhere.  I guess there is a dependency that is not expressed correctly.  Usually running "make -j" again finishes the build but the error should not happen in the first place.

**Comment by pw374** [comment]
@amirmc could you post the complete build outputs somewhere?

**Comment by amirmc** [comment]
Two files at: https://gist.github.com/amirmc/10600379

First is the result of `make clean && make -j` and the second is after another `make -j`

**Comment by pw374** [comment]
On 13 Apr 2014, at 21:14 pm, Amir Chaudhry notifications@github.com wrote:

> Two files at: https://gist.github.com/amirmc/10600379
> 
> First is the result of make clean && make -j and the second is after another make -j

The first one has many lines with 
"bash: fork: Resource temporarily unavailable"

which means you’re forking too many processes… which is a common error with `make -j`

Could you try `make clean && make -j 4` ?

where 4 is an arbitrary number to limit the number of parallel makes, you could try 2, 3, 8, …
When -j isn’t given a number, it basically forks without limit and may just fail if the children (processes) of `make` also create many processes…

**Comment by amirmc** [comment]
That works. I've tried several values and it falls over somewhere between 64 and 128 (on my system). Thanks for the clarification, I'll close this now (the opam-repo question belongs elsewhere).

**Comment by Chris00** [comment]
On Sun, 13 Apr 2014 13:21:23 -0700, Philippe Wang wrote:

> The first one has many lines with
> "bash: fork: Resource temporarily unavailable"
> 
> which means you’re forking too many processes… which is a common error with
> `make -j`
> 
> Could you try `make clean && make -j 4` ?

Maybe we should add that advice in the README to help other people who might encounter similar problems.

**Comment by amirmc** [comment]
Good idea. I'll add it directly.

**Comment by amirmc** [comment]
done in https://github.com/ocaml/ocaml.org/commit/09916c9027ee3b14e48cee131326c2e51a94918c

**Comment by pw374** [comment]
On 13 Apr 2014, at 21:35 pm, Christophe Troestler notifications@github.com wrote:

> On Sun, 13 Apr 2014 13:21:23 -0700, Philippe Wang wrote:
> 
> > The first one has many lines with
> > "bash: fork: Resource temporarily unavailable"
> > 
> > which means you’re forking too many processes… which is a common error with
> > `make -j`
> > 
> > Could you try `make clean && make -j 4` ?
> 
> Maybe we should add that advice in the README to help other people who might encounter similar problems.

To keep it short, we could simply replace `make -j` by "`make -j N` where N is the number of core of your machine”.

My guess is that `-j` (unlimited) will not be faster than `-j N` on most standard machine (because there are so many things that don’t go faster when there are too many concurrent parallel processes: disk accesses will block a lot in those processes, 32-bit kernels will often refuse to fork and/or die, memory bandwidth is divided between concurrent parallel processes, etc.).

**Comment by pw374** [comment]
I think that make -j 64  is a bad idea. 64 only makes sense on a 64 core machine (which I bet are not often used to build ocaml.org), or when a lot of those processes spend a _lot_ of time waiting on (slow) blocking operations (typically network communication).

If we want to put a constant number, we should put a smaller one, and I wouldn’t put any number greater than 8.

**Comment by amirmc** [comment]
It's now `make -j 8`

**Comment by dbuenzli** [comment]
On linux and osx you could set it to `getconf _NPROCESSORS_ONLN`.
