### ISSUE TITLE
Run builds on Travis CI

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#463]
As a result of a local problem (#462), I tried to run a build on Travis. It does pass but there may still be things that need to be fixed.  I'm doing this on a fork and the console output can be seen at https://travis-ci.org/amirmc/ocaml.org if anyone cares to take a look.

The next step is to commit/rsync the resulting static site into another 'deploy' repo.

**Comment by Chris00** [comment]
On Sun, 13 Apr 2014 10:14:14 -0700, Amir Chaudhry wrote:

> there may still be things that need to be fixed. [...] https://travis-ci.org/amirmc/ocaml.org

May you be more precise?

**Comment by amirmc** [comment]
You can see the outputs of all the builds on Travis and I've only run two so far but they both completed successfully [1].  However, both builds have had some kind of problem with the opam files step [2, 3] and it wasn't immediately clear to me if it was an omission on my part (do I need to configure the git user in travis?) or if it's something else (the script making assumptions about the environment).

Until I get the output files deployed somewhere, I can't visually inspect the site and I'm not sure if this is the only problem.  Apologies, that I can't be more specific at the moment.

[1] https://travis-ci.org/amirmc/ocaml.org
[2] https://travis-ci.org/amirmc/ocaml.org/builds/22892470#L568
[3] https://travis-ci.org/amirmc/ocaml.org/builds/22893218#L924

**Comment by pw374** [comment]
As far as I know, the ocaml.org scripts will not make on their own a clone of an opam repository in order to build the list of recent opam packages updates. That may explain why you have those many lines with `[WARNING] …`

So in your travis script you’d need to clone that repo, and do it in the right location...

**Comment by agarwal** [comment]
#241 requests to set up Travis CI, so closing this one.
