### ISSUE TITLE
Add Esper logo

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#467]
I notice that Esper has a logo so we should add it to the companies page.

@mjambon, I notice different variants on the website and the github repo. Is there a preferred one I should use? (assuming you're ok with me doing this).

**Comment by mjambon** [comment]
Nick (@nychen),

Could you please send me an Esper logo suitable for the following page 
(white background) next to the description of our company?

or you can put it directly into the git repository at 
https://github.com/timeco/ocaml.org

Thanks,

Martin
