### ISSUE TITLE
Import French mailing list page

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#47]
The page [Forums où l'on parle de Caml](http://caml.inria.fr/resources/forums.fr.html) should be imported — uit is referred by the "companies" page.

**Comment by eelsther** [comment]
Do you mean that  we should import it in our French mode ?

**Comment by Chris00** [comment]
Yes.

**Comment by eelsther** [comment]
How do I do that ?
Do I just need to create a file named mailing_lists.fr.html and put the french content in it ?

**Comment by Chris00** [comment]
On Tue, 4 Sep 2012 06:41:54 -0700, Esther wrote:

> Do I just need to create a file named mailing_lists.fr.html and put
> the french content in it ?

Yes.

**Comment by eelsther** [comment]
commit 5f2458b

**Comment by Chris00** [comment]
Great!
