### ISSUE TITLE
Add URL to the planet

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/v2.ocaml.org#481]
- Name: Daniel Bünzli (log)
- URL: http://erratique.ch/log/feed.atom
- Type: personal

Thanks !

**Comment by dbuenzli** [comment]
Ping. Is there a way for me to provide a PR to add the feed myself ?

**Comment by agarwal** [comment]
We forward these requests to ocamlcore. I've just submitted it [here](https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1396&group_id=1&atid=101).

**Comment by dbuenzli** [comment]
Ah thanks !

**Comment by agarwal** [comment]
I'll leave this open, so we can make sure it gets done.

**Comment by gildor478** [comment]
Actually planet.ocaml.org already has a feed:
http://erratique.ch/feeds/news.atom

I have added the new "(log)" entry...

**Comment by dbuenzli** [comment]
@gildor478 Thanks for the add. You are right but they are different things, the erratique feed is for updates about the website and release announces. The log is for longer blurbs about ongoing work. (And for technical reasons making an aggregate feed of the two is more work than it should be).
