### ISSUE TITLE
add Rackspace to credits page

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#483]
Rackspace donates hosting, so they should be added to the credits page. Should we also add to footer? Should OCaml Labs is also be mentioned?

**Comment by amirmc** [comment]
Just the credits page IMHO.  I don't think we need to call out OCaml Labs either, the individuals who've contributed are already (and automatically) represented.

**Comment by agarwal** [comment]
I pushed a commit, but I'll let @amirmc review it as he wanted to consider the wording.

**Comment by amirmc** [comment]
Looks good to me! Thanks for speedy commit, closing this issue.
