### ISSUE TITLE
fix Making_plugins.md page

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#486]
Content in learn/tutorials/ocamlbuild/Making_plugins.md gets duplicated during processing. Note sure why. Possibly OMD is doing something because the content was also duplicated in my [initial import](7f445245fddfc6eb420dd24e3f0bb11f20bad3e6), where I had used OMD to convert pages to get the Markdown in the first place. The source page was fixed in 7970f65d0559a33d320f6960dda5a7561b8fad0b, but we're still getting content duplication in the output html.

**Comment by dsheets** [comment]
This was also reported at #558 and was due to ocaml/omd#134. Pull request #559 is pending to fix this issue. Closing.
