### ISSUE TITLE
<pre> spaces

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#49]
It seems that editor modes do not cope well with &lt;pre&gt; tags.  Should we use weberizer to process these tags, removing the spaces at the beginning of the lines and removing all white space (including newlines) before &lt;/pre&gt;?

**Comment by agarwal** [comment]
Space at the beginnings of lines could be deliberate indentation. Removing newlines before </pre> is probably always ok. But is it worth automating? We can instead think of content within <pre> tags to be verbatim text, and so have to write it exactly as intended.

**Comment by Chris00** [comment]
OK.  I posted this because I got frustrated porting the pages of the tutorial which contains many such problems.  I have now indeed used the fact that spaces at the beginning of lines are significant.
