### ISSUE TITLE
Add TrustInSoft to companies list

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#496]
See recent thread in caml-list on TLS announcement.

**Comment by amirmc** [comment]
Ugh, not on caml-list. In my inbox. #needcoffee

**Comment by agarwal** [comment]
Did their email include text that could be used? Else, from their website I think it is reasonable to infer all of their development is in OCaml. Along with the general description of their goals, that should be enough.

Note: I'm avoiding contacting each company when we add them now. I think that is reasonable, and so far whenever we contact a company it has been very slow to get a response.
