### ISSUE TITLE
Redirect ocaml-lang.{org | com} to ocaml.org

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#499]
It's just been pointed out to me that http://ocaml-lang.org and http://ocaml-lang.org redirect to http://ocaml.ocamlpro.com

This is very confusing for anyone who inadvertently finds their way to that URL.  We've done a lot of work over the last year to (successfully) raise the profile of OCaml and we should ensure that all links to the language point back to http://ocaml.org.

Who manages these domains? I thought it was @agarwal but `whois` tells me that it's `Muriel Shan Sei Fan` but I don't know who that is.  @lefessan, would you be able to help with this?

**Comment by lefessan** [comment]
Hi Amir,

Muriel Shan Sei Fan (@MuSSF) is the CEO of OCamlPro. I understand your concern, you want more visibility for ocaml.org, but we have exactly the same concern, as a commercial entity doing all its business on OCaml, OCamlPro needs visibility in the OCaml world (yes, some people don't know that we exist, or don't know what we have done and what we can do for them), and ocaml.org, as a neutral website, cannot provide this visibility (and also the freedom on the content that we can put on ocaml.ocamlpro.com). You are welcome to put a huge blinking OCamlPro logo on ocaml.org front page, but some people in the community might not like it, and unless you manage to convince them, these redirections are the least expensive way we have to increase OCamlPro's visibility for OCaml users. Note that we redirect them immediatly to ocaml.org, if they are looking for the community website.

**Comment by agarwal** [comment]
I kind of agree with @lefessan. It's his domain and he is free to use it how he wants to. We also have http://ocaml.io forwarding to OCaml Labs, which I think is fine.

Had the same issue arisen for http://ocaml.org, I might have argued differently. The domain _ocaml.org_ is too encompassing to be claimed by some subset of the community. However, it's probably not fair for the community to claim ownership over all variations; there is still _ocaml-language.org_, _ocaml-programming.com_, _ocaml.in_, etc. They are free for the taking!

**Comment by avsm** [comment]
Yes, that's a good point.  I wonder if ocaml.io is a little worse to redirect to OCaml Labs than the OCamlPro redirect.  I pretty much set it up as a quick alias without much thought about what to use the domain for aside from a less unwieldy way to href to OCL when it was getting started.

**Comment by agarwal** [comment]
I can't think of any other use for ocaml.io at this time, so redirecting to OCaml Labs seems quite fine to me.
