### ISSUE TITLE
pleac: port content into repo

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#5]
Contact author of [Pleac](http://pleac.sourceforge.net/pleac_ocaml/) and request that content be imported directly into ocamlweb repo, and current [link](http://pleac.sourceforge.net/pleac_ocaml/) should be changed to re-direct to new page on this site.

**Comment by Chris00** [comment]
Each language variant is sotred in a single file http://pleac.cvs.sourceforge.net/viewvc/pleac/pleac/pleac/   I do not think they will update the links to point to our site (it is still a moving target anyway) but that may allow us to use the ocaml file to generate pages on our site.  One should of course refer to their site on each of these pages.

Provided we have a agreement with them, all that remains to do is to write a script that transform their syntax to HTML (and colorize the code).   http://pleac.cvs.sourceforge.net/viewvc/pleac/pleac/pleac/sample.data?revision=1.5&view=markup

**Comment by agarwal** [comment]
This is another example of an unjustified desire to have the full site self-contained. Given how big the OCaml community is now, this isn't feasible (a good thing). Thus, closing this issue as a _will-not-do_.
