### ISSUE TITLE
Cross references

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#50]
The Inria web site has many cross links that allow you to see oages of related interest.  See the “Related Pages” box on e.g. [A Hundred Lines of Caml](http://caml.inria.fr/about/taste.en.html).  We should aim to provide such rich navigation possibilities.

**Comment by agarwal** [comment]
Any idea how they are implementing this?

**Comment by Chris00** [comment]
Probably ba hand... (but we can ask!)

**Comment by agarwal** [comment]
@Chris00 I consider this too difficult to do even once, and even more difficult to keep maintained. If you agree, let's consider this a _will-not-do_ and close this issue.
