### ISSUE TITLE
Need first step tutorial for OCaml

### ISSUE THREAD

**Issue by ghost** [ocaml/v2.ocaml.org#500]
A good first step tutorial
http://caml.inria.fr/pub/docs/u3-ocaml/ocaml-steps.html

I have no idea how to deal with OCaml, till i read this .
I installed OCamal from yum (or zypper), it's ok, but how to write one piece of code? i have not idea.
There be very hard if you not read the first hello world tutorial.

Why not add this to Learn page?

I am very new to OCaml, how can we understand how to wrote code with OCaml.
Please add it to Learn OCaml, it's very useful for newbie.

**Comment by ghost** [comment]
The first things we want to know when learn new programming language:
1. how to wrote hello world?
2. how to compile it ? or run it ?
3. if it has a interactive console, how to open it and how to leave it ?

**Comment by Chris00** [comment]
On Thu, 24 Jul 2014 22:39:03 -0700, netroby wrote:

> A good first step tutorial
> http://caml.inria.fr/pub/docs/u3-ocaml/ocaml-steps.html
> 
> I have no idea how to deal with OCaml, till i read this .
> I installed OCamal from yum (or zypper), it's ok, but how to write one piece of
> code? i have not idea.
> There be very hard if you not read the first hello world tutorial.

Did you try to read one of the books on the page http://ocaml.org/learn/ ?  "Real World OCaml" is even available online for free.

**Comment by LuoZijun** [comment]
Ocaml tutorials(chinese lanuage): http://ocaml.org/learn/tutorials/index.zh.html
很适合入门。

**Comment by ghost** [comment]
I know i can read this book. but the official document should improve. 
The OCaml tutorial is not prepared for very new starter. who may not learn other programming language.
