### ISSUE TITLE
Add "http://www.ocamljava.org/feed.xml" to planet

### ISSUE THREAD

**Issue by xclerc** [ocaml/v2.ocaml.org#501]
This is (obviously) the feed for the OCaml-Java project...

thanks,

Xavier

**Comment by agarwal** [comment]
Submitted [upstream](https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1413&group_id=1&atid=101). Leaving this open till we confirm it is done.

**Comment by Chris00** [comment]
Processing feeds is being rewritten which will make this a simple pull request.

**Comment by agarwal** [comment]
The upstream ticket is closed, but I don't see it working yet. Maybe it takes a little while to take effect. Let's check tomorrow.

**Comment by Chris00** [comment]
The headlines show when building the site with the [syndic](https://github.com/ocaml/ocaml.org/tree/syndic) branch.
@xclerc could you add a copy of your posts in the feed?  Otherwise, only the title show on the planet page which is a bit odd.

**Comment by xclerc** [comment]
Not sure what you mean by "add a copy of (the) post in the feed".
The current feed contains a summary tag; shouldn't that be enough?

For the record, the `summary` tag has the following form:

```
<summary type="html"><p>actual post summary</p></summary>
```

**Comment by Chris00** [comment]
Right.  You used `<summary type="html">` while the parser expected `<summary type="xhtml">`.  I fixed the parser.  I am not sure `<summary type="html">`` is allowed by the spec though.  Do you have a reference?

**Comment by dbuenzli** [comment]
@xclerc @Chris00, `html` is allowed by the spec but then the html should be escaped which is not the case in that feed. See [here](http://tools.ietf.org/html/rfc4287#section-3.1.1.2) for the reference.

**Comment by Chris00** [comment]
@dbuenzli Thanks — I somehow managed to miss that! :-(

**Comment by Chris00** [comment]
It shows in the feed list of the website, so closing this.

**Comment by xclerc** [comment]
Thanks for adding the feed.
Please note that it is now properly escaped.
