### ISSUE TITLE
Add platform blog to Planet

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#504]
http://opam.ocaml.org/blog/feed.xml

This is submitted upstream. Placeholder here to keep track of it.
https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1416

**Comment by amirmc** [comment]
This is closed upstream so I assume it's merged.  Not sure how to double-check since examining the Planet RSS feed only takes me as far as 28 Jul (the OPAM post is dated for Jan).

**Comment by Chris00** [comment]
On Mon, 11 Aug 2014 03:00:30 -0700, Amir Chaudhry wrote:

> This is closed upstream so I assume it's merged. Not sure how to 
> double-check since examining the Planet RSS feed only takes me as 
> far as 28 Jul (the OPAM post is dated for Jan).

If it appears in the "Syndications" list, I think this is fine.

**Comment by amirmc** [comment]
I can see it now on http://planet.ocamlcore.org - closing this issue.
