### ISSUE TITLE
tutorial for recursive types (content request)

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/v2.ocaml.org#505]
Some example and exercices where recursive types are needed (and unavoidable).

**Comment by dinakajoy** [comment]
I would love to know if this issue is still open, I might be able to come up with something

**Comment by UnixJunkie** [comment]
Yes it is.

**Comment by pitag-ha** [comment]
To also add a comment from the Outreachy mentor's side: this would be a great issue for you to work on @dinakajoy , if you can come up with something nice! :) Don't hesitate to ask here if you have any doubts about something.

**Comment by dinakajoy** [comment]
Thank you @pitag-ha, I will update you on whatever I come up with before adding it up for a PR

**Comment by pitag-ha** [comment]
Perfect! :) If you have concrete ideas, you can also directly open a PR and we can discuss there. I just wanted to let you know that it would also be ok if you had less concrete ideas and wanted discuss them with us.

**Comment by dinakajoy** [comment]
@pitag-ha from my research so far, a good place to add a recursive type is when writing a custom linkedlist.
As it can be empty or a list of similar types.
For example: 
`type 'a a_linkedlist = Nil | List of ('a * 'a a_linkedlist);;`
What do you think about this?

**Comment by pitag-ha** [comment]
@dinakajoy, thanks for the research you've done! Yes, I think a custom linked list would be a great example, since there's no way to implement it without recursive types (or at least none I could think of), it's simple and most people know what it is. Where about in the tutorials would you add it?

**Comment by pitag-ha** [comment]
I've just seen that there already is a similar example in the tutorials: see [here](https://ocaml.org/learn/tutorials/data_types_and_matching.html#Recursive-variants-used-for-trees).

@UnixJunkie, were you aware of that when filing this issue? :) If so, what did you have in mind with this issue?
