### ISSUE TITLE
`make -j` fails

### ISSUE THREAD

**Issue by dsheets** [ocaml/v2.ocaml.org#508]
The README suggests it but it doesn't work.

**Comment by Chris00** [comment]
On Thu, 14 Aug 2014 08:46:48 -0700, David Sheets wrote:

> The README suggests it but it doesn't work.

Yes, I know.  I'll have to track that down.  I wonder whether is has
something to do with the cache files not being locked but I have not
found the time to investigate that.

**Comment by dbuenzli** [comment]
Wasn't there a discussion about that a long time ago with @amirmc ?
