### ISSUE TITLE
TLS: Include complete cert chain

### ISSUE THREAD

**Issue by dsheets** [ocaml/v2.ocaml.org#513]
From @hannesm on the infrastructure list:

> - Chain issues     Incomplete This requires another download of the
>   Gandi Standard SSL CA cert. Maybe we should bundle this cert for
>   all our TLS sites?

Yes, that should be done. While my firefox does not complain about the
certificate chain (most likely it already has ghandi's certificate
installed), the server should distribute the chain up till the
self-signed CA certificate -- thus please include ghandi's cert.

**Comment by dsheets** [comment]
This is causing real-world problems. See https://sympa.inria.fr/sympa/arc/caml-list/2014-09/msg00276.html. This must be resolved before we start propagating https://ocaml.org/

**Comment by hannesm** [comment]
agreed. seems like some browsers have gandi in their truststore (most likely because lots of domain administrators don't send the intermediate certificates over); also see https://www.ssllabs.com/ssltest/analyze.html?d=ocaml.org for some analysis

**Comment by agarwal** [comment]
@dsheets Can we close this issue?

**Comment by dsheets** [comment]
I believe this issue is no longer applicable as ocaml.org has switched from Gandi to Let's Encrypt.
