### ISSUE TITLE
TLS: Host non-HTTPS content

### ISSUE THREAD

**Issue by dsheets** [ocaml/v2.ocaml.org#515]
Content to mirror:
From https://ocaml.org/learn/:
http://caml.inria.fr/about/successes-images/unison-thumb.jpg
http://caml.inria.fr/about/successes-images/lexifi-thumb.png

Alternately, get caml.inria.fr to start serving on 443 with TLS...

**Comment by Chris00** [comment]
On Wed, 20 Aug 2014 08:37:49 -0700, David Sheets wrote:

> Content to mirror:
> 
> > From https://ocaml.org/learn/:
> > http://caml.inria.fr/about/successes-images/unison-thumb.jpg
> > http://caml.inria.fr/about/successes-images/lexifi-thumb.png
> 
> Alternately, get caml.inria.fr to start serving on 443 with TLS...

I am in favor to host them on the site — caml.inria.fr is supposed to be deprecated...  We could use this opportunity to take (or ask for Lexifi) more recent screenshots.

**Comment by agarwal** [comment]
Only `caml.inria.fr/pub` is active. All other URLs under caml.inria.fr are deprecated.

**Comment by agarwal** [comment]
The images you link to are not under caml.inria.fr/pub/, and thus should be ported to ocaml.org. I wouldn't call it "mirroring", which implies we're supposed to remain in sync with the original URLs. Rather, the previous URLs are no longer relevant.

**Comment by Chris00** [comment]
@alainfrisch Would you like to provide a more recent screenshot of your product?

**Comment by Chris00** [comment]
Unison images were [uploaded](https://github.com/ocaml/ocaml.org/commit/6898223730b9e84ecdf8f49ddc270fbf003046aa).

**Comment by alainfrisch** [comment]
@Chris00: Here is a more recent screenshot.

![picture1](https://cloud.githubusercontent.com/assets/3305274/6601498/4832ad04-c816-11e4-9bcf-32454b04fa5f.png)

Thanks!
