### ISSUE TITLE
add link to Learning OCaml, for C, C++, Perl and Java programmers

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#52]
Richard Jones apparently wrote a nice tutorials called Learning OCaml, for C, C++, Perl and Java programmers. The [link](Learning OCaml, for C, C++, Perl and Java programmers) is however dead. Find out if it still exists elsewhere, and add in `tutorials/index.html` under the _Coming From Another Language_ section.

**Comment by Chris00** [comment]
I think this is (became) http://mirror.ocamlcore.org/ocaml-tutorial.org/ that we started porting to the site...

**Comment by agarwal** [comment]
I don't see any tutorial here that is meant for people familiar with C,
C++, Perl, or Java, which is what [this page](http://lwn.net/Articles/36456/) implies the content was about.

**Comment by Chris00** [comment]
You can ask Richard but I still think that was the one.

**Comment by agarwal** [comment]
I've emailed Richard to confirm.

**Comment by agarwal** [comment]
Richard confirmed that this tutorial refers to the content on ocaml-tutorial.org. Thus we already have it.

**Comment by Chris00** [comment]
On Tue, 4 Sep 2012 08:40:53 -0700, Ashish Agarwal wrote:

> Richard confirmed that this tutorial refers to the content on
> ocaml-tutorial.org. Thus we already have it.

OK.  I think we can leave it as it is, without changing the name, as
more tutorials have already been added.

Some tutorials also $B!H(Bconflict$B!I(B with $B!H(BDev tools$B!I(B $B!=(B we have to sort that
out.  We also want to restructure the tutorial links with titles
indicating what must absolutely be read and what is more advanced or
pertain to subjects that are $B!H(Boptional$B!I(B (i.e. may not be of interest
to everybody).

**Comment by agarwal** [comment]
On Tue, Sep 4, 2012 at 1:36 PM, Christophe Troestler

Some tutorials also $B!H (Bconflict $B!I (B with $B!H (BDev tools $B!I (B

> $B!= (B we have to sort that
> out.

Are you using special characters? I'm getting garbled output like above,
and it also looks this way on github.

**Comment by Chris00** [comment]
Well, just “normal” UTF-8 chars like the opening quote “, the closing quote ” and the hypen —

When I type them directly in the web interface, it is OK but I tend to forget that github does work well with UTF-8 mails...

**Comment by Chris00** [comment]
Maybe a bug report for github developers is in order? (email is really convenient!)
