### ISSUE TITLE
sync ocaml.org-media on server

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#520]
As of #517, the ocaml.org-media repo is being used and needs to be synced to the server.

**Comment by Chris00** [comment]
I have cloned `ocaml.org-media` on the side of `ocaml.org` and modified `build_ocaml.org.bash` so that a pull for `ocaml.org-media`  is done before compiling.

P.S. I think it would be better if the scripts used to build the site were version controlled as well...

**Comment by avsm** [comment]
Yikes, these really should be in version control too... any reason why not?

**Comment by agarwal** [comment]
I've opened #532.
