### ISSUE TITLE
Add *More OCaml* book to front docs page?

### ISSUE THREAD

**Issue by dsheets** [ocaml/v2.ocaml.org#524]
Also, I think there was another issue somewhere about some recent OCaml book in French...

**Comment by Chris00** [comment]
Yes, there is space to add 2 more.  

For the record: http://www.amazon.com/More-OCaml-Algorithms-Methods-Diversions/dp/0957671113/
and http://ocaml-book.com/more-ocaml-algorithms-methods-diversions/

**Comment by Chris00** [comment]
French book: https://github.com/ocaml/ocaml.org/issues/445

**Comment by johnwhitington** [comment]
I have prepared a cover image for "More OCaml" at 300x376, which is the same size as the one you're using for "OCaml from the Very Beginning" on the books & documentation page:

http://www.coherentpdf.com/more-ocaml-300-376.png
