### ISSUE TITLE
Videos at OCaml 2014

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#527]
Continuation of #266.

I offered to email the organisers and ask about videos from this year's meeting. If there are no plans for video, then I'll email the caml-list and see if there are any volunteers who would be willing to do some recording. @Chris00 has offered to take care of post-processing as long as we can get the video files to him.

If there are no existing plans for video recording and/or no volunteers step forward, then it's unlikely we'll have video from this meeting. I just want to acknowledge this upfront so there are no misunderstandings.
- [x] AC to email chair of OCaml 2014

~~[ ] AC to email caml-list for volunteers (depending on outcome from above)~~ (<-- not needed)

**Comment by amirmc** [comment]
Apparently ICFP is doing the recording and I've also heard that @heidi-ann is specifically recording at OCaml 2014.  Heidi, can you tell us what you'll be doing with the recording once you're done?

**Comment by heidihoward** [comment]
I don't handle the upload, I just record

**Comment by Drup** [comment]
Videos will be [here](https://www.youtube.com/channel/UCP9g4dLR7xt6KzCYntNqYcw/videos) when available (should be tomorrow). Videos from the ML family workshop are already available.

**Comment by heidihoward** [comment]
Yes, the ICFP team have been very good at upload the videos. I'm hear now recording all the talks

**Comment by Chris00** [comment]
Links to the videos added 2a9ebf2

**Comment by Chris00** [comment]
Adding the PDFs of the slides to https://github.com/ocaml/ocaml.org-media would be nice too.

**Comment by Chris00** [comment]
Any chance of having the missing slides?
