### ISSUE TITLE
ocaml  OSX binary page link is broken

### ISSUE THREAD

**Issue by jaimelipton** [ocaml/v2.ocaml.org#528]
http://caml.inria.fr/pub/distrib/ocaml-4.02/ocaml-4.02.0-intel.dmg  gives a page not found error.

**Comment by agarwal** [comment]
This is an error on the caml.inria site, which we do not have control over. Probably best option is to reply to the email from Damien Doligez, which announced the 4.02 release.

**Comment by dbuenzli** [comment]
They are no longer doing binary distribution for osx, see [annoucement message](https://sympa.inria.fr/sympa/arc/caml-list/2014-08/msg00127.html) on the list. 

ccing @planar, the binary distribution links should be removed from [that page](http://caml.inria.fr/ocaml/release.en.html).

**Comment by agarwal** [comment]
Looping in @avsm, who pointed out:

> most of those links are broken (bin packages and man pages)
> 
> bin packages for 4.02 from here: http://software.opensuse.org/download.html?project=home%3Aocaml&package=ocaml

**Comment by agarwal** [comment]
I'll do the following:
- delete the sections _Precompiled binaries for Linux_ and _Precompiled binaries for MacOS X_.
- add a section _Binary distributions for Linux_, where I provide the link given by @avsm.
