### ISSUE TITLE
57/99 problems code

### ISSUE THREAD

**Issue by RjiukYagami** [ocaml/v2.ocaml.org#539]
I've been doing many of this tasks ( i mean 99 ocaml problem ) i and got into 57. problem. There is no code, but i've done it so someone might use it if find it usefull. It works but it's not the best code ever ofc. I've just started to learn OCaml, but code works and solve problem. 

https://github.com/emil3566/99-ocamls-problem/blob/master/src/50-59/57.Layout%20a%20binary%20tree%20%283%29.ml

Ofc if someone use it somewhere please consider fact that i'm an author :)

Follow me on Git, love :yellow_heart:

**Comment by Chris00** [comment]
Glad that the 99 problems were useful to your learning of OCaml.  It is easier to comment on pull requests, so, if you want feedback on your code, polish it as much as you can and submit a pull request.  Thanks.

**Comment by RjiukYagami** [comment]
Ok, i didn't know where to put it, in the nearest future i'll do that :)

**Comment by dsheets** [comment]
This is being tracked by #541. Closing.
