### ISSUE TITLE
Enable menu dropdown when the mouse is over the menu title

### ISSUE THREAD

**Issue by eelsther** [ocaml/v2.ocaml.org#55]
I would avoid clicking on the menu title to see its content.

**Comment by Chris00** [comment]
On Tue, 4 Sep 2012 06:43:58 -0700, Esther wrote:

> I would avoid clicking on the menu title to see its content.

Fine with me $B!=(B we'll see how it goes using that feature.

**Comment by Chris00** [comment]
https://github.com/twitter/bootstrap/issues/983

**Comment by agarwal** [comment]
This request is now moot since the new design does away with drop down menus, which @amirmc was strongly opposed to.  :)

**Comment by amirmc** [comment]
Indeed :)  #257 will go some way to reducing unnecessary clicks without the potential UI/UX issues caused by `:hover` tags.
