### ISSUE TITLE
fix publish script

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#550]
As reported [here](https://github.com/ocaml/ocaml.org/pull/548#issuecomment-58646218), the publish script is failing. The logs are:

stdout.log:

```
`make production` returned with  2
```

stderr.log:

```
Sat Oct 11 17:00:57 UTC 2014
timeout: failed to run command `opam': No such file or directory
/home/buildpreview/build_ocaml.org.bash: line 50: opam: command not found
make: ocamlfind: Command not found
make: *** [script/code_types.cmi] Error 127
rsync: change_dir "/home/buildpreview/ocaml.org//ocaml.org" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1070) \
[sender=3.0.9]
```

**Comment by agarwal** [comment]
The `opam` binary is located in /alien/bin, which is added to PATH only in .profile. Thus, I fixed this by passing `--login` to bash from within the cronjob. Not sure why the behavior would have changed recently.

**Comment by Chris00** [comment]
On Sat, 11 Oct 2014 12:04:19 -0700, Ashish Agarwal wrote:

> The opam binary is located in /alien/bin, which is added to PATH only in .profile. Thus, I fixed this by passing --login to bash from within the cronjob. Not sure why the behavior would have changed recently.

Thanks Ashish for tracking this!  I noticed too there was a problem with the update script but I had no time to deal with it.
