### ISSUE TITLE
OCamlbuild Plugins Page Formatting Issues

### ISSUE THREAD

**Issue by trevorsummerssmith** [ocaml/v2.ocaml.org#558]
This page: https://ocaml.org/learn/tutorials/ocamlbuild/Making_plugins.html

After "Dynamic dependencies" appears to not be parsing the content formatting. This appears to be some escape problem on the server side (I do not think it is browser related). However, if you need more debug info I can provide more. I am on Mac OS 10.9.5. Chrome 38.0.2125.104.

**Comment by dsheets** [comment]
Other problems with the OCamlbuild pages: no titles, breadcrumb links include ".md", duplicate content.

**Comment by dsheets** [comment]
I've filed ocaml/omd#134 to fix the markdown processor issue. I will also fix the escaping in the document and add a title.
