### ISSUE TITLE
[Tutorial] inconsistent language tags

### ISSUE THREAD

**Issue by BerlinNurse** [ocaml/v2.ocaml.org#563]
In the rigth top corner of each page are the language-tags.
e.g. "  
    en
    fr
    it
    ja
    ko
    中文
"

This is inconsistent. For simplified Chinese you use the language-own-characters.
For Japanese you don't. A japanese person wouldn't recognize his own language behind "ja". Please change it to 日本 (Japan) or 日本語 (Japanese).

**Comment by dbuenzli** [comment]
Le jeudi, 6 novembre 2014 à 17:34, BerlinNurse a écrit :

> 日本語 (Japanese).

FWIW that's what wikipedia uses.  

Daniel
