### ISSUE TITLE
[Tutorial] open_graph calls

### ISSUE THREAD

**Issue by BerlinNurse** [ocaml/v2.ocaml.org#564]
For example this page of the tutorial
http://ocaml.org/learn/tutorials/structure_of_ocaml_programs.html
but maybe there are more.

In some codes Graphics.open_graph is called. The parameter everytime is " 640x480". Please be aware of the blank/space character after the first '"'. I see no need for this blank. It will confuse new coders.

**Comment by Chris00** [comment]
On Thu, 6 Nov 2014 08:39:58 -0800, BerlinNurse wrote:

> In some codes Graphics.open_graph is called. The parameter 
> everytime is "
> 640x480". Please be aware of the blank/space character after the 
> first '"'. I
> see no need for this blank. It will confuse new coders.

The manual says otherwise: 
http://caml.inria.fr/pub/docs/manual-ocaml/libgraph.html

**Comment by BerlinNurse** [comment]
Ok, I see.
But then is the question why is there a blank/space?

It works well without.

**Comment by Chris00** [comment]
Not really:

``` ocaml
# open_graph "100x100";;
Exception: Graphics.Graphic_failure "Cannot open display 100x100".
# open_graph " 100x100";;
- : unit = ()
```

**Comment by pw374** [comment]
> It works well without.

Only if you don't specify the size nor the location of the window.
