### ISSUE TITLE
ocaml-shell with repeate?

### ISSUE THREAD

**Issue by BerlinNurse** [ocaml/v2.ocaml.org#567]
In a bash-shell (R-shell, etc) I can reuse the last commands/expressions when I press Arrow-Up or Page-Up, etc.

In my ocaml-shell it isn't possible. Is there a way?

If it is it should be described in the beginning of the tutorial section.

**Comment by pw374** [comment]
You might want to use rlwrap or ledit 
http://utopia.knoware.nl/~hlub/uck/rlwrap/#rlwrap

http://pauillac.inria.fr/~ddr/ledit/ or http://opam.ocaml.org/packages/ledit/ledit.2.03/

**Comment by BerlinNurse** [comment]
nice workaround

**Comment by agarwal** [comment]
Please consider `utop` instead of the standard ocaml toplevel.
