### ISSUE TITLE
Teaching page is not linked from anywhere

### ISSUE THREAD

**Issue by yminsky** [ocaml/v2.ocaml.org#584]
Maybe we should link it from the Learn page?

**Comment by pw374** [comment]
At least, Google has seen it: https://www.google.com/search?as_sitesearch=ocaml.org&q=teaching-ocaml.html&gws_rd=ssl#q=teaching+site:ocaml.org

> Maybe we should link it from the Learn page?

Finding a place in the Learn page doesn't seem trivial to me, but I'm fine with the idea.

**Comment by yminsky** [comment]
I just made a pull request.

https://github.com/ocaml/ocaml.org/pull/586

**Comment by pw374** [comment]
Merged :)

I think there should be a link from http://ocaml.org/learn/description.html too, since it's supposed to be a more detailed version of that paragraph...

**Comment by yminsky** [comment]
OK.  Give me a minute.

**Comment by yminsky** [comment]
I've added the link, and done a bit of related tidying.

https://github.com/ocaml/ocaml.org/pull/587

**Comment by pw374** [comment]
I guess having 2 links to the page is enough to close this issue :)
