### ISSUE TITLE
Sections headings are not formatted on "Code Examples" page

### ISSUE THREAD

**Issue by phtrivier** [ocaml/v2.ocaml.org#594]
On http://ocaml.org/learn/taste.html , all headings starting with "## Polymorphism" are not formatted, and displayed with the two dash signs. 

The corresponding links on the left hand side of the page do not seem to work either.

**Comment by pw374** [comment]
Thanks for spotting this weird thing.

**Comment by pw374** [comment]
I thought [omd](https://github.com/ocaml/omd/) was doing something wrong. But it doesn't seem like it.
So, now I suspect there's a preprocessing script that does something weird, @Chris00 any idea?

(The links not working is normal, since the corresponding headers are not created.)

**Comment by pw374** [comment]
There's something wrong in `script/md_preprocess`, as it deletes some essential `\n`s; I don't know if it's due to OMD or not.

**Comment by pw374** [comment]
Found the culprit! It's a bug in OMD! :(

The markdown backend has an issue when a header follows an HTML block.

**Comment by pw374** [comment]
I managed to install `omd.1.2.3`, which fixes this issue.

[At the time of writing, `omd.1.2.3` is not yet in opam](https://github.com/ocaml/opam-repository/pull/3109), though. Also, at the time of writing, omd.1.2.3 is announced on http://ocaml.org/, which is wrong, but it should disappear anytime soon. (edit: it has disappeared :) and shall reappear in time)
