### ISSUE TITLE
404 not found  opam quick install

### ISSUE THREAD

**Issue by ghost** [ocaml/v2.ocaml.org#599]
http://opam.ocaml.org/doc/Quick_Install.html

**Comment by ghost** [comment]
Can not access this page.
visit http://ocaml.org/docs/install.html

then click quick install link

**Comment by amirmc** [comment]
Thanks for the report!  I guess that link got broken when opam 1.2 was released and the docs page was restructured.  I notice that the 'Advanced Install' link is also broken and that trying to go to http://opam.ocaml.org/doc/ also gives an unexpected result (I'll file a separate issue about that).

I'll push a fix momentarily for the broken link.
