### ISSUE TITLE
install.html: outline various install scenarios clearly

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#6]
Installation instructions are all currently too sparse to be of practical use. As a first step, let's clearly outline the various instruction sets we would like, e.g. installing with godi on Unix, installing with godi on Mac OS X (if instructions differ at all from from Unix), installing from source, etc.

**Comment by Chris00** [comment]
All installations should recommend strongly to use findlib (with a pointer to the dev tools").

**Comment by agarwal** [comment]
Closing this issue for the [same reason](https://github.com/ocaml/ocaml.org/issues/7#issuecomment-28941820) as described in #7.
