### ISSUE TITLE
fix svn repo URLs

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#607]
@Teemperor removed _dir_ from the svn repos URLs in 4ef3ef94a91f3baf8af25b4f425c82ffd0aad6dc. I'm not sure that fix is correct as _dir_ is mentioned in the text and table of the [svn page](http://ocaml.org/releases/svn.html).

I've been unable to confirm since I'm unable to connect to the SVN repo. Is anyone else able to pull, e.g.
`svn checkout http://caml.inria.fr/svn/ocaml/trunk`.

**Comment by avsm** [comment]
Yes, this below command line works fine for me on a fresh checkout.

**Comment by agarwal** [comment]
Thanks for confirming. I haven't used svn in ages, so maybe it's just my settings. I get:

```
$ svn checkout http://caml.inria.fr/svn/ocaml/trunk
svn: E175002: Unable to connect to a repository at URL 'http://caml.inria.fr/svn/ocaml/trunk'
svn: E175002: OPTIONS of 'http://caml.inria.fr/svn/ocaml/trunk': Could not read status line: connection was closed by server (http://caml.inria.fr)
```

**Comment by avsm** [comment]
I never use this SVN url, but for reference I'm on MacOS X 10.10's default SVN, which is

$ svn --version
svn, version 1.7.17 (r1591372)
   compiled Sep 18 2014, 13:06:44

**Comment by agarwal** [comment]
I'm using exact same svn. The URL I gave is the recommended one on [ocaml.org](http://ocaml.org/releases/svn.html).

**Comment by agarwal** [comment]
The fix is explained in this [comment](https://github.com/ocaml/ocaml.org/issues/605#issuecomment-68532711).
