### ISSUE TITLE
create local opam file

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#609]
It's been a long time since I've actually been able to build the site locally. Why don't we create a local opam file to force us to state the dependencies clearly. We can then use that for Travis as requested in #241.

In the mean time, it will be great if anyone can state what is required. Is there a specific version of omd, ocamlrss, opamfu, etc. needed? I'm trying to work through it, but still stuck.

**Comment by Chris00** [comment]
On Fri, 9 Jan 2015 14:01:10 -0800, Ashish Agarwal wrote:

> It's been a long time since I've actually been able to build the site locally.
> Why don't we create a local opam file to force us to state the dependencies
> clearly. We can then use that for Travis as requested in #241.

What would the opam file install?  How about to add a "dep" target in
the Makefile (with version constraints)?

> In the mean time, it will be great if anyone can state what is required. Is
> there a specific version of omd, ocamlrss, opamfu, etc. needed? I'm trying to
> work through it, but still stuck.

The dependencies are in the README — hopefully up to date.

**Comment by agarwal** [comment]
> What would the opam file install?

Nothing. It would just be a controlled syntax for listing the packages and knowing that "make" should be run. It doesn't have to be an opam file, but I thought it covers the desired features.

> The dependencies are in the README — hopefully up to date.

I'm not sure. Currently, I can't install opam2web because it depends on opamfu, in which I have issue ocamllabs/opamfu#13. Are you pinning opam2web?

**Comment by Chris00** [comment]
Well, yes, I pinned

opam-lib
opamfu
opam2web

@dsheets any hope of releasing a new version of `opamfu` in the near future?

**Comment by agarwal** [comment]
What did you pin to? Specific commits for each? I've tried many combinations and none get me to a working state. Specifically, the current head of opamfu doesn't compile.

**Comment by Chris00** [comment]
On Fri, 9 Jan 2015 15:32:51 -0800, Ashish Agarwal wrote:

> What did you pin to? Specific commits for each? I've tried many combinations
> and none get me to a working state. Specifically, the current head of opamfu
> doesn't compile.

It does but you may have to install opam-libs from the HEAD as well.

**Comment by agarwal** [comment]
Are you pinning `cow`? Pinning opam2web forces a downgrade of cow to 0.6.2, but opam2web still has a compile error related to cow.

**Comment by Chris00** [comment]
@GitHub: I can send this as many times as I want, it is never
appended to https://github.com/ocaml/ocaml.org/issues/609#issuecomment-69471997

On Sat, 10 Jan 2015 13:08:16 -0800, Ashish Agarwal wrote:

> Are you pinning cow? Pinning opam2web forces a downgrade of cow to 0.6.2, but
> opam2web still has a compile error related to cow.

$ opam show opam2web --raw
opam-version: "1"
name: "opam2web"
version: "1.3.1"
maintainer: "contact@ocamlpro.com"
homepage: "https://github.com/ocaml/opam2web"
bug-reports: "https://github.com/ocaml/opam2web/issues"
build: [
  [make]
  [make "install" "PREFIX=%{prefix}%"]
]
remove: [
  ["rm" "-f" "%{prefix}%/bin/opam2web"]
  ["ocamlfind" "remove" "opam2web"]
]
depends: [
  "ocamlfind"
  "opam-lib" {>= "1.1.1"}
  "opamfu" {>= "0.1.1"}
  "re"
  "uri" {>= "1.3.11"}
  "cow" {>= "0.6.0" & (< "0.8.0" | > "0.8.0")}
  "js_of_ocaml" {>= "1.3"}
  "cmdliner"
]
ocaml-version: [>= "4.00.0"]

**Comment by agarwal** [comment]
Thanks for answering all of my questions, but unfortunately it's a chain reaction of issues. Cow < 1.0.0 requires OCaml < 4.02.0. Unfortunately, in an effort to resolve this issue, I just created a new switch, and I chose 4.02.1. I don't feel like doing another round with < 4.02.0, since I'm confident there'll be some other issue anyway.

The correct solution is to have new releases as I requested in: ocaml/opam2web#126 and ocamllabs/opamfu#13. I'll wait for that.

**Comment by dsheets** [comment]
I'll get to these soon. I'm sorry that I've left these repos in a bit of a mess. Deadlines and aspirations of refactoring and site integration half-completed do not a nice project make.

**Comment by agarwal** [comment]
@dsheets Thanks.

**Comment by dsheets** [comment]
Please test #616 and ocaml/opam-repository#3439.

**Comment by agarwal** [comment]
This appears to work. (I am hitting another issue on compilation of the pa_foreach.ml tutorial, but I guess that's unrelated.) I'll merge this into master with the following changes:
- Change the package name to `ocamlorg`, which is what we use when unable to include a dot. Irrelevant really since this package won't be added to opam-repository. I'll add a comment in the README explaining the purpose of having an opam file.
- I'll also delete the `license` field, which is set to ISC. That is the license for the code implementing the site, but putting that in the OPAM file might incorrectly suggest it applies to everything. Is it valid to have the license field set to "See LICENSE.md file"?

**Comment by Chris00** [comment]
On Thu, 22 Jan 2015 06:09:13 -0800, Ashish Agarwal wrote:

> This appears to work. (I am hitting another issue on compilation of the
> pa_foreach.ml tutorial, but I guess that's unrelated.)

It may not — camlp4 is now a separate package.

**Comment by dsheets** [comment]
There are supposed to be some errors in that tutorial. We don't handle the expected error case very well in the build (but the build doesn't and shouldn't fail).

**Comment by agarwal** [comment]
> It may not — camlp4 is now a separate package.

I happened to have camlp4 installed, but it should be added as a dependency since we directly rely on it.

**Comment by agarwal** [comment]
> build doesn't and shouldn't fail

It does for me. I opened #617.
