### ISSUE TITLE
Correction to Install OCaml page

### ISSUE THREAD

**Issue by yansh** [ocaml/v2.ocaml.org#613]
In the Mac OS paragraph it says:

_This is the easiest way to set up a basic OCaml installation for OS X. Simply download Intel disk image, mount the disk image, double-click on the ocaml.pkg file contained within, and follow the instructions from there. 

**There is no image for OCaml 4.02.X**

**Comment by Chris00** [comment]
As I do not use OS X, a PR with the appropriate changes would be very welcome.

**Comment by yansh** [comment]
Done.

**Comment by Chris00** [comment]
PR is [merged](https://github.com/ocaml/ocaml.org/pull/620).
