### ISSUE TITLE
change version to `dev` in opam file

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#618]
@dsheets I'm assuming the version number in the opam file is a copy/paste artifact. We should just set it to `dev`.

**Comment by dsheets** [comment]
That's fine. I actually chose 2.1.0 because I didn't know what to put there and it seemed like a 2.1.0...

**Comment by agarwal** [comment]
Closed by 424aeb09e27cfb01bf78a9cb5c9655cb6eb7fa88.
