### ISSUE TITLE
simplify first page

### ISSUE THREAD

**Issue by lefessan** [ocaml/v2.ocaml.org#62]
Hi,

  I am impressed by the content that is now available on ocaml-lang.org. However, I think there is too much content on the first page. 

Here are a few suggestions:
- Increase the font size of the text (the font is currently too small)
- Move the "what's new in OCaml version 4.00.*" to another page, and keep only a pointer (a button similar to the download button)
- Move the "News from the community" to another page, and keep only the titles of the news
- Simplify the few lines of OCaml to something that anybody can understand (hello world ?)
- Add the logos of the Caml Consortium Members in the bottom of the first page
- Give arguments in favor of OCaml (why should I use OCaml rather than Python ?). 
  For inspiration, I think good websites are:
  - For its simplicity: http://golang.org/
  - A drawing is sometimes better than text: http://pythonxy.googlecode.com/files/python_2722.png

In the success stories, most of them are 10 years old. Instead of a list of items like it is, I think it could be improved by:
- adding a page on the use of OCaml in Jane Street (and a little Lexifi), with a title like "OCaml in the financial industry" 
- adding a page on the use of OCaml in Citrix, with a title like "OCaml in the virtualization industry"
- adding a page on the use of OCaml for verification, with a title like "OCaml in the avionic industry" (with Astree, Frama-C, Coq&CompCert, etc.)
- and move all the other items into a page "OCaml in the open-source community"

**Comment by agarwal** [comment]
Thanks, these are some great ideas.  

> I think there is too much content on the first page.
> I agree. The What's New part is especially unnecessary I feel.
> 
> Increase the font size of the text (the font is currently too small)
> Agreed. Anil also requested to use pure black for the font to enhance
> contrast. I've been meaning to dig into bootstrap more to learn how to make
> these changes (right now we use their precompiled css).
> 
> Move the "News from the community" to another page, and keep only
> the titles of the news
> Sounds right to me.
> 
> Simplify the few lines of OCaml to something that anybody can
> understand (hello world ?)
> Gasche added this following the idea of a [Minimal Viable Snippet](http://blog.fogus.me/2012/08/23/minimum-viable-snippet/),
> which explicitly says do not make this just a "hello world" example. But
> we're of course free to ignore that advice if people disagree with it.
> 
> Add the logos of the Caml Consortium Members in the bottom of the
> first page
> I think this will get quite cluttered.
> 
> For its simplicity: http://golang.org/
> Nice! This is a dramatically different design. We'd have to rethink a lot.
> Perhaps we could move our main content links (the Discover Learn Use
> Community sections) lower down, and have the more playful interactive items
> on top, but these don't exist yet. We'd need to embed tryocaml directly and
> get a cute drawing of a Camel.  :)
> 
> A drawing is sometimes better than text:
> http://pythonxy.googlecode.com/files/python_2722.png
> I have no idea how to make this, but your point is well taken. We could
> benefit from additional graphics somehow.
> 
> In the success stories, most of them are 10 years old.
> This page is terribly outdated. Let's open a separate issue about updating
> it.

**Comment by Chris00** [comment]
> Move the "News from the community" to another page, and keep only the titles of the news

Done: 2f2ecd3570eff7aa6feb12cd50b9c0ed6991923e and b77d77c8de58ceff1d63718f1a74a15100c1bb97

**Comment by Chris00** [comment]
> > Simplify the few lines of OCaml to something that anybody can understand (hello world ?)
> 
> Gasche added this following the idea of a [Minimal Viable Snippet](http://blog.fogus.me/2012/08/23/minimum-viable-snippet/), which explicitly says do not make this just a "hello world" example. But we're of course free to ignore that advice if people disagree with it.

Maybe adding a short description of what it does is enough?

**Comment by agarwal** [comment]
> Maybe adding a short description of what it does is enough?
> 
> I'm not sure about this. Having to add a paragraph of text kind of defeats
> the point, which I think is "see how easy OCaml is, here's some code, it
> makes sense already, right." But now there's a whole paragraph you have to
> read, which also diminishes the aesthetic simplicity of the front page that
> this Issue is asking for. Maybe we have to come up with an example that is
> easier to understand.

**Comment by Chris00** [comment]
Then I think, explicit type parameters should not be used — I think it is a syntax that is not easy to understand unless one already knows what parametric polymorphism is.  I also named explicitly function arguments.  899c27b7cd1c1bf8ffae8b99fa386dfd0e0f7f41

**Comment by agarwal** [comment]
I like this. Type parameters are unnecessary at this point. I also like the
use of `match` instead of `function`. I would also name the type simply
`tree` to reduce syntactic clutter even further.

**Comment by Chris00** [comment]
I have done so.  (I also added a comment which may help to get started and shows the syntax for comments.  It may be judged unnecessary though.) 74dd59865d551e8978dbfa9874052dc18457ff48

**Comment by agarwal** [comment]
I published it.

**Comment by agarwal** [comment]
Closing this issue. All points mentioned are either implemented, will be
considered by a professional design firm, or for one point opened new Issue
#80.
