### ISSUE TITLE
Add book "OCaml: Programação funcional na prática"

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#624]
Add book "[OCaml: Programação funcional na prática](http://andreiformiga.com/livro/ocaml/)".

**Comment by dbuenzli** [comment]
Issue on the book's code repo https://github.com/tautologico/opfp/issues/1

**Comment by johnwhitington** [comment]
This was fixed by:

https://github.com/ocaml/ocaml.org/pull/626

So we can close this now.
