### ISSUE TITLE
Add Mashape to companies page

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#633]
Users of cohttp, as reported by @SGrondin in the cohttp [gitter chat](https://gitter.im/mirage/ocaml-cohttp).

Would need some blurb to go with it so I put together the following:

"Mashape makes it easy to distribute, monetize, manage and consume cloud APIs. Mashape is building a world-class marketplace for cloud APIs, driven by a passionate community of developers from all over the world.  We use OCaml in our [APIAnalytics](http://apianalytics.com) product — as part of a mission-critical, lightweight HTTP proxy."

Comments welcome.

**Comment by amirmc** [comment]
I'll probably do a push later today and collect any other outstanding companies from the issues list.

**Comment by SGrondin** [comment]
Nice write up. The only edit I'd make is that we're expanding from just an API marketplace to everything related to APIs, including management, analytics, billing, etc.

My edit:
"
Mashape makes it easy to distribute, monetize, manage and consume cloud APIs. Mashape is building a world-class marketplace for cloud APIs driven by a passionate community of developers from all over the world as well as enterprise API management and analytics products. We use OCaml in our APIAnalytics product — as part of a mission-critical, lightweight HTTP proxy.
"
