### ISSUE TITLE
https on ocaml.org and Fedora22 alpha: sec_error_unknown_issuer

### ISSUE THREAD

**Issue by edwintorok** [ocaml/v2.ocaml.org#638]
Everything is fine on Debian, however on Fedora22 Alpha I get this with firefox 36.0:
ocaml.org uses an invalid security certificate.
The certificate is not trusted because no issuer chain was provided.
sec_error_unknown_issuer

ca-certificates package is installed, so not sure whats wrong, but looks like the intermediate certificate is missing from the trust store and its not provided by ocaml.org either.

**Comment by amirmc** [comment]
Thanks for the report. I believe @avsm handles the certificates for the domain so this may be one for him to look at.

**Comment by amirmc** [comment]
A quick search of the error message led me to https://support.mozilla.org/en-US/questions/984505

"Mozilla has a strong policy to decide which CA to include with root certificates … Required intermediate certificates need to be send by the server to make it possible to build a certificate chain that ends in a root certificate."

**Comment by edwintorok** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=ocaml.org
"Chain issues   Incomplete"
Looks like you'll need to concatenate the intermediate and leaf certificates, not sure in which order, IIRC apache/lighttpd/nginx didn't all agree on the order, you'll have to see which order works for your server.

**Comment by avsm** [comment]
This should be fixed -- we were missing a Comodo cross certificate, which I bundled into the chain from https://wiki.gandi.net/en/ssl/intermediate

Could you confirm on Firefox by any chance?

**Comment by edwintorok** [comment]
Looks good now, thanks.
