### ISSUE TITLE
Planet should not aggregate content, only links.

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/v2.ocaml.org#643]
As I said to @Chris00 privately. I don't think that the planet page:

http://ocaml.org/community/planet/

should aggregate _content_. There's no chance you will be able to render the content correctly for all the blogs (which may e.g. contain JavaScript for `js_of_ocaml` demos). As such it degrades the value of the content and is somehow disrespectful to the blog authors;  see for example the rendering of `Pearl No.3 - Saddleback Search` in the current list.

I think this page should be a simple link list like this:

http://ocaml.org/community/planet/older.html

Note that for this reason my blog entries have no content but only links, I want to retain control over the page rendering.

**Comment by dbuenzli** [comment]
> Note that for this reason my blog entries have no content but only links, I want to retain control over the page rendering.

Now of course we could say that you should simply proceed that way (or only have one or two sentences and a "read more" as content) if you don't want your content to be misrepresented, but I'm not sure all blogging platforms actually give you control over this.

**Comment by Chris00** [comment]
As an element in the discussion, the W3 validator complains that [your feed has no content](http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Ferratique.ch%2Flog%2Ffeed.atom).

I personally prefer to read the posts on the planet, occasionally going to the original web site when some content does not display properly.  However, Atom is not limiting you in any way.  You can choose to have a `<summary>` element in case you do not want to embed the entire content in your feed.

**Comment by dbuenzli** [comment]
> As an element in the discussion, the W3 validator complains that your feed has no content.

Well it does not _complain_ that's only a suggestion, the feed validates. I'm not going to devise summaries for my posts and I feel that a "Read more" summary linking to the same URI as the title is just redundant.

> I personally prefer to read the posts on the planet, occasionally going to the original web site when some content does not display properly.

I think this is a very poor user experience. But then maybe it is the authors' responsability. I still find it disappointing and rather amateurish to see half-rendered and layout broken articles on that page.

**Comment by Chris00** [comment]
> Well it does not complain that's only a suggestion

Right but the explanation insists that it'd be a good thing: “_Experience teaches that feeds which contain textual content are in general more useful than those which do not. Some applications (one example is full-text indexers) require a minimum amount of text or (X)HTML to function reliably and predictably. Feed producers should be aware of these issues. It is advisable that each atom:entry element contain a non-empty atom:title element, a non-empty atom: content element when that element is present, and a non-empty atom: summary element when the entry contains no atom:content element. However, the absence of atom:summary is not an error._”

> I think this is a very poor user experience.

While I do not deny that there are some problems — I try to improve the situation when I have time but it's hard to cater for all the different markups and some of the problems are due to _badly constructed feeds_ — at least it's a consistent experience.  Some of the chosen color schemes hurt my eyes and some of the sites are hard to read on a phone.  At least with the current scheme, everybody gets to choose his evil! ;-)

**Comment by dbuenzli** [comment]
Le vendredi, 10 avril 2015 à 02:02, Christophe Troestler a écrit :

> Experience teaches that feeds which contain textual content are in general more useful than those which do not.

Experience shows that a title is textual content.  

> at least it's a consistent experience
> Right, a consistently broken experience.  

There's no chance you will be able to fix this, the feed content model is broken and unsuitable for layout/interactive intensive content. Beyond simple textual/image snippets it should only be used as a signaling mechanism.  

Besides the very notion that the publication of a diversity of writers should be normalized without their agreement to stick to a code is a very questionable one; the aims and style of each one of these are very different and there is no reason this shouldn't show up in the way they consider information should be presented.

Best,

Daniel

**Comment by amirmc** [comment]
Thanks for raising this and there are some interesting points to consider.

My summary of Daniel's argument is:  It is impossible to render all posts *as the author intended* and **therefore** ocaml.org should not attempt to do so. 

I fully agree with the first part and I doubt the extent to which we can fix it.  However, I do not agree with the conclusion that we should not render content *at all*.  My viewpoint stems from the following:

- The feed itself already contains the content -- which the author put there themselves (we must presume this as the alternative leads to madness).
- Other feed-readers will *also* render content and the authors have no control over how those work.
- I don't see a reason why ocaml.org should have to behave differently to other feed-readers, which also aggregate content.

One could argue (as Daniel pointed out) that some blogging software may not give you control over the content of the feed.  I'd argue that the same blogging software is also likely to limit the author in other ways too -- trade-offs the author has accepted.  Therefore, the only sensible option is to assume that the feed contains the information that the author wishes to broadcast via that medium. In Daniel's case, this is the link back to the website.  In the case of Andrej Bauer (see the planet page now for item on April 3rd), it's only an excerpt with a link.  In my case, it's the full content.  

From my perspective as an author, I would want it to be clear that the Planet page is *not* the canonical source and I believe it already communicates that pretty well.  If people come across rendering issues, then I'd want them to *easily* get back to the original source, which they *can* do via the links.

Overall, if authors feel strongly about the content of their feeds, I'd encourage them to use software that *gives* them more control.  The alternative of attempting to enact policies elsewhere in the system is a sisyphean endeavour.

Given this, I'm inclined to leave things as they are.

**Comment by amirmc** [comment]
_[I noticed that GitHub completely borked the rendering of my email reply so I deleted it and posted it again via the website — Oh, the irony ...]_

Thanks for raising this and there are some interesting points to consider.

My summary of Daniel's argument is:  It is impossible to render all posts _as the author intended_ and **therefore** ocaml.org should not attempt to do so. 

I fully agree with the first part and I doubt the extent to which we can fix it.  However, I do not agree with the conclusion that we should not render content _at all_.  My viewpoint stems from the following:
- The feed itself already contains the content -- which the author put there themselves (we must presume this as the alternative leads to madness).
- Other feed-readers will _also_ render content and the authors have no control over how those work.
- I don't see a reason why ocaml.org should have to behave differently to other feed-readers, which also aggregate content.

One could argue (as Daniel pointed out) that some blogging software may not give you control over the content of the feed.  I'd argue that the same blogging software is also likely to limit the author in other ways too -- trade-offs the author has accepted.  Therefore, the only sensible option is to assume that the feed contains the information that the author wishes to broadcast via that medium. In Daniel's case, this is the link back to the website.  In the case of Andrej Bauer (see the planet page now for item on April 3rd), it's only an excerpt with a link.  In my case, it's the full content.  

From my perspective as an author, I would want it to be clear that the Planet page is _not_ the canonical source and I believe it already communicates that pretty well.  If people come across rendering issues, then I'd want them to _easily_ get back to the original source, which they _can_ do via the links.

Overall, if authors feel strongly about the content of their feeds, I'd encourage them to use software that _gives_ them more control.  The alternative of attempting to enact policies elsewhere in the system is a sisyphean endeavour.

Given this, I'm inclined to leave things as they are.

**Comment by dbuenzli** [comment]
> Given this, I'm inclined to leave things as they are.

Why not. 

But personally I still think page http://ocaml.org/community/planet/older.html is a much better user interface to planet. Contrary to what seems to be implied it _does_ render content: the title, the date and the author and can do so in a reliable and normalized way without jeopardizing's the authors intentions. This gives a much better birds-eye view to what is happening on the planet allowing comfortable and quick skimming over a larger period of time while still retaining direct, quick and non-broken access to the content. 

You seem to imply that the page should be a feed reader, I don't see any reason why it should be so (and somehow doubt that a lot people are using this page as a feed reader). I rather see this page as a way to make people subscribe (or be added) to the feed and here again the page I mention does a much better job at that for the reasons I mentioned earlier.
