### ISSUE TITLE
The Acunu link is dead

### ISSUE THREAD

**Issue by yallop** [ocaml/v2.ocaml.org#647]
The [link to Acunu](http://www.acunu.com/) on the [companies page](https://ocaml.org/learn/companies.html) goes nowhere, apparently because Acunu has been [acquired](http://appleinsider.com/articles/15/03/25/apple-acquires-big-data-analytics-firm-acunu) by Apple.

**Comment by Chris00** [comment]
There is not much to do but remove it.

Objections @agarwal @amirmc @avsm ?

**Comment by amirmc** [comment]
No objections from me. 

... though maybe we could just change it to be Apple, instead? (just kidding) :-P

**Comment by agarwal** [comment]
No objection from me.

> though maybe we could just change it to be Apple, instead? (just kidding) :-P

Well, not totally a joke. If we knew that Apple is using OCaml, then that would be reasonable. But it seems there is little information about what actually happened with Acunu, so we can't say that Apple has an OCaml code base.

**Comment by avsm** [comment]
No, we definitely can't say that.
