### ISSUE TITLE
Add lchown to Unix

### ISSUE THREAD

**Issue by jcourant** [ocaml/v2.ocaml.org#649]
Hi,

I wish lchown were available in the `Unix` module. As `man lchown` says: "lchown() is like chown(), but does not dereference symbolic links." (linux slackware, 14.1).

I had to use it for a pet project.

The most difficult part for me was to figure out how to find the version of `otherlibs/unix/chown.c` matching my binary distribution (actually, I switched to the latest compiler version instead), then it was just a matter of doing

```
sed -e 's/chown/lchown/g' -e 's|"unixsupport.h"|<caml/unixsupport.h>|" < chown.c > lchown.c
```

then adding `external lchown : string -> int -> int -> unit = "unix_lchown"` in my ml source.
It seems to work, at least for me, on my slackware (I did not attempt at testing other systems).

BTW, I also miss the lutimes function...

Yours,

Judicaël Courant.

PS: the man page also says:

Feature Test Macro Requirements for glibc (see feature_test_macros(7)):

```
   fchown(), lchown():
       _BSD_SOURCE || _XOPEN_SOURCE >= 500 || _XOPEN_SOURCE && _XOPEN_SOURCE_EXTENDED
       || /* Since glibc 2.12: */ _POSIX_C_SOURCE >= 200809L
```

so I guess that means it is pretty standard.

**Comment by Chris00** [comment]
This is the wrong place to ask this.  The project is concerned with the _web site_ for OCaml.  For the standard library, ask on the [compiler project](https://github.com/ocaml/ocaml).  You may also want to post this on one of the [mailing lists](http://ocaml.org/community/), an [OPAM](http://opam.ocaml.org/) package may already have the functions you desire.

**Comment by jcourant** [comment]
Hi,

> This is the wrong place to ask this.

Sorry about that. As a long time OCaml-user (since its first release
actually, and of Caml-Light before that), I am happy to see that the
old-fashion Caml site is evolving.

However, I consider the current community page is misleading:

> You may also want to post this on one of the [mailing
> lists](http://ocaml.org/community/)

Actually, I browsed that page. It is the very reason why I sent my bug
report in the wrong place:
- I could not find any pointer to the bug tracker in the ``Support''
  section (I _knew_ it existed).
- I found a `Feedback'' link under the`Contact'' (leading to the bug
  tracker for the site). I am visiting this site because I am interested
  in Caml, so I expected this feedback to be about Caml, not the site (I
  thought the caml team decided to use another tool).
- Actually there is a pointer to the bug tracker in the trailer, in the
  column ``Community''. But I was on the community web page. Since I
  read the page body and could not find what I looked for, I did not
  even had a look at this column.

May I kindly suggest that:
- you add the relevant pointers on the community page;
- you put a more specific name instead of `Feedback'' under the
  `Contact column'' --- or link to a ``disambiguation'' page;
- you add a real ``contact'' page, like the old one
  (http://caml.inria.fr/contact.en.html). Then, I would be easier to
  know where to ask and where not to ask.

> For the standard library, ask on the [compiler
> project](https://github.com/ocaml/ocaml).

Actually, the README on this page points to the bug tracker or
caml@inria.fr (and that is consistent with the information on the old
contact page), so I should rather ask there shouldn't I ?

> an [OPAM](http://opam.ocaml.org/)
> package may already have the functions you desire.

Only candidate found: extunix. Unfortunately:

$ find extunix -type f | xargs grep lchown
$ # nothing

Yours,

## J. Courant.

TEL : (+33) (0)4 72 50 48 13
GPG public key: 783D F28F DBEA 5600 C0CB A7C4 828A B452 479A 5941

**Comment by agarwal** [comment]
> you put a more specific name instead of `Feedback'' under the`Contact column''

Makes sense. I'll rename it to "Website Issues".

> you add the relevant pointers on the community page

Good point. If the Community section of the footer has a link to Mantis, then presumably it is quite important and should certainly also be mentioned in the corresponding Community page. Adding it to the Support section of the page would make sense. I'll do that.

> you add a real ``contact'' page, like the old one (http://caml.inria.fr/contact.en.html)

We have a more comprehensive version of this page, but we call it Mailing Lists and Forums. It is linked from the Community page a few times.

> > For the standard library, ask on the [compiler project](https://github.com/ocaml/ocaml).
> > Actually, the README on this page points to the bug tracker or caml@inria.fr

Well, there's been an experiment run by @gasche to use GitHub instead of Mantis. He reported on this in the last OUD meeting. I think both are acceptable.

Thanks for all the feedback. It is very helpful.

As a separate point, I encourage you to use the official name of the language, "OCaml" instead of "Caml".

**Comment by agarwal** [comment]
Actually I don't see an Issues link at the OCaml GitHub repo. I think it is only pull requests that are taken there, so I mentioned only Mantis in ae472121469e1a45ddd041d437acc2bd190e43bf.
