### ISSUE TITLE
Remove the Think OCaml book from the list

### ISSUE THREAD

**Issue by dmbaturin** [ocaml/v2.ocaml.org#656]
Initially I included its removal in a pull request, but @agarwal pointed out that it should not be done without discussion, which is indeed a good point. Here's my motivation for removing it.

That book has multiple problems at this moment and I think in its current state it will likely confuse beginners more than help them.

The translation from python is incomplete. There are empty sections (e.g. 6.4, 9.8, 9.9, 10.3), snippets of python code (e.g. 7.2, or chapter 16 that is all Python, no OCaml code at all, same with the appendix), snippets of mixed language (e.g. 7.6, 8.1).

Due to the same incomplete translation, the concepts of assignment and binding are often mixed up (original text was about assignment, then the code was translated to binding but the text was not), e.g. in ch. 13.

Chapter 15 mentions a module that is not on the book website and I could not find it anywhere. The sentence reads "Go to inserturlhere and download oturtle.zip".

The pattern matching chapter only uses examples with constant patterns and doesn't even mention algebraic types. Conversely, the chapters about algebraic types (which don't call them algebraic types) do not mention matching, neither they explain what's a constructor or what are polymorphic types. Types get very little attention in general.

Exceptions are mentioned a few times, but the book doesn't explain how to define or handle them. Same with modules, it mentions some modules from the standard library, but never explains what modules are and how to make your own.

Currying is explained backwards (from partial application) and the explanation makes the reader think currying and partial application are the same thing.

I hope some day the authors complete the book, but until they do, I think it should not be recommended.

**Comment by pw374** [comment]
> [...] chapter 16 that is all Python, no OCaml code at all [...]

Well, actually there is some in 16.2, but the rest of the chapter is indeed in Python... This book is a mess!

Couldn't go further than https://github.com/ocaml/ocaml.org/commit/9e18fc7db517a546e326b8b4f5e2fed5375f76d9 (which is very far) trying to find out how it made it into the list.

Anyhow I agree that, due to its current state, this book should be removed from the list.

**Comment by agarwal** [comment]
So the book is essentially incomplete. We can compare the situation to Hongbo Zhang's _OCaml Book_, which we also have listed. To be consistent, we should remove both or keep both. I think we can keep both. For _Think OCaml_, I suggest:
- Move it further down the list, next to Zhang's.
- Add a comment that the the book is incomplete, just like we do for Zhang's.

**Comment by pw374** [comment]
Does Zhang's have some Python code that hasn't been translated to OCaml yet?
In my opinion, being incomplete is not such a big deal, but having some non-OCaml code waiting to be translated is quite confusing! Perhaps the author could hide the sections that haven't been translated?

**Comment by agarwal** [comment]
> Does Zhang's have some Python code that hasn't been translated to OCaml yet?

No. The comparison to Zhang's book isn't exact. I just meant we are listing other works in progress, so why remove this one. I don't have too strong of an opinion. If the feeling is that listing the book actually hurts the community, then I don't oppose removing it.

On the other hand, I'm suggesting to leave the list as complete as possible, and add comments that allow people to focus on the books that are more important. There are so many other books on this list, which I also don't know the quality of. They were published long ago, and I suspect they are completely out of date, but we have them listed anyway just to be exhaustive.

**Comment by dmbaturin** [comment]
I'd argue that introductory books need to follow very high standards of completeness. Experienced people may ignore rough edges and correct typos as long as the intended meaning is clear (and even submit a patch to the author), but for beginners examples that don't compile are be _very_ frustrating. A mix of OCaml and Python and statements that are actually about Python are going to be even more frustrating.
Lack of attention to topics like types and modules will also do a lot of disservice to beginners IMHO, since they will find that they don't understand most of real-life code after working through the book.

I've looked into Zhang's book now when you mentioned it, and I think it should be removed too. ;)
To put it bluntly, there is no book. There's some code and some comments, but in its current state it's not helpful. The link to the precompiled PDF in the repo readme is dead, and the code doesn't build cleanly (even after correcting some mistakes, still lots of latex warnings and an obviously incomplete PDF with just camlp4 chapter).

Also, I _hope_ both of these books will be completed some day, but at the moment they aren't really work in progress. The Think OCaml book was last modified five years ago, Zhang's book last commit is from two years ago. I think this counts as abandoned.

**Comment by dmbaturin** [comment]
> There are so many other books on this list, which I also don't know the quality of

It's been just about a year since I started using OCaml, and that list was my primary source of book references. I can confirm that most of them are perfectly good. :)

**Comment by agarwal** [comment]
@dmbaturin Okay, I'd give a couple days for others to chime in, but otherwise your argument is good enough for me so you could remove both.

**Comment by Chris00** [comment]
I agree with the principle that if these books hurt the community, then they should be removed.  Maybe one should keep the links in a non-published file so that it is easy to revisit them in, say, 1year and see whether they became better?

**Comment by pw374** [comment]
Work in progress should be at least very very clearly marked as such, if they are referenced.

**Comment by agarwal** [comment]
Another idea is to create a new section called "Works in Progress", make it the last section so it has lowest visibility, and move the books to that part.

**Comment by pw374** [comment]
Sounds good to me :)

**Comment by Chris00** [comment]
OK.  https://github.com/ocaml/ocaml.org/issues/667 could also be added to it.

**Comment by dmbaturin** [comment]
Should I make a pull request?

**Comment by Chris00** [comment]
Would be nice, thanks.

**Comment by agarwal** [comment]
I moved Think OCaml down and noted it as a work in progress.

@dmbaturin If you're still not satisfied and prefer these books be in a separate "Work in Progress" section, please submit a pull request.
