### ISSUE TITLE
Linked-to Windows installer breaks user's search path

### ISSUE THREAD

**Issue by Toxaris** [ocaml/v2.ocaml.org#658]
The ocaml.org website has a link to a installer at http://ocaml.org/docs/install.html#OCPWINSelfContainedOCamlforWindows. This installer overrides the user's search path with the path of the installed ocaml distribution, **overwriting the existing search path**. This breaks the user's system! (Experienced users might be able to restore the path by extracting the environment variable from a running process, other users presumably have to reinstall all software to re-configure the search path).

This was reported months ago at https://github.com/OCamlPro/ocpwin-distrib/issues/8 but apparently not acted upon.

Since the linked-to installer destroys the user's configuration, I think the link should be removed.

**Comment by Chris00** [comment]
I tend to agree, breaking the user machine is _really bad_ advertisement for OCaml—many people simply will not want to try OCaml anymore.  Could you submit a PR?

**Comment by Toxaris** [comment]
> Could you submit a PR?

Sorry, I'm not set up to edit and test the website. This is my first interaction with OCaml or the OCaml community. (I did manage to restore my PATH, though, so I might get around to try out OCaml).

**Comment by pw374** [comment]
I'll edit the file.

**Comment by pw374** [comment]
I have removed the link. However I'm leaving this issue open, since the link should be put back when the OCPWin issue has been solved.

**Comment by pw374** [comment]
@Toxaris thank you for reporting the issue. And welcome to the OCaml community !
Please note that you may edit the ocaml.org website directly in Github: when you're on an ocaml.org page, just click on the edit button (which is the pencil in the top-right corner of each page), and then click on the edit button (which is this time the (github) pen, between the screen icon and the bin icon). When it's just for a minor modification, editing in the browser is not too bad. :)
Once you're done, you can submit a pull request quite easily (github assists you in that).

**Comment by agarwal** [comment]
This issue has been resolved by #751.
