### ISSUE TITLE
code in tutorials is not highlighted

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#66]
All [tutorials](http://ocaml.org/tutorials/index.html) are not being processed with the code highlighter. Reported by Maxence Guesdon.

**Comment by Chris00** [comment]
I have started to do so fc7fbaf17d19e48aa7fb217497e83e3e0a90cfb5

**Comment by Chris00** [comment]
I have done some more: 51c3ad5902c60fc71e85b474fcbe9f2a8da1891b 91c4e1678cca7fac5e67946927e1a009f3615951
Note that this is time consuming because it requires cleaning the code.

**Comment by Chris00** [comment]
This is done!  "Stream expressions" enables camlp4 however, which slows down the build process.

**Comment by agarwal** [comment]
Congratulations! That was quite an effort.
