### ISSUE TITLE
Wiki complement to ocaml.org

### ISSUE THREAD

**Issue by OlleHaerstedt** [ocaml/v2.ocaml.org#661]
How about adding a wiki to ocaml.org, like done in the haskell community? wiki.ocaml.org, e.g. It could encourage more contribution and discussion.

**Comment by agarwal** [comment]
This has been [discussed before](https://sympa.inria.fr/sympa/arc/caml-list/2014-04/msg00021.html). Many people were opposed to the idea or thought the current implementation is already nearly the same as a wiki. @bluddy was the main proponent, and the compromise solution was to use the wiki of this repo. That is editable by anyone, and if the content there matures, it can be moved to the main site.

I'll close this issue, but please discuss more and let us know if we can make contributions easier still.
