### ISSUE TITLE
ocamlorg is not available because your system doesn't comply with ocaml-version = "4.01.0"

### ISSUE THREAD

**Issue by eatonphil** [ocaml/v2.ocaml.org#662]
I'm just coming to this for the first time during `make deps` and am about to make a pull request. This doesn't affect my PR but I just wanted to bring up that ocaml.org is trailing behind.

**Comment by agarwal** [comment]
Yes it is! If you're motivated to, it would be great to get a pull request updating the code to work with the latest version of OCaml.

**Comment by gasche** [comment]
Since can be closed since #805 was merged, updating the requirement to 4.03.0.

**Comment by Chris00** [comment]
Thanks pointing this out!  (the requirement is >= 4.01.0 but I have tested it with 4.03.0; tests with older versions welcome).
