### ISSUE TITLE
difficult to find "companies using ocaml"

### ISSUE THREAD

**Issue by avsm** [ocaml/v2.ocaml.org#676]
I tried navigating to the "companies using ocaml" page from the front page, and ended up giving up and using Google.  I went to the "Community" tab, but it turns out to actually live in the "Learn" tab, which is a very strange place to look for it.

Cross linking it from the Community page would be very helpful I think...

**Comment by Chris00** [comment]
Hopefully, the text added will make it blend well with the rest of the content.
