### ISSUE TITLE
Broken link to the 'xen-org' project on GitHub

### ISSUE THREAD

**Issue by 10nasty** [ocaml/v2.ocaml.org#679]
On the webpage listing the companies (https://ocaml.org/learn/companies.html), the link to Xen-org github is broken (github.com/xen-org). I haven't done more researches, so I don't know if the project has been moved, renamed or simply deleted from GitHub.

**Comment by amirmc** [comment]
Possibly renamed to https://github.com/xapi-project/

Best wishes,
Amir

## 

Sent via mobile

**Comment by 10nasty** [comment]
Yes, you're probably right, as this project contains mostly Ocaml code.

I've also noticed that the link to RunOrg website is broken too. I don't know if the project is still going on, but their Facebook page seems active so I contacted them by this way. I will make a new post here as soon as I have an answer.
