### ISSUE TITLE
the French Install page is out of date

### ISSUE THREAD

**Issue by gasche** [ocaml/v2.ocaml.org#682]
The French version [Installer OCaml](http://ocaml.org/docs/install.fr.html) of the [Install OCaml](http://ocaml.org/docs/install.html) webpage is out of date and confusing. It should be either completed or removed, because right now it is a disservice to french users wishing to install OCaml.

**Comment by agarwal** [comment]
I fear this will be an ongoing issue. Perhaps all of our non-English pages should have a message added to them saying "This page maybe out of date with respect to the primary English source. We welcome contributions from translators."

**Comment by Chris00** [comment]
We should create a script that checks whether a more recent version (recent in terms of commits in the Git history) of the translated page exists and 1. displays that warning, 2. build a dashboard of translated pages to update.

**Comment by Theomat** [comment]
I have translated the install page and created a [pull request](https://github.com/ocaml/ocaml.org/pull/849).

**Comment by redianthus** [comment]
@Chris00, I think this can be closed.

**Comment by Chris00** [comment]
Thanks.
