### ISSUE TITLE
The link to Jason Hickey's Introduction to OCaml book is dead

### ISSUE THREAD

**Issue by dmbaturin** [ocaml/v2.ocaml.org#683]
My friend asked me for an ML book suggestion today and I was going to suggest that book, but found out that the link to it (http://files.metaprl.org/doc/ocaml-book.pdf) is dead.

Specifically, files.metaprl.org returns NXDOMAIN, while metaprl.org itself is still alive.

I have a saved copy and I could theoretically re-host it somewhere, but the front page says DRAFT, DO NOT REDISTRIBUTE, which would make the moral and legal status of this action rather questionable.

There is an alternative link at caltech website (http://courses.cms.caltech.edu/cs134/cs134b/book.pdf), since Jason apparently works there, it probably counts as authorized, but if anyone knows his contacts and can ask him, it would be nice.

**Comment by amirmc** [comment]
I wonder how outdated that text is and whether we should point people at Real World OCaml instead. Jason Hickey is listed as an author and the content is freely available online under a CC licence (CC BY-NC-ND 3.0 US).

**Comment by agarwal** [comment]
Real World OCaml is more advanced. A better up-to-date alternative to Hickey's original book is OCaml from Very Beginning, but it isn't free. The price is very reasonable but still a deterrent for someone who just wants learn OCaml for a couple days to see if they like it. Thus, I feel Hickey's free book still serves a role. We can just update the link to the alternative found by @dmbaturin. There's no reason this should require permission.

**Comment by amirmc** [comment]
> We can just update the link to the alternative found by @dmbaturin. There's no reason this should require permission.

Sounds good. I agree that it shouldn't require permission.

**Comment by dmbaturin** [comment]
It pays a bit more attention to the basics than RWO, and it's not really outdated (that is, there is nothing that doesn't compile or considered outright obsolete). If we can, I think we should keep it. Different people have different learning style, I bet there are people who'll find that this one fits theirs perfectly.

Shall I make a pull request with the caltech link?

**Comment by agarwal** [comment]
> Shall I make a pull request with the caltech link?

Yes please.

**Comment by agarwal** [comment]
@dmbaturin Would you still like to submit a pull request. It would be greatly appreciated. Thanks.

**Comment by shayne-fletcher** [comment]
On Sat, Aug 15, 2015 at 11:14 AM, Amir Chaudhry notifications@github.com
wrote:

> I wonder how outdated that text is

​I don't think it is. I think it's very good and it would be a shame to
lose it.

## 

Shayne Fletcher

**Comment by dmbaturin** [comment]
Sure, I'll make a pull request then. Do you want this and the Think OCaml removal to be one or two pull requests?

Frankly, as there was no progress in Think OCaml in nearly a year since last time we talked about it, I think it's safe to declare it dead. ;)

**Comment by agarwal** [comment]
> Do you want this and the Think OCaml removal to be one or two pull requests?

Each distinct fix should be a separate pull request please.

**Comment by Chris00** [comment]
@dmbaturin Any progress on this?
