### ISSUE TITLE
Add the ocsigen blog to the planet

### ISSUE THREAD

**Issue by Drup** [ocaml/v2.ocaml.org#687]
name: "Ocsigen Blog"
website: https://ocsigen.github.io/blog/
feed: https://ocsigen.github.io/feed.xml

The feed is generated here: https://github.com/ocsigen/ocsigen.github.io/blob/master/feed.xml
I think the id is right that way.

cc @vasilisp

**Comment by amirmc** [comment]
The feed is now generated from: https://github.com/ocaml/ocaml.org/blob/master/planet_feeds.txt
Can you edit that file and submit a PR? Should be able to do it right from your browser.

**Comment by Drup** [comment]
You should probably modify http://ocaml.org/community/planet/syndication.html
