### ISSUE TITLE
Broken HTML rendering on http://ocaml.org/learn/

### ISSUE THREAD

**Issue by bgeron** [ocaml/v2.ocaml.org#695]
The code examples on http://ocaml.org/learn/ look broken for me. This is what I see, on line 8:

```
(* e1 &and; … &and; eN *)
```

These `&and;`s should be rendered as a ∧ instead. Indeed, the [source](https://github.com/ocaml/ocaml.org/blob/master/template/learn_code_snippet.md) uses Unicode:

```
(* e1 ∧ … ∧ eN *)    <--  /template/learn_code_snippet.md:9
```

The renderer transforms it to the following HTML:

```
(* e1&nbsp;&<span class='governing'>and</span>;&nbsp;&hellip;&nbsp;&<span class='governing'>and</span>;&nbsp;eN *)
```

The `<span class='governing'>` should not have been inserted in that position, because it breaks up the `&and;` HTML entity. If it were just `&and;`, the HTML would display fine.

**Comment by Chris00** [comment]
What browser do you use?

**Comment by bgeron** [comment]
Chromium 43 on Ubuntu 14.10. Does it work for you?

**Comment by pw374** [comment]
I think it's the ocaml code highlighter that converts `&and;` to `&<span class="governing">and</span>;` because `and` is an ocaml keyword.

`<span class="comment">(* e1&nbsp;&amp;<span class="governing">and</span>;&nbsp;…&nbsp;&amp;<span class="governing">and</span>;&nbsp;eN *)</span>`

What does the conversion from `∧` to `&and;` ?

```
$ omd <<< '∧'
<p>∧</p>
```

**Comment by bgeron** [comment]
Presumably it's converted to avoid any chance of encoding mismatches. Such `&and;` string is called an _entity_; it's an encoding-independent way to use Unicode in HTML.

You can write Unicode directly in HTML, e.g. the bytes 0xe2 0x88 0xa7 for the UTF-8 encoding of the wedge ∧; these bytes indeed occur in the template file in the repository. But then the browser needs to know that it should interpret those bytes using UTF-8; I don't believe UTF-8 is the default. You can indicate the encoding in the HTML `<head>` section, and indeed this is present on http://ocaml.org/learn/, but presumably some converter along the pipeline decided it would be good to generate encoding-independent HTML.

I'm not sure what's the best way to fix this. You need some HTML entities, because you can only render a `<` in HTML by writing `&lt;` or something like that. The clean way would be to make the output part of the highlighter do the conversion from Unicode to HTML entities, but I'm not sure if that would be a major reorganisation. I actually have no idea how the HTML is currently generated.

**Comment by pw374** [comment]
It's `script/md_preprocess` that over processes that '∧'.

`````` sh
$ printf '```ocaml\n(* ∧ *)\n```\n' | script/md_preprocess  
<pre><code class='ocaml'><span class='comment'>(* &<span class='governing'>and</span>; *)</span></code></pre>
``````

 https://github.com/ocaml/ocaml.org/blob/master/script/code.ml#L24  says we shouldn't have HTML encoded stuff.

Even when it's not in a comment, it still does the conversion: 

`````` sh
printf '```ocaml\n"∧"\n```' | script/md_preprocess  
<pre><code class='ocaml'><span class='string'>&quot;&<span class='governing'>and</span>;&quot;</span></code></pre>
``````

`````` sh
printf '```ocaml\n∧\n```' | script/md_preprocess  
<pre><code class='ocaml'>&<span class='governing'>and</span>;</code></pre>
``````

**Comment by pw374** [comment]
There must be a bug in `script/md_preprocess`:

in my opinion, this is wrong:

`````` sh
$ printf '```ocaml\n"and"\n```' | script/md_preprocess  
<pre><code class='ocaml'><span class='string'>&quot;<span class='governing'>and</span>&quot;</span></code></pre>
$ printf '```ocaml\n"foo"\n```' | script/md_preprocess  
<pre><code class='ocaml'><span class='string'>&quot;foo&quot;</span></code></pre>
``````

**Comment by bgeron** [comment]
It is indeed not; HTML encoding seems to happen in https://github.com/ocaml/ocaml.org/blob/master/script/code.ml#L135 .

Maybe we should move the `html_encode` to line 130, around `before` and `qstring`? Seems the cleanest solution. That would also require that `color_string` searches for `'`, not `&quot;`, and some numbers there would need to be recalculated.

**Comment by bgeron** [comment]
Wait, that wouldn't work. The current algorithm
1. html_encodes `s`,
2. then colours the strings,
3. then applies the regexes.

I think all three would need to happen simultaneously.

Can't we just reuse someone else's highlighter? ;)

**Comment by pw374** [comment]
> Can't we just reuse someone else's highlighter? ;)

It's kind of easier said than done... I mean, would you have any suggestions for an alternative highlighter? (preferably written in OCaml, of course)

**Comment by bgeron** [comment]
Yeah, good point. I don't know much about the OCaml ecosystem; a [Github search](https://github.com/search?utf8=%E2%9C%93&q=highlighter+language%3AOCaml&type=Repositories&ref=advsearch&l=OCaml) provides one project that might do it https://github.com/mjambon/caml2html .

New idea: add another regexp that replaces `&and;` by `&#8743;`. Fixes this specific instance. That is, until we highlight numbers.

I'm more familiar with the Python ecosystem, where Pygments is widely used, fwiw. It's very customisable, and no doubt there's an OCaml definition in it already.

**Comment by pw374** [comment]
It doesn't seem too hard to adapt https://github.com/mjambon/caml2html/blob/master/output.ml for ocaml.org... Hmmm... I wonder which one takes less time, between fixing the existing or adapting something else, I'll think about it.

**Comment by bgeron** [comment]
Re your comment on 25ee251f6d3f8586e7215c506ddf5743acc71f5c, that sounds like a decent fix for the whole ticket. I think many programmers don't know about &and; anyway; I know I didn't before I started uni.

Feel free to close.

Bonus tip which I discovered in the commit comment: `&and;` in Markdown automatically shows up as &and; in GitHub.

**Comment by pw374** [comment]
Ok, I'm closing this issue. I'll open a new one regarding `∧` and `script/md_preprocess`.
