### ISSUE TITLE
Release OCaml 4

### ISSUE THREAD

**Issue by Fourchaux** [ocaml/v2.ocaml.org#698]
Hello 

http://ocaml.org/releases/

**Comment by Fourchaux** [comment]
Nothing about the 4.02.3 release ?

**Comment by pw374** [comment]
thank you for reminding us of that

**Comment by agarwal** [comment]
I'm reopening. Still need to:
- Mention 4.02.3 on the main releases page.
- Create the URL http://ocaml.org/releases/4.02.3.html
