### ISSUE TITLE
install.html: write high-level description of various installation options

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#7]
Write an introductory section that lays out the possible installation options at a high-level. For example: "you can install from source, with Godi, with odb, on Mac with godi or homebrew, on Debian with built-in debian package manager, etc". And describe roughly the factors affecting the choice, e.g. "on Debian, the built-in packages are about 1 year behind the latest releases, so very stable but will not have latest versions".

**Comment by Chris00** [comment]
I slightly modified install.html, adding a TOC. I feel the Mac OS X section is rather long. Maybe it would be more readable if the content is kept but presented a tabs http://twitter.github.com/bootstrap/javascript.html#tabs

Also, various sections contain a recommendation about libraries (e.g. batteries). This is not the right place IMHO. rather a page about how to get libraries (also speaking about odb,...) should be set up. This page can then recommend some basic libraries in a general way (independently of the way they are to be installed).

**Comment by agarwal** [comment]
Closing this issue because:
- The high level descriptions were provided long ago, even before the current redesign.
- The general issue that the page isn't well written is now redundant to more recently opened issues: #6, #136, #213, #256, #284.
