### ISSUE TITLE
Are ocaml.org graphic resources reusable for a custom reddit theme?

### ISSUE THREAD

**Issue by gasche** [ocaml/v2.ocaml.org#703]
On the [OCaml subreddit](https://www.reddit.com/r/ocaml/) I am asking whether we could have a ocaml-styled CSS theme. What is the license of the graphics content of ocaml.org, could it be reused (I'm thinking of e.g. the site logo and some of the color palette) on the subreddit?

(I couldn't find information on this by following the "About this site" or "Credits" links from the home page.)

It  goes without saying that if anyone here was interested in helping come with an OCaml reddit theme, that would be wonderful.

**Comment by amirmc** [comment]
Some of the info you're after is probably in the [LICENSE file](https://github.com/ocaml/ocaml.org/blob/master/LICENSE.md).

The logo was released under the UNLICENSE (and various files are available via https://github.com/ocaml/ocaml-logo).  The design of the site belongs to the OCaml.org project but I don't think anyone would object to using it for what you describe (though I'm not sure if that's what you meant by 'graphics').

As a separate note, we should probably add links to the LICENSE file from the two pages you mention ('About' and 'Credits').

**Comment by dbuenzli** [comment]
> (I'm thinking of e.g. the site logo and some of the color palette)

Are you talking about the banner or the ocaml logo ? The ocaml logo can be freely downloaded [here](http://ocaml.org/docs/logos.html).

There's a bit more information about the site's copyrights [here](https://github.com/ocaml/ocaml.org/blob/master/LICENSE.md).

**Comment by gasche** [comment]
Yes, I was thinking of the banner (but I'm not a designer and I'm not sure that would actually be a good idea; also arguably reuse one of the most distinctive visual elements of ocaml.org could hurt the site's visual brand), sorry for the confusion.

(Thinking about it more, I don't think there is enough vertical space available for the banner to be included as-is on a reddit page, except maybe as a background image partly visible on the top, left and right margins of the main area.)

If I understand the LICENSE document correctly, the aspect I think would be interesting to reuse, namely some of the color palette, are "reserved by the OCaml.org project". One option of course is to go for the "just a customized logo" route and there I think reusing the modern ocaml logo would be just fine, but if the reddit people would like to experiment with a more marked visual identity, I would be interested to know what the people here (and the OCaml.org project) think of some reuse. What do you think would make sense and be acceptable?

(As a point of comparison, see the visual correspondence between [r/haskell](https://www.reddit.com/r/haskell/) and [haskell.org](https://www.haskell.org/). We could similarly reuse the website gray background color and top-menu design (in addition to the OCaml logo); maybe the link colors as well, although that could be perceived as too invasive.)

**PS.:** my main question here is about the licensing aspects: which kind of reuse of the site graphical identity would be acceptable in the specific context of the OCaml subreddit? I would rather discuss the more practical design/styling advice on the reddit thread or as a separate issue -- although I understand the question of "how does the result look" is not really separable from the licensing decisions.

**Comment by amirmc** [comment]
I believe that one of the reasons for reserving the rights on the design was to avoid potential confusion if another site were to appear with the same design (i.e. we'd have some rights to fall back on if it came to that).

In my view, reusing some of the colour scheme (and the logo) for [r/ocaml](https://www.reddit.com/r/ocaml/) is fine.  I certainly don't consider it invasive and the visual correspondence is probably a nice thing to have :) --  However, I think the header image (with the sand dunes and camel) shouldn't be used elsewhere.

**Comment by agarwal** [comment]
I agree with @amirmc's interpretation of the license.

**Comment by gasche** [comment]
That's fine with me, thanks for the clarification. (I understand why the rights are reserved and I see nothing wrong with that.)

The usage suggestion by @amirmc (reuse colour scheme but not the header image) answers my question and sets a good path for a customized r/ocaml, so I'm closing this issue.
