### ISSUE TITLE
Why are the ocaml consortium and ocaml labs under "Commercial Support"?

### ISSUE THREAD

**Issue by pw374** [ocaml/v2.ocaml.org#710]
http://ocaml.org/community/support.html

This has something to do with https://github.com/ocaml/ocaml.org/issues/707 and https://github.com/ocaml/ocaml.org/commit/45c83647726705b6dbd7991959ade89110d8ee79, which did something weird on the structure of the page...

So now, I think we should either add a section title for {the ocaml consortium and ocaml labs} or remove them, because they don't provide _commercial support_. (tell me if i'm wrong)

**Comment by agarwal** [comment]
Note that this mistake isn't new. The structure of this page never quite made sense, #110.

The only reason I've left the Consortium and OCaml Labs on this page is to avoid breaking the two links: support.html#consortium and support.html#ocamllabs. Internal to the repo, I've already changed all links to consortium/index.html and ocamllabs/index.html, respectively (actually the latter didn't occur).

Probably there aren't many external sites on the internet pointing to support.html#consortium and support.html#ocamllabs, so we could just delete these. If you agree, I'll do that.

**Comment by pw374** [comment]
Ok, we agree that it's weird. :)

If we don't want to break links, and since the file is named support.html (and not commercial-support.html), perhaps we could title the page "Support" and use 2 sections: 
1. Commercial Support 
2. Giving Support

(yup, almost like it was [before](https://web.archive.org/web/20150905053218/http://ocaml.org/community/support.html), the difference being that we let section 2. small as it is now.)

**Comment by agarwal** [comment]
Ok, doing this now.

**Comment by agarwal** [comment]
Done.

For the record, I don't feel too strongly about preserving links. Websites have to change, and we shouldn't strive to make every link ever created be permanent.

**Comment by amirmc** [comment]
> Probably there aren't many external sites on the internet pointing to support.html#consortium and support.html#ocamllabs, so we could just delete these. If you agree, I'll do that.

That sounds fine to me.

I think we should avoid placing pages at 'ocaml.org/foo' where possible.  I think it makes long-term content maintenance more difficult as we end up with too many things at the top level of the site.  There are a few cases where it _does_ make a lot of sense, like the consortium page or the governance page, but ocamllabs belongs somewhere in community.

**Comment by agarwal** [comment]
> we should avoid placing pages at 'ocaml.org/foo' where possible

Agreed. I did feel the consortium was a reasonable toplevel directory. I think ocamllabs is also okay, except for the fact that the page itself isn't all that useful. I'm wondering if you would prefer linking directly to http://www.cl.cam.ac.uk/projects/ocamllabs/. Why duplicate the content.

**Comment by amirmc** [comment]
I think we added the content to the page to have some presence on the main website and to encourage others to do so.  It would be good to keep a short paragraph somewhere on the site for now, with a link back to the website.  Having said that, I _really_ don't think OCaml Labs in particular should have a toplevel page.  Although a lot of work happens to touch this group, that's primarily because it's very community focused and provides a useful co-ordination point. It's not as formal a model as the consortium is.

You're right that the current page isn't very helpful so perhaps having a few words in the 'support' section of the existing community page (with a link) might be the way to go.

**Comment by agarwal** [comment]
Ok, will you submit a pull request.

**Comment by amirmc** [comment]
Working on it now.

**Comment by amirmc** [comment]
Can't come up with a short sentence that doesn't sound clunky. :)
Will work on this later tonight.

**Comment by lefessan** [comment]
I think one of the reasons why the distinction between "Getting Support" and "Giving Support" was removed in the first time was the fact that OCamlPro and Gerd are also contributing to the ecosystem, so they should also be in the "Giving Support" area. For example, the OPAM software is developed by OCamlPro, ocamlfind by Gerd, and people should be encouraged to fund these entities also, just to contribute to OCaml.

**Comment by pw374** [comment]
Yeah, it's confusing... We should remove the "Giving Support" part and only keep the Commercial Support part. Any objections?

**Comment by agarwal** [comment]
Yeah, I'm in favor of that too. Will do in a day or so, just in case more comments are made.

@lefessan If you like, you can already adjust the text to reflect that people can also "give" support to OCamlPro's projects.

**Comment by agarwal** [comment]
Given the latest addition of IRILL on this page, I'm again unsure what to do. If we remove the Giving Support section, where would IRILL be mentioned? Even if we make a separate page for it, where would those pages be linked from? Maybe better to just leave it as-is.
