### ISSUE TITLE
list of new packages is empty (front page)

### ISSUE THREAD

**Issue by pwbs** [ocaml/v2.ocaml.org#714]
![screen shot 2015-10-09 at 10 54 04](https://cloud.githubusercontent.com/assets/15014298/10389726/186a0af4-6e74-11e5-806b-5f548cbeee73.png)

**Comment by pw374** [comment]
This is due to an error, `Fatal error: exception OpamFormat.Bad_format(_, 0, "Not a recognised version-control URL")`

**Comment by pw374** [comment]
This exception is raised in https://github.com/ocaml/ocaml.org/blob/master/script/generate_opam_update_list.ml#L7

``` ocaml
  let u = O2wUniverse.of_repositories ~preds:[] OpamfUniverse.Index_all
                                      [`opam] in
```

**Comment by pw374** [comment]
More details:

``` sh
$ OCAMLRUNPARAM=g ./generate_opam_update_list
[ERROR] At ~/.opam/repo/default/packages/unison/unison.2.48.3/opam:9:51:
  Not a recognised version-control URL
[ERROR] At ~/.opam/repo/default/packages/unison/unison.2.48.3/opam:9:51:
  Not a recognised version-control URL
Fatal error: exception OpamFormat.Bad_format(_, 0, "Not a recognised version-control URL")
```

I traced the error to https://github.com/ocamllabs/opamfu/blob/master/lib/opamfUniverse.ml and got lost...

@dsheets could you help on this one?

**Comment by dsheets** [comment]
Apparently, GitHub does not notify people of mentions made in edits to comments. Sorry this took a while to notice. The longer-term solution is to update the opam2web stuff (incl. opamfu) to use a newer opam-lib that doesn't explode on these kinds of issues (or catch and ignore errors in systems that only provide summary statistics).

**Comment by dsheets** [comment]
This does not appear to have fixed the problem and I don't appear to be able to log in to the web host.

**Comment by pw374** [comment]
@dsheets thank you. I've just forced an `opam update` and built the list in `/tmp`. 
The next build should make the list appear.

**Comment by pw374** [comment]
The list is back online :)
Closing this issue.
