### ISSUE TITLE
Please, remove or synchronize the “old” planet

### ISSUE THREAD

**Issue by smondet** [ocaml/v2.ocaml.org#728]
This seems to be the master copy: http://ocaml.org/community/planet/
while the old one http://planet.ocaml.org/ is slightly out-of-sync (e.g. the ocsigen blog is not there)

**Comment by Chris00** [comment]
It probably better to be removed.  @avsm ?

**Comment by amirmc** [comment]
Old planet DNS should be redirected to the new url. I had a brief email exchange with Sylvain about this some time ago and the plan IIRC was to add one last post to the old feed to let the subscribers know about the change. 

Best wishes,
Amir

## 

Sent via mobile

**Comment by Chris00** [comment]
On Wed, 4 Nov 2015 12:57:29 -0800, Amir Chaudhry wrote:

> Old planet DNS should be redirected to the new url. I had a brief email exchange with Sylvain about this some time ago and the plan IIRC was to add one last post to the old feed to let the subscribers know about the change.

This is a reasonable course of action.  Is somebody in charge of implementing it?

**Comment by Drup** [comment]
Ping, could we get this done ?

**Comment by gildor478** [comment]
I am pretty busy right now, but I plan to do it.

**Comment by Chris00** [comment]
Ping?

**Comment by gildor478** [comment]
Indeed it is time to move on and start this migration.

Here is the text for the final post I plan to do on the forge (which is republished on planet.ocamlcore.org and ocaml.org):

Title: planet.ocamlcore.org will soon be deprecated

For the past 8 years the OCaml Planet was running on http://planet.ocamlcore.org. A few years ago, another planet has forked and it is now better maintained than the old one. This new planet is located here http://ocaml.org/community/planet/ and the old planet will soon redirect to this new location.

If you were using a feed reader, I recommend to point your feed reader directly to the new planet:
http://ocaml.org/feed.xml

Tell me if it looks good and I'll publish it.

**Comment by Chris00** [comment]
Sylvain Le Gall writes:

>  Tell me if it looks good and I'll publish it.

Looks fine to me.
