### ISSUE TITLE
Accept Transfer of ocaml.net Domain

### ISSUE THREAD

**Issue by sharpjs** [ocaml/v2.ocaml.org#733]
I own the [`ocaml.net`](http://ocaml.net) domain. I registered it a few years ago when it expired, to prevent it from being snatched by a squatter.  I set up a web redirect to [`ocaml.org`](http://ocaml.org) and mail forwarding at that time, but was unable to stay in contact with an OCaml site administrator.

I want to transfer the domain to the proper owner.  No payment is desired — I just want to donate the domain.  Please let me know what steps to take.

**Comment by dsheets** [comment]
Hi @sharpjs, @avsm is the delegate in charge of ocaml.org as directed by @xavierleroy. I believe one of them can tell you the appropriate action to take.

Thanks for your quick reflexes and forethought -- I'm sure everyone in the community appreciates your contribution (even if they don't know it, yet :stuck_out_tongue:).

**Comment by amirmc** [comment]
Indeed, thank you very much!

Best wishes,
Amir

## 

Sent via mobile

**Comment by avsm** [comment]
Dear @sharpjs, thank you very much for doing this!  The owner of the domain should be @xavierleroy, but I can handle the administrative end.  The appropriate Gandi handle is XL27-GANDI (owned by Xavier Leroy and where the current ocaml.org domain is held).  If you would like to coordinate over email, please free to contact me at anil@recoil.org.

**Comment by sharpjs** [comment]
Email sent to @avsm.  Let me know if it does not reach you.  Thanks!

**Comment by sharpjs** [comment]
Retry email sent to @avsm, this time from my Gmail account, in case the first one didn't make it.  The authorization code was included in this email.  Hope it hasn't expired already.  Let me know if you need me to get a newer code.

**Comment by Chris00** [comment]
Were are we on this issue? @avsm ?

**Comment by xavierleroy** [comment]
ocaml.net was successfully transferred to Gandi last December, and I'm now the proud owner of this domain!

Unless I goofed again,  @avsm has technical admin rights on ocaml.net and can set up the DNS.  But there's nothing urgent.

**Comment by agarwal** [comment]
@avsm It would be great if we could have ocaml.net forward to ocaml.org.

**Comment by Chris00** [comment]
[ocaml.net](http://ocaml.net/) is still a white page at the moment.  Any plan to do what @agarwal suggests?

**Comment by ghost** [comment]
This is done

**Comment by agarwal** [comment]
I also confirm ocaml.net is forwarding to ocaml.org. Not sure who configured this, but we have confirmation that Xavier owns the domain. So I think we're all good on this issue. I'm closing. @sharpjs Thank you!
