### ISSUE TITLE
Packages widget on the main page is empty

### ISSUE THREAD

**Issue by artemkin** [ocaml/v2.ocaml.org#738]
![Packages widget on the main page is empty](https://cloud.githubusercontent.com/assets/472955/11540958/0b4d2ebe-9949-11e5-9505-d2050fa8eb4d.png)

**Comment by pwbs** [comment]
again! that's not cool... :( 

however, it seems that it's not empty, right now...

**Comment by artemkin** [comment]
yes, it works now
