### ISSUE TITLE
Ubuntu instructions are needlessly opaque

### ISSUE THREAD

**Issue by mor1** [ocaml/v2.ocaml.org#744]
Install instructions at http://ocaml.org/docs/install.html#Ubuntu say to "mimic the instructions in the opam-repository's test script" with a link on "script" to https://github.com/ocaml/opam-repository/blob/master/.travis-ci-install.sh which simply fetches and executes https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-ocaml.sh which then works through a set of possible configurations that might be required to setup a Travis build environment.

It would surely be simpler for new users to replace all that with instructions something like:
1. Add @avsm PPAs by `sudo add-apt-repository --yes ppa:avsm/ocaml42+opam12`
2. Update package lists by `sudo apt-get update -qq`
3. Install OPAM by `sudo apt-get install -y opam`
4. Enable OPAM by `eval $(opam config env)`
5. Run `utop`

...I don't know the PPA system but obviously if there's some way to indicate `latest` or similar instead of specifying the exact PPA, that would be even better.

**Comment by avsm** [comment]
I have a stable ppa at `ppa:avsm/ppa` with the latest good versions.

**Comment by mor1** [comment]
Ah, ok. So (1) would become "... `sudo add-apt-repository --yes ppa:avsm/ppa`" ?  Cool!

I'm happy to create a PR with the above edits if that's appropriate...

**Comment by agarwal** [comment]
A pull request would be great.

**Comment by mor1** [comment]
Ok, will try and do that today

On 10 December 2015 at 15:18, Ashish Agarwal notifications@github.com
wrote:

> A pull request would be great.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ocaml/ocaml.org/issues/744#issuecomment-163655582.

## 

Richard Mortier
mort@cantab.net

**Comment by Chris00** [comment]
@mor1 Gentle reminder

**Comment by mor1** [comment]
Sorry-- PR incoming... :)

**Comment by redianthus** [comment]
@Chris00, I think this can be closed.

**Comment by Chris00** [comment]
Thanks.
