### ISSUE TITLE
Site isn't self-contained bc link to http://caml.inria.fr/pub/docs/manual-ocaml/

### ISSUE THREAD

**Issue by 0joshuaolson1** [ocaml/v2.ocaml.org#750]
This could be two issues:
- it should be possible to browse a local build of the website without internet
- "Manual" under "Documentation" links to the INRIA-discouraged domain caml.inria.fr

**Comment by amirmc** [comment]
Related issues are #115 and #664.

_edit: from [this comment](https://github.com/ocaml/ocaml.org/issues/115#issuecomment-108096177) onwards_.

**Comment by 0joshuaolson1** [comment]
Sorry! Should I close as won't be done or duplicate?

**Comment by amirmc** [comment]
@MrMormon No need to apologise!  #115 is for context for others who find their way to this issue, (including other maintainers). #664 is the one that would resolve this so I just cross-referenced it.

There's definitely intent to fix this but I didn't want to 'close as dupe' just yet.

Thank you for filing this issue :)

**Comment by agarwal** [comment]
> INRIA-discouraged domain caml.inria.fr

To clarify, all of `caml.inria.fr` is deprecated _except_ `caml.inria.fr/pub`. The `pub/` directory at INRIA is the master source of that data.

The mirroring suggested in #664 is unlikely to resolve your desire to have all of ocaml.org available offline. The `pub/` directory contains a rather large amount of data, which I doubt you'll be willing to download locally.

**Comment by agarwal** [comment]
I don't see any actionable item in this issue, so I'm closing it.
