### ISSUE TITLE
ocaml pro's RSS is 404

### ISSUE THREAD

**Issue by pwbs** [ocaml/v2.ocaml.org#759]
@lefessan 

![screen shot 2016-02-22 at 19 49 09](https://cloud.githubusercontent.com/assets/15014298/13228659/726a3328-d99d-11e5-9753-a4abebfee8bc.png)

**Comment by cagdasbozman** [comment]
Sorry, we did some maintenance on our server, the new feed url is the following:

```
http://www.ocamlpro.com/feed/
```

**Comment by pwbs** [comment]
Could you please make a PR ? :)

Philippe Wang
(mail sent from a phone)

**Comment by Chris00** [comment]
As a general note: inaccessible RSS feeds are stroked through on the page  http://ocaml.org/community/planet/ with a message explaining the reason when you hover them.

**Comment by cagdasbozman** [comment]
@pwbs [done](https://github.com/ocaml/ocaml.org/pull/761) :)

**Comment by cagdasbozman** [comment]
@Chris00 This is very cool, I didn't notice that feature on this page. I totally forgot to update the feed URL on ocaml.org.
