### ISSUE TITLE
Travis builds failing on opam update.

### ISSUE THREAD

**Issue by rudenoise** [ocaml/v2.ocaml.org#760]
During my pull request (a change on a Markdown file) https://github.com/ocaml/ocaml.org/pull/758 the Travis build failed.

Log here: https://travis-ci.org/ocaml/ocaml.org/builds/110806601

From what I can see, opam is not able to load a config file for OCaml 4.01.0, the error message originates here: https://github.com/ocaml/opam/blob/master/src/state/opamState.ml#L1406

**Comment by AltGr** [comment]
Thanks for reporting. This seems related to the way the travis script caches ~/.opam. I don't know exactly what happened, but clearing the cache seems to have made the situation better. The main issue is that the travis script tries to recover in case of opam errors and reinit, but in this case opam displayed loads of errors... but exited with 0, so no recovery was attempted. I'll make sure the next opam version doesn't do that.

**Comment by rudenoise** [comment]
Looks good on Travis, I'll close this issue. Thanks.
