### ISSUE TITLE
New packages list empty

### ISSUE THREAD

**Issue by yallop** [ocaml/v2.ocaml.org#769]
The "New packages" list on http://ocaml.org is looking rather empty.   Has something gone wrong with the process that updates the list?

**Comment by pwbs** [comment]
there's something wrong indeed...

```
$ ocaml.org/script/generate_opam_update_list
[ERROR] At ~/.opam/repo/default/packages/planets/planets.0.1.14/opam:6:48:
  Not a recognised version-control URL
Fatal error: exception OpamFormat.Bad_format(_, 0, "Not a recognised version-control URL")
```

**Comment by pwbs** [comment]
@dsheets  please can you look into this?

**Comment by amirmc** [comment]
@dsheets is away this week.  Seems the dev-repo field is incorrect.  Looking at the most [recent change](https://github.com/ocaml/opam-repository/commit/6f933d6d7a0dd214e6799dbd7b3f408f8daa2a45#diff-ef3f2d7780e7295f7e67aab435c8e01f), it seems the dev-repo field was edited too.

**Comment by pwbs** [comment]
If the field is clearly wrong, perhaps it should just be removed ?

Philippe Wang
(mail sent from a phone)

**Comment by amirmc** [comment]
I've commented it out for now (a repo maintainer should merge that PR).  I tried to figure out how to represent a Bitbucket/Mercurial repo but couldn't.

**Comment by pwbs** [comment]
I had tried for a few minutes to git-clone it, then I gave up.
I don't understand how bitbucket advertises git-based services but make is so anti-obvious to just clone their repos...

Philippe Wang
(mail sent from a phone)

**Comment by amirmc** [comment]
Is it git or hg? I couldn't really tell though I noticed a .hgignore file in the repo. Having said that, adding '.git' to the current dev-repo field seemed to be a valid URL.

Best wishes,
Amir

## 

Sent via mobile

**Comment by pw374** [comment]
It's empty again... We really need to put an alert when it's empty...

**Comment by pw374** [comment]
```
$ make opam_update_list
script/generate_opam_update_list
[ERROR] At ~/.opam/repo/default/packages/ordma/ordma.0.0.1/opam:7:45:
  Not a recognised version-control URL
[ERROR] At ~/.opam/repo/default/packages/ordma/ordma.0.0.1/opam:7:45:
  Not a recognised version-control URL
Fatal error: exception OpamFormat.Bad_format(_, 0, "Not a recognised version-control URL")
make: *** [opam_update_list] Error 2
```

**Comment by pw374** [comment]
I suspect that the opamlib installed on ocaml.org is not the latest, hence this issue. But I'm only guessing!

@dsheets ?

**Comment by dsheets** [comment]
That's likely. I think all of the ocaml.org stuff runs on OCaml 4.01 and opam 1.1 and badly needs updating.

**Comment by samoht** [comment]
Not sure why Github closed that issue automatically, but I've pushed a fix to opam repo which should fix the current issue with ordma.

**Comment by dsheets** [comment]
The substring "fixes #x" trigger issue/PR closure of #x when found in commit messages or PR descriptions.

**Comment by AltGr** [comment]
@samoht seems like Github likes to take words out of context: your commit msg was "_Hopefully_ fixes ocaml/ ocaml.org#769" [edited to make sure it won't close again...] ☺

@pw374 no, the system compiler is still 4.01 but the repo is running on 1.2.2 (it couldn't work at all on 1.1 !) ; it's using an opam compiled locally in ~opam/ though. URL handling has been rewritten in august, but there was no release since then (just a _little_ bit more patience, it's coming very soon).

**Comment by yallop** [comment]
Something seems to be wrong again.  The new packages list is a few days out of date:

![newpackages](https://cloud.githubusercontent.com/assets/1736496/14641682/643f2898-063f-11e6-8d6f-b7d710d7ae6f.png)

and packages merged in recent days ([e.g.](https://github.com/ocaml/opam-repository/pull/6258)) aren't showing up in the `https://opam.ocaml.org` remote.

**Comment by agarwal** [comment]
This list is again empty.

**Comment by pw374** [comment]
I resuscitated my old generator (written in bash). 

Please restore the good ocaml version when it's working again.

**Comment by pw374** [comment]
Well, plugging the old script was not as trivial as expected, but now it should work fine for a while.

**Comment by pw374** [comment]
When the opam_update stuff is fixed, remove 

``` bash
    # TEMPORARY FIX
    if [[ -s ~/opam-repository/packages/.package-list ]] ; then
    cp  ~/opam-repository/packages/.package-list opam_update_list
    touch -d 200101 opam_update_list # touch the file far in the future (year 2020) so that make doesn't re-generate it
    fi
```

from `build_ocaml.org.bash` and it'll get out of the way. (And maybe kill the `screen` that runs `bash make_opam_package_list.bash`.)

**Comment by Chris00** [comment]
Commented out the temporary fix.

**Comment by pw374** [comment]
Does it mean that this issue can be closed?

**Comment by Chris00** [comment]
Yes — there is https://github.com/ocaml/ocaml.org/issues/815 to take care of the the strengthening of the reporting.
