### ISSUE TITLE
ocaml install fails (debian)

### ISSUE THREAD

**Issue by hgouraud** [ocaml/v2.ocaml.org#775]
environment is : Linux icpu3029 3.2.72-grsec-infong-15294 #1 SMP Wed Oct 21 14:57:23 CEST 2015 x86_64 GNU/Linux

fresh install from sources ocaml-3.12.1
./configure -prefix $HOME

error message is:

<pre>
make[2]: Entering directory `/homepages/30/d456759237/htdocs/packages/ocaml-3.12.1/otherlibs/num'
gcc -fno-defer-pop -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -I../../byterun -O -fPIC -DBNG_ARCH_amd64 -DBNG_ASM_LEVEL=1 -c bng.c
In file included from bng.c:23:
bng_amd64.c: In function 'bng_amd64_mult_add_digit':
bng_amd64.c:113: error: can't find a register in class 'GENERAL_REGS' while reloading 'asm'
bng_amd64.c:113: error: 'asm' operand has impossible constraints
make[2]: *** [bng.o] Error 1
make[2]: Leaving directory `/homepages/30/d456759237/htdocs/packages/ocaml-3.12.1/otherlibs/num'
make[1]: *** [otherlibraries] Error 2
make[1]: Leaving directory `/homepages/30/d456759237/htdocs/packages/ocaml-3.12.1'
make: *** [world] Error 2
</pre>

Ultimately, my goal is to install ocaml 4.02 and opam, but I run into similar problems.

Thanks for any help
Henri

**Comment by pw374** [comment]
please open this issue on https://github.com/ocaml/ocaml

**Comment by hgouraud** [comment]
I dont see any "new issue" button at this location!!

**Comment by pw374** [comment]
Aaaaaah... :( 

Then I guess it should go to either http://caml.inria.fr/mantis/my_view_page.php or email caml-list@inria.fr (https://sympa.inria.fr/sympa/info/caml-list)

**Comment by pw374** [comment]
If you want quick replies, I advise using caml-list@inria.fr ;-)
