### ISSUE TITLE
Ocaml compile fails on Linux Roxx 3.10.23-xxxx-std-ipv6-64 #1 SMP Tue Mar 18 14:48:24 CET 2014 x86_64 x86_64 x86_64 GNU/Linux

### ISSUE THREAD

**Issue by hgouraud** [ocaml/v2.ocaml.org#776]
Starting from scratch
tar xvf ocaml-4.02.3.tar
cd ocaml-4.02.3
./configure -prefix $HOME
make clean
make world.opt
make coldstart
make[1]: Entering directory `/homepages/30/d456759237/htdocs/packages/ocaml-4.02.3'
cd byterun; make all

……

make[4]: Entering directory `/homepages/30/d456759237/htdocs/packages/ocaml-4.02.3/asmrun'
gcc -I../byterun -DCAML_NAME_SPACE -DNATIVE_CODE -DTARGET_amd64 -DSYS_linux  -O -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT   -c -o startup.o startup.c
ln -s ../byterun/main.c main.c

………

gcc -I../byterun -DCAML_NAME_SPACE -DNATIVE_CODE -DTARGET_amd64 -DSYS_linux  -O -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT   -c -o signals_asm.o signals_asm.c
signals_asm.c: In function 'segv_handler':
signals_asm.c:207: error: 'REG_CR2' undeclared (first use in this function)
signals_asm.c:207: error: (Each undeclared identifier is reported only once
signals_asm.c:207: error: for each function it appears in.)
signals_asm.c:213: error: 'REG_RIP' undeclared (first use in this function)
signals_asm.c:228: error: 'REG_R14' undeclared (first use in this function)
signals_asm.c:229: error: 'REG_R15' undeclared (first use in this function)
make[4]: **\* [signals_asm.o] Error 1
make[4]: Leaving directory `/homepages/30/d456759237/htdocs/packages/ocaml-4.02.3/asmrun’

???

Henri

p.s. full log available on reguest

**Comment by pw374** [comment]
I think you meant to open this issue on https://github.com/ocaml/ocaml instead...
