### ISSUE TITLE
latest version number in web page

### ISSUE THREAD

**Issue by JuliaLawall** [ocaml/v2.ocaml.org#786]
The number of the latest version should be more easily accessible at ocaml.org.

**Comment by Chris00** [comment]
Gabriel Scherer said on the mailing list:

> We discussed how to give more visibility to OCaml releases last September:
>   http://lists.ocaml.org/pipermail/infrastructure/2015-September/000537.html
>   OCaml.org issue: https://github.com/ocaml/ocaml.org/issues/701
> 
> The feature request #701 did not result in a change, but the discussions were about more invasive change than just adding some content on one of the pages, so I'm not sure it's reasonable to expect an external contributor to lead it.
> 
> From an "upstream OCaml" point of view, what I would like to have is a clear description of the process to follow to edit ocaml.org on the event of an OCaml release. I think the people that know ocaml.org best should decide on that, and then I'd try to get it done on each release.

**Comment by agarwal** [comment]
I've resolved #701, which regarded making the Releases page more evident. That indirectly makes the latest version more evident, but maybe you don't think it addresses it enough. If not, please propose a more specific change.

**Comment by JuliaLawall** [comment]
On Sat, 14 May 2016, Ashish Agarwal wrote:

> I've resolved #701, which regarded making the Releases page more evident.
> That indirectly makes the latest version more evident, but maybe you don't
> think it addresses it enough. If not, please propose a more specific change.

I looked and it still seems obscure.  At the bottom of ocaml.org there is 
a section with packages and their most recent releases.  Why not put ocaml 
itself there?  Another idea could be to make the first sentence on the 
"Install OCaml" page be "The most recent release of OCaml is XXX".  Both 
would be fine too.

thanks,
julia

**Comment by Chris00** [comment]
From a technical point of view, I think the first thing to do is to define a MPP variable with the latest OCaml version.  IMHO, the value of this variable should be inferred from the content of `site/releases/` (maybe using Git history for the release date?).  Once this is done, the latest OCaml version should indeed be displayed at various places to be easier to find.

> At the bottom of ocaml.org there is a section with packages and their most recent releases. Why not put ocaml itself there? 

I do not think it will work because the release would only stay a couple of days — unless a special line is added that is not treated as a normal package (maybe your idea).

**Comment by JuliaLawall** [comment]
On Sun, 15 May 2016, Christophe Troestler wrote:

> From a technical point of view, I think the first thing to do is to define a
> MPP variable with the latest OCaml version. IMHO, the value of this variable
> should be inferred from the content of site/releases/ (maybe using Git
> history for the release date?). Once this is done, the latest OCaml version
> should indeed be displayed at various places to be easier to find.
> 
> ```
>   At the bottom of ocaml.org there is a section with packages and
>   their most recent releases. Why not put ocaml itself there?
> ```
> 
> I do not think it will work because the release would only stay a couple of
> days — unless a special line is added that is not treated as a normal
> package (maybe your idea).

OK, as seems convenient.  As an OCaml user, I am much more interested in 
the current version of OCaml than the current version of packages that I 
am not using, so it seems strange that the information I am not interested 
in is easy to find and the information I am interested in is hard to find.

But looking for the latest version on the download page is also a 
reasonable strategy.

thanks,
julia

**Comment by Chris00** [comment]
@dsheets Is there a simple way to get the version of the latest compiler using `opamfu`?

**Comment by dsheets** [comment]
I don't believe there is right now. `opamfu` only deals with packages at this time.

**Comment by amirmc** [comment]
I agree with making it easier to find out the current version of OCaml release. For example, taking Christophe's suggestion, the version could be added to the top of the [install page](http://ocaml.org/docs/install.html) or even underneath the "Install OCaml" button on the front page.

>  As an OCaml user, I am much more interested in
> the current version of OCaml than the current version of packages that I
> am not using, so it seems strange that the information I am not interested
> in is easy to find and the information I am interested in is hard to find.

The current version of OCaml doesn't change very often, whereas packages are released all the time.  The purpose of the packages pane is to highlight newly updated packages, signalling activity in the ecosystem — especially to new visitors.
