### ISSUE TITLE
Only minor missue: OCaml 4.03.0 released, May 25, 2016

### ISSUE THREAD

**Issue by manfredlotz** [ocaml/v2.ocaml.org#793]
https://ocaml.org/ says 

OCaml 4.03.0 released
May 25, 2016

Perhaps it should read: May 15

**Comment by Chris00** [comment]
Why do you [think](http://caml.inria.fr/pub/distrib/ocaml-4.03/) [so](http://caml.inria.fr/news.en.rss)?

**Comment by dbuenzli** [comment]
april

**Comment by Chris00** [comment]
The files were released on April 25 (and this is the date used on the [release page](http://ocaml.org/releases/)) but the news was on [May 25](http://caml.inria.fr/news.en.rss) so this is the date reported in the news feed.  
@xavierleroy @damiendoligez This is a typo in Inria RSS file (assuming it is generated by hand).

**Comment by manfredlotz** [comment]
> Why do you think so?

Well, it is clear that is must be wrong because on the one hand May 25 is next week and on the other hand I knew 4.03.0 was out already. I hadn't checked the date (just assumed May 15th) but right it was April 25.

**Comment by Chris00** [comment]
@manfredlotz I agree — I first just looked at the difference you mentioned, not paying attention to the month.

**Comment by Chris00** [comment]
Since it is the RSS file that must be fixed, I am closing this issue.

**Comment by manfredlotz** [comment]
I fully agree.

**Comment by damiendoligez** [comment]
FYI, I fixed the RSS on the Inria server.
