### ISSUE TITLE
Ubuntu installation instructions out of date

### ISSUE THREAD

**Issue by GemmaG** [ocaml/v2.ocaml.org#801]
https://ocaml.org/learn/tutorials/get_up_and_running.html

Update installation instructions here.

**Comment by avsm** [comment]
Ubuntu 16.10 does not need the PPA anymore, so the opam.ocaml.org and ocaml.org instructions should reflect that ... earlier versions still do.

**Comment by ggirtsou** [comment]
I confirm installing OCaml on Ubuntu 16.10 via `sudo apt-get install ocaml` works, same for `ocamlbuild`. At first I thought the package I installed was broken, because it couldn't find the command `ocambuild` but then I realised I made a typo and it should be `ocamlbuild`.

**Comment by redianthus** [comment]
I think this is fixed for the English version. I updated the french one in #992.
