### ISSUE TITLE
Make Caml Weekly News archives more prominent

### ISSUE THREAD

**Issue by avsm** [ocaml/v2.ocaml.org#804]
One of the best resources for keeping up with OCaml events is the [OCaml Weekly News](http://alan.petitepomme.net/cwn/) maintained by Alan Schmitt for the past 15 years and counting.  However, it is rather difficult to find from the front page of ocaml.org, and so is skipped by most newcomers to the language.

Could we make this more prominent or at least linked somewhere from the front page?

**Comment by amirmc** [comment]
Some previous discussion in https://github.com/ocaml/ocaml.org/issues/336 (some comments may still be useful).

**Comment by Chris00** [comment]
I am thinking of a colored block at the bottom of the "News" feed and maybe replace the Meetings block on the [Community page](https://ocaml.org/community/) which is not at all up to date. :-(

**Comment by amirmc** [comment]
The meeting block was hard coded as we didn't (IIRC) have the necessary libs to consume an iCal feed and auto-generate content. I'm not sure if we have those now. 

Replacing it with something that refreshes would be better. :)

Best wishes,
Amir

## 

Sent via mobile

**Comment by Chris00** [comment]
@brabalan How do you feel about the CWN to be duplicated on a page of ocaml.org?  It seems difficult to have CWN more prominently displayed (front page & community page) if it sends outside the domain.

**Comment by brabalan** [comment]
Sure thing. How do we do it technically?

By the way, the three weeks hiatus is due to me being on holidays on an island with a broken phone. The next CWN will be published on Tuesday.

**Comment by Chris00** [comment]
So far, I put a link on the [front page](http://ocaml.org/) and on the [community page](http://ocaml.org/community/), the date being taken from your RSS2 feed.  They both point to a [CWN page](http://ocaml.org/community/cwn/), scraped from your site.  (This last page may benefit from some styling.)  @avsm Would this be enough for you?

If you want to keep doing as of now, this is thus possible (and the easier probably).  If you would like to publish the following CWN directly on ocaml.org, I guess this would not be a problem to give you commit access — in which case I would use the current script to import all old ones.  What do you think?

**Comment by brabalan** [comment]
If I don't need to change anything, then I'm very happy. I need to redo the whole generation chain to make it more flexible (at the moment I'm relying on a 13 years old xtatic program), but for that I need to find some time.

I propose the following: we use the scraping approach for the moment, and when/if I've redone the generation chain, I'll include a step to generate something that fits well with ocaml.org (I suppose it should be markdown?). Does this work with you?

**Comment by Chris00** [comment]
The removal of the first few items (the navigation links and the "Hello") is brittle at the moment.  If you rework your script, maybe we could agree on a tag to serve as a container for the part of the content that is to be published on ocaml.org?

**Comment by brabalan** [comment]
We could do that, but I need to redo the chain from scratch: I just tried and I cannot modify the source and get it to compile (the mono compiler just does not terminate).

In the meantime, can't you remove everything between the `body` tag and the first `ol` tag?

**Comment by Chris00** [comment]
I could but the first sentence is useful — in particular because it says what period is covered.

**Comment by brabalan** [comment]
Then I would remove everything from the body to the second `p` tag (to remove the Hello, but not the period and the eventual extra commentary). It's generated, so it will always be like that.

**Comment by Chris00** [comment]
I have implemented your suggestion.

So far I have kept the `<script>` at the end so visits to http://ocaml.org/community/cwn/ may register as hits (even though I would prefer to keep google out of the way).  Let me know if you would prefer to remove it.

**Comment by brabalan** [comment]
You can remove the `<script>` (this is something I will remove when I rewrite the generator). Thanks!
