### ISSUE TITLE
display companies on a world map

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#81]
Would be nice to display companies listed [here](http://ocaml.org/companies.html) on a world map. Extra points for making the marker be each company's icon.

**Comment by amirmc** [comment]
Thanks for the info. I'm actually reluctant to make a map with markers -- something like the kind displayed by Google Analytics would be preferable.

(I'd rather not make a map at all for the moment, I think it'd be more valuable once there are many more companies listed).

**Comment by agarwal** [comment]
I think this isn't a good idea anymore. Many companies are global, so don't have a single location. Also, emphasizing geography is somewhat meaningless for a technology that can be quite effectively employed from anywhere with internet access.
