### ISSUE TITLE
port media from Inria

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#82]
As recommended by Anil, port all static media (e.g. PDF, tarballs) from caml.inria.fr to a new github repo and make that repo a submodule of this one.

**Comment by agarwal** [comment]
I've created a new ocaml.org-media repo, and emailed Xavier about a bulk transfer of the files on Inria's server.

**Comment by agarwal** [comment]
Xavier's impression is that it will be easier to leave most static media on caml.inria.fr, especially as long as Damien is the release manager. They will continue to manage most of this content, and they feel it will be easier for them to continue using their current setup. However, we should look through all of the media and assure that none of it relates strictly to html content (e.g. images). Such items really should be moved to the ocaml.org repo.

Most (perhaps all) of the content in question here is available tat http://caml.inria.fr/pub/. We can use `wget -R` to pull all of it and look through it to assess what perhaps should be moved.

**Comment by dsheets** [comment]
Any news on this? I think it's related to #515.

**Comment by agarwal** [comment]
My view has been that all content under `caml.inria.fr/pub/` is still fully valid, and all other paths under `caml.inria.fr` are deprecated. I don't think there's anything we can do about this. Inria wants to maintain the pub/ folder as-is. (Ideally we could do #115.)

Thus, I think we can close this issue.
