### ISSUE TITLE
Robots.txt blocked in production

### ISSUE THREAD

**Issue by rsiddle** [ocaml/v2.ocaml.org#821]
The robots.txt file at https://ocaml.org/robots.txt is blocking all web crawlers from visiting the website, so it makes it very difficult for Google, Bing, etc to find the documentation and other resources. This only affects the main domain with no subdomain prefix. https://opam.ocaml.org would not be affected, for example.

Not all URLs have been removed by Google yet. The screenshot below shows that there are still 418 pages left, however they will be phased out slowly if the web crawlers are not allowed to revisit. Notice that the homepage isn't indexed.

<img width="778" alt="screen shot 2016-08-08 at 09 03 40" src="https://cloud.githubusercontent.com/assets/18415/17473208/25df6428-5d47-11e6-825e-21a9ad51717f.png">

Flux on IRC said

>  it seems like a genuine bug as https://github.com/ocaml/ocaml.org/blob/a772c6ff256a79f1969c9593a3ab06313919eb84/Makefile has 'rm ocaml.org/robots.txt' in its production rule

The current code is:

```
User-agent: *
Disallow: /
```

It should read

```
User-agent: *
Allow: /
```

**Comment by Chris00** [comment]
Yeah, that file should never have made it to the production server (it was destined to copies of the website used for testing).  I'll fix that ASAP.

**Comment by Chris00** [comment]
The file is now gone (for some reason, it was put there once and the update script did not dot remove it—now it does!).

Thanks for reporting!
