### ISSUE TITLE
fix code in FAQ

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#83]
Content of Inria's faq were imported, but the code highlighting is not right.

**Comment by Chris00** [comment]
This is done 51c3ad5902c60fc71e85b474fcbe9f2a8da1891b but there are still some glitches.

**Comment by Chris00** [comment]
I think it is now satisfactory 9a6a2578aa3909bc6fc1cf46c7a050f69b231c9b e80faad3c1276515edc4da6d4a80baa904d866df 0a5c8597510f22a09d4e4d032d7b9645851809ec
