### ISSUE TITLE
Page tocs are broken if the section header is a link itself

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/v2.ocaml.org#832]
E.g. on this page http://ocaml.org/docs/install.html a lot of the section platform headers are links to the corresponding system. Clicking in the toc on a section doesn't lead you to the section but the destination link of the header.

**Comment by pw374** [comment]
Indeed, the generated HTML is wrong. Thanks for reporting.

**Comment by pw374** [comment]
Now fixed in OMD. I'll try to deploy that today.

**Comment by pw374** [comment]
It should be fixed now. Thanks again.

**Comment by pw374** [comment]
Or maybe it's not... o_O

**Comment by dbuenzli** [comment]
Thanks !
