### ISSUE TITLE
opam.ocaml.org presents an expired certificate

### ISSUE THREAD

**Issue by emillon** [ocaml/v2.ocaml.org#835]
Not sure if it's related to #834, but it is impossible to connect to `opam.ocaml.org` at the moment.

As a consequence, `opam update` fails.

![expired](https://cloud.githubusercontent.com/assets/496345/18665400/6c1d5312-7f27-11e6-8d71-60a4784699ef.png)

```
% openssl s_client -host opam.ocaml.org -port 443       
CONNECTED(00000003)
depth=2 C = US, ST = UT, L = Salt Lake City, O = The USERTRUST Network, OU = http://www.usertrust.com, CN = UTN-USERFirst-Hardware
verify return:1
depth=1 C = FR, O = GANDI SAS, CN = Gandi Standard SSL CA
verify return:1
depth=0 OU = Domain Control Validated, OU = PositiveSSL Multi-Domain, CN = ocaml.org
verify error:num=10:certificate has expired
notAfter=Sep 19 23:59:59 2016 GMT
verify return:1
depth=0 OU = Domain Control Validated, OU = PositiveSSL Multi-Domain, CN = ocaml.org
notAfter=Sep 19 23:59:59 2016 GMT
verify return:1

---
```

Thanks.

**Comment by samoht** [comment]
We are trying to resolve the issue but unfortunately it is due to multiple causes so it takes longer than it should be.

As a workaround you can use the Git repository directly:

```
opam repo add git https://github.com/ocaml/opam-repository.git
```

**Comment by emillon** [comment]
OK, thanks. Good luck! :closed_lock_with_key:

**Comment by Chris00** [comment]
For those trying to `opam init`, you can create a file `~/.curlrc` with content `insecure` (do not forget to remove it when the problem is fixed).

**Comment by emillon** [comment]
Hey,

It seems to be back up. Shall I close this bug?

**Comment by pw374** [comment]
> It seems to be back up. Shall I close this bug?

Sure.

**Comment by AltGr** [comment]
Ah, just saw this issue... thankfully, I had noticed and quickly put in a Letsencrypt certificate to fix the situation during jet-lag induced insomnia in the middle of ICFP :p
Users of opam 1.2 likely didn't notice since that still has `--insecure` enabled by default.
Note that this is separate from the issue `ocaml.org` had (different VM, which got completely broken) -- but they shared the same certificate.
