### ISSUE TITLE
Issue with HTTPS

### ISSUE THREAD

**Issue by dave-tucker** [ocaml/v2.ocaml.org#844]
Browsing to `https://ocaml.org` results in the following error in Chrome (Version 53.0.2785.143 (64-bit))

<img width="729" alt="screenshot 2016-10-04 14 01 57" src="https://cloud.githubusercontent.com/assets/3781777/19075056/248e1b5c-8a3b-11e6-9bd9-f2596326dde3.png">

However this works fine in Safari.

Having checked with https://www.ssllabs.com/ssltest/analyze.html?d=ocaml.org it seems that the chain of trust is incomplete. I'm not sure whether this might be the cause of the issue

For comparison, here is the same result for Let's Encrypt's "Hello World" page
https://www.ssllabs.com/ssltest/analyze.html?d=helloworld.letsencrypt.org

**Comment by avsm** [comment]
Looks like we were missing an entry for `ssl.ca-file` in the lighttpd.conf. I've added it and restarted the service, and https://www.ssllabs.com/ssltest/analyze.html?d=ocaml.org&latest also appears to be happy.

Thanks for the report @dave-tucker!
