### ISSUE TITLE
The consortium page is outdated

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/v2.ocaml.org#846]
http://caml.inria.fr/consortium/index.en.html

has more companies than 

http://ocaml.org/consortium/

maybe one page should simply link to the other to avoid them going out of sync ? 

/cc @xavierleroy

**Comment by Chris00** [comment]
Thanks.

**Comment by Chris00** [comment]
There is a deprecation warning on top of http://caml.inria.fr/consortium/index.en.html — it is my opinion that submitting PR to ocaml.org should be encouraged since it is the "up to date" site.  Before this becomes a routine, one may want write a script to track changes to the Inria pages... ☹
