### ISSUE TITLE
logos go 404

### ISSUE THREAD

**Issue by pwbs** [ocaml/v2.ocaml.org#850]
```
https://ocaml.org/docs/logos.html -> logos are not found 
```

https://github.com/ocaml/ocaml.org/blob/master/site/docs/logos.md

**Comment by agarwal** [comment]
The ocaml/ocaml-logo repo is supposed to be cloned to the server hosting ocaml.org. Apparently our build script doesn't do so automatically as noted [here](https://github.com/ocaml/ocaml-logo/issues/2#issuecomment-39951892).

@Chris00 and/or @avsm Can you please update us on where and how the builds are now being executed, and where is the hosting. I'm no longer able to ssh into the server (maybe my key got deleted).

**Comment by Chris00** [comment]
This is now fixed but the SVG file http://ocaml.org/logo/Colour/SVG/colour-logo.svg seems to suffer the same problem (not displaying well) as some of the SVG files on the front page used ot have.

**Comment by Chris00** [comment]
See https://github.com/ocaml/ocaml.org/issues/469

**Comment by Chris00** [comment]
Seems OK now.
