### ISSUE TITLE
OCaml 4.04.0 release is not available on opam.ocaml.org

### ISSUE THREAD

**Issue by yallop** [ocaml/v2.ocaml.org#853]
OCaml 4.04.0 was [merged into `opam-repository` three days ago](https://github.com/ocaml/opam-repository/pull/7756), but is not yet available via the https://opam.ocaml.org remote.

Is this the right place to report the problem?  What's the best way to find out what's happened to the release?

**Comment by avsm** [comment]
Thanks for spotting this @yallop.  It looks like the cron job for the site update is failing, see: http://lists.ocaml.org/pipermail/opam-commits/2016-November/002748.html

@Altgr this looks like a change for opam2 rewriting?

**Comment by avsm** [comment]
immediate issue addressed by @altgr in ocaml/opam-repository@be3fcc15eb1e8cdb3a2b3b84e51d4ecafecfafcf

**Comment by avsm** [comment]
now fixed, followup for improving infrastructure in ocaml/infrastructure#3
