### ISSUE TITLE
Difficulties building 4.04 on Solaris with the SUNWSPro C compiler

### ISSUE THREAD

**Issue by shayne-fletcher** [ocaml/v2.ocaml.org#857]
`cc -V` gives, "cc: Sun C 5.12 SunOS_sparc Patch 148917-07 2013/10/18"
which according to
http://www.oracle.com/technetwork/server-storage/solarisstudio/training/index-jsp-141991.html
seems to indicate, Oracle Solaris Studio 12.3, C Compiler 5.12.

(1) C99 required:
  - Resolution:
    - Add `-xc99=all` to the compiler flags

(2) Problems with the newly added `CAML_SYS_EXIT` macro:
  - Defined in 'ocaml/byterun/caml/misc.h' 
  - The problem is:

     ```
     #define CAML_SYS_EXIT(retcode) \
       CAML_SYS_PRIM_1(CAML_CPLUGINS_EXIT,exit,retcode)
      ```
      ultimately reduces to something like,

      ```
      (caml_cplugins_prim == NULL) ? prim(arg1) :
         caml_cplugins_prim(code,(intnat) (arg1),0,0)
     ```
    Where `exit` is concerned, the 'then' part of the conditional evaluates to `void`, the 'else' part of the conditional evaluates to `long`. This is a hard error for this compiler.

  - Resolution:

    - Modify 'ocaml/byterun/sys.c' and 'ocaml/byterun/printexc.c', replacing occurences of `CAML_SYS_EXIT(2)` with

     ```
     #if defined(__SUNPRO_C)
       exit (2);
     #else
       CAML_SYS_EXIT(2);
     #endif /*defined __SUNPRO_C*/
     ```
(3) Unresolved symbols linking 'objinfo_helper'
  - The problem here is due to newly added code to 'caml/alloc.h':

       ```
       static inline value caml_alloc_boxed (value arg) {
         value result = caml_alloc_small (1, 0);
          ...
       }
       ```

     Despite not being called from 'objinfo_helper.c', this morally  induces a link dependency of `objinfo_helper`on 'libcamlrun.a' which in turn obligates a dependency on `prims.o`.

  - Resolution:
    - Add `-Xlinker -znodefs` to the compiler flags to permit unresolved dependencies (note : not a recommended practice, maybe better to not have these `static inline` constructions in the header at all).

**Comment by dbuenzli** [comment]
This issue tracker is about the ocaml website you should report this here https://caml.inria.fr/mantis/

**Comment by shayne-fletcher** [comment]
On Fri, Nov 11, 2016 at 11:54 AM, Daniel Bünzli notifications@github.com
wrote:

> This issue tracker is about the ocaml webiste you should report this here
> https://caml.inria.fr/mantis/

​Yes. Sorry about that. Swift fingers.

## 

Shayne Fletcher

**Comment by shayne-fletcher** [comment]
Moved to Mantis.
