### ISSUE TITLE
"taste" on welcome page has inconsistent colors

### ISSUE THREAD

**Issue by lefessan** [ocaml/v2.ocaml.org#86]
I think it would be better to have more consistent colors in the "taste" example of index.html, to help the newcomer to understand the program.
In particular:
- all keywords should have exactly the same color (type, of, let, rec, match, with, etc.)
- all variable identifiers should have the same color, independently of if they are on a use-site or on a def-site
- all constructors should have the same color

which makes only three colors (with bold for keywords).

**Comment by agarwal** [comment]
Closing this issue because the general problem of syntax highlighting is now being discussed in #286, #221, and #58.
