### ISSUE TITLE
The planet has not been updated for 6 days (as of 2017-01-10)

### ISSUE THREAD

**Issue by gildor478** [ocaml/v2.ocaml.org#864]
If I visit:
http://ocaml.org/community/planet/

The top article is:
Full Time: Software Developer (Functional Programming) at Jane Street in New York, NY; London, UK; Hong Kong — GitHub Jobs, Jan 03, 2017

As a matter of fact Jane Street has published an article yesterday:

	<updated>2017-01-09T13:58:12Z</updated>
	<link rel="alternate" type="text/html" href="https://blogs.janestreet.com" />

The planet is missing a few other blog posts (like the Caml Weekly News).

**Comment by agarwal** [comment]
Seems this is still broken, but unfortunately I can't get to this right now.

**Comment by Chris00** [comment]
On 2017-01-17, Ashish Agarwal wrote:
> 
> Seems this is still broken, but unfortunately I can't get to this 
> right now.

Sorry — no time to work on it yet.  I hope to find some today or 
tomorrow...

**Comment by brabalan** [comment]
Is there an alternative feed? For the moment I'm just leaving this section out of the Caml Weekly News.

**Comment by dinosaure** [comment]
Hmmhmm, I just try to compile the script `rss2tohtml` with the last version of Syndic (1.5.3) and all is ok in my side but I found lot of out of date (like 404 error) feeds.

**Comment by Chris00** [comment]
On 2017-01-31, Calascibetta Romain wrote:
>
> Hmmhmm, I just try to compile the script rss2tohtml with the last 
> version of Syndic (1.5.3) and all is ok in my side but I found lot of 
> out of date (like 404 error) feeds.

Normally, 404 feeds do not cause problems to the whole processing. 
These feeds are strike through in the “Syndications” list (with a pop up 
giving the “reason”).

Sorry for the delay on this one — too many things on my plate...

**Comment by Chris00** [comment]
One problem was `ocamlfu` which seems to have been uninstalled during automatic opam updates making the compilation fail.  There was also a stranger problem with the group of the files in `/var/www/html/`.  I think this is fixed.
