### ISSUE TITLE
add link to GODI

### ISSUE THREAD

**Issue by gerdstolpmann** [ocaml/v2.ocaml.org#88]
Don't know where this belongs. maybe on the Releases page. The official GODI link is now godi.camlcity.org.

Short sentence about GODI: "GODI is an independent distribution of OCaml and add-on software (covering both libraries and applications), running on multiple operating systems (Linux, MacOSX, Windows, and other). GODI compiles software from source, and allows it to adapt it to one's needs, using configuration options and even patches. GODI also supports binary releases as a user option."

**Comment by agarwal** [comment]
This belongs on the Install page, where GODI does already have a section.
I've updated the description with the provided text
in fa24842dab599f28a9231b2703ed23afabf2b1f0. And if you found it hard to
notice that GODI is discussed on this page, note we already have an issue
open to reformat this page.
