### ISSUE TITLE
Suggest copying opam_installer.sh from browser to file

### ISSUE THREAD

**Issue by mars0i** [ocaml/v2.ocaml.org#883]
I suggest adding an alternative opam_installer.sh installation: Just copy the file's content into a file and make it executable.  It's obvious that this will work, but it might be worth adding as a suggestion for people who are momentarily being clueless--as I was last night.

(I tried following the instructions to install opam by first downloading opam_installer.sh.  I didn't have `wget`, so I tried `curl` but got an error.  `curl` apparently doesn't like https.  Then I tried to install `wget`, which I wouldn't mind having anyway.  Didn't want to install homebrew--this might be worth having, too--but had other things to do.  Tried to compile `wget` and got an error from a header.  I could diagnose and fix it but [see above].  Finally I realized that I was being dense, and just pasted the opam_installer.sh url into the browser, copied the text into a file, chmod'ed it, and am now using ocaml happily.)

**Comment by dbuenzli** [comment]
This is useful feedback but for some reasons the instructions for installing opam are on their own sub-website whose official issue tracker is https://github.com/ocaml/opam it would be better to file an issue there. /cc @AltGr

**Comment by mars0i** [comment]
Thanks.  I've now done that.

**Comment by redianthus** [comment]
@Chris00, this can be closed, see (PR on opam)[https://github.com/ocaml/opam/pull/2947]

**Comment by Chris00** [comment]
Thanks.
