### ISSUE TITLE
https://ocaml.org/docs/install.html refers to inexistent 4.04.1.html page

### ISSUE THREAD

**Issue by mauny** [ocaml/v2.ocaml.org#889]
`https://ocaml.org/docs/install.html` refers to `/releases/4.04.1.html`, which does not exist. It should probably be `/releases/4.04.html` instead.

If this is the case, `/releases/4.04.html` should also be updated by saying that **4.04.1** is the latest release.

**Comment by agarwal** [comment]
Done in 69a76fc90bfd802d527d0f95dd211d37a95480a3.
