### ISSUE TITLE
add link to docs.camlcity.org

### ISSUE THREAD

**Issue by gerdstolpmann** [ocaml/v2.ocaml.org#89]
This site allows API and package search of the packages in GODI and OASIS (partially so far). 

Text: "docs.camlcity.org allows browsing and searching the packages in GODI and OASIS. The corpus includes compiled code, manuals, and sources. You can search for various objects, including values, types, modules, and classes."

**Comment by Chris00** [comment]
This is no longer an issue since GODI [has shut down](http://blog.camlcity.org/blog/godi_shutdown.html) and [oasis DB](http://oasis.ocamlcore.org/dev/home) did not take off.
