### ISSUE TITLE
Web tutorial is somewhat out of date

### ISSUE THREAD

**Issue by glennsl** [ocaml/v2.ocaml.org#892]
See: https://ocaml.org/learn/tutorials/ocaml_and_the_web.html

I can't exactly remember the last time the idea of CGI programming entered my head, but I don't think it was this decade at least. So perhaps it would be a good idea to either remove it, or if there's a desire to preserve it as a historical curiosity, mark it as obsolete. It seems quite misleading and counterproductive to keep it as it is.

I would of course volunteer to write a new web tutorial if I thought I had a good enough grasp of the topic, but I came across this precisely because I don't.

**Comment by agarwal** [comment]
The tutorials are sadly out of date and in need of substantial work. First useful thing would be for someone to simply reorganize the list. Completely out of date tutorials could be deleted or moved into an _archive_ section. Another idea is to convert this page from _tutorials_ to more general _references_. As suggested [here](https://github.com/ocaml/ocaml.org/issues/502#issuecomment-51655236), the [Awesome OCaml](https://github.com/rizo/awesome-ocaml) repo would be a great start.

Volunteers are needed.

**Comment by glennsl** [comment]
I've submitted a PR which deprecates and archives this and the camlp4 tutorial. "References" seems a bit vague to me, but I'll have a think about how this might be structured. The external links and translated pages could certainly do with some weeding too, though
