### ISSUE TITLE
Installing info file for emacs

### ISSUE THREAD

**Issue by cool88** [ocaml/v2.ocaml.org#894]
Hi,

I tried this on my macOS Sierra.  I downloaded the info-file from the http://caml.inria.fr/pub/docs/manual-ocaml/

`install-info --info-file=./ocaml-4.04-refman.info.tar.gz --info-dir=/usr/local/share/info/ `

But I get the following warning (error? )

`install-info: warning: no info dir entry in `./ocaml-4.04-refman.info.tar.gz'`

**Comment by agarwal** [comment]
This is not an _ocaml.org_ issue. The manual is maintained as part of the main compiler distribution, so it might make sense to post there if you feel there is an error in the info file they are generating. Or alternatively, you might send a message to the OCaml Mailing list.

**Comment by cool88** [comment]
The OCAML repo here doesn't have an issue page. But thanks, I'll try the mailing list.

**Comment by agarwal** [comment]
> The OCAML repo here doesn't have an issue page. But thanks, I'll try the mailing list.

Oh right. I should have pointed you to [Mantis](https://caml.inria.fr/mantis/my_view_page.php). In any case, I see you got your answer on [discuss.ocaml.org](https://discuss.ocaml.org/t/emacs-texinfo-help/192).
