### ISSUE TITLE
Broken link for release

### ISSUE THREAD

**Issue by charguer** [ocaml/v2.ocaml.org#898]
On page : http://ocaml.org/docs/install.html
The link in the sentence: 
"The latest version of OCaml is 4.04.1. For more information about this release, see the 4.04.1 page."
points to a page that does not seem to exist.

**Comment by agarwal** [comment]
Thanks for reporting. The website build is not working for some reason. It is being looked into.
cc: @Chris00

**Comment by Chris00** [comment]
The problem is that `script/generate_opam_update_list` terminates with the exception
```
[ERROR] At ~/.opam/repo/default/packages/i3ipc/i3ipc.0.1/opam:8:52:
  Unsupported protocol git+https
Fatal error: exception OpamFormat.Bad_format(_, 0, "Unsupported protocol git+https")
```
I'll try to fix it as fast as I can.

**Comment by Chris00** [comment]
To fix the problem, on needs [opam2web with opam-lib-1.3](https://github.com/ocaml/opam2web/pull/145).

**Comment by Chris00** [comment]
The site is now again up and running.  Note that `opam2web` is pinned for now.

**Comment by agarwal** [comment]
Thanks! I'm closing this issue.
