### ISSUE TITLE
faq.html: import content from external sources

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#9]
The FAQ page is currently empty. Import content from various external sources, such as the Inria page.

**Comment by agarwal** [comment]
Inria's FAQs are here in [english](http://caml.inria.fr/resources/doc/faq/index.en.html) and [french](http://caml.inria.fr/resources/doc/faq/index.fr.html).

**Comment by Chris00** [comment]
I imported the "General Questions" (slightly modified).  09e46c800cc1de9b34e153dc731cbea4e6c0b3df

**Comment by agarwal** [comment]
I imported remaining FAQs from Inria site: c33544fc2ae353fc9b61c32dd36e80605eb205bf, b291ef07db8f6e62f9d120d75d9e8ef4421e06a8, 28e393018a897c66ff64e755bde0b607ac9defc3, and 5cf85a0bb0cae6e3eec0522d521b31d91bccb63e.

Closing this issue. We can open a new one for importing from external sources if we have specific other sites to import from.
