### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by voila** [ocaml/v2.ocaml.org#90]
I've run the W3C link checker on the website 

http://validator.w3.org/checklink?uri=ocaml.org&hide_type=all&depth=&check=Check

and here's the list of broken links:
- [x] http://ocaml.org/tutorials/hashtbl.html
- [x] http://ocaml.org/tutorials/map.html
- [x] http://ocaml.org/tutorials/set.html
- [x] http://ocaml.org/tutorials/comparison_of_standard_containers.html
- [x] http://ocaml.org/caml.inria.fr/pub/docs/manual-ocaml/libref/Pervasives.html (via beaf7a696b33311febebac06574287c27819837c)
- [x] http://ocaml.org/caml.inria.fr/pub/docs/manual-ocaml/libref/Printf.html (via beaf7a696b33311febebac06574287c27819837c)
- [x] http://ocaml.org/caml.inria.fr/pub/ml-archives/caml-list/2003/06/2732fbf1bed1ae50fefb6ea410ea9955.en.html (via c77d3ae0fcafc62731260eab57e20c169389c01d)
- [x] http://www.noir-medical.com/graphics/diode_graph.gif (via 67ca5e6b4beb8b5a19342880878b283ddaa12d77)
- [x] http://ocaml.org/tutorials/ocaml_and_the_web/discussion.html (via c6edb48cf6423f18a3502924da36db6b04f6bc48)
- [x] http://ocaml.org/caml.inria.fr/pub/ml-archives/caml-list/2008/09/2bc9b38171177af5dc0d832a365d290d.en.html (via c77d3ae0fcafc62731260eab57e20c169389c01d)
- [x] http://ocaml.org/caml.inria.fr/pub/docs/manual-ocaml/manual029.html (via beaf7a696b33311febebac06574287c27819837c)
- [x] http://www.princeton.edu/~sacm/humor/proof.html (via 69a17c4bfe6fec16a6d9e3f9850f319ef3f4628e)
- [x] http://cocan.org/tips/single_line_comment_syntax redirected to http://www.cocan.org/tips/single_line_comment_syntax (_non existent_)
- [x] http://ocaml.org/tutorials/compiling_with_gnu_make.html
- [x] http://ocaml.org/caml.inria.fr/cgi-bin/hump.en02dc.html?sort=1&browse=55 (_non existent_)
- [x] http://ocaml.org/tutorials/compiling_with_omake.html
- [x] http://ocaml.org/tutorials/_file/objcache.ml (via 1c6bf766f6da504ebb536da5c3db9e8e8098c251)
- [x] http://ocaml.org/caml.inria.fr/pub/ml-archives/caml-list/2002/08/e109df224ff0150b302033e2002dbf87.en.html (via c77d3ae0fcafc62731260eab57e20c169389c01d)
- [x] http://www.bagley.org/~doug/ocaml/Notes/lazy.shtml (via 8ba0f910b65d4d12913fd538663464590532b608)
- [x] http://ocaml.org/caml.inria.fr/resources/doc/guides/guidelines.en.html (_non existent_)
- [x] http://ocaml.org/tutorials/programming_style/discussion.html (_no more referenced_)
- [x] http://ocaml.org/tutorials/camlp4_3.10/foreach_tutorial.html (exists in c25102b)
- [x] http://ocaml.org/tutorials/camlp4_3.10/dynamic_functor_example.html (exists in c25102b)
- [x] http://ocaml.org/tutorials/camlp4_3.10/static_old_syntax.html (exists in c25102b)
- [x] http://ocaml.org/caml.inria.fr/pub/ml-archives/caml-list/2007/04/47c5c935136351afaefee6a0aa9cc506.en.html (via c77d3ae0fcafc62731260eab57e20c169389c01d)
- [x] http://ocaml.org/tutorials/camlp4_3.10/static_functor_example.html (exists in c25102b)
- [x] http://ocaml.org/tutorials/camlp4_3.10/quick_non_extensible_example.html (exists in c25102b)
- [x] http://ocaml.org/tutorials/camlp4_3.10/dynamic_old_syntax.html (exists in c25102b)
- [x] http://ocaml.org/caml.inria.fr/pub/docs/manual-ocaml/libref/Arg.html (via beaf7a696b33311febebac06574287c27819837c)
- [x] http://ocaml.org/caml.inria.fr/FAQ/FAQ_EXPERT-eng.html (all experts links are OK in c25102b)
- [x] http://ocaml.org/caml.inria.fr/pub/ml-archives/caml-list/2002/05/a6520926c4eac029206a31d6aa22f967.fr.html (via c77d3ae0fcafc62731260eab57e20c169389c01d)
- [x] http://ocaml.org/caml.inria.fr/pub/old_caml_site/FAQ/FAQ_EXPERT-eng.html (all experts links are OK in c25102b)

How do we tackle this ?

**Comment by agarwal** [comment]
Thanks! We'll go through these.

**Comment by agarwal** [comment]
This issue got closed accidentally.

**Comment by agarwal** [comment]
Commit 7a42130b30d9445d527887824ead05c500287858 fixes links to compiling_with_gnu_make.html and compiling_with_omake.html.

**Comment by Chris00** [comment]
All reported links have been checked.
