### ISSUE TITLE
email obfuscation breaks with subject line

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#92]
We automatically obfuscate email links. But the following gets corrupted:

```
<a href="mailto:me@example.com?subject=hi there">
```

The issue appears to be the space in the subject. Replacing it with `&nbsp;` resolves the problem, but perhaps we can do that automatically.

**Comment by Chris00** [comment]
Technically, spaces should be encoded with %20 but I'll see what I can do.

**Comment by Chris00** [comment]
I have added some code in Weberizer v0.7.3 for this.
