### ISSUE TITLE
fix ssl certificate issue correctly

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#926]
@dbuenzli [explains](https://github.com/ocaml/ocaml.org/issues/876#issuecomment-325140331) the source of our recurring certificate expiration problem. Would be great to fix this correctly. According to him, it will happen again every 3 months, which seems to be right based on a search of ssl issues in this repo.

I believe @avsm is the one who handles this.

**Comment by Benestar** [comment]
Yeah please find a permanent solution, this gets annoying.

**Comment by maxiSchaeff** [comment]
+1

**Comment by Chris00** [comment]
This is being worked on...  Sorry for the trouble.

**Comment by avsm** [comment]
There is a rotation script in the ocaml.org VM, but it had a minor typo in it that was causing the lighttpd process to not restart with the new keys.  This is now fixed and so expiry shouldn't happen in normal circumstances.

In the medium term, @hannesm mentioned that he's almost got a LE client working. I'm keen to move over ocaml.org to being served from an OCaml webserver, and that will include the LE certificate functionality so we don't need to  depend on external cron jobs to keep our certificates fresh.
