### ISSUE TITLE
IRILL links broken

### ISSUE THREAD

**Issue by rickyvetter** [ocaml/v2.ocaml.org#927]
Two of the links on https://ocaml.org/community/support.html appear to be broken:

http://ows.irill.org/latest/today 404s. Made an issue to get clarification here - https://github.com/OCamlPro/ows/issues/17

http://cudf-solvers.irill.org/index.html 502s. I didn't see a good place to put an issue for this, but did see that it looks like it's been down for a while - https://groups.google.com/forum/#!msg/ocaml-aggregation-list/_en--TtFsEU/bd4F5PyaCAAJ.

**Comment by Chris00** [comment]
Thanks for letting us know.  For OWS, let's wait for OCamlPro reply.

**Comment by rickyvetter** [comment]
Closing this out because http://ows.irill.org/latest/today/ is back up. Still some problems on deeper pages, but those can be addressed in the linked issue.

**Comment by Thra11** [comment]
It appears to be broken again. (http://opam.ocaml.org/about.html links to http://ows.irill.org/, which results in "Server Not Found")
