### ISSUE TITLE
SSL certificate expired on ocaml.org

### ISSUE THREAD

**Issue by seryl** [ocaml/v2.ocaml.org#932]
See below; expired on 10/16/2017

![cert-expiration](https://user-images.githubusercontent.com/134032/31739718-b692a4a8-b403-11e7-898d-636ae6699c5d.PNG)

Probably need to setup some automatic LetsEncrypt cert  renewal or something.

**Comment by pw374** [comment]
I'm hoping it's already solved, cf. https://github.com/ocaml/ocaml.org/issues/926

I'm closing this issue. Please reopen if need be.
