### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by playpianolikewoah** [ocaml/v2.ocaml.org#936]
Another spelling error on https://github.com/ocaml/ocaml.org/blob/master/site/learn/tutorials/guidelines.md: 
> Justitification: I don't see any good reason for this rule, unless you are paid proportionally to the number of lines of code: in this case use this rule to get more money without adding more bugs in your OCaml programs!

I think you meant 

> Justification

**Comment by playpianolikewoah** [comment]
That's the only two spelling errors I found on that page.

**Comment by Chris00** [comment]
Thanks.
