### ISSUE TITLE
Dead link to https://ocaml.org/caml-light/releases/

### ISSUE THREAD

**Issue by gallais** [ocaml/v2.ocaml.org#939]
On [the page for Caml Light](https://ocaml.org/caml-light/) there is a dead link to https://ocaml.org/caml-light/releases/ which ought to be pointing at a download page for "the latest release".

**Comment by agarwal** [comment]
Might be related to #608.

**Comment by patricoferris** [comment]
I've looked into this and it appears the reason for the deadlink is that the initial collecting of markdown files doesn't include symbolic links: https://github.com/ocaml/ocaml.org/blob/master/Makefile#L46 and the file in question is indeed a symbolic link to `0.75`: https://github.com/ocaml/ocaml.org/tree/master/site/caml-light/releases 

Adding `-type l` to that find statement fixes this locally, PR to follow. 

--- 

I don't think it is related to #608. I think this has just been duplicated at some point and it would seem the `releases/` version is less up to date then the `caml-light/` version.
