### ISSUE TITLE
Header Image SVG

### ISSUE THREAD

**Issue by m4lu** [ocaml/v2.ocaml.org#953]
I am looking for a vector graphic of the header image https://github.com/ocaml/ocaml.org/blob/master/site/img/header.jpg , preferably under a permissive license.

As far as I can see the issue was already discussed in #444 and I would like to bring it up again as the issue still persists for high resolution displays.

Any hints to possible sources for a vector version of the image and possible updates to the website are appreciated.

**Comment by agarwal** [comment]
> preferably under a permissive license

As per the [license file](https://github.com/ocaml/ocaml.org/blob/master/LICENSE.md), the header image is not available for use by other projects. It falls under the "Design of the site" category. The rationale for that was that ocaml.org should have a recognizable look and feel. It was felt that it would be odd for other websites to look similar.

Would the [logos](https://github.com/ocaml/ocaml-logo) meet your needs? They are released under the UNLICENSE and intended for use everywhere.

**Comment by m4lu** [comment]
>> preferably under a permissive license  

> As per the license file,  the header image is not available for use by other projects. It falls  under the "Design of the site" category. The rationale for that was that  ocaml.org should have a recognizable look and feel. It was felt that it  would be odd for other websites to look similar. 

I missed that part, thanks for pointing it out.

> Would the logos meet your needs? They are released under the UNLICENSE and intended for use everywhere.


They do not, because I am looking for a complete camel (or possibly a caravan + textured background imagery) not only 50%-75% of it. However I think I will try my luck with freely available silhouettes from the internet.

Thanks for the fast response and the pointer to the reposetory, please consider this issue closed (unless you have further remarks, maybe this kind of imagery could be added as 'additional graphical content' to the ocaml-logo repository).

**Comment by agarwal** [comment]
> maybe this kind of imagery could be added as 'additional graphical content' to the ocaml-logo repository

My personal view is that the banner image is a prominent image of ocaml.org, and as such its categorization under "design of the site" is correct. I hope some alternative images can meet your needs more easily than changing the license, which would be some work. There are [governance guidelines](http://ocaml.org/about.html#Governance-of-this-website) that have to be followed.
