### ISSUE TITLE
caml/misc.h leaks reserved identifier

### ISSUE THREAD

**Issue by ghost** [ocaml/v2.ocaml.org#954]
clang -Wreserved-id-macro -x c /dev/null -S -include $(ocamlc -where)/caml/misc.h
In file included from <built-in>:1:
/net/lib/ocaml/caml/misc.h:208:9: warning: macro name is a reserved identifier
      [-Wreserved-id-macro]
#define _T(x) x
        ^
1 warning generated.

===
7.1.3 of ISO/IEC 9899:201x in part reads:

All identifiers that begin with an underscore and either an uppercase letter or another
underscore are always reserved for any use.

**Comment by Chris00** [comment]
You should report that to [OCaml](https://github.com/ocaml/ocaml), this project is for the website only.
