### ISSUE TITLE
404 link to http://ocaml.org/releases/4.06.1.html

### ISSUE THREAD

**Issue by letouzey** [ocaml/v2.ocaml.org#961]
Hi ! 
Today's [Install page](http://ocaml.org/docs/install.html) refer to 4.06.1 but the [given link]( http://ocaml.org/releases/4.06.1.html) is currently dead...
Thanks...
Pierre

**Comment by letouzey** [comment]
thanks

**Comment by Chris00** [comment]
Thanks for reporting!
