### ISSUE TITLE
unable to build ocaml.org

### ISSUE THREAD

**Issue by tarptaeya** [ocaml/v2.ocaml.org#965]
When I executed `make deps` I always get the following error 
```console
...
┌─ The following actions failed
│ λ  build dose3              5.0.1
│ λ  build js_of_ocaml-camlp4 3.0.2
│ λ  build syndic             1.5.3
└─ 
...
make: *** [Makefile:28: deps] Error 31
```
I even tried with `opam update` & `opam upgrade` but no success, my ocaml version is 4.05.0 and that of opam is 2.0.0~beta6

**Comment by Chris00** [comment]
This looks more like a problem installing packages than a problem with ocaml.org itself.

**Comment by Chris00** [comment]
May you try again?  The dependencies were improved so that should work (including with the latest OCaml version).

**Comment by Chris00** [comment]
No response, closing.
