### ISSUE TITLE
planet.ocaml.org seems defunct

### ISSUE THREAD

**Issue by yomimono** [ocaml/v2.ocaml.org#973]
It now redirects to https://lists.forge.ocamlcore.org/ instead of the OCaml Planet feed aggregator.

**Comment by agarwal** [comment]
I'm not sure who controls the planet.ocaml.org url, but I think the correct behavior would be for it to redirect to http://ocaml.org/community/planet/.

**Comment by Chris00** [comment]
@avsm May you do it or dispatch to the appropriate person?
