### ISSUE TITLE
4.06.1 isn't consistently mentioned everywhere

### ISSUE THREAD

**Issue by pmetzger** [ocaml/v2.ocaml.org#981]
The latest release is 4.06.1, but a lot of pages still list 4.06 as the latest release. For example, if you click on https://ocaml.org/docs/install.html, see the 4.06.1 release listed, and click on it, you eventually end up at https://ocaml.org/releases/4.06.html which only lists. 4.06.0.

**Comment by agarwal** [comment]
I see `site/releases/4.06.1.html`, but for some reason the published [Releases](http://ocaml.org/releases/index.html) page doesn't list it.

**Comment by Chris00** [comment]
I will change the page 4.06.1.  Is there any place where **4.06.0** is actually mentioned — normally every place should use a macro to be updated automatically.
