### ISSUE TITLE
Reason is an alternative syntax

### ISSUE THREAD

**Issue by ShalokShalom** [ocaml/v2.ocaml.org#983]
And not an "OCaml-to-Javascript superset"

It is neither a superset nor Bucklescript.

**Comment by Chris00** [comment]
On what page?

**Comment by hhugo** [comment]
https://ocaml.org/learn/tutorials/get_up_and_running.html

**Comment by ShalokShalom** [comment]
Sorry, forget to mention that. 
Thank you both :)

**Comment by Chris00** [comment]
Thanks.

**Comment by ShalokShalom** [comment]
Sure
