### ISSUE TITLE
make dep fails

### ISSUE THREAD

**Issue by pmetzger** [ocaml/v2.ocaml.org#985]
I'm trying to build the docs locally so I can make some changes and submit them. The README indicates you should run `make deps` but that's failing for me.

```$ make deps
opam pin add ocamlorg . --no-action --yes --kind=path
Package ocamlorg does not exist, create as a NEW package ? [Y/n] y
ocamlorg is now path-pinned to /Users/perry/src/ocaml.org/ocaml.org

[ocamlorg] /Users/perry/src/ocaml.org/ocaml.org/ synchronized
[ocamlorg] Installing new package description from
/Users/perry/src/ocaml.org/ocaml.org

opam install ocamlorg --deps-only

=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ocamlorg] /Users/perry/src/ocaml.org/ocaml.org/ already up-to-date
The following dependencies couldn't be met:
  - ocamlorg -> mpp >= 0.3.1
Your request can't be satisfied:
  - mpp>=0.3.1 is not available because your system doesn't comply with ocaml-version < "4.06.0".

No solution found, exiting
make: *** [deps] Error 3
```

**Comment by wokalski** [comment]
> Your request can't be satisfied:
>   - mpp>=0.3.1 is not available because your system doesn't comply with ocaml-version < "4.06.0".

**Comment by Chris00** [comment]
Well, the problem is MPP, you should file an issue there https://github.com/ocaml/MPP-language-blender/issues

For now, `opam switch 4.05.0`

**Comment by pmetzger** [comment]
Yah, I got that from the error messages, but I didn't feel like rebuilding a lot of stuff just to build the web site, and others might not as well.

Is this simply a safe string issue in MPP or is it worse? Given that MPP is used as part of a piece of critical infrastructure (ocaml.org), it might be useful to update it for >4.06 — if it's just safe string I could volunteer to do that.

**Comment by pmetzger** [comment]
Ah, it looks like there is an extant pull request: https://github.com/ocaml/MPP-language-blender/pull/26 but that it has been left alone since January 5. Since MPP is an OCaml github project, would it be possible for someone to attend to that pull request?

**Comment by pw374** [comment]
that's just been merged, apologies

**Comment by pmetzger** [comment]
@pw374 Cool! Can opam get updated appropriately?

**Comment by pw374** [comment]
I'm trying (to remember how) to create the appropriate opam files... Should be done soon.

**Comment by pw374** [comment]
Ummm... I don't like the opam files that have been generated. https://github.com/ocaml/opam-repository/pull/11813  Also, some checks fail... I'll try to find time to investigate.

Edit: let's see if https://github.com/ocaml/opam-repository/pull/11814 builds better somehow...

**Comment by pmetzger** [comment]
Following the mpp update in opam, I've been able to start the site building. (Wow, it takes a long time!)

**Comment by pmetzger** [comment]
Anyway, this problem now seems fixed.
