### ISSUE TITLE
Add ocaml.org to opam

### ISSUE THREAD

**Issue by bluddy** [ocaml/v2.ocaml.org#987]
It's really painful to manage dependencies without opam taking care of things. We want people to iterate designs quickly, and that can only happen if ocaml.org is easy to build.

**Comment by pmetzger** [comment]
By this, do you mean "package all dependencies"? The site itself probably doesn't need to be in opam.

**Comment by bluddy** [comment]
OK my bad. There's an opam file. Closing this issue.

**Comment by pmetzger** [comment]
That said, it might be reasonable to have an issue for the fact that netstrings isn't packaged?

**Comment by bluddy** [comment]
It should be handled by pinning locally. You do `opam pin add X .`  where X is the name you want to give it, say `website`. I'll prompt you for creating a new package, and you just say yes. It'll then try to build everything.

There are so many breakages though -- right now it's failing at opam-lib constraint solving for me, and that's in addition to the 2 other compilation issues that are waiting down the line. I posted an [issue on the opam repo](https://github.com/ocaml/opam/issues/3300).

**Comment by Chris00** [comment]
netstrings is part of ocamlnet

**Comment by pmetzger** [comment]
Okay, so that dependency is already there.
