### ISSUE TITLE
nuke stale branches?

### ISSUE THREAD

**Issue by pmetzger** [ocaml/v2.ocaml.org#989]
Apparently all of the branches on this project (omd, cohttp, oloop, pw374-patch-1) are many years stale. Would it be reasonable to gc at least some of them?

**Comment by agarwal** [comment]
`omd` and `pw374-patch-1` have no commits ahead of master, so I think those certainly can be deleted.

@Chris00 has unmerged commits in `cohttp` anad `oloop`, so I'll let him decide on those.

**Comment by Chris00** [comment]
I'll delete them as well.  I believe that the choices should be revisited on a larger scale anyway.
