### ISSUE TITLE
export OCAMLRUNPARAM='b' required to compile

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#99]
Regarding comments on commit f94883dc1dee9e9e46afbb8e120aec9329700896, it seems the issue is that export OCAMLRUNPARAM='b' is required. Otherwise, compilation fails on streams.html.

**Comment by voila** [comment]
that solves my problem, thanks

**Comment by martindemello** [comment]
this fixed my problem, which was an actual segmentation fault when processing streams.html. if it helps figure out the base issue, changing this block to noeval makes it not segfault:

```
<pre ml:content="ocaml noeval">
  #directory "+threads";;
  #load "threads.cma";;
  let elements iter coll =
    let channel = Event.new_channel () in
    let producer () =
      let () =
        iter (fun x -&gt; Event.sync (Event.send channel (Some x))) coll in
      Event.sync (Event.send channel None) in
    let consumer i =
      Event.sync (Event.receive channel) in
    ignore (Thread.create producer ());
    Stream.from consumer
</pre>
```

**Comment by Chris00** [comment]
The toplevel evaluation [changed](5606c2197bda19b967ec89c06f399e55091cf28b) since this bug was open.  It seems that `OCAMLRUNPARAM=b` is [no longer needed](fefc17e35c747790345c1b61bbaca67615b983ee).  May you please confirm it also works for you?

**Comment by agarwal** [comment]
It works for me.
